#---------- CoD: World at War Ranks | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Notifications
WAW_RANK_PROMOTED=You've been promoted!
WAW_RANK_PLAYER_WAS_PROMOTED=%s was promoted to %s!
  
# Ranks
WAW_RANK_PVT_FULL=Private
WAW_RANK_PFC_FULL=Private First Class
WAW_RANK_CPL_FULL=Corporal
WAW_RANK_SGT_FULL=Sergeant
WAW_RANK_SSGT_FULL=Staff Sergeant
WAW_RANK_GYSGT_FULL=Gunnery Sergeant
WAW_RANK_MSGT_FULL=Master Sergeant
WAW_RANK_SGTM_FULL=Sergeant Major
WAW_RANK_2NDLT_FULL=2nd Lieutenant
WAW_RANK_1STLT_FULL=1st Lieutenant
WAW_RANK_CAPT_FULL=Captain
WAW_RANK_MAJ_FULL=Major
WAW_RANK_LTCOL_FULL=Lieutenant Colonel
WAW_RANK_COL_FULL=Colonel
WAW_RANK_BGEN_FULL=Brigadier General
WAW_RANK_MAJGEN_FULL=Major General
WAW_RANK_LTGEN_FULL=Lieutenant General
WAW_RANK_GEN_FULL=General
WAW_RANK_COMM_FULL=Commander
WAW_RANK_1STLT_FULL2=1st Lieutenant I
WAW_RANK_1STLT_FULL3=1st Lieutenant II
WAW_RANK_2NDLT_FULL2=2nd Lieutenant I
WAW_RANK_2NDLT_FULL3=2nd Lieutenant II
WAW_RANK_BGEN_FULL2=Brigadier General I
WAW_RANK_BGEN_FULL3=Brigadier General II
WAW_RANK_CAPT_FULL2=Captain I
WAW_RANK_CAPT_FULL3=Captain II
WAW_RANK_COL_FULL2=Colonel I
WAW_RANK_COL_FULL3=Colonel II
WAW_RANK_CPL_FULL2=Corporal I
WAW_RANK_CPL_FULL3=Corporal II
WAW_RANK_GYSGT_FULL2=Gunnery Sergeant I
WAW_RANK_GYSGT_FULL3=Gunnery Sergeant II
WAW_RANK_LCPL_FULL2=Lance Corporal I
WAW_RANK_LCPL_FULL3=Lance Corporal II
WAW_RANK_LTCOL_FULL2=Lieutenant Colonel I
WAW_RANK_LTCOL_FULL3=Lieutenant Colonel II
WAW_RANK_MAJ_FULL2=Major I
WAW_RANK_MAJ_FULL3=Major II
WAW_RANK_MAJGEN_FULL2=Major General I
WAW_RANK_MAJGEN_FULL3=Major General II
WAW_RANK_MGYSGT_FULL2=Master Gunnery Sergeant I
WAW_RANK_MGYSGT_FULL3=Master Gunnery Sergeant II
WAW_RANK_MSGT_FULL2=Master Sergeant I
WAW_RANK_MSGT_FULL3=Master Sergeant II
WAW_RANK_PFC_FULL2=Private First Class I
WAW_RANK_PFC_FULL3=Private First Class II
WAW_RANK_PVT_FULL2=Private I
WAW_RANK_PVT_FULL3=Private II
WAW_RANK_REC_FULL2=Recruit I
WAW_RANK_REC_FULL3=Recruit II
WAW_RANK_SGT_FULL2=Sergeant I
WAW_RANK_SGT_FULL3=Sergeant II
WAW_RANK_SSGT_FULL2=Staff Sergeant I
WAW_RANK_SSGT_FULL3=Staff Sergeant II
WAW_RANK_LTGEN_FULL2=Lieutenant General I
WAW_RANK_LTGEN_FULL3=Lieutenant General II
WAW_RANK_GYSGT_FULL4=Gunnery Sergeant III
WAW_RANK_LTGEN_FULL4=Lieutenant General III
WAW_RANK_MAJGEN_FULL4=Major General III
WAW_RANK_BGEN_FULL4=Brigadier General III
WAW_RANK_COL_FULL4=Colonel III
WAW_RANK_LTCOL_FULL4=Lieutenant Colonel III
WAW_RANK_MAJ_FULL4=Major III
WAW_RANK_CAPT_FULL4=Captain III
WAW_RANK_1STLT_FULL4=1st Lieutenant III
WAW_RANK_2NDLT_FULL4=2nd Lieutenant III
WAW_RANK_SSGT_FULL4=Staff Sergeant III
WAW_RANK_MSGT_FULL4=Master Sergeant III
WAW_RANK_SGTM_FULL2=Sergeant Major I
WAW_RANK_SGTM_FULL3=Sergeant Major II
WAW_RANK_SGTM_FULL4=Sergeant Major III