#---------- Black Ops HUD | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Factions
BO1_MP_TROPAS_NAME=TROPAS
BO1_MP_NVA_NAME=NVA
BO1_MP_RUSSIAN_NAME=SPETSNAZ
BO1_MP_SPECOPS_NAME=BLACK OPS
BO1_MP_MARINE_NAME=SOG
BO1_MP_REBELS_NAME=OP 40

BO1_MPUI_TROPAS_SHORT=Tropas
BO1_MPUI_NVA_SHORT=NVA
BO1_MPUI_RUSSIAN_SHORT=Spetsnaz
BO1_MPUI_SPECOPS_SHORT=Black Ops
BO1_MPUI_MARINE_SHORT=SOG
BO1_MPUI_REBELS_SHORT=Op 40

BO1_MPUI_TROPAS_SHORT_CAPS=TROPAS
BO1_MPUI_NVA_SHORT_CAPS=NVA
BO1_MPUI_RUSSIAN_SHORT_CAPS=SPETSNAZ
BO1_MPUI_SPECOPS_SHORT_CAPS=BLACK OPS
BO1_MPUI_MARINE_SHORT_CAPS=SOG
BO1_MPUI_REBELS_SHORT_CAPS=OP 40

# Splashes
BO1_MEDAL_BUZZ_KILL=Buzzkill
BO1_MEDAL_BUZZ_KILL_DESC=Stoppade en fiende nära en dråpserie.
BO1_MEDAL_LONG_SHOT=Långt skott
BO1_MEDAL_LONG_SHOT_DESC=Dödade en fiende från avstånd.
BO1_MEDAL_HEAD_SHOT=Huvudskott
BO1_MEDAL_HEAD_SHOT_DESC=Boom, direkt i nyllet.
BO1_MEDAL_STUCK_TO_PLAYER=Fast
BO1_MEDAL_STUCK_TO_PLAYER_DESC=Fastnade sprängmedel på en fiende.
BO1_MEDAL_BULLS_EYE=Skalperare
BO1_MEDAL_BULLS_EYE_DESC=Dödade en fiende med en Tomahawk.
BO1_MEDAL_EXECUTION=Avrättning
BO1_MEDAL_EXECUTION_DESC=Dödade en nere fiende med ett huvudskott.
BO1_MEDAL_COMEBACK=Comeback
BO1_MEDAL_COMEBACK_DESC=Kom tillbaka från en rad dödsfall.
BO1_MEDAL_AVENGER=Hämnare
BO1_MEDAL_AVENGER_DESC=Dödade en fiende som nyligen dödade en lagkamrat.
BO1_MEDAL_AFTERLIFE=Från efterlivet
BO1_MEDAL_AFTERLIFE_DESC=Dödade en fiende medans du själv var död.
BO1_MEDAL_DOUBLE_KILL=Dubbeldråp
BO1_MEDAL_DOUBLE_KILL_DESC=Dödade 2 fiender på kort stund.
BO1_MEDAL_TRIPLE_KILL=Trippeldråp
BO1_MEDAL_TRIPLE_KILL_DESC=Dödade 3 fiender på kort stund.
BO1_MEDAL_MULTI_KILL=Flerdråp
BO1_MEDAL_MULTI_KILL_DESC=Dödade fler än 3 fiender på kort stund.
BO1_MEDAL_FIRST_BLOOD=Första blodet
BO1_MEDAL_FIRST_BLOOD_DESC=Fick första dråpet.
BO1_MEDAL_BACK_STABBER=I ryggen
BO1_MEDAL_BACK_STABBER_DESC=Knivade en fiende i ryggen.
BO1_MEDAL_HIJACKER=Tjuv
BO1_MEDAL_HIJACKER_DESC=Stal en fientlig kista.
BO1_MEDAL_SHARE_PACKAGE=Paket delat
BO1_MEDAL_SHARE_PACKAGE_DESC=En lagkamrat räddade din kista.
BO1_MEDAL_ONE_SHOT_KILL=Ett skott, en död
BO1_MEDAL_ONE_SHOT_KILL_DESC=Dödade en fiende med ett skott.
BO1_MEDAL_PAYBACK=Hämnd
BO1_MEDAL_PAYBACK_DESC=Dödade fienden som dödade dig.
BO1_MEDAL_RESCUER=Räddare
BO1_MEDAL_RESCUER_DESC=Räddade en skadad lagkamrat.
BO1_MEDAL_ASSISTED_SUICIDE=Assisterat självmord
BO1_MEDAL_ASSISTED_SUICIDE_DESC=Skadade en fiende som tog livet av sig.
BO1_MEDAL_HEROIC=Utöver det vanliga
BO1_MEDAL_HEROIC_DESC=Erövrade en punkt i Andra Chans.
BO1_MEDAL_ASSISTS=Assist
BO1_MEDAL_ASSISTS_DESC=Hjälpte till med ett dråp.
BO1_MEDAL_DESTROYER=Krossad
BO1_MEDAL_DESTROYER_DESC=Förstörde ett fientligt fordon.
BO1_MEDAL_STREAKER=Seriekallare
BO1_MEDAL_STREAKER_DESC=Kallade in en Dråpserie.
BO1_MEDAL_HERO=Hjälte
BO1_MEDAL_HERO_DESC=Desarmerade bomben.
BO1_MEDAL_ANTI_BOMBER=Anti-bombare
BO1_MEDAL_ANTI_BOMBER_DESC=Dödade fienden som höll på att desarmera.
BO1_MEDAL_OFFENSE=Offensiv
BO1_MEDAL_OFFENSE_DESC=Dödade en fiende nära uppdragsmålet.
BO1_MEDAL_DEFENSE=Defensiv
BO1_MEDAL_DEFENSE_DESC=Dödade en fiende nära försvarspunkten.
BO1_MEDAL_POSITION_SECURE=Punkt säkrad
BO1_MEDAL_POSITION_SECURE_DESC=Tog ett uppdragsmål.
BO1_MEDAL_FLAG_RUNNER=Flaggspringare
BO1_MEDAL_FLAG_RUNNER_DESC=Plockade upp fiendens flagga.
BO1_MEDAL_FLAG_CAPTURE=Flagga erövrad
BO1_MEDAL_FLAG_CAPTURE_DESC=Erövrade fiendens flagga.
BO1_MEDAL_SABOTEUR=Sabotör
BO1_MEDAL_SABOTEUR_DESC=Armerade bomben.
BO1_MEDAL_BOMBER=Bombare
BO1_MEDAL_BOMBER_DESC=Sprängde bomben.
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=Förstörde en anti-spionplan.
BO1_MEDAL_DESTROYER_UAV_DESC=Förstörde ett spionplan.
BO1_MEDAL_DESTROYER_TURRET_DESC=Förstörde ett vaktgevär.
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=Förstörde en helikopter.
BO1_MEDAL_FLAG_RETURN=Flagga återvänd
BO1_MEDAL_FLAG_RETURN_DESC=Återvände flaggan.
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=Vaktgevär dråp
BO1_MEDAL_BALLISTIC_KNIFE_KILL=Grillspett
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=Sköt och dödade en fiende med Ballistiska kniven.
BO1_MEDAL_BANK_SHOT=Studsskott
BO1_MEDAL_BANK_SHOT_DESC=Dödade en fiende med en studsande Tomahawk.
BO1_MEDAL_REVIVE=Sjukvårdare
BO1_MEDAL_REVIVE_DESC=Återupplevde en skadad lagkamrat.
BO1_MEDAL_DESTROYER_M220_TOW=Avstängd
BO1_MEDAL_DESTROYER_M220_TOW_DESC=Skjöt ner en Valkyria.
BO1_MEDAL_DESTROYER_RCBOMB=Vägras
BO1_MEDAL_DESTROYER_RCBOMB_DESC=Förstörde en RC-XD.
BO1_MEDAL_AIRCRAFT_ASSIST=Assist krossare
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=Hjälpte till ett förstöra en fientlig dråpserie.

# Round Starter
BO1_MP_MATCH_STARTING_IN=MATCHEN BÖRJAR OM

# Other
BO1_MENU_WINNING_CAPS=VINNER
BO1_MENU_LOSING_CAPS=FÖRLORAR
BO1_MENU_TIED_CAPS=LIKA

BO1_MENU_WINNING=Vinner
BO1_MENU_TIED=Lika
BO1_MENU_LOSING=Förlorar

# Scoreboard
BO1_CGAME_SB_KILLS=Dråp
BO1_CGAME_SB_ASSISTS=Assists
BO1_CGAME_SB_KDRATIO=Snitt
BO1_CGAME_SB_SCORE=Poäng
BO1_CGAME_SB_DEATHS=Död
BO1_CGAME_SB_PING=Latens

# Gamemodes
BO1_OBJECTIVES_SD_ATTACKER_HINT=FÖRSTÖR UPPDRAGSMÅL A ELLER B
BO1_OBJECTIVES_SD_DEFENDER_HINT=FÖRSVARA UPPDRAGSMÅL A OCH B
BO1_OBJECTIVES_SAB_HINT=FÖRSTÖR FIENTLIGA UPPDRAGSMÅLET
BO1_OBJECTIVES_DOM_HINT=ERÖVRA OCH FÖRSVARA FLAGGORNA
BO1_OBJECTIVES_DM_HINT=ELIMINERA ANDRA SPELARE
BO1_OBJECTIVES_TDM_HINT=ELIMINERA FIENTLIGA SPELARE
BO1_OBJECTIVES_CTF_HINT=ERÖVRA FIENDENS FLAGGA
BO1_OBJECTIVES_DEM_ATTACKER_HINT=FÖRSTÖR UPPDRAGSMÅL A OCH B

# Notifications
BO1_RANK_PROMOTED_TO=Befordrad: Level %s!
BO1_RANK_PLAYER_WAS_PROMOTED=%s blev befordrad till %s!
  
# Ranks
BO1_RANK_PRVT_FULL=Private
BO1_RANK_PRVT_FULL2=Private I
BO1_RANK_PRVT_FULL3=Private II
BO1_RANK_PRVT_FULL_N=Private %s
BO1_RANK_PFC_FULL=Private First Class
BO1_RANK_PFC_FULL2=Private First Class I
BO1_RANK_PFC_FULL3=Private First Class II
BO1_RANK_PFC_FULL_N=Private First Class %s
BO1_RANK_SPC_FULL=Specialist
BO1_RANK_SPC_FULL2=Specialist I
BO1_RANK_SPC_FULL3=Specialist II
BO1_RANK_SPC_FULL_N=Specialist %s
BO1_RANK_CPL_FULL=Corporal
BO1_RANK_CPL_FULL2=Corporal I
BO1_RANK_CPL_FULL3=Corporal II
BO1_RANK_CPL_FULL_N=Corporal %s
BO1_RANK_SGT_FULL=Sergeant
BO1_RANK_SGT_FULL2=Sergeant I
BO1_RANK_SGT_FULL3=Sergeant II
BO1_RANK_SGT_FULL_N=Sergeant %s
BO1_RANK_SSGT_FULL=Staff Sergeant
BO1_RANK_SSGT_FULL2=Staff Sergeant I
BO1_RANK_SSGT_FULL3=Staff Sergeant II
BO1_RANK_SSGT_FULL_N=Staff Sergeant %s
BO1_RANK_SFC_FULL=Sergeant First Class
BO1_RANK_SFC_FULL2=Sergeant First Class I
BO1_RANK_SFC_FULL3=Sergeant First Class II
BO1_RANK_SFC_FULL_N=Sergeant First Class %s
BO1_RANK_SGTM_FULL=Sergeant Major
BO1_RANK_SGTM_FULL2=Sergeant Major I
BO1_RANK_SGTM_FULL3=Sergeant Major II
BO1_RANK_SGTM_FULL_N=Sergeant Major %s
BO1_RANK_LT_FULL=Lieutenant
BO1_RANK_LT_FULL2=Lieutenant I
BO1_RANK_LT_FULL3=Lieutenant II
BO1_RANK_LT_FULL_N=Lieutenant %s
BO1_RANK_CPT_FULL=Captain
BO1_RANK_CPT_FULL2=Captain I
BO1_RANK_CPT_FULL3=Captain II
BO1_RANK_CPT_FULL_N=Captain %s
BO1_RANK_MAJ_FULL=Major
BO1_RANK_MAJ_FULL2=Major I
BO1_RANK_MAJ_FULL3=Major II
BO1_RANK_MAJ_FULL_N=Major %s
BO1_RANK_LTCOL_FULL=Lieutenant Colonel
BO1_RANK_LTCOL_FULL2=Lieutenant Colonel I
BO1_RANK_LTCOL_FULL3=Lieutenant Colonel II
BO1_RANK_LTCOL_FULL_N=Lieutenant Colonel %s
BO1_RANK_COL_FULL=Colonel
BO1_RANK_COL_FULL2=Colonel I
BO1_RANK_COL_FULL3=Colonel II
BO1_RANK_COL_FULL_N=Colonel %s
BO1_RANK_BRIGGEN_FULL=Brigadier General
BO1_RANK_BRIGGEN_FULL2=Brigadier General I
BO1_RANK_BRIGGEN_FULL3=Brigadier General II
BO1_RANK_BRIGGEN_FULL_N=Brigadier General %s
BO1_RANK_MAJGEN_FULL=Major General
BO1_RANK_MAJGEN_FULL2=Major General I
BO1_RANK_MAJGEN_FULL3=Major General II
BO1_RANK_MAJGEN_FULL_N=Major General %s
BO1_RANK_LTGEN_FULL=Lieutenant General
BO1_RANK_LTGEN_FULL2=Lieutenant General I
BO1_RANK_LTGEN_FULL3=Lieutenant General II
BO1_RANK_LTGEN_FULL_N=Lieutenant General %s
BO1_RANK_GEN_FULL=General
BO1_RANK_COM_FULL=Commander
