#---------- Black Ops II HUD | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Factions
BO2_MP_SEALS_NAME=SEALS
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Legosoldater
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Milis

BO2_MPUI_SEALS_SHORT=SEALS
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Legosoldater
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Milis

BO2_MPUI_SEALS_SHORT_CAPS=SEALS
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=LEGOSOLDATER
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILIS

# Splashes
BO2_MEDAL_FIRST_KILL=FÖRSTA BLODET
BO2_MEDAL_ASSISTED_SUICIDE=ASSISTERAD SJÄLVMORD
BO2_MEDAL_HEADSHOT=HUVUDSKOTT
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=ÅTERKOMST
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=EFTERLIVET
BO2_MEDAL_LONGSHOT_KILL=LÅNGT SKOTT
BO2_MEDAL_REVENGE_KILL=HÄMND
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=ÖVERLEVARE
BO2_MEDAL_KILL_ENEMY_IN_AIR=LJUFTSKOTT
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=ETT SKOTT, EN DÖD
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=4-I-RAD
BO2_MEDAL_KILLSTREAK_5=BLODTÖRSTIG
BO2_MEDAL_KILLSTREAK_10=SKONINGSLÖS
BO2_MEDAL_KILLSTREAK_15=HÄNSYNSLÖS
BO2_MEDAL_KILLSTREAK_20=OBEVEKLIG
BO2_MEDAL_KILLSTREAK_25=BRUTAL
BO2_MEDAL_KILLSTREAK_30=NUKLEÄR
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=OSTOPPBAR
BO2_MEDAL_MULTIKILL_2=DUBBELDRÅP
BO2_MEDAL_MULTIKILL_3=TRIPPELDRÅP
BO2_MEDAL_MULTIKILL_4=VREDESDRÅP
BO2_MEDAL_MULTIKILL_5=FRENESIDRÅP
BO2_MEDAL_MULTIKILL_6=SUPERDRÅP
BO2_MEDAL_MULTIKILL_7=MEGADRÅP
BO2_MEDAL_MULTIKILL_8=ULTRA-DRÅP
BO2_MEDAL_MULTIKILL_MORE_THAN_8=DRÅPKEDJA
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=HÄMNARE
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=RÄDDARE

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s POÄNG FÖR ATT VINNA