#---------- CoD: World at War HUD | Svenska | Swedish -- CUSTOM
# Translator: Moka

# Factions
WAW_MPUI_RUSSIAN=Röda armén
WAW_MPUI_JAPANESE=Kejserliga armén
WAW_MPUI_GERMAN=Wehrmacht
WAW_MPUI_MARINE=Marine Raiders

WAW_MPUI_RUSSIAN_SHORT=Röda armén
WAW_MPUI_JAPANESE_SHORT=Kejserliga armén
WAW_MPUI_GERMAN_SHORT=Wehrmacht
WAW_MPUI_MARINE_SHORT=Marine Raiders

# Gamemodes
WAW_MPUI_TANK_WAR=Krig
WAW_OBJECTIVES_TWAR_HINT=Erövra flaggorna och försvara dem.