#---------- CoD HUD System Notifications | Svenska | Swedish
# Translator: Moka

CoDHUD.System.ResetTime=Matchtimer återställd till %s.
CoDHUD.System.ResetTime.Off=Matchtimer bortplockad.

CoDHUD.System.RestrictType=Spelet ändrades till %s.
CoDHUD.System.RestrictType.NotNow=Du kan inte ändra spel just nu.

CoDHUD.System.Faction.NotNow=Du kan inte byta team just nu.
CoDHUD.System.Faction.Denied=Du kan inte byta team.

CoDHUD.System.ChallengeReset=Alla utmaningar har återställts.
CoDHUD.System.RankReset=Rang och stats på '%s'-gränssnittet har återställts.

CoDHUD.System.CVChanged=Servervariabel '%s' ändrades till %s.

CoDHUD.System.ForceEndRound.NotNow=Du kan inte tvångsstoppa rundan just nu.
CoDHUD.System.ForceEndRound.NotStarting=Du kan inte tvångsstoppa rundan när en håller på att påbörja.