#---------- CoD4 HUD | 日本語 | Japanese
# Translator: Original Game

# Factions
CoD4_MPUI_MARINES=海兵隊武装偵察部隊
CoD4_MPUI_SPETSNAZ=スペツナズ
CoD4_MPUI_OPFOR=対抗部隊
CoD4_MPUI_SAS=S.A.S.

CoD4_MPUI_MARINES_SHORT=海兵隊
CoD4_MPUI_SPETSNAZ_SHORT=スペツナズ
CoD4_MPUI_OPFOR_SHORT=対抗部隊
CoD4_MPUI_SAS_SHORT=S.A.S.

# Challenges
CoD4_MP_CHALLENGE_COMPLETED=チャレンジ完了！