#---------- Black Ops II HUD | 日本語 | Japanese
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEALS
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercs
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Militia

BO2_MPUI_SEALS_SHORT=SEALS
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercs
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Militia

BO2_MPUI_SEALS_SHORT_CAPS=SEALS
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCS
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILITIA

# Splashes
BO2_MEDAL_FIRST_KILL=ファースト ブラッド
BO2_MEDAL_ASSISTED_SUICIDE=自滅アシスト
BO2_MEDAL_HEADSHOT=ヘッド ショット
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=カムバック
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=死に土産
BO2_MEDAL_LONGSHOT_KILL=ロング ショット
BO2_MEDAL_REVENGE_KILL=リベンジ
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=生存者
BO2_MEDAL_KILL_ENEMY_IN_AIR=エアショット
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=ワンショット ワンキル
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=四連フィード
BO2_MEDAL_KILLSTREAK_5=スチール ストリーク
BO2_MEDAL_KILLSTREAK_10=ブロンズ ストリーク
BO2_MEDAL_KILLSTREAK_15=シルバー ストリーク
BO2_MEDAL_KILLSTREAK_20=ゴールドストリーク
BO2_MEDAL_KILLSTREAK_25=プラチナ ストリーク
BO2_MEDAL_KILLSTREAK_30=アトミック ストリーク
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=セレリウム ストリーク
BO2_MEDAL_MULTIKILL_2=ダブルキル
BO2_MEDAL_MULTIKILL_3=トリプルキル
BO2_MEDAL_MULTIKILL_4=フューリー キル
BO2_MEDAL_MULTIKILL_5=フレンジー キル
BO2_MEDAL_MULTIKILL_6=スーパーキル
BO2_MEDAL_MULTIKILL_7=メガキル
BO2_MEDAL_MULTIKILL_8=ウルトラキル
BO2_MEDAL_MULTIKILL_MORE_THAN_8=キルチェーン
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=復讐者
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=救世主

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=勝利ポイント: %s
