#---------- Black Ops HUD | 日本語 | Japanese
# Translator: Original Game

# Factions
BO1_MP_TROPAS_NAME=TROPAS
BO1_MP_NVA_NAME=北ベトナム軍
BO1_MP_RUSSIAN_NAME=スペツナズ
BO1_MP_SPECOPS_NAME=ブラックオプス
BO1_MP_MARINE_NAME=SOG
BO1_MP_REBELS_NAME=OP40

BO1_MPUI_TROPAS_SHORT=TROPAS
BO1_MPUI_NVA_SHORT=北ベトナム軍
BO1_MPUI_RUSSIAN_SHORT=スペツナズ
BO1_MPUI_SPECOPS_SHORT=ブラックオプス
BO1_MPUI_MARINE_SHORT=SOG
BO1_MPUI_REBELS_SHORT=Op40

BO1_MPUI_TROPAS_SHORT_CAPS=TROPAS
BO1_MPUI_NVA_SHORT_CAPS=北ベトナム軍
BO1_MPUI_RUSSIAN_SHORT_CAPS=スペツナズ
BO1_MPUI_SPECOPS_SHORT_CAPS=ブラックオプス
BO1_MPUI_MARINE_SHORT_CAPS=SOG
BO1_MPUI_REBELS_SHORT_CAPS=Op40

# Splashes
BO1_MEDAL_BUZZ_KILL=キルストッパー
BO1_MEDAL_BUZZ_KILL_DESC=キルストリーク報酬を獲得する目前の敵を倒した
BO1_MEDAL_LONG_SHOT=ロングショット
BO1_MEDAL_LONG_SHOT_DESC=遠距離から敵を倒した
BO1_MEDAL_HEAD_SHOT=ヘッドショット
BO1_MEDAL_HEAD_SHOT_DESC="BOOM, HEADSHOT"
BO1_MEDAL_STUCK_TO_PLAYER=粘着気質
BO1_MEDAL_STUCK_TO_PLAYER_DESC=敵に粘着系爆発物をとりつけた
BO1_MEDAL_BULLS_EYE=トマホークキル
BO1_MEDAL_BULLS_EYE_DESC=トマホークで敵を倒した
BO1_MEDAL_EXECUTION=処刑人
BO1_MEDAL_EXECUTION_DESC=ダウンした敵をヘッドショットで倒した
BO1_MEDAL_COMEBACK=カムバック
BO1_MEDAL_COMEBACK_DESC=デスストリーク状態から盛り返した
BO1_MEDAL_AVENGER=復讐者
BO1_MEDAL_AVENGER_DESC=チームメイトを最近殺した敵を倒した
BO1_MEDAL_AFTERLIFE=死に土産
BO1_MEDAL_AFTERLIFE_DESC=死亡中に敵を倒した
BO1_MEDAL_DOUBLE_KILL=ダブルキル
BO1_MEDAL_DOUBLE_KILL_DESC=敵2人を続けざまに倒した
BO1_MEDAL_TRIPLE_KILL=トリプルキル
BO1_MEDAL_TRIPLE_KILL_DESC=続けざまに3人倒した
BO1_MEDAL_MULTI_KILL=マルチキル
BO1_MEDAL_MULTI_KILL_DESC=3人以上の敵を続けざまに倒した
BO1_MEDAL_FIRST_BLOOD=ファーストブラッド
BO1_MEDAL_FIRST_BLOOD_DESC=最初のキルをきめた
BO1_MEDAL_BACK_STABBER=バックスタバー
BO1_MEDAL_BACK_STABBER_DESC=プレイヤーを背中からナイフで刺した
BO1_MEDAL_HIJACKER=ハイジャック
BO1_MEDAL_HIJACKER_DESC=敵の箱を横取りした
BO1_MEDAL_SHARE_PACKAGE=シェアパッケージ
BO1_MEDAL_SHARE_PACKAGE_DESC=チームメイトが箱を確保してくれた
BO1_MEDAL_ONE_SHOT_KILL=ワンショット・ワンキル
BO1_MEDAL_ONE_SHOT_KILL_DESC=敵を1発で倒した
BO1_MEDAL_PAYBACK=復讐
BO1_MEDAL_PAYBACK_DESC=自分を殺した敵を倒した
BO1_MEDAL_RESCUER=救助者
BO1_MEDAL_RESCUER_DESC=負傷したチームメイトを救護した
BO1_MEDAL_ASSISTED_SUICIDE=セルフキルアシスト
BO1_MEDAL_ASSISTED_SUICIDE_DESC=負傷させた敵が自滅した
BO1_MEDAL_HEROIC=限界を超えて
BO1_MEDAL_HEROIC_DESC=セカンドチャンス中に拠点を確保した
BO1_MEDAL_ASSISTS=アシスト
BO1_MEDAL_ASSISTS_DESC=キルの達成をアシストした
BO1_MEDAL_DESTROYER=廃車確定
BO1_MEDAL_DESTROYER_DESC=敵の車両を破壊した
BO1_MEDAL_STREAKER=ストリーカー
BO1_MEDAL_STREAKER_DESC=キルストリーク報酬を発動した
BO1_MEDAL_HERO=ヒーロー
BO1_MEDAL_HERO_DESC=爆弾を解除した
BO1_MEDAL_ANTI_BOMBER=アンチサボタージュ
BO1_MEDAL_ANTI_BOMBER_DESC=爆弾を解除している敵を倒した
BO1_MEDAL_OFFENSE=攻勢に貢献
BO1_MEDAL_OFFENSE_DESC=目標地点近くで敵を倒した
BO1_MEDAL_DEFENSE=防衛に貢献
BO1_MEDAL_DEFENSE_DESC=防衛地点近くで敵を倒した
BO1_MEDAL_POSITION_SECURE=拠点確保
BO1_MEDAL_POSITION_SECURE_DESC=目標地点を確保した
BO1_MEDAL_FLAG_RUNNER=フラッグランナー
BO1_MEDAL_FLAG_RUNNER_DESC=敵のフラッグを取った
BO1_MEDAL_FLAG_CAPTURE=フラッグ奪取
BO1_MEDAL_FLAG_CAPTURE_DESC=敵のフラッグを持ち帰った
BO1_MEDAL_SABOTEUR=サボタージュ要員
BO1_MEDAL_SABOTEUR_DESC=爆弾を設置した
BO1_MEDAL_BOMBER=爆破成功
BO1_MEDAL_BOMBER_DESC=爆弾を起爆した
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=カウンター偵察機を撃墜した
BO1_MEDAL_DESTROYER_UAV_DESC=偵察機を撃墜した
BO1_MEDAL_DESTROYER_TURRET_DESC=ターレットを破壊した
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=ヘリコプターを撃墜した
BO1_MEDAL_FLAG_RETURN=フラッグ奪還
BO1_MEDAL_FLAG_RETURN_DESC=フラッグを取り返した
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=ターレットキル
BO1_MEDAL_BALLISTIC_KNIFE_KILL=串刺し
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=バリスティックナイフで敵を撃って倒した
BO1_MEDAL_BANK_SHOT=バンクショット
BO1_MEDAL_BANK_SHOT_DESC=物体に跳ね返ったトマホークで敵を倒した
BO1_MEDAL_REVIVE=衛生兵
BO1_MEDAL_REVIVE_DESC=倒れたチームメイトを蘇生した
BO1_MEDAL_DESTROYER_M220_TOW=送信終了
BO1_MEDAL_DESTROYER_M220_TOW_DESC=ヴァルキリーを破壊した
BO1_MEDAL_DESTROYER_RCBOMB=交通事故
BO1_MEDAL_DESTROYER_RCBOMB_DESC=RC‐XDを破壊した
BO1_MEDAL_AIRCRAFT_ASSIST=スクラップアシスト
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=航空機の撃墜をアシストした

# Round Starter
BO1_MP_MATCH_STARTING_IN=マッチ開始まで：

# Other
BO1_MENU_WINNING_CAPS=勝利
BO1_MENU_LOSING_CAPS=劣勢
BO1_MENU_TIED_CAPS=引き分け

BO1_MENU_WINNING=勝利
BO1_MENU_TIED=引き分け
BO1_MENU_LOSING=劣勢

# Scoreboard
BO1_CGAME_SB_KILLS=キル
BO1_CGAME_SB_ASSISTS=アシスト
BO1_CGAME_SB_KDRATIO=比率
BO1_CGAME_SB_SCORE=スコア
BO1_CGAME_SB_DEATHS=デス
BO1_CGAME_SB_PING=Ping

# Gamemodes
BO1_OBJECTIVES_SD_ATTACKER_HINT=目標AもしくはBを破壊せよ
BO1_OBJECTIVES_SD_DEFENDER_HINT=目標AおよびBを防衛しろ
BO1_OBJECTIVES_SAB_HINT=敵側の目標を破壊する
BO1_OBJECTIVES_DOM_HINT=フラッグを奪取したうえで守り抜け
BO1_OBJECTIVES_DM_HINT=他のプレイヤーを殲滅しろ
BO1_OBJECTIVES_TDM_HINT=敵プレイヤーの殲滅
BO1_OBJECTIVES_CTF_HINT=敵のフラッグを奪取しろ
BO1_OBJECTIVES_DEM_ATTACKER_HINT=目標AおよびBを破壊せよ
