#---------- CoD HUD System Notifications | 日本語 | Japanese
# Translator: Machine translated

CoDHUD.System.ResetTime=ラウンドタイマーが %s にリセットされました。
CoDHUD.System.ResetTime.Off=ラウンドタイマーが削除されました。

CoDHUD.System.RestrictType=ゲームが %s に変更されました。
CoDHUD.System.RestrictType.NotNow=現在ゲームを変更できません。

CoDHUD.System.Faction.NotNow=現在陣営を変更できません。
CoDHUD.System.Faction.Denied=陣営を変更できません。

CoDHUD.System.ChallengeReset=すべてのチャレンジがリセットされました。
CoDHUD.System.RankReset='%s' HUD のランクと統計がリセットされました。

CoDHUD.System.CVChanged=サーバー変数 '%s' が %s に変更されました。

CoDHUD.System.ForceEndRound.NotNow=現在ラウンドを強制終了できません。
CoDHUD.System.ForceEndRound.NotStarting=開始中のラウンドを強制終了することはできません。