#---------- Black Ops II HUD | 日本語 | Japanese
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEALS
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercs
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Militia

BO2_MPUI_SEALS_SHORT=SEALS
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercs
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Militia

BO2_MPUI_SEALS_SHORT_CAPS=SEALS
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCS
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILITIA

# Splashes
BO2_MEDAL_FIRST_KILL=ファースト ブラッド
BO2_MEDAL_ASSISTED_SUICIDE=自滅アシスト
BO2_MEDAL_HEADSHOT=ヘッド ショット
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=カムバック
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=死に土産
BO2_MEDAL_LONGSHOT_KILL=ロング ショット
BO2_MEDAL_REVENGE_KILL=リベンジ
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=生存者
BO2_MEDAL_KILL_ENEMY_IN_AIR=エアショット
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=ワンショット ワンキル
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=四連フィード
BO2_MEDAL_KILLSTREAK_5=スチール ストリーク
BO2_MEDAL_KILLSTREAK_10=ブロンズ ストリーク
BO2_MEDAL_KILLSTREAK_15=シルバー ストリーク
BO2_MEDAL_KILLSTREAK_20=ゴールドストリーク
BO2_MEDAL_KILLSTREAK_25=プラチナ ストリーク
BO2_MEDAL_KILLSTREAK_30=アトミック ストリーク
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=セレリウム ストリーク
BO2_MEDAL_MULTIKILL_2=ダブルキル
BO2_MEDAL_MULTIKILL_3=トリプルキル
BO2_MEDAL_MULTIKILL_4=フューリー キル
BO2_MEDAL_MULTIKILL_5=フレンジー キル
BO2_MEDAL_MULTIKILL_6=スーパーキル
BO2_MEDAL_MULTIKILL_7=メガキル
BO2_MEDAL_MULTIKILL_8=ウルトラキル
BO2_MEDAL_MULTIKILL_MORE_THAN_8=キルチェーン
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=復讐者
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=救世主

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=勝利ポイント: %s

# Notifications
BO2_RANK_PROMOTED=昇進した！
BO2_RANK_PLAYER_WAS_PROMOTED=%sが%sに昇進した！

# Ranks
BO2_RANK_PRVT_FULL=二等兵
BO2_RANK_PRVT_FULL2=二等兵II
BO2_RANK_PRVT_FULL3=二等兵III
BO2_RANK_PFC_FULL=上等兵
BO2_RANK_PFC_FULL2=上等兵II
BO2_RANK_PFC_FULL3=上等兵III
BO2_RANK_LCPL_FULL=上等兵
BO2_RANK_LCPL_FULL2=上等兵II
BO2_RANK_LCPL_FULL3=上等兵III
BO2_RANK_CPL_FULL=伍長
BO2_RANK_CPL_FULL2=伍長II
BO2_RANK_CPL_FULL3=伍長III
BO2_RANK_SGT_FULL=三等軍曹
BO2_RANK_SGT_FULL2=三等軍曹II
BO2_RANK_SGT_FULL3=三等軍曹III
BO2_RANK_SSGT_FULL=二等軍曹
BO2_RANK_SSGT_FULL2=二等軍曹II
BO2_RANK_SSGT_FULL3=二等軍曹III
BO2_RANK_GYSGT_FULL=米海兵隊一等軍曹
BO2_RANK_GYSGT_FULL2=米海兵隊一等軍曹II
BO2_RANK_GYSGT_FULL3=米海兵隊一等軍曹III
BO2_RANK_MSGT_FULL=曹長
BO2_RANK_MSGT_FULL2=曹長II
BO2_RANK_MSGT_FULL3=曹長III
BO2_RANK_MGYSGT_FULL=米海兵隊上級曹長
BO2_RANK_MGYSGT_FULL2=米海兵隊上級曹長II
BO2_RANK_MGYSGT_FULL3=米海兵隊上級曹長III
BO2_RANK_2NDLT_FULL=少尉
BO2_RANK_2NDLT_FULL2=少尉II
BO2_RANK_2NDLT_FULL3=少尉III
BO2_RANK_LT_FULL=中尉
BO2_RANK_LT_FULL2=中尉II
BO2_RANK_LT_FULL3=中尉III
BO2_RANK_CPT_FULL=大尉
BO2_RANK_CPT_FULL2=大尉II
BO2_RANK_CPT_FULL3=大尉III
BO2_RANK_MAJ_FULL=少佐
BO2_RANK_MAJ_FULL2=少佐II
BO2_RANK_MAJ_FULL3=少佐III
BO2_RANK_LTCOL_FULL=中佐
BO2_RANK_LTCOL_FULL2=中佐II
BO2_RANK_LTCOL_FULL3=中佐III
BO2_RANK_COL_FULL=大佐
BO2_RANK_COL_FULL2=大佐II
BO2_RANK_COL_FULL3=大佐III
BO2_RANK_BGEN_FULL=准将
BO2_RANK_BGEN_FULL2=准将II
BO2_RANK_BGEN_FULL3=准将III
BO2_RANK_MAJGEN_FULL=少将
BO2_RANK_MAJGEN_FULL2=少将II
BO2_RANK_MAJGEN_FULL3=少将III
BO2_RANK_LTGEN_FULL=中将
BO2_RANK_LTGEN_FULL2=中将II
BO2_RANK_LTGEN_FULL3=中将III
BO2_RANK_GEN_FULL=大将
BO2_RANK_GEN_FULL2=大将II
BO2_RANK_GEN_FULL3=大将III
BO2_RANK_COM_FULL=司令官
