#---------- Black Ops II HUD | Türkçe | Turkish (CUSTOM)
# Translator: landocalrissian

# Takımlar
BO2_MP_SEALS_NAME=SEALs
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercs
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Militia

BO2_MPUI_SEALS_SHORT=SEALs
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercs
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Militia

BO2_MPUI_SEALS_SHORT_CAPS=SEALS
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCS
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILITIA

# Madalya & Bildirimler
BO2_MEDAL_FIRST_KILL=İLK KAN
BO2_MEDAL_ASSISTED_SUICIDE=İNTİHARA YARDIM
BO2_MEDAL_HEADSHOT=TAM KAFADAN
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=GERİ DÖNÜŞ
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=ÖTEKİ TARAFTAN
BO2_MEDAL_LONGSHOT_KILL=UZAK MESAFE
BO2_MEDAL_REVENGE_KILL=İNTİKAM
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=AYAKTA KALAN
BO2_MEDAL_KILL_ENEMY_IN_AIR=HAVA ATIŞI
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=TEK ATIŞ, TEK ÖLÜM
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=DÖRDÜZ
BO2_MEDAL_KILLSTREAK_5=KANA SUSAMIŞ
BO2_MEDAL_KILLSTREAK_10=ACIMASIZ
BO2_MEDAL_KILLSTREAK_15=GADDAR
BO2_MEDAL_KILLSTREAK_20=DURDURULAMAZ
BO2_MEDAL_KILLSTREAK_25=VAHŞİ
BO2_MEDAL_KILLSTREAK_30=NÜKLEER
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=ENGELLENEMEZ
BO2_MEDAL_MULTIKILL_2=ÇİFTE ÖLDÜRME
BO2_MEDAL_MULTIKILL_3=ÜÇLÜ ÖLDÜRME
BO2_MEDAL_MULTIKILL_4=ÖFKE KIYIMI
BO2_MEDAL_MULTIKILL_5=ÇILGINLIK KIYIMI
BO2_MEDAL_MULTIKILL_6=SÜPER KIYIM
BO2_MEDAL_MULTIKILL_7=MEGA KIYIM
BO2_MEDAL_MULTIKILL_8=ULTRA KIYIM
BO2_MEDAL_MULTIKILL_MORE_THAN_8=ÖLÜM ZİNCİRİ
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=İNTİKAMCI
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=KURTARICI

# Diğer
BO2_MPUI_X_POINTS_TO_WIN_CAPS=KAZANMAYA %s PUAN
