#---------- CoD HUD Settings | Türkçe | Turkish (CUSTOM)
# Translator: landocalrissian

# ------------------[ GENEL ]------------------
CoDHUD.Title=CoD HUD

CoDHUD.Client=İstemci
CoDHUD.Server=Sunucu
CoDHUD.General=Genel

# CoDHUD.Close=Close

# CoDHUD.Default=Default: %s
# CoDHUD.Current=Current: %s

# ------------------[ MENU GLYPHS ]------------------
# CoDHUD.Glyph.Toggle=[+attack] Toggle
# CoDHUD.Glyph.Open=[+attack] Open
# CoDHUD.Glyph.OpenMenu=[+attack] Open Menu
# CoDHUD.Glyph.Select=[+attack] Select
# CoDHUD.Glyph.Confirm=[+attack] Confirm
# CoDHUD.Glyph.Return=[+attack] Return
# CoDHUD.Glyph.Close=[+attack] Close
# CoDHUD.Glyph.Tab=[+attack] Open Tab
# CoDHUD.Glyph.Reset=[+attack2] Reset

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
# CoDHUD.Admin.RoundStart=Round Controls

# CoDHUD.RoundStart.Gamemode=Gamemode
# CoDHUD.RoundStart.Info=Choose the gamemode to play.

CoDHUD.RoundStart.Start=Başlat
# CoDHUD.RoundStart.Start.desc=Once a gamemode is selected and settings are to your liking, you may begin the round start process.

CoDHUD.RoundStart.Notice=Yeni bir tur başlatmak istediğine emin misin?\nTüm skorlar sıfırlanacak ve tüm oyuncular yeniden doğacak.
CoDHUD.RoundStart.Yes=Başlat

CoDHUD.RoundStart.Timer=Tur Başlangıç Sayacı
CoDHUD.RoundStart.Timer.desc=Tur başlamadan önce kaç saniye bekleme süresi olacağını belirler.

CoDHUD.RoundStart.Autobalance=Tur Başında Takımları Rastgele Dağıt
CoDHUD.RoundStart.Autobalance.desc=Açıksa, tur başladığında tüm oyuncular geçerli bir takıma rastgele atanır.

CoDHUD.Scorelimit=Skor Limiti
CoDHUD.Scorelimit.desc=Skor sayacındaki maksimum skor limitini ayarlar.\n\nÖldürme sayısı cinsindendir.

CoDHUD.Timelimit=Süre Limiti
CoDHUD.Timelimit.desc=Turun otomatik bitmeden önceki süre limitini ayarlar.\n\nDakika cinsindendir.\n\nSınırsız için 0 olarak ayarla.

CoDHUD.Autobalance.Amount=Otomatik Denge Takım Limiti
CoDHUD.Autobalance.Amount.desc=Oyuncuların otomatik dengelenebileceği en fazla takım sayısını belirler.

CoDHUD.Autobalance.Amount.disable=Devre Dışı
CoDHUD.Autobalance.Amount.2=2 Takım
CoDHUD.Autobalance.Amount.3=3 Takım
CoDHUD.Autobalance.Amount.4=4 Takım

CoDHUD.RoundStart.Auto=Sunucu Başladığında Turu Otomatik Başlat
CoDHUD.RoundStart.Auto.desc=Açıksa, sunucuya ilk oyuncu katıldığı anda yeni bir tur hemen başlar.

CoDHUD.Admin.ResetTime=Tur Sayacını Sıfırla
CoDHUD.Admin.ResetTime.desc=Mevcut tur sayacını anlık değerinden Süre Limiti değerine sıfırlar.

# CoDHUD.ForceEndRound=Force-Stop the Round
# CoDHUD.ForceEndRound.desc=Click here if you need to, or want to, end the round before the score or time limit is reached.

# CoDHUD.ForceEndRound.Notice=Are you sure you want to forcefully end the round?

# ---------[ TUR SONU ]---------
CoDHUD.Admin.EndScreen="Maç Sonu" Ekranını Aç
CoDHUD.Admin.EndScreen.desc=Skor limitine ulaşıldığında "maç sonu" sistemini devreye sokar.

CoDHUD.Admin.EndScreen.StartNext=Maç Sonu'nun ardından Yeni Tur Başlasın mı?
CoDHUD.Admin.EndScreen.StartNext.desc=Açıksa, maç sonu süresi dolduğunda yeni bir tur başlar.\n\nKapalıysa, oyuncular normal şekilde yeniden doğar.

MW2HUD.Admin.FriendlyFire=Dost ateşine izin ver.
MW2HUD.Admin.FriendlyFire.desc=Açıksa, oyuncular aynı takımdaki diğer oyunculara hasar verebilir hale gelir.

# ---------[ TAKIM & HUD TİPİ KISITLAMA ]---------
CoDHUD.Admin.RestrictType=Takımları ve HUD Tipini Kısıtla
CoDHUD.Admin.RestrictType.Choose=Oyun Seç
CoDHUD.Admin.RestrictType.desc=Kullanıcıları hangi CoD oyununa kısıtlayacağını seç. Bu, HUD'u ve hangi takımların açık olacağını etkiler.

CoDHUD.Admin.RestrictType.Warning=Uyarı!\nOyunu değiştirmenin şu sonuçları olacak:\n- Tüm oyuncuların takımları rastgele seçilecek.\n- Tüm oyuncu skorları sıfırlanacak.\n- Tüm oyuncular öldürülüp yeniden doğacak.\n\nOyunu değiştirmek istediğine hala emin misin?

CoDHUD.Type.cod4=Modern Warfare 1
CoDHUD.Type.waw=World at War
CoDHUD.Type.mw2=Modern Warfare 2
CoDHUD.Type.bo1=Black Ops
CoDHUD.Type.mw3=Modern Warfare 3
CoDHUD.Type.bo2=Black Ops II
CoDHUD.Type.ghosts=Ghosts
CoDHUD.Type.aw=Advanced Warfare
CoDHUD.Type.bo3=Black Ops III
CoDHUD.Type.iw=Infinite Warfare
CoDHUD.Type.ww2=WWII

CoDHUD.Admin.RestrictFactionChance=Takım Değiştirmeyi Kısıtla
CoDHUD.Admin.RestrictFactionChance.desc=Oyuncuların ne zaman takım değiştirebileceğini seç.

CoDHUD.Admin.RestrictFactionChance.disable=Değiştiremez
CoDHUD.Admin.RestrictFactionChance.freely=Serbestçe Değiştirebilir
CoDHUD.Admin.RestrictFactionChance.pool=Yalnızca Aktif Havuzdan

# ------------------[ İSTEMCİ AYARLARI ]------------------
# ---------[ TAKIM AYARLARI ]---------
CoDHUD.Faction.Select=Takım Seç
CoDHUD.Faction.Select.desc=Hangi takımı temsil edeceğini seç.\nDost-düşman durumunu etkiler; spikerini ve müziğini takımına göre değiştirir.

CoDHUD.Faction.ChangeWarning=Uyarı!\nTakım değiştirmenin şu sonuçları olacak:\n- Skorun sıfırlanacak.\n- Öldürülüp yeniden doğacaksın.\n\nTakım değiştirmek istediğine hala emin misin?

# ---------[ HIZLI ERİŞİM ]---------
CoDHUD.Quick.title=Hızlı Erişim

CoDHUD.Quick.DisableHUD=Tüm HUD Seçeneklerini Anında Kapat
CoDHUD.Quick.DisableHUD.desc=Tüm CoD HUD seçeneklerini devre dışı bırakır.

# ---------[ HUD AYARLARI ]---------
CoDHUD.Enable.Options=HUD Ayarları

# Genel
CoDHUD.HUD.Outline=Çerçeveli Yazı
CoDHUD.HUD.Outline.desc=Bazı öğelerin yazılarına çerçeve ekler; aşırı aydınlık sahnelerde okumayı kolaylaştırır.

CoDHUD.HUD.Sound=Ses Efektlerini Çal
CoDHUD.HUD.Sound.desc=HUD Tipi destekliyorsa, ilgili ses efektlerini çalar.

CoDHUD.HUD.Time.Total=Ekranda Kalma Süresi
CoDHUD.HUD.Time.Total.desc=Öğe tamamen belirdikten sonra, kaybolmaya başlamadan önce ekranda kalma süresi.

CoDHUD.HUD.Time.Fadein=Belirme Süresi
CoDHUD.HUD.Time.Fadein.desc=Bu öğenin ekranda belirme süresi.

CoDHUD.HUD.Time.Fadeout=Kaybolma Süresi
CoDHUD.HUD.Time.Fadeout.desc=Bu öğenin ekrandan kaybolma süresi.

# Ölçek
CoDHUD.HUD.Scale=Arayüz Ölçeği

CoDHUD.HUD.Scale.Enable=Ölçek Çarpanı
CoDHUD.HUD.Scale.Enable.desc=Arayüz öğelerinin boyutunu büyütür ya da küçültür.\n\nDüşük veya ultrawide çözünürlüklerde işe yarar.

# Skor Tablosu
CoDHUD.HUD.Scoreboard=Skor Tablosu

CoDHUD.HUD.Scoreboard.Enable=Skor Tablosunu Aç
CoDHUD.HUD.Scoreboard.Enable.desc=Temalı skor tablosunu açar. Oyuncuların bulunduğu takımları listeler.

# Skor Sayacı
CoDHUD.HUD.Scorecounter=Skor Sayacı

CoDHUD.HUD.Scorecounter.Enable=Skor Sayacını Aç
CoDHUD.HUD.Scorecounter.Enable.desc=Temalı sunucu zamanlayıcısını, takım ikonunu ve skor sayaçlarını açar.\n\nBazı HUD tiplerinde takım ikonu gösterilmez.

# Madalyalar
CoDHUD.HUD.Medals=Madalyalar

CoDHUD.HUD.Medals.Enable=Madalyaları Aç
CoDHUD.HUD.Medals.Enable.desc=Belirli aksiyonlarla (hızlı öldürme, kafadan atış vs.) kazanılan temalı madalyaları açar.\n\nBazı HUD tiplerinde sadece yazı, bazılarında yazı ve ikon gözükür.

CoDHUD.HUD.Medals.Speedup=Sıra Uzunsa Hızlandır
CoDHUD.HUD.Medals.Speedup.desc=Aynı anda birden çok madalya birikirse sırayı hızlandırır.\n\nHUD Tipine göre, 3'ten fazla madalya sırada bekliyorsa ses efektlerini de devre dışı bırakır.

# Öldürme Akışı
CoDHUD.HUD.Options.Killfeed=Öldürme Akışı

CoDHUD.HUD.Killfeed.Enable=Öldürme Akışını Aç
CoDHUD.HUD.Killfeed.Enable.desc=Temalı öldürme akışını (kill feed) açar.

# Mini Harita
CoDHUD.HUD.Minimap=Mini Harita

CoDHUD.HUD.Minimap.Enable=Mini Haritayı Aç
CoDHUD.HUD.Minimap.Enable.desc=Temalı mini haritayı açar.

# İsabet İşareti
CoDHUD.HUD.Hitmarker=İsabet İşareti (Hitmarker)

CoDHUD.HUD.Hitmarker.Enable=İsabet İşaretini Aç
CoDHUD.HUD.Hitmarker.Enable.desc=Temalı isabet işaretini (hitmarker) ve ses efektini açar.

# Silah Bilgisi
CoDHUD.HUD.WeaponInfo=Silah Bilgisi

CoDHUD.HUD.WeaponInfo.Enable=Silah Bilgisini Aç
CoDHUD.HUD.WeaponInfo.Enable.desc=Silah adını ve mermi sayacını gösteren temalı silah panelini açar.\n\nBazı HUD tiplerinde pusula da buraya entegredir.

CoDHUD.HUD.WeaponPrompts.Enable=Silah Uyarılarını Aç
CoDHUD.HUD.WeaponPrompts.Enable.desc=Düşük mermi bildirimi gibi temalı silah uyarılarını açar.

# XP Sayacı
CoDHUD.HUD.XP=XP Bildirimi

CoDHUD.HUD.XP.Enable=XP Bildirimini Aç
CoDHUD.HUD.XP.Enable.desc=Temalı XP bildirimini açar.

# Hedef Kimliği / Dost-Düşman
CoDHUD.HUD.IFF=Dost-Düşman Tanımlama

CoDHUD.HUD.IFF.Enable=Dost-Düşman Tanımlamayı Aç
CoDHUD.HUD.IFF.Enable.desc=Temalı "Dost-Düşman Tanımlama" sistemini açar; hedefin yakınına nişan aldığında adını başının üstünde gösterir.

# Ölüm İkonu
CoDHUD.HUD.DeathIcon=Ölüm İkonu

CoDHUD.HUD.DeathIcon.Enable=Ölüm İkonunu Aç
CoDHUD.HUD.DeathIcon.Enable.desc=Aynı takımdan bir oyuncu öldüğünde o konumda beliren ölüm ikonunu açar.

# Sohbet
CoDHUD.HUD.Chat=Sohbet

CoDHUD.HUD.Chat.Enable=Sohbeti Aç
CoDHUD.HUD.Chat.Enable.desc=Temalı sohbeti açar.

# Görevler
CoDHUD.HUD.Challenges=Görevler

CoDHUD.HUD.Challenges.Enable=Görev Bildirimlerini Aç
CoDHUD.HUD.Challenges.Enable.desc=Temalı görev bildirimlerini açar.\n\nGörevlerin takibini ya da açılmasını etkilemez.

# ---------[ DİĞER AYARLAR ]---------
CoDHUD.Settings=Diğer Ayarlar
# CoDHUD.Audio=Audio Settings
CoDHUD.Audio.Announcer=Spiker
CoDHUD.Audio.Music=Müzik

CoDHUD.Audio.Announcer.Enable=Spiker Sesini Aç
CoDHUD.Audio.Announcer.Enable.desc=Spikeri etkinleştirir.

CoDHUD.Audio.Announcer.English=İngilizce Spikeri Zorla
CoDHUD.Audio.Announcer.English.desc=Oyun dili ne olursa olsun spikerin İngilizce seslerini oynatır.

CoDHUD.Audio.Music.Enable=Müziği Aç
CoDHUD.Audio.Music.Enable.desc=Müziği etkinleştirir.

CoDHUD.Audio.Music.Ambient=Ortam Müziğini Aç
CoDHUD.Audio.Music.Ambient.desc=Arka planda çalan ortam müziğini etkinleştirir.

# CoDHUD.Reset=Reset Settings
CoDHUD.Challenges.Reset=Görevleri Sıfırla
CoDHUD.Challenges.Reset.desc=Kilidi açılmış tüm görevleri sıfırlar.

# CoDHUD.Rank.Reset=Reset Rank & Stats
# CoDHUD.Rank.Reset.desc=Resets the rank and all stats on the current HUD.
# CoDHUD.Rank.Reset.Warning=Warning!\nYou're about to reset your rank and stats on this HUD!\nThis cannot be undone! Are you sure you want to reset your rank and stats?

CoDHUD.Menu=Menü Ayarları
CoDHUD.Menu.Fullscreen=Tam Ekran Olarak Aç
CoDHUD.Menu.Fullscreen.desc=CoD HUD Menüsünü küçük pencere yerine tam ekran olarak açar.

# CoDHUD.Menu.SFX=Menu SFX
# CoDHUD.Menu.SFX.desc=Play themed menu sound effects when hovering over or pressing buttons.

# CoDHUD.Menu.Music=Menu Music
# CoDHUD.Menu.Music.desc=Play themed menu music when any CoD HUD Menu instance is active.

# CoDHUD.Menu.HideDesc=Hide Description
# CoDHUD.Menu.HideDesc.desc=If enabled, the menu descriptions will be hidden.

# CoDHUD.Menu.HidePrompts=Hide Prompts
# CoDHUD.Menu.HidePrompts.desc=If enabled, the button prompts in the menu will be hidden.

# CoDHUD.Menu.OpenSpeed=Menu Open Speed
# CoDHUD.Menu.OpenSpeed.desc=How quickly the CoD HUD Menu will open new instances.\n\nMeasured in seconds.

# CoDHUD.Menu.CloseSpeed=Menu Close Speed
# CoDHUD.Menu.CloseSpeed.desc=How quickly the CoD HUD Menu will close instances.\n\nMeasured in seconds.

# ---------[ RANK & STATS ]---------
# CoDHUD.Stats=Player Stats
# CoDHUD.Stats.Rank=Player Level: %d - %s
# CoDHUD.Stats.XPNext=XP for Next Rank: %d
# CoDHUD.Stats.XP=Total XP: %d
# CoDHUD.Stats.Kills=Total Kills: %d
# CoDHUD.Stats.Headshots=Headshots: %d
# CoDHUD.Stats.Deaths=Total Deaths: %d
# CoDHUD.Stats.Challenges=Challenges Completed: %d

# CoDHUD.Stats.Unknown=Unknown