#---------- Black Ops II HUD | English
# Translator: Original Game

# Factions
# BO2_MP_SEALS_NAME=SEALS
# BO2_MP_PLA_NAME=SDC
# BO2_MP_FBI_NAME=FBI
# BO2_MP_PMC_NAME=Mercs
# BO2_MP_ISA_NAME=ISA
# BO2_MP_CD_NAME=Militia

# BO2_MPUI_SEALS_SHORT=SEALS
# BO2_MPUI_PLA_SHORT=SDC
# BO2_MPUI_FBI_SHORT=FBI
# BO2_MPUI_PMC_SHORT=Mercs
# BO2_MPUI_ISA_SHORT=ISA
# BO2_MPUI_CD_SHORT=Militia

# BO2_MPUI_SEALS_SHORT_CAPS=SEALS
# BO2_MPUI_PLA_SHORT_CAPS=SDC
# BO2_MPUI_FBI_SHORT_CAPS=FBI
# BO2_MPUI_PMC_SHORT_CAPS=MERCS
# BO2_MPUI_ISA_SHORT_CAPS=ISA
# BO2_MPUI_CD_SHORT_CAPS=MILITIA

# Splashes
# BO2_MEDAL_FIRST_KILL=FIRST BLOOD
# BO2_MEDAL_ASSISTED_SUICIDE=ASSISTED SUICIDE
# BO2_MEDAL_HEADSHOT=HEADSHOT
# BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=COMEBACK
# BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=AFTERLIFE
# BO2_MEDAL_LONGSHOT_KILL=LONG SHOT
# BO2_MEDAL_REVENGE_KILL=REVENGE
# BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=SURVIVOR
# BO2_MEDAL_KILL_ENEMY_IN_AIR=AIRSHOT
# BO2_MEDAL_KILL_ENEMY_ONE_BULLET=ONE SHOT, ONE KILL
# BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=QUAD FEED
# BO2_MEDAL_KILLSTREAK_5=BLOODTHIRSTY
# BO2_MEDAL_KILLSTREAK_10=MERCILESS
# BO2_MEDAL_KILLSTREAK_15=RUTHLESS
# BO2_MEDAL_KILLSTREAK_20=RELENTLESS
# BO2_MEDAL_KILLSTREAK_25=BRUTAL
# BO2_MEDAL_KILLSTREAK_30=NUCLEAR
# BO2_MEDAL_KILLSTREAK_MORE_THAN_30=UNSTOPPABLE
# BO2_MEDAL_MULTIKILL_2=DOUBLE KILL
# BO2_MEDAL_MULTIKILL_3=TRIPLE KILL
# BO2_MEDAL_MULTIKILL_4=FURY KILL
# BO2_MEDAL_MULTIKILL_5=FRENZY KILL
# BO2_MEDAL_MULTIKILL_6=SUPER KILL
# BO2_MEDAL_MULTIKILL_7=MEGA KILL
# BO2_MEDAL_MULTIKILL_8=ULTRA KILL
# BO2_MEDAL_MULTIKILL_MORE_THAN_8=KILL CHAIN
# BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=AVENGER
# BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=SAVIOR

# Other
# BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s POINTS TO WIN