#---------- Black Ops HUD | Türkçe | Turkish (CUSTOM)
# Translator: landocalrissian

# Takımlar
BO1_MP_TROPAS_NAME=TROPAS
BO1_MP_NVA_NAME=NVA
BO1_MP_RUSSIAN_NAME=SPETSNAZ
BO1_MP_SPECOPS_NAME=BLACK OPS
BO1_MP_MARINE_NAME=SOG
BO1_MP_REBELS_NAME=OP 40

BO1_MPUI_TROPAS_SHORT=Tropas
BO1_MPUI_NVA_SHORT=NVA
BO1_MPUI_RUSSIAN_SHORT=Spetsnaz
BO1_MPUI_SPECOPS_SHORT=Black Ops
BO1_MPUI_MARINE_SHORT=SOG
BO1_MPUI_REBELS_SHORT=Op 40

BO1_MPUI_TROPAS_SHORT_CAPS=TROPAS
BO1_MPUI_NVA_SHORT_CAPS=NVA
BO1_MPUI_RUSSIAN_SHORT_CAPS=SPETSNAZ
BO1_MPUI_SPECOPS_SHORT_CAPS=BLACK OPS
BO1_MPUI_MARINE_SHORT_CAPS=SOG
BO1_MPUI_REBELS_SHORT_CAPS=OP 40

# Madalya & Bildirimler
BO1_MEDAL_BUZZ_KILL=Keyif Kaçıran
BO1_MEDAL_BUZZ_KILL_DESC=Düşmanın öldürme serisini eşiğin altında kestin.
BO1_MEDAL_LONG_SHOT=Uzak Mesafe
BO1_MEDAL_LONG_SHOT_DESC=Bir düşmanı uzaktan indirdin.
BO1_MEDAL_HEAD_SHOT=Tam Kafadan
BO1_MEDAL_HEAD_SHOT_DESC=Pat, tam kafadan.
BO1_MEDAL_STUCK_TO_PLAYER=Yapıştı
BO1_MEDAL_STUCK_TO_PLAYER_DESC=Düşmana patlayıcı yapıştırdın.
BO1_MEDAL_BULLS_EYE=Kafa Derisi
BO1_MEDAL_BULLS_EYE_DESC=Bir düşmanı Tomahawk ile indirdin.
BO1_MEDAL_EXECUTION=İnfaz
BO1_MEDAL_EXECUTION_DESC=Yerdeki düşmanı kafadan vurarak bitirdin.
BO1_MEDAL_COMEBACK=Geri Dönüş
BO1_MEDAL_COMEBACK_DESC=Üst üste ölmekten kendini topladın.
BO1_MEDAL_AVENGER=İntikamcı
BO1_MEDAL_AVENGER_DESC=Az önce takım arkadaşını öldüren düşmanı indirdin.
BO1_MEDAL_AFTERLIFE=Öteki Taraftan
BO1_MEDAL_AFTERLIFE_DESC=Öldükten sonra bir düşmanı alt ettin.
BO1_MEDAL_DOUBLE_KILL=Çifte Öldürme
BO1_MEDAL_DOUBLE_KILL_DESC=Üst üste 2 düşman öldürdün.
BO1_MEDAL_TRIPLE_KILL=Üçlü Öldürme
BO1_MEDAL_TRIPLE_KILL_DESC=Üst üste 3 düşman öldürdün.
BO1_MEDAL_MULTI_KILL=Çoklu Öldürme
BO1_MEDAL_MULTI_KILL_DESC=Üst üste 3'ten fazla düşman öldürdün.
BO1_MEDAL_FIRST_BLOOD=İlk Kan
BO1_MEDAL_FIRST_BLOOD_DESC=İlk öldürme senin.
BO1_MEDAL_BACK_STABBER=Sırttan Bıçaklayan
BO1_MEDAL_BACK_STABBER_DESC=Bir oyuncuyu arkadan bıçakladın.
BO1_MEDAL_HIJACKER=Gaspçı
BO1_MEDAL_HIJACKER_DESC=Düşmanın sandığını çaldın.
BO1_MEDAL_SHARE_PACKAGE=Paylaşılan Paket
BO1_MEDAL_SHARE_PACKAGE_DESC=Bir takım arkadaşın sandığını kurtardı.
BO1_MEDAL_ONE_SHOT_KILL=Tek Atış, Tek Ölüm
BO1_MEDAL_ONE_SHOT_KILL_DESC=Bir düşmanı tek atışta indirdin.
BO1_MEDAL_PAYBACK=Rövanş
BO1_MEDAL_PAYBACK_DESC=Seni öldüren düşmanı sen de öldürdün.
BO1_MEDAL_RESCUER=Kurtarıcı
BO1_MEDAL_RESCUER_DESC=Yaralı takım arkadaşını kurtardın.
BO1_MEDAL_ASSISTED_SUICIDE=İntihara Yardım
BO1_MEDAL_ASSISTED_SUICIDE_DESC=Kendini öldüren düşmanı önce sen yaralamıştın.
BO1_MEDAL_HEROIC=Destansı
BO1_MEDAL_HEROIC_DESC=Second Chance'deyken bir hedef aldın.
BO1_MEDAL_ASSISTS=Asist
BO1_MEDAL_ASSISTS_DESC=Bir öldürmeye asist yaptın.
BO1_MEDAL_DESTROYER=Hurda
BO1_MEDAL_DESTROYER_DESC=Bir düşman aracını yok ettin.
BO1_MEDAL_STREAKER=Seri Yakalayıcı
BO1_MEDAL_STREAKER_DESC=Bir Killstreak çağırdın.
BO1_MEDAL_HERO=Kahraman
BO1_MEDAL_HERO_DESC=Bombayı etkisiz hale getirdin.
BO1_MEDAL_ANTI_BOMBER=Bomba Avcısı
BO1_MEDAL_ANTI_BOMBER_DESC=Bombayı etkisizleştiren düşmanı öldürdün.
BO1_MEDAL_OFFENSE=Saldırı
BO1_MEDAL_OFFENSE_DESC=Hedefin yakınında bir düşman öldürdün.
BO1_MEDAL_DEFENSE=Savunma
BO1_MEDAL_DEFENSE_DESC=Savunma noktasının yakınında bir düşman öldürdün.
BO1_MEDAL_POSITION_SECURE=Mevzi Güvende
BO1_MEDAL_POSITION_SECURE_DESC=Bir hedefi ele geçirdin.
BO1_MEDAL_FLAG_RUNNER=Bayrak Taşıyıcı
BO1_MEDAL_FLAG_RUNNER_DESC=Düşman bayrağını aldın.
BO1_MEDAL_FLAG_CAPTURE=Bayrak Ele Geçirme
BO1_MEDAL_FLAG_CAPTURE_DESC=Düşman bayrağını ele geçirdin.
BO1_MEDAL_SABOTEUR=Sabotajcı
BO1_MEDAL_SABOTEUR_DESC=Bombayı yerleştirdin.
BO1_MEDAL_BOMBER=Bombacı
BO1_MEDAL_BOMBER_DESC=Bombayı patlattın.
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=Bir Karşı-Casus Uçağı düşürdün.
BO1_MEDAL_DESTROYER_UAV_DESC=Bir Casus Uçağı düşürdün.
BO1_MEDAL_DESTROYER_TURRET_DESC=Bir taretmi indirdin.
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=Bir helikopter düşürdün.
BO1_MEDAL_FLAG_RETURN=Bayrak İadesi
BO1_MEDAL_FLAG_RETURN_DESC=Bayrağı geri getirdin.
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=Taret Avı
BO1_MEDAL_BALLISTIC_KNIFE_KILL=Şiş
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=Bir düşmanı Balistik Bıçak ile vurarak öldürdün.
BO1_MEDAL_BANK_SHOT=Sektirme
BO1_MEDAL_BANK_SHOT_DESC=Tomahawk'ı sektirip bir düşman öldürdün.
BO1_MEDAL_REVIVE=Sıhhiye
BO1_MEDAL_REVIVE_DESC=Düşen bir takım arkadaşını dirilttin.
BO1_MEDAL_DESTROYER_M220_TOW=Yayından Düştü
BO1_MEDAL_DESTROYER_M220_TOW_DESC=Bir Valkyrie indirdin.
BO1_MEDAL_DESTROYER_RCBOMB=Yol Öfkesi
BO1_MEDAL_DESTROYER_RCBOMB_DESC=Bir RC-XD indirdin.
BO1_MEDAL_AIRCRAFT_ASSIST=Hurda Asisti
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=Bir düşman hava aracının düşürülmesine yardım ettin.

# Maç Başlatıcı
BO1_MP_MATCH_STARTING_IN=MAÇIN BAŞLAMASINA

# Diğer
BO1_MENU_WINNING_CAPS=KAZANIYORUZ
BO1_MENU_LOSING_CAPS=KAYBEDİYORUZ
BO1_MENU_TIED_CAPS=BERABERE

BO1_MENU_WINNING=Kazanıyoruz
BO1_MENU_TIED=Berabere
BO1_MENU_LOSING=Kaybediyoruz

# Skor Tablosu
BO1_CGAME_SB_KILLS=Öldürme
BO1_CGAME_SB_ASSISTS=Asist
BO1_CGAME_SB_KDRATIO=Ö. Oranı
BO1_CGAME_SB_SCORE=Skor
BO1_CGAME_SB_DEATHS=Ölüm
BO1_CGAME_SB_PING=Gecikme

# Oyun Modları
BO1_OBJECTIVES_SD_ATTACKER_HINT=A VEYA B HEDEFİNİ YOK ET
BO1_OBJECTIVES_SD_DEFENDER_HINT=A VE B HEDEFLERİNİ KORU
BO1_OBJECTIVES_SAB_HINT=DÜŞMAN HEDEFİNİ YOK ET
BO1_OBJECTIVES_DOM_HINT=BAYRAKLARI ELE GEÇİR VE SAVUN
BO1_OBJECTIVES_DM_HINT=DİĞER OYUNCULARI ELİMİNE ET
BO1_OBJECTIVES_TDM_HINT=DÜŞMAN OYUNCULARI ELİMİNE ET
BO1_OBJECTIVES_CTF_HINT=DÜŞMAN BAYRAĞINI ELE GEÇİR
BO1_OBJECTIVES_DEM_ATTACKER_HINT=A VE B HEDEFLERİNİ YOK ET
