#---------- Black Ops Ranks | Polska | Polish
# Translator: Original Game

# Notifications
BO1_RANK_PROMOTED_TO=Awans: Poziom %s
BO1_RANK_PLAYER_WAS_PROMOTED=%s - awans na: %s!
  
# Ranks
BO1_RANK_PRVT_FULL=Szeregowy
BO1_RANK_PRVT_FULL2=Szeregowy I
BO1_RANK_PRVT_FULL3=Szeregowy II
BO1_RANK_PRVT_FULL_N=Szeregowy %s
BO1_RANK_PFC_FULL=Starszy szeregowy
BO1_RANK_PFC_FULL2=Starszy szeregowy I
BO1_RANK_PFC_FULL3=Starszy szeregowy II
BO1_RANK_PFC_FULL_N=Starszy szeregowy %s
BO1_RANK_SPC_FULL=Specjalista
BO1_RANK_SPC_FULL2=Specjalista I
BO1_RANK_SPC_FULL3=Specjalista II
BO1_RANK_SPC_FULL_N=Specjalista %s
BO1_RANK_CPL_FULL=Kapral
BO1_RANK_CPL_FULL2=Kapral I
BO1_RANK_CPL_FULL3=Kapral II
BO1_RANK_CPL_FULL_N=Kapral %s
BO1_RANK_SGT_FULL=Sierżant
BO1_RANK_SGT_FULL2=Sierżant I
BO1_RANK_SGT_FULL3=Sierżant II
BO1_RANK_SGT_FULL_N=Sierżant %s
BO1_RANK_SSGT_FULL=Sierżant sztabowy
BO1_RANK_SSGT_FULL2=Sierżant sztabowy I
BO1_RANK_SSGT_FULL3=Sierżant sztabowy II
BO1_RANK_SSGT_FULL_N=Sierżant sztabowy %s
BO1_RANK_SFC_FULL=Starszy sierżant
BO1_RANK_SFC_FULL2=Starszy sierżant I
BO1_RANK_SFC_FULL3=Starszy sierżant II
BO1_RANK_SFC_FULL_N=Starszy sierżant %s
BO1_RANK_SGTM_FULL=Chorąży
BO1_RANK_SGTM_FULL2=Chorąży I
BO1_RANK_SGTM_FULL3=Chorąży II
BO1_RANK_SGTM_FULL_N=Chorąży %s
BO1_RANK_LT_FULL=Porucznik
BO1_RANK_LT_FULL2=Porucznik I
BO1_RANK_LT_FULL3=Porucznik II
BO1_RANK_LT_FULL_N=Porucznik %s
BO1_RANK_CPT_FULL=Kapitan
BO1_RANK_CPT_FULL2=Kapitan I
BO1_RANK_CPT_FULL3=Kapitan II
BO1_RANK_CPT_FULL_N=Kapitan %s
BO1_RANK_MAJ_FULL=Major
BO1_RANK_MAJ_FULL2=Major I
BO1_RANK_MAJ_FULL3=Major II
BO1_RANK_MAJ_FULL_N=Major %s
BO1_RANK_LTCOL_FULL=Podpułkownik
BO1_RANK_LTCOL_FULL2=Podpułkownik I
BO1_RANK_LTCOL_FULL3=Podpułkownik II
BO1_RANK_LTCOL_FULL_N=Podpułkownik %s
BO1_RANK_COL_FULL=Pułkownik
BO1_RANK_COL_FULL2=Pułkownik I
BO1_RANK_COL_FULL3=Pułkownik II
BO1_RANK_COL_FULL_N=Pułkownik %s
BO1_RANK_BRIGGEN_FULL=Generał brygady
BO1_RANK_BRIGGEN_FULL2=Generał brygady I
BO1_RANK_BRIGGEN_FULL3=Generał brygady II
BO1_RANK_BRIGGEN_FULL_N=Generał brygady %s
BO1_RANK_MAJGEN_FULL=Generał major
BO1_RANK_MAJGEN_FULL2=Generał major I
BO1_RANK_MAJGEN_FULL3=Generał major II
BO1_RANK_MAJGEN_FULL_N=Generał major %s
BO1_RANK_LTGEN_FULL=Generał dywizji
BO1_RANK_LTGEN_FULL2=Generał dywizji I
BO1_RANK_LTGEN_FULL3=Generał dywizji II
BO1_RANK_LTGEN_FULL_N=Generał dywizji %s
BO1_RANK_GEN_FULL=Generał
BO1_RANK_COM_FULL=Komandor
