#---------- Black Ops II HUD | English
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEALS
BO2_MP_PLA_NAME=KSO
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Najemnicy
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Milicja

BO2_MPUI_SEALS_SHORT=SEALS
BO2_MPUI_PLA_SHORT=KSO
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Najemnicy
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Milicja

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=KSO
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=NAJEMNICY
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILICJA

# Splashes
BO2_MEDAL_FIRST_KILL=PIERWSZA KREW
BO2_MEDAL_ASSISTED_SUICIDE=EUTANAZJA
BO2_MEDAL_HEADSHOT=HEADSHOT
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=POWRÓT
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=ŻYCIE PO ŻYCIU
BO2_MEDAL_LONGSHOT_KILL=DALEKI STRZAŁ
BO2_MEDAL_REVENGE_KILL=ZEMSTA
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=OCALAŁY
BO2_MEDAL_KILL_ENEMY_IN_AIR=STRZAŁ W POWIETRZE
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=JEDEN STRZAŁ, JEDEN TRUP
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=POCZWÓRNA SERIA
BO2_MEDAL_KILLSTREAK_5=ŻĄDNY KRWI
BO2_MEDAL_KILLSTREAK_10=BEZLITOSNY
BO2_MEDAL_KILLSTREAK_15=BEZWZGLĘDNY
BO2_MEDAL_KILLSTREAK_20=NIEPOWSTRZYMANY
BO2_MEDAL_KILLSTREAK_25=BRUTALNY
BO2_MEDAL_KILLSTREAK_30=NUKLEARNY
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=NIE DO ZATRZYMANIA
BO2_MEDAL_MULTIKILL_2=PODWÓJNE ZABICIE
BO2_MEDAL_MULTIKILL_3=POTRÓJNE ZABICIE
BO2_MEDAL_MULTIKILL_4=FURIAT
BO2_MEDAL_MULTIKILL_5=SZALONE ZABICIE
BO2_MEDAL_MULTIKILL_6=SUPERZABICIE
BO2_MEDAL_MULTIKILL_7=MEGAZABICIE
BO2_MEDAL_MULTIKILL_8=ULTRAZABICIE
BO2_MEDAL_MULTIKILL_MORE_THAN_8=ŁAŃCUCH OFIAR
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=MŚCICIEL
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=ZBAWCA

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=PKT DO WYGRANEJ: %s
