#---------- Black Ops II HUD | Polska | Polish
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEALS
BO2_MP_PLA_NAME=KSO
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Najemnicy
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Milicja

BO2_MPUI_SEALS_SHORT=SEALS
BO2_MPUI_PLA_SHORT=KSO
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Najemnicy
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Milicja

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=KSO
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=NAJEMNICY
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILICJA

# Splashes
BO2_MEDAL_FIRST_KILL=Pierwsza krew
BO2_MEDAL_ASSISTED_SUICIDE=Eutanazja
BO2_MEDAL_HEADSHOT=Headshot
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=Powrót
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=Życie po życiu
BO2_MEDAL_LONGSHOT_KILL=Daleki strzał
BO2_MEDAL_REVENGE_KILL=Zemsta
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=Ocalały
BO2_MEDAL_KILL_ENEMY_IN_AIR=Strzał w powietrze
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=Jeden strzał, jeden trup
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=Poczwórna seria
BO2_MEDAL_KILLSTREAK_5=Żądny krwi
BO2_MEDAL_KILLSTREAK_10=Bezlitosny
BO2_MEDAL_KILLSTREAK_15=Bezwzględny
BO2_MEDAL_KILLSTREAK_20=Niepowstrzymany
BO2_MEDAL_KILLSTREAK_25=Brutalny
BO2_MEDAL_KILLSTREAK_30=Nuklearny
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=Nie do zatrzymania
BO2_MEDAL_MULTIKILL_2=Podwójne zabicie
BO2_MEDAL_MULTIKILL_3=Potrójne zabicie
BO2_MEDAL_MULTIKILL_4=Furiat
BO2_MEDAL_MULTIKILL_5=Szalone zabicie
BO2_MEDAL_MULTIKILL_6=Superzabicie
BO2_MEDAL_MULTIKILL_7=Megazabicie
BO2_MEDAL_MULTIKILL_8=Ultrazabicie
BO2_MEDAL_MULTIKILL_MORE_THAN_8=Łańcuch ofiar
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=Mściciel
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=Zbawca

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=PKT DO WYGRANEJ: %s

# Notifications
BO2_RANK_PROMOTED=Otrzymujesz awans!
BO2_RANK_PLAYER_WAS_PROMOTED=%s - awans na: %s!

# Ranks
BO2_RANK_PRVT_FULL=Szeregowy
BO2_RANK_PRVT_FULL2=Szeregowy II
BO2_RANK_PRVT_FULL3=Szeregowy III
BO2_RANK_PFC_FULL=Starszy szeregowy
BO2_RANK_PFC_FULL2=Starszy szeregowy II
BO2_RANK_PFC_FULL3=Starszy szeregowy III
BO2_RANK_LCPL_FULL=Kapral
BO2_RANK_LCPL_FULL2=Kapral II
BO2_RANK_LCPL_FULL3=Kapral III
BO2_RANK_CPL_FULL=Starszy kapral
BO2_RANK_CPL_FULL2=Starszy kapral II
BO2_RANK_CPL_FULL3=Starszy kapral III
BO2_RANK_SGT_FULL=Sierżant
BO2_RANK_SGT_FULL2=Sierżant II
BO2_RANK_SGT_FULL3=Sierżant III
BO2_RANK_SSGT_FULL=Sierżant sztabowy
BO2_RANK_SSGT_FULL2=Sierżant sztabowy II
BO2_RANK_SSGT_FULL3=Sierżant sztabowy III
BO2_RANK_GYSGT_FULL=Starszy sierżant
BO2_RANK_GYSGT_FULL2=Plutonowy II
BO2_RANK_GYSGT_FULL3=Plutonowy III
BO2_RANK_MSGT_FULL=St. sierż. sztab.
BO2_RANK_MSGT_FULL2=Starszy sierżant II
BO2_RANK_MSGT_FULL3=Starszy sierżant III
BO2_RANK_MGYSGT_FULL=Gł. st. sierż. sztab.
BO2_RANK_MGYSGT_FULL2=Starszy sierżant sztabowy II
BO2_RANK_MGYSGT_FULL3=Starszy sierżant sztabowy III
BO2_RANK_2NDLT_FULL=Podporucznik
BO2_RANK_2NDLT_FULL2=Podporucznik II
BO2_RANK_2NDLT_FULL3=Podporucznik III
BO2_RANK_LT_FULL=Porucznik
BO2_RANK_LT_FULL2=Porucznik II
BO2_RANK_LT_FULL3=Porucznik III
BO2_RANK_CPT_FULL=Kapitan
BO2_RANK_CPT_FULL2=Kapitan II
BO2_RANK_CPT_FULL3=Kapitan III
BO2_RANK_MAJ_FULL=Major
BO2_RANK_MAJ_FULL2=Major II
BO2_RANK_MAJ_FULL3=Major III
BO2_RANK_LTCOL_FULL=Podpułkownik
BO2_RANK_LTCOL_FULL2=Podpułkownik II
BO2_RANK_LTCOL_FULL3=Podpułkownik III
BO2_RANK_COL_FULL=Pułkownik
BO2_RANK_COL_FULL2=Pułkownik II
BO2_RANK_COL_FULL3=Pułkownik III
BO2_RANK_BGEN_FULL=Generał brygady
BO2_RANK_BGEN_FULL2=Generał brygady II
BO2_RANK_BGEN_FULL3=Generał brygady III
BO2_RANK_MAJGEN_FULL=Generał dywizji
BO2_RANK_MAJGEN_FULL2=Generał dywizji II
BO2_RANK_MAJGEN_FULL3=Generał dywizji III
BO2_RANK_LTGEN_FULL=Generał broni
BO2_RANK_LTGEN_FULL2=Generał dywizji II
BO2_RANK_LTGEN_FULL3=Generał dywizji III
BO2_RANK_GEN_FULL=Generał
BO2_RANK_GEN_FULL2=Generał II
BO2_RANK_GEN_FULL3=Generał III
BO2_RANK_COM_FULL=Głównodowodzący
