#---------- CoD: World at War HUD | Polska | Polish
# Translator: Original Game

# Factions
WAW_MPUI_RUSSIAN=Armia Czerwona
WAW_MPUI_JAPANESE=Armia imperialna
WAW_MPUI_GERMAN=Wehrmacht
WAW_MPUI_MARINE=Marines

WAW_MPUI_RUSSIAN_SHORT=Armia Czerwona
WAW_MPUI_JAPANESE_SHORT=Armia imperialna
WAW_MPUI_GERMAN_SHORT=Wehrmacht
WAW_MPUI_MARINE_SHORT=Marines

# Gamemodes
WAW_MPUI_TANK_WAR=Wojna
WAW_OBJECTIVES_TWAR_HINT=Zdobądź flagi i broń ich.