#---------- MW2 HUD | Polska | Polish
# Translator: Original Game

# Notifications
MW2_RANK_PROMOTED=Awansowałeś!
MW2_RANK_PLAYER_WAS_PROMOTED=%s awansował do rangi: %s.

# Ranks
MW2_RANK_REC_FULL=Rekrut
MW2_RANK_PVT_FULL=Szeregowy
MW2_RANK_PFC_FULL=Szer. pierw. kl.
MW2_RANK_LCPL_FULL=Starszy szeregowy
MW2_RANK_CPL_FULL=Kapral
MW2_RANK_SGT_FULL=Sierżant
MW2_RANK_SSGT_FULL=Sierżant sztabowy
MW2_RANK_GYSGT_FULL=Starszy sierżant
MW2_RANK_MSGT_FULL=St. sierż. szt.
MW2_RANK_MGYSGT_FULL=Gł. st. sierż. szt.
MW2_RANK_2NDLT_FULL=Podporucznik
MW2_RANK_1STLT_FULL=Porucznik
MW2_RANK_CAPT_FULL=Kapitan
MW2_RANK_MAJ_FULL=Major
MW2_RANK_LTCOL_FULL=Podpułkownik
MW2_RANK_COL_FULL=Pułkownik
MW2_RANK_BGEN_FULL=Generał brygady
MW2_RANK_MAJGEN_FULL=Generał major
MW2_RANK_LTGEN_FULL=Generał porucznik
MW2_RANK_GEN_FULL=Generał
MW2_RANK_COMM_FULL=Komandor
MW2_RANK_1STLT_FULL2=Porucznik I
MW2_RANK_1STLT_FULL3=Porucznik II
MW2_RANK_2NDLT_FULL2=Podporucznik I
MW2_RANK_2NDLT_FULL3=Podporucznik II
MW2_RANK_BGEN_FULL2=Generał brygady I
MW2_RANK_BGEN_FULL3=Generał brygady II
MW2_RANK_CAPT_FULL2=Kapitan I
MW2_RANK_CAPT_FULL3=Kapitan II
MW2_RANK_COL_FULL2=Pułkownik I
MW2_RANK_COL_FULL3=Pułkownik II
MW2_RANK_COMM_FULL2=Komandor I
MW2_RANK_COMM_FULL3=Komandor II
MW2_RANK_CPL_FULL2=Kapral I
MW2_RANK_CPL_FULL3=Kapral II
MW2_RANK_GEN_FULL2=Generał I
MW2_RANK_GEN_FULL3=Generał II
MW2_RANK_GYSGT_FULL2=Starszy sierżant I
MW2_RANK_GYSGT_FULL3=Starszy sierżant II
MW2_RANK_LCPL_FULL2=Starszy szeregowy I
MW2_RANK_LCPL_FULL3=Starszy szeregowy II
MW2_RANK_LTCOL_FULL2=Podpułkownik I
MW2_RANK_LTCOL_FULL3=Podpułkownik II
MW2_RANK_MAJ_FULL2=Major I
MW2_RANK_MAJ_FULL3=Major II
MW2_RANK_MAJGEN_FULL2=Generał major I
MW2_RANK_MAJGEN_FULL3=Generał major II
MW2_RANK_MGYSGT_FULL2=Gł. st. sierż. szt. I
MW2_RANK_MGYSGT_FULL3=Gł. st. sierż. szt. II
MW2_RANK_MSGT_FULL2=St. sierż. szt. I
MW2_RANK_MSGT_FULL3=St. sierż. szt. II
MW2_RANK_PFC_FULL2=Szer. pierw. kl. I
MW2_RANK_PFC_FULL3=Szer. pierw. kl. II
MW2_RANK_PVT_FULL2=Szeregowy I
MW2_RANK_PVT_FULL3=Szeregowy II
MW2_RANK_REC_FULL2=Rekrut I
MW2_RANK_REC_FULL3=Rekrut II
MW2_RANK_SGT_FULL2=Sierżant I
MW2_RANK_SGT_FULL3=Sierżant II
MW2_RANK_SSGT_FULL2=Sierżant sztabowy I
MW2_RANK_SSGT_FULL3=Sierżant sztabowy II
MW2_RANK_LTGEN_FULL2=Generał porucznik I
MW2_RANK_LTGEN_FULL3=Generał porucznik II
MW2_RANK_SGTMAJ_FULL=Sierżant sztabowy
MW2_RANK_SGTMAJ_FULL2=Sierżant sztabowy I
MW2_RANK_SGTMAJ_FULL3=Sierżant sztabowy II
MW2_RANK_SPC_FULL=Specjalista
MW2_RANK_SPC_FULL2=Specjalista I
MW2_RANK_SPC_FULL3=Specjalista II
MW2_RANK_SFC_FULL=Starszy sierżant
MW2_RANK_SFC_FULL2=Starszy sierżant I
MW2_RANK_SFC_FULL3=Starszy sierżant II
MW2_RANK_1STSGT_FULL=Sierżant sztabowy
MW2_RANK_1STSGT_FULL2=Sierżant sztabowy I
MW2_RANK_1STSGT_FULL3=Sierżant sztabowy II
MW2_RANK_CSM_FULL=Sierżant
MW2_RANK_CSM_FULL2=Sierżant I
MW2_RANK_CSM_FULL3=Sierżant II
MW2_RANK_CSM_FULL4=Sierżant III
MW2_RANK_GEN_FULL4=Generał III
MW2_RANK_LTGEN_FULL4=Generał porucznik III
MW2_RANK_MAJGEN_FULL4=Generał major III
MW2_RANK_BGEN_FULL4=Generał brygady III
MW2_RANK_COL_FULL4=Pułkownik III
MW2_RANK_LTCOL_FULL4=Podpułkownik III
MW2_RANK_MAJ_FULL4=Major III
MW2_RANK_CAPT_FULL4=Kapitan III
MW2_RANK_1STLT_FULL4=Porucznik III
MW2_RANK_2NDLT_FULL4=Podporucznik III
