#---------- CoD HUD System Notifications | Polska | Polish
# Translator: Machine translated

CoDHUD.System.ResetTime=Timer rundy został zresetowany do %s.
CoDHUD.System.ResetTime.Off=Timer rundy został usunięty.

CoDHUD.System.RestrictType=Gra została zmieniona na %s.
CoDHUD.System.RestrictType.NotNow=Nie można teraz zmienić gry.

CoDHUD.System.Faction.NotNow=Nie można teraz zmienić frakcji.
CoDHUD.System.Faction.Denied=Nie można zmienić frakcji.

CoDHUD.System.ChallengeReset=Wszystkie wyzwania zostały zresetowane.
CoDHUD.System.RankReset=Ranga i statystyki HUD '%s' zostały zresetowane.

CoDHUD.System.CVChanged=Zmienna serwera '%s' została zmieniona na %s.

CoDHUD.System.ForceEndRound.NotNow=Nie można teraz wymusić zakończenia rundy.
CoDHUD.System.ForceEndRound.NotStarting=Nie można wymusić zakończenia rundy, która właśnie się rozpoczyna.