#---------- CoD4 HUD | Polska | Polish
# Translator: Original Game

# Factions
CoD4_MPUI_MARINES=Zwiad marines
CoD4_MPUI_SPETSNAZ=Specnaz
CoD4_MPUI_OPFOR=Przeciwnik
CoD4_MPUI_SAS=S.A.S.

CoD4_MPUI_MARINES_SHORT=Marines
CoD4_MPUI_SPETSNAZ_SHORT=Specnaz
CoD4_MPUI_OPFOR_SHORT=Przeciwnik
CoD4_MPUI_SAS_SHORT=S.A.S.