#---------- MW3 HUD | 简体中文 | Simplified Chinese
# Translator: WhatUziname7

# Factions
MW3_MP_SAS=英国特别空勤团
MW3_MP_INNERCIRCLE_NAME=核心集团
MW3_MP_AFRICA_MILITIA_NAME=非洲民兵
MW3_MP_DELTA_NAME=三角洲部队
MW3_MP_GIGN=法国国家宪兵特勤队
MW3_MP_SPETSNAZ_NAME=俄罗斯特种部队
MW3_MP_PMC_NAME=私人军事公司
	
MW3_MP_SAS_SHORT_NAME=S.A.S.
MW3_MP_INNERCIRCLE_SHORT_NAME=核心集团
MW3_MP_AFRICA_MILITIA_SHORT_NAME=民兵
MW3_MP_DELTA_SHORT_NAME=三角洲
MW3_MP_GIGN_SHORT_NAME=GIGN
MW3_MPUI_SPETSNAZ_SHORT=俄特
MW3_MP_PMC_SHORT_NAME=PMC

# Notifications
MW3_RANK_PROMOTED=你已晋升！
MW3_RANK_PROMOTED_WEAPON=你的武器等级已提升！
MW3_RANK_PLAYER_WAS_PROMOTED=%s 已晋升为 %s！

# Ranks
MW3_RANK_REC_FULL=新兵
MW3_RANK_PVT_FULL=列兵
MW3_RANK_PFC_FULL=一等兵
MW3_RANK_LCPL_FULL=准下士
MW3_RANK_CPL_FULL=下士
MW3_RANK_SGT_FULL=中士
MW3_RANK_SSGT_FULL=上士
MW3_RANK_GYSGT_FULL=三级军士长
MW3_RANK_MSGT_FULL=二级军士长
MW3_RANK_MGYSGT_FULL=一级军士长
MW3_RANK_2NDLT_FULL=少尉
MW3_RANK_1STLT_FULL=中尉
MW3_RANK_CAPT_FULL=上尉
MW3_RANK_MAJ_FULL=少校
MW3_RANK_LTCOL_FULL=中校
MW3_RANK_COL_FULL=上校
MW3_RANK_BGEN_FULL=准将
MW3_RANK_MAJGEN_FULL=少将
MW3_RANK_LTGEN_FULL=中将
MW3_RANK_GEN_FULL=上将
MW3_RANK_COMM_FULL=指挥官
MW3_RANK_1STLT_FULL2=中尉 I
MW3_RANK_1STLT_FULL3=中尉 II
MW3_RANK_2NDLT_FULL2=少尉 I
MW3_RANK_2NDLT_FULL3=少尉 II
MW3_RANK_BGEN_FULL2=准将 I
MW3_RANK_BGEN_FULL3=准将 II
MW3_RANK_CAPT_FULL2=上尉 I
MW3_RANK_CAPT_FULL3=上尉 II
MW3_RANK_COL_FULL2=上校 I
MW3_RANK_COL_FULL3=上校 II
MW3_RANK_COMM_FULL2=指挥官 I
MW3_RANK_COMM_FULL3=指挥官 II
MW3_RANK_CPL_FULL2=下士 I
MW3_RANK_CPL_FULL3=下士 II
MW3_RANK_GEN_FULL2=上将 I
MW3_RANK_GEN_FULL3=上将 II
MW3_RANK_GYSGT_FULL2=三级军士长 I
MW3_RANK_GYSGT_FULL3=三级军士长 II
MW3_RANK_LCPL_FULL2=准下士 I
MW3_RANK_LCPL_FULL3=准下士 II
MW3_RANK_LTCOL_FULL2=中校 I
MW3_RANK_LTCOL_FULL3=中校 II
MW3_RANK_MAJ_FULL2=少校 I
MW3_RANK_MAJ_FULL3=少校 II
MW3_RANK_MAJGEN_FULL2=少将 I
MW3_RANK_MAJGEN_FULL3=少将 II
MW3_RANK_MGYSGT_FULL2=一级军士长 I
MW3_RANK_MGYSGT_FULL3=一级军士长 II
MW3_RANK_MSGT_FULL2=二级军士长 I
MW3_RANK_MSGT_FULL3=二级军士长 II
MW3_RANK_PFC_FULL2=一等兵 I
MW3_RANK_PFC_FULL3=一等兵 II
MW3_RANK_PVT_FULL2=列兵 I
MW3_RANK_PVT_FULL3=列兵 II
MW3_RANK_REC_FULL2=新兵 I
MW3_RANK_REC_FULL3=新兵 II
MW3_RANK_SGT_FULL2=中士 I
MW3_RANK_SGT_FULL3=中士 II
MW3_RANK_SSGT_FULL2=上士 I
MW3_RANK_SSGT_FULL3=上士 II
MW3_RANK_LTGEN_FULL2=中将 I
MW3_RANK_LTGEN_FULL3=中将 II
MW3_RANK_SGTMAJ_FULL=军士长
MW3_RANK_SGTMAJ_FULL2=军士长 I
MW3_RANK_SGTMAJ_FULL3=军士长 II
MW3_RANK_SGTMAJ_FULL_N=军士长 %s
MW3_RANK_COMM_FULL_N=指挥官 %s
MW3_RANK_SPC_FULL=技术兵
MW3_RANK_SPC_FULL2=技术兵 I
MW3_RANK_SPC_FULL3=技术兵 II
MW3_RANK_SPC_FULL_N=技术兵 %s
MW3_RANK_SFC_FULL=军士长
MW3_RANK_SFC_FULL2=军士长 I
MW3_RANK_SFC_FULL3=军士长 II
MW3_RANK_SFC_FULL_N=军士长 %s
MW3_RANK_1STSGT_FULL=一级军士长
MW3_RANK_1STSGT_FULL2=一级军士长 I
MW3_RANK_1STSGT_FULL3=一级军士长 II
MW3_RANK_1STSGT_FULL_N=一级军士长 %s
MW3_RANK_CSM_FULL=总军士长
MW3_RANK_CSM_FULL2=总军士长 I
MW3_RANK_CSM_FULL3=总军士长 II
MW3_RANK_CSM_FULL_N=总军士长 %s
MW3_RANK_CSM_FULL4=总军士长 III
MW3_RANK_GEN_FULL4=上将 III
MW3_RANK_LTGEN_FULL4=中将 III
MW3_RANK_MAJGEN_FULL4=少将 III
MW3_RANK_BGEN_FULL4=准将 III
MW3_RANK_COL_FULL4=上校 III
MW3_RANK_LTCOL_FULL4=中校 III
MW3_RANK_MAJ_FULL4=少校 III
MW3_RANK_CAPT_FULL4=上尉 III
MW3_RANK_1STLT_FULL4=中尉 III
MW3_RANK_2NDLT_FULL4=少尉 III
MW3_RANK_SSGT_FULL4=上士 III
MW3_RANK_SFC_FULL4=军士长 III
MW3_RANK_MSGT_FULL4=二级军士长 III
MW3_RANK_1STSGT_FULL4=一级军士长 III
MW3_RANK_SGTMAJ_FULL4=军士长 III
