#---------- CoD HUD System Notifications | 简体中文 | Simplified Chinese
# Translator: WhatUziname7

CoDHUD.System.ResetTime=回合计时器已重置为 %s。
CoDHUD.System.ResetTime.Off=回合计时器已移除。

CoDHUD.System.RestrictType=游戏已更改为 %s。
CoDHUD.System.RestrictType.NotNow=当前无法更改游戏。

CoDHUD.System.Faction.NotNow=当前无法更换阵营。
CoDHUD.System.Faction.Denied=无法更换阵营。

CoDHUD.System.ChallengeReset=所有挑战已重置。
CoDHUD.System.RankReset='%s' HUD 的等级与数据已重置。

CoDHUD.System.CVChanged=服务器变量 '%s' 已更改为 %s。

CoDHUD.System.ForceEndRound.NotNow=当前无法强制结束回合。
CoDHUD.System.ForceEndRound.NotStarting=无法强制结束正在开始的回合。