#---------- CoD HUD Settings | 简体中文 | Simplified Chinese
# Translator: WhatUziname7

# ------------------[ GENERAL ]------------------
CoDHUD.Title=使命召唤 HUD

CoDHUD.Client=客户端
CoDHUD.Server=服务器
CoDHUD.General=通用

CoDHUD.Close=关闭

CoDHUD.Default=默认：%s
CoDHUD.Current=当前：%s

# ------------------[ MENU GLYPHS ]------------------
CoDHUD.Glyph.Toggle=[+attack] 切换
CoDHUD.Glyph.Open=[+attack] 开启
CoDHUD.Glyph.OpenMenu=[+attack] 打开菜单
CoDHUD.Glyph.Select=[+attack] 选择
CoDHUD.Glyph.Confirm=[+attack] 确认
CoDHUD.Glyph.Return=[+attack] 返回
CoDHUD.Glyph.Close=[+attack] 关闭
CoDHUD.Glyph.Tab=[+attack] 切换标签页
CoDHUD.Glyph.Reset=[+attack2] 重置

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.RoundStart=回合控制

CoDHUD.RoundStart.Gamemode=游戏模式
CoDHUD.RoundStart.Info=选择要游玩的游戏模式。

CoDHUD.RoundStart.Start=开始回合
CoDHUD.RoundStart.Start.desc=选择游戏模式并根据喜好调整设置后，即可开始回合流程。

CoDHUD.RoundStart.Notice=确定要开始新回合吗？\n所有分数将重置，所有玩家将重生。
CoDHUD.RoundStart.Yes=开始回合

CoDHUD.RoundStart.Timer=回合开始倒计时
CoDHUD.RoundStart.Timer.desc=回合开始前应有几秒的休息时间。

CoDHUD.RoundStart.Autobalance=回合开始时随机分配阵营
CoDHUD.RoundStart.Autobalance.desc=启用后，回合开始时所有玩家将被随机分配到一个合法阵营。

CoDHUD.Scorelimit=分数上限
CoDHUD.Scorelimit.desc=设置计分板上的最高分数上限。\n\n以击杀数衡量。

CoDHUD.Timelimit=时间限制
CoDHUD.Timelimit.desc=设置回合自动结束前的持续时间。\n\n以分钟衡量。\n\n设置为 0 则不限制。

CoDHUD.Autobalance.Amount=自动平衡队伍上限
CoDHUD.Autobalance.Amount.desc=设置玩家能被自动平衡到的最大阵营数量。

CoDHUD.Autobalance.Amount.disable=禁用
CoDHUD.Autobalance.Amount.2=2 个阵营
CoDHUD.Autobalance.Amount.3=3 个阵营
CoDHUD.Autobalance.Amount.4=4 个阵营

CoDHUD.RoundStart.Auto=服务器启动时自动开始回合
CoDHUD.RoundStart.Auto.desc=启用后，当服务器加入第一名玩家时，将立即开始新回合。

CoDHUD.Admin.ResetTime=重置回合计时器
CoDHUD.Admin.ResetTime.desc=将当前回合的计时器重置为设定的时间限制数值。

CoDHUD.ForceEndRound=强制结束回合
CoDHUD.ForceEndRound.desc=在未达到分数或时间限制之前，需要或想要结束回合时，请点击此处。

CoDHUD.ForceEndRound.Notice=确定要强制结束回合吗？

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen=启用“比赛结束”
CoDHUD.Admin.EndScreen.desc=达成分数上限后启用“比赛结束”系统。

CoDHUD.Admin.EndScreen.StartNext=比赛结束后开始下一回合
CoDHUD.Admin.EndScreen.StartNext.desc=启用后，比赛结束倒计时结束后将开始新回合。\n\n禁用后，所有玩家将正常重生。

CoDHUD.Admin.FriendlyFire=允许友军伤害
CoDHUD.Admin.FriendlyFire.desc=启用后，同一阵营的玩家可以互相造成伤害。\n\n仅适用于团队死斗模式。

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=限制阵营与 HUD 类型
CoDHUD.Admin.RestrictType.Choose=选择游戏
CoDHUD.Admin.RestrictType.desc=选择要限制玩家使用的 CoD 游戏。这将影响 HUD 和可用的阵营。

CoDHUD.Admin.RestrictType.Warning=警告！\n切换游戏将产生以下后果：\n- 所有玩家的阵营将被随机分配。\n- 所有玩家分数将重置为 0。\n- 所有玩家将阵亡并重生。\n\n确定要继续更换游戏吗？

CoDHUD.Type.cod4=现代战争 1
CoDHUD.Type.waw=战争世界
CoDHUD.Type.mw2=现代战争 2
CoDHUD.Type.bo1=黑色行动
CoDHUD.Type.mw3=现代战争 3
CoDHUD.Type.bo2=黑色行动 2
CoDHUD.Type.ghosts=幽灵
CoDHUD.Type.aw=高级战争
CoDHUD.Type.bo3=黑色行动 3
CoDHUD.Type.iw=无限战争
CoDHUD.Type.ww2=二战

CoDHUD.Admin.RestrictFactionChance=限制更换阵营
CoDHUD.Admin.RestrictFactionChance.desc=选择玩家何时可以更换阵营。

CoDHUD.Admin.RestrictFactionChance.disable=禁止更换
CoDHUD.Admin.RestrictFactionChance.freely=可自由更换
CoDHUD.Admin.RestrictFactionChance.pool=仅限当前可用阵营

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=阵营选择
CoDHUD.Faction.Select.desc=选择要代表的阵营。\n影响敌我识别状态，并更改播报员和主题以匹配该阵营。

CoDHUD.Faction.ChangeWarning=警告！\n更换阵营将产生以下后果：\n- 你的分数将重置为 0。\n- 你将阵亡并重生。\n\n确定要继续更换阵营吗？

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=快捷操作

CoDHUD.Quick.DisableHUD=快速禁用所有 HUD 选项
CoDHUD.Quick.DisableHUD.desc=禁用所有使命召唤 HUD 选项。

# ---------[ HUD-RELATED ]---------
CoDHUD.HUD=HUD 设置

# Multiple
CoDHUD.HUD.Outline=文字描边
CoDHUD.HUD.Outline.desc=在某些元素上激活文字描边，使其在强光区域更容易阅读。

CoDHUD.HUD.Sound=播放音效
CoDHUD.HUD.Sound.desc=如果 HUD 类型支持，则播放相应的音效。

CoDHUD.HUD.Time.Total=停留时间
CoDHUD.HUD.Time.Total.desc=元素完全淡入后，在屏幕上保留多长时间再开始淡出。

CoDHUD.HUD.Time.Fadein=淡入时间
CoDHUD.HUD.Time.Fadein.desc=元素淡入所需的时间。

CoDHUD.HUD.Time.Fadeout=淡出时间
CoDHUD.HUD.Time.Fadeout.desc=元素淡出所需的时间。

# Scale
CoDHUD.HUD.Scale=UI 缩放

CoDHUD.HUD.Scale.Enable=UI 缩放倍率
CoDHUD.HUD.Scale.Enable.desc=调整使命召唤 HUD 使用的 UI 元素比例。\n\n对于较低分辨率或超宽分辨率非常有用。\n\n<color=255,255,100>注意</color>：应用后会重新加载菜单。\n\n<color=255,100,100>警告</color>：如果该值过高或过低，部分元素可能会严重错位。

# Scoreboard
CCoDHUD.HUD.Scoreboard=计分板

CoDHUD.HUD.Scoreboard.Enable=启用计分板
CoDHUD.HUD.Scoreboard.Enable.desc=启用计分板。显示所有玩家所属的阵营。

# Score Counter
CoDHUD.HUD.Scorecounter=分数计数器

CoDHUD.HUD.Scorecounter.Enable=启用分数计数器
CoDHUD.HUD.Scorecounter.Enable.desc=启用服务器计时器、阵营图标和分数计数器。\n\n部分 HUD 类型不会显示阵营图标。

# Medals
CoDHUD.HUD.Medals=勋章

CoDHUD.HUD.Medals.Enable=启用勋章
CoDHUD.HUD.Medals.Enable.desc=启用勋章，通过执行特定动作（如快速击杀或爆头）获得。\n\n注意，部分 HUD 类型仅显示文字，部分则显示文字和图标。

CoDHUD.HUD.Medals.Speedup=长队列时加速显示
CoDHUD.HUD.Medals.Speedup.desc=如果同时有大量勋章排队，则加速显示。\n\n根据 HUD 类型，如果排队数超过 3 个，则会禁用相关的音效。

# Kill Feed
CoDHUD.HUD.Killfeed=击杀提示

CoDHUD.HUD.Killfeed.Enable=启用击杀提示
CoDHUD.HUD.Killfeed.Enable.desc=启用击杀提示。

# Minimap
CoDHUD.HUD.Minimap=小地图

CoDHUD.HUD.Minimap.Enable=启用小地图
CoDHUD.HUD.Minimap.Enable.desc=启用小地图。

# Hitmarker
CoDHUD.HUD.Hitmarker=命中提示

CoDHUD.HUD.Hitmarker.Enable=启用命中提示
CoDHUD.HUD.Hitmarker.Enable.desc=启用命中提示及其关联的命中音效。

# Weapon Info
CoDHUD.HUD.WeaponInfo=武器信息

CoDHUD.HUD.WeaponInfo.Enable=启用武器信息
CoDHUD.HUD.WeaponInfo.Enable.desc=启用武器信息面板，显示武器名称和弹药计数器。\n\n部分 HUD 类型在此处也包含指南针。

CoDHUD.HUD.WeaponPrompts.Enable=启用武器提示
CoDHUD.HUD.WeaponPrompts.Enable.desc=启用武器提示，例如低弹药通知。

# XP Counter
CoDHUD.HUD.XP=经验值提示

CoDHUD.HUD.XP.Enable=启用经验值提示
CoDHUD.HUD.XP.Enable.desc=启用经验值提示。

# Target ID / IFF
CoDHUD.HUD.IFF=敌我识别

CoDHUD.HUD.IFF.Enable=启用敌我识别
CoDHUD.HUD.IFF.Enable.desc=启用“敌我识别”系统，当瞄准目标附近时，会在目标头顶显示其名称。

# Death Icon
CoDHUD.HUD.DeathIcon=死亡图标

CoDHUD.HUD.DeathIcon.Enable=启用死亡图标
CoDHUD.HUD.DeathIcon.Enable.desc=启用死亡图标，在同一阵营玩家阵亡的位置显示。

# Chat
CoDHUD.HUD.Chat=聊天框

CoDHUD.HUD.Chat.Enable=启用聊天框
CoDHUD.HUD.Chat.Enable.desc=启用聊天框。

# Headers
CoDHUD.HUD.Headers=标题提示

CoDHUD.HUD.Headers.Enable=启用标题提示
CoDHUD.HUD.Headers.Enable.desc=启用标题提示，例如完成挑战或升级时。

# Subtitles
CoDHUD.HUD.Subtitles=字幕

CoDHUD.HUD.Subtitles.Enable=启用字幕
CoDHUD.HUD.Subtitles.Enable.desc=每当播放播报员语音时启用字幕。\n\n<color=255,100,100>警告</color>：字幕是为英语语音创建的。

CoDHUD.HUD.Subtitles.Callsign=启用呼号
CoDHUD.HUD.Subtitles.Callsign.desc=启用正在播放的播报员的呼号。

CoDHUD.HUD.Subtitles.NameAlign=呼号对齐方式
CoDHUD.HUD.Subtitles.NameAlign.desc=选择播报员呼号的位置。

CoDHUD.HUD.Subtitles.NameAlign.Left=文本左侧
CoDHUD.HUD.Subtitles.NameAlign.Top=文本上方

# ---------[ OTHER SETTINGS ]---------
CoDHUD.Settings=其他设置
CoDHUD.Audio=音频设置
CoDHUD.Audio.Announcer=播报员
CoDHUD.Audio.Music=音乐

CoDHUD.Audio.Announcer.Enable=启用播报员语音
CoDHUD.Audio.Announcer.Enable.desc=启用播报员。

CoDHUD.Audio.Announcer.English=强制使用英文播报员
CoDHUD.Audio.Announcer.English.desc=强制播放英文播报员语音，无论游戏语言设置如何。

CoDHUD.Audio.Music.Enable=启用音乐
CoDHUD.Audio.Music.Enable.desc=启用音乐。

CoDHUD.Audio.Music.Ambient=启用环境音乐
CoDHUD.Audio.Music.Ambient.desc=启用背景环境音乐播放。

CoDHUD.Reset=重置设置
CoDHUD.Challenges.Reset=重置挑战
CoDHUD.Challenges.Reset.desc=重置所有已解锁的挑战。

CoDHUD.Rank.Reset=重置等级与数据
CoDHUD.Rank.Reset.desc=重置当前 HUD 上的等级和所有数据。
CoDHUD.Rank.Reset.Warning=警告！\n你即将重置此 HUD 上的等级和数据！\n此操作无法撤销！确定要重置你的等级和数据吗？

CoDHUD.Menu=菜单设置
CoDHUD.Menu.Fullscreen=全屏打开
CoDHUD.Menu.Fullscreen.desc=以全屏模式打开使命召唤 HUD 菜单，而非小窗口。

CoDHUD.Menu.SFX=菜单音效
CoDHUD.Menu.SFX.desc=悬停或点击按钮时播放主题菜单音效。

CoDHUD.Menu.Music=菜单音乐
CoDHUD.Menu.Music.desc=当任何使命召唤 HUD 菜单实例处于活动状态时，播放主题菜单音乐。

CoDHUD.Menu.HideDesc=隐藏描述
CoDHUD.Menu.HideDesc.desc=启用后，菜单描述将被隐藏。

CoDHUD.Menu.HidePrompts=隐藏提示
CoDHUD.Menu.HidePrompts.desc=启用后，菜单中的按键提示将被隐藏。

CoDHUD.Menu.OpenSpeed=菜单打开速度
CoDHUD.Menu.OpenSpeed.desc=使命召唤 HUD 菜单打开新实例的速度。\n\n以秒为单位。

CoDHUD.Menu.CloseSpeed=菜单关闭速度
CoDHUD.Menu.CloseSpeed.desc=使命召唤 HUD 菜单关闭实例的速度。\n\n以秒为单位。

# ---------[ RANK & STATS ]---------
CoDHUD.Stats=玩家数据
CoDHUD.Stats.Rank=玩家等级：%d - %s
CoDHUD.Stats.XPNext=下一等级所需经验：%d
CoDHUD.Stats.XP=总经验：%d
CoDHUD.Stats.Kills=总击杀：%d
CoDHUD.Stats.Headshots=爆头数：%d
CoDHUD.Stats.Deaths=总死亡：%d
CoDHUD.Stats.Challenges=已完成挑战：%d

CoDHUD.Stats.Unknown=未知