#---------- MW2 HUD | 简体中文 | Simplified Chinese
# Translator: WhatUziname7

# Factions
MW2_MP_US_ARMY_NAME=陆军游骑兵
MW2_MP_SEALS_UDT_NAME=海豹突击队
MW2_MP_MILITIA_NAME=民兵
MW2_MP_TASKFORCE_NAME=141特遣队
MW2_MP_OPFOR_NAME=敌对武装
MW2_MP_SPETSNAZ_NAME=俄罗斯特种部队

MW2_MP_US_ARMY_SHORT_NAME=游骑兵
MW2_MP_SEALS_UDT_SHORT_NAME=海豹
MW2_MP_MILITIA_SHORT_NAME=民兵
MW2_MP_TASKFORCE_SHORT_NAME=TF 141
MW2_MPUI_OPFOR_SHORT=敌对武装
MW2_MPUI_SPETSNAZ_SHORT=俄特

# Splashes
MW2_SPLASHES_HEADSHOT=爆头！
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=助攻自杀！
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=你助攻了敌人的自杀。
MW2_SPLASHES_LONGSHOT=远射！
MW2_SPLASHES_LONGSHOT_DESC=漂亮的远距离击杀！
MW2_SPLASHES_EXECUTION=处决！
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=复仇者！
MW2_SPLASHES_AVENGER_DESC=你为队友复仇了。
MW2_SPLASHES_DEFENDER=救援者！
MW2_SPLASHES_DEFENDER_DESC=你救了一名队友。
MW2_SPLASHES_POSTHUMOUS=死后击杀！
MW2_SPLASHES_POSTHUMOUS_DESC=你死后击杀了一名敌人。
MW2_SPLASHES_REVENGE=复仇！
MW2_SPLASHES_REVENGE_DESC=你已成功复仇。
MW2_SPLASHES_DOUBLEKILL=双杀！
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=三杀！
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=多杀！
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=首杀！
MW2_SPLASHES_FIRSTBLOOD_DESC=你拿到了全场第一杀。
MW2_SPLASHES_BUZZKILL=中断连杀！
MW2_SPLASHES_BUZZKILL_DESC=阻止了敌人的连杀。
MW2_SPLASHES_COMEBACK=逆境反杀！
MW2_SPLASHES_COMEBACK_DESC=你从连续阵亡中扳回一城。
MW2_SPLASHES_FLAGRETURN=归还旗帜！
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=夺旗手！
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=据点稳固！
MW2_SPLASHES_CAPTURE_DESC=你占领了一个目标点。
MW2_SPLASHES_DEFEND=防守成功！
MW2_SPLASHES_DEFEND_DESC=你防守了目标点。
MW2_SPLASHES_ASSAULT=进攻成功！
MW2_SPLASHES_ASSAULT_DESC=你击杀了一名防守者。
MW2_SPLASHES_PLANT=安放炸弹！
MW2_SPLASHES_PLANT_DESC=你安放了炸弹。
MW2_SPLASHES_DEFUSE=拆弹英雄！
MW2_SPLASHES_DEFUSE_DESC=你拆除了炸弹。
MW2_SPLASHES_SAB_OVERTIME=加时！
MW2_SPLASHES_SAB_OVERTIME_DESC=距离炸弹最近的基地将被摧毁。
MW2_SPLASHES_MARTYRDOM_DESC=你阵亡时会掉落一颗活手雷。
MW2_SPLASHES_FINALSTAND_DESC=倒地时会给你第二次机会。
MW2_SPLASHES_ENDGAME_DESC=接下来几秒内获得额外生命值。
MW2_SPLASHES_C4DEATH_DESC=在死前拔出C4。
MW2_SPLASHES_KNIFETHROW_DESC=你使用飞刀击杀了一名敌人。
MW2_SPLASHES_KNIFETHROW=飞刀击杀！
MW2_SPLASHES_HIJACKER_DESC=你夺取了敌方空投补给箱。
MW2_SPLASHES_HIJACKER=劫持者！
MW2_SPLASHES_HIJACKED=%s 劫持了你的补给箱。
MW2_SPLASHES_DEFCON_LOWER=警戒等级降低！
MW2_SPLASHES_DEFCON_RAISE=警戒等级提升
MW2_SPLASHES_DEFCON_LOWER_DESC=连杀奖励升级！
MW2_SPLASHES_DEFCON_RAISE_DESC=连杀奖励降级。
MW2_SPLASHES_DEFCON_5=警戒等级 5
MW2_SPLASHES_DEFCON_4=警戒等级 4
MW2_SPLASHES_DEFCON_3=警戒等级 3
MW2_SPLASHES_DEFCON_2=警戒等级 2
MW2_SPLASHES_DEFCON_1=警戒等级 1
MW2_SPLASHES_DEFCON_5_DESC=警戒等级 5
MW2_SPLASHES_DEFCON_4_DESC=比赛即将开始！
MW2_SPLASHES_DEFCON_3_DESC=紧急空投即将抵达！
MW2_SPLASHES_DEFCON_2_DESC=连杀奖励轮转！
MW2_SPLASHES_DEFCON_1_DESC=目标双倍得分！
MW2_SPLASHES_COMBATHIGH_DESC=短时间内提升生命值。
MW2_SPLASHES_RESTED=日常经验加成！
MW2_SPLASHES_RESTED_DESC=获得每日加成经验值！
MW2_SPLASHES_RESTED_DONE=日常经验加成结束。
MW2_SPLASHES_RESTED_DONE_DESC=已获取额外经验值。
MW2_SPLASHES_VIP=你是 VIP
MW2_SPLASHES_STUCK_SEMTEX=粘住了！
MW2_SPLASHES_STUCK_SEMTEX_DESC=你用赛姆汀粘性手雷粘中了敌人！
MW2_SPLASHES_HEROIC=英勇表现！
MW2_SPLASHES_HEROIC_DESC=你在绝境求生状态下占领了目标！
MW2_SPLASHES_DENIED=阻止成功！
MW2_SPLASHES_DENIED_DESC=你摧毁了敌人的战术重生装置！
MW2_SPLASHES_DESTROYED_INSERTION=阻止了你的战术重生！
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=抢走了你的空投箱！
MW2_SPLASHES_REVIVER_DESC=你救起了一名倒地的队友。
MW2_SPLASHES_REVIVER=救援者！
MW2_SPLASHES_GIVEAWAY_SENTRY=... 拿走了一个哨戒机枪
MW2_SPLASHES_GIVEAWAY_AIRDROP=... 拿走了一个空投连杀奖励。
MW2_SPLASHES_SEMTEX_STUCK=用赛姆汀粘住了你
MW2_SPLASHES_ONE_SHOT_KILL=一枪毙命
MW2_SPLASHES_ONE_SHOT_KILL_DESC=一发子弹...一个击杀
MW2_SPLASHES_NINJA_DEFUSE=隐秘拆弹
MW2_SPLASHES_NINJA_DEFUSE_DESC=偷偷摸摸...
MW2_SPLASHES_COPYCAT_DESC=在击杀回放中窃取击杀者的职业配置。
MW2_SPLASHES_COPIED=已复制职业配置！
MW2_SPLASHES_REVIVED=已救起你
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=最后幸存！
MW2_SPLASHES_LAST_ENEMY_ALIVE=最后幸存！
MW2_SPLASHES_SHIELDASSIST=人群控制！
MW2_SPLASHES_SHIELDASSIST_DESC=你提供了极好的火力吸引。
MW2_SPLASHES_DESTROYED_HELICOPTER=摧毁直升机！
MW2_SPLASHES_DESTROYED_PAVELOW=摧毁铺路低地直升机！
MW2_SPLASHES_DESTROYED_UAV=摧毁侦察机！
MW2_SPLASHES_DESTROYED_HARRIER=摧毁鹞式战机！
MW2_SPLASHES_DESTROYED_AC130=摧毁 AC-130！
MW2_SPLASHES_DESTROYED_MINIGUNNER=摧毁武装炮艇！
MW2_SPLASHES_FLAG_RETURN=已归还旗帜！
MW2_SPLASHES_FLAG_CAPTURE=已夺取旗帜！
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=抢走了你的旗帜！
MW2_SPLASHES_FLAG_PICKUP_ENEMY=抢走了敌方旗帜！
MW2_SPLASHES_FLAG_PICKUP=拾取了旗帜！
MW2_SPLASHES_CAPTURED_NUKE=夺取核弹！
MW2_SPLASHES_DESC_CAPTURED_NUKE=你已经夺取了核弹。
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=解锁扩容弹匣！
MW2_SPLASHES_UNLOCKED_HEARTBEAT=解锁心跳感应器！
MW2_SPLASHES_UNLOCKED_AKIMBO=解锁双持！
MW2_SPLASHES_UNLOCKED_THERMAL=解锁热成像瞄准镜！
MW2_SPLASHES_UNLOCKED_EOTECH=解锁全息瞄准镜！
MW2_SPLASHES_UNLOCKED_SHOTGUN=解锁霰弹枪！
MW2_SPLASHES_GRABBED_THE_FLAG=已夺取旗帜！
MW2_SPLASHES_HIJACKED_SENTRY=抢走了你的哨戒机枪！
MW2_SPLASHES_HIJACKED_AIRDROP=抢走了你的空投箱！
MW2_SPLASHES_BOMB_PLANTED=已安放炸弹！
MW2_SPLASHES_BOMB_DEFUSED=已拆除炸弹！
MW2_SPLASHES_TIMEADDED=增加时间！
MW2_SPLASHES_GTNW_OVERTIME=突然死亡！
MW2_SPLASHES_GTNW_OVERTIME_DESC=禁止重生。
MW2_SPLASHES_DESTROYED_OBJECTIVE=摧毁目标！
MW2_SPLASHES_SAVED_OBJECTIVE=拯救目标！
MW2_SPLASHES_CAPTURED_HQ=占领总部！
MW2_SPLASHES_DESTROYED_HQ=摧毁总部！
MW2_SPLASHES_BOMB_TAKEN=拾取炸弹！
MW2_SPLASHES_BOMB_DROPPED=掉落炸弹！
MW2_SPLASHES_KILLED_CARRIER=击杀携弹者！
MW2_SPLASHES_SHAREPACKAGE=共享空投！
MW2_SPLASHES_SHAREPACKAGE_DESC=队友为你保住了空投补给箱！
MW2_SPLASHES_DESTROYED_COUNTER_UAV=恢复UAV！
MW2_SPLASHES_FLAGS_CAPTURE=夺取了一面旗帜！
MW2_SPLASHES_FLAG_ASSAULT=旗帜进攻！
MW2_SPLASHES_FLAG_DEFEND=旗帜防守！
MW2_SPLASHES_FLAG_ASSAULT_DESC=你击杀了一名旗点防守者。
MW2_SPLASHES_FLAG_DEFEND_DESC=你防守了旗帜。
MW2_SPLASHES_FLAG_CAPTURED=已夺取旗帜！
MW2_SPLASHES_FLAG_CAPTURED_DESC=你已经夺取了敌方旗帜。
MW2_SPLASHES_SECURED_POSITION=占领据点！
MW2_SPLASHES_SECURED_POSITION_A=占领A点！
MW2_SPLASHES_SECURED_POSITION_B=占领B点！
MW2_SPLASHES_SECURED_POSITION_C=占领C点！
MW2_SPLASHES_TIME_ADDED=时间延长！
MW2_SPLASHES_TIME_ADDED_DESC=炸弹点已被摧毁。游戏时间已延长。

# Other
MW2_MP_CONNECTED=%s 已连接
MW2_MP_DISCONNECTED=%s 已断开
MW2_EXE_LEFTGAME=%s 离开了游戏

MW2_PLATFORM_RELOAD=换弹
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=弹药不足
MW2_WEAPON_NO_AMMO=无弹药

MW2_MPUI_WINNING_CAPS=领先
MW2_MPUI_LOSING_CAPS=落后
MW2_MPUI_TIED_CAPS=平局

MW2_CGAME_SB_SCORE=得分
MW2_CGAME_SB_DEATHS=死亡
MW2_CGAME_SB_KILLS=击杀
MW2_CGAME_SB_ASSISTS=助攻

MW2_PLATFORM_THROWBACKGRENADE=%s 投回手雷

MW2_MP_FIRSTPLACE_NAME=第1名 %s
MW2_MP_SECONDPLACE_NAME=第2名 %s
MW2_MP_THIRDPLACE_NAME=第3名 %s

# Partially custom
MW2_GAME_CHANGEDTO=%s 已更改为 %s

# Round Starter
MW2_MP_MATCH_STARTING_IN=比赛将开始于：
MW2_MP_MATCH_RESUMING_IN=比赛将恢复于：

# Gamemodes
MW2_MPUI_SABOTAGE=破坏模式
MW2_MPUI_DEATHMATCH=混战
MW2_MPUI_CAPTURE_THE_FLAG=夺旗模式
MW2_MPUI_HEADQUARTERS=总部模式
MW2_MPUI_SEARCH_AND_DESTROY=搜索与摧毁
MW2_MPUI_WAR=团队死斗
MW2_MPUI_DOMINATION=统治模式
MW2_MPUI_ONE_FLAG=单旗夺旗
MW2_MPUI_ARENA=竞技场
MW2_MPUI_DD=破坏模式
MW2_MPUI_VIP=VIP护送
MW2_MPUI_GTNW=全球核战

MW2_MP_OBJ_DM_HINT=消灭其他玩家。
MW2_MP_OBJ_WAR_HINT=消灭敌方玩家。
MW2_OBJECTIVES_WAR_HINT=消灭敌方玩家。
MW2_OBJECTIVES_SD_ATTACKER_HINT=摧毁目标 A 或 B。
MW2_OBJECTIVES_SD_DEFENDER_HINT=保护目标 A 和 B。
MW2_OBJECTIVES_SAB_HINT=摧毁敌方目标。
MW2_OBJECTIVES_DOM_HINT=占领旗帜并防守。
MW2_OBJECTIVES_DM_HINT=消灭其他玩家。
MW2_OBJECTIVES_KOTH_HINT=占领总部。
MW2_OBJECTIVES_CTF_HINT=夺取敌方旗帜。
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=夺取敌方旗帜。
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=防守己方旗帜。
MW2_OBJECTIVES_DD_ATTACKER_HINT=摧毁目标 A 和 B。
MW2_OBJECTIVES_DD_DEFENDER_HINT=保护目标 A 和 B。
MW2_OBJECTIVES_VIP_ATTACKER_HINT=击杀VIP，阻止其到达撤离点。
MW2_OBJECTIVES_VIP_DEFENDER_HINT=保护VIP，助其到达撤离点。
MW2_OBJECTIVES_ARENA_HINT=消灭敌人或夺取旗帜
MW2_OBJECTIVES_GTNW_HINT=夺取核弹。
MW2_OBJECTIVES_GRAB_FLAG_HINT=夺取敌方旗帜。

# Round Ender
MW2_MP_DRAW=平局
MW2_MP_VICTORY=胜利！
MW2_MP_DEFEAT=失败！
MW2_MP_ROUND_DRAW=回合平局
MW2_MP_ROUND_WIN=回合胜利
MW2_MP_ROUND_LOSS=回合失败
MW2_MP_HALFTIME=半场休息
MW2_MP_OVERTIME=加时
MW2_MP_MATCH_BONUS_IS=比赛奖励：%s

MW2_MP_SCORE_LIMIT_REACHED=已达分数上限
MW2_MP_ROUND_LIMIT_REACHED=已达回合上限
MW2_MP_TIME_LIMIT_REACHED=已达时间上限
MW2_MP_HOST_ENDED_GAME=主机已结束游戏

# Notifications
MW2_RANK_PROMOTED=你已晋升！
MW2_RANK_PLAYER_WAS_PROMOTED=%s 已晋升为 %s！

# Ranks
MW2_RANK_REC_FULL=新兵
MW2_RANK_PVT_FULL=列兵
MW2_RANK_PFC_FULL=一等兵
MW2_RANK_LCPL_FULL=准下士
MW2_RANK_CPL_FULL=下士
MW2_RANK_SGT_FULL=中士
MW2_RANK_SSGT_FULL=上士
MW2_RANK_GYSGT_FULL=三级军士长
MW2_RANK_MSGT_FULL=二级军士长
MW2_RANK_MGYSGT_FULL=一级军士长
MW2_RANK_2NDLT_FULL=少尉
MW2_RANK_1STLT_FULL=中尉
MW2_RANK_CAPT_FULL=上尉
MW2_RANK_MAJ_FULL=少校
MW2_RANK_LTCOL_FULL=中校
MW2_RANK_COL_FULL=上校
MW2_RANK_BGEN_FULL=准将
MW2_RANK_MAJGEN_FULL=少将
MW2_RANK_LTGEN_FULL=中将
MW2_RANK_GEN_FULL=上将
MW2_RANK_COMM_FULL=指挥官
MW2_RANK_1STLT_FULL2=中尉 I
MW2_RANK_1STLT_FULL3=中尉 II
MW2_RANK_2NDLT_FULL2=少尉 I
MW2_RANK_2NDLT_FULL3=少尉 II
MW2_RANK_BGEN_FULL2=准将 I
MW2_RANK_BGEN_FULL3=准将 II
MW2_RANK_CAPT_FULL2=上尉 I
MW2_RANK_CAPT_FULL3=上尉 II
MW2_RANK_COL_FULL2=上校 I
MW2_RANK_COL_FULL3=上校 II
MW2_RANK_COMM_FULL2=指挥官 I
MW2_RANK_COMM_FULL3=指挥官 II
MW2_RANK_CPL_FULL2=下士 I
MW2_RANK_CPL_FULL3=下士 II
MW2_RANK_GEN_FULL2=上将 I
MW2_RANK_GEN_FULL3=上将 II
MW2_RANK_GYSGT_FULL2=三级军士长 I
MW2_RANK_GYSGT_FULL3=三级军士长 II
MW2_RANK_LCPL_FULL2=准下士 I
MW2_RANK_LCPL_FULL3=准下士 II
MW2_RANK_LTCOL_FULL2=中校 I
MW2_RANK_LTCOL_FULL3=中校 II
MW2_RANK_MAJ_FULL2=少校 I
MW2_RANK_MAJ_FULL3=少校 II
MW2_RANK_MAJGEN_FULL2=少将 I
MW2_RANK_MAJGEN_FULL3=少将 II
MW2_RANK_MGYSGT_FULL2=一级军士长 I
MW2_RANK_MGYSGT_FULL3=一级军士长 II
MW2_RANK_MSGT_FULL2=二级军士长 I
MW2_RANK_MSGT_FULL3=二级军士长 II
MW2_RANK_PFC_FULL2=一等兵 I
MW2_RANK_PFC_FULL3=一等兵 II
MW2_RANK_PVT_FULL2=列兵 I
MW2_RANK_PVT_FULL3=列兵 II
MW2_RANK_REC_FULL2=新兵 I
MW2_RANK_REC_FULL3=新兵 II
MW2_RANK_SGT_FULL2=中士 I
MW2_RANK_SGT_FULL3=中士 II
MW2_RANK_SSGT_FULL2=上士 I
MW2_RANK_SSGT_FULL3=上士 II
MW2_RANK_LTGEN_FULL2=中将 I
MW2_RANK_LTGEN_FULL3=中将 II
MW2_RANK_SGTMAJ_FULL=军士长
MW2_RANK_SGTMAJ_FULL2=军士长 I
MW2_RANK_SGTMAJ_FULL3=军士长 II
MW2_RANK_SPC_FULL=技术兵
MW2_RANK_SPC_FULL2=技术兵 I
MW2_RANK_SPC_FULL3=技术兵 II
MW2_RANK_SFC_FULL=军士长
MW2_RANK_SFC_FULL2=军士长 I
MW2_RANK_SFC_FULL3=军士长 II
MW2_RANK_1STSGT_FULL=一级军士长
MW2_RANK_1STSGT_FULL2=一级军士长 I
MW2_RANK_1STSGT_FULL3=一级军士长 II
MW2_RANK_CSM_FULL=总军士长
MW2_RANK_CSM_FULL2=总军士长 I
MW2_RANK_CSM_FULL3=总军士长 II
MW2_RANK_CSM_FULL4=总军士长 III
MW2_RANK_GEN_FULL4=上将 III
MW2_RANK_LTGEN_FULL4=中将 III
MW2_RANK_MAJGEN_FULL4=少将 III
MW2_RANK_BGEN_FULL4=准将 III
MW2_RANK_COL_FULL4=上校 III
MW2_RANK_LTCOL_FULL4=中校 III
MW2_RANK_MAJ_FULL4=少校 III
MW2_RANK_CAPT_FULL4=上尉 III
MW2_RANK_1STLT_FULL4=中尉 III
MW2_RANK_2NDLT_FULL4=少尉 III
