#---------- Black Ops II HUD | 简体中文 | Simplified Chinese
# Translator: WhatUziname7

# Factions
BO2_MP_SEALS_NAME=海豹突击队
BO2_MP_PLA_NAME=战略防御联盟
BO2_MP_FBI_NAME=联邦调查局
BO2_MP_PMC_NAME=雇佣兵
BO2_MP_ISA_NAME=国际安全联盟
BO2_MP_CD_NAME=民兵

BO2_MPUI_SEALS_SHORT=海豹
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=雇佣兵
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=民兵

BO2_MPUI_SEALS_SHORT_CAPS=海豹
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=雇佣兵
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=民兵

# Splashes
BO2_MEDAL_FIRST_KILL=首杀
BO2_MEDAL_ASSISTED_SUICIDE=助攻自杀
BO2_MEDAL_HEADSHOT=爆头
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=逆境反杀
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=死后击杀
BO2_MEDAL_LONGSHOT_KILL=远射
BO2_MEDAL_REVENGE_KILL=复仇
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=幸存者
BO2_MEDAL_KILL_ENEMY_IN_AIR=空击杀
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=一枪毙命
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=四连杀
BO2_MEDAL_KILLSTREAK_5=暴怒
BO2_MEDAL_KILLSTREAK_10=无情
BO2_MEDAL_KILLSTREAK_15=残忍
BO2_MEDAL_KILLSTREAK_20=冷酷
BO2_MEDAL_KILLSTREAK_25=狂暴
BO2_MEDAL_KILLSTREAK_30=核弹
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=势不可挡
BO2_MEDAL_MULTIKILL_2=双杀
BO2_MEDAL_MULTIKILL_3=三杀
BO2_MEDAL_MULTIKILL_4=狂怒击杀
BO2_MEDAL_MULTIKILL_5=疯狂击杀
BO2_MEDAL_MULTIKILL_6=超级击杀
BO2_MEDAL_MULTIKILL_7=巨兽击杀
BO2_MEDAL_MULTIKILL_8=极限击杀
BO2_MEDAL_MULTIKILL_MORE_THAN_8=杀戮链
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=复仇者
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=拯救者

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s 分获胜

# Notifications
BO2_RANK_PROMOTED=你已晋升！
BO2_RANK_PLAYER_WAS_PROMOTED=%s 已晋升为 %s！

# Ranks
BO2_RANK_PRVT_FULL=列兵
BO2_RANK_PRVT_FULL2=列兵 II
BO2_RANK_PRVT_FULL3=列兵 III
BO2_RANK_PFC_FULL=一等兵
BO2_RANK_PFC_FULL2=一等兵 II
BO2_RANK_PFC_FULL3=一等兵 III
BO2_RANK_LCPL_FULL=准下士
BO2_RANK_LCPL_FULL2=准下士 II
BO2_RANK_LCPL_FULL3=准下士 III
BO2_RANK_CPL_FULL=下士
BO2_RANK_CPL_FULL2=下士 II
BO2_RANK_CPL_FULL3=下士 III
BO2_RANK_SGT_FULL=中士
BO2_RANK_SGT_FULL2=中士 II
BO2_RANK_SGT_FULL3=中士 III
BO2_RANK_SSGT_FULL=上士
BO2_RANK_SSGT_FULL2=上士 II
BO2_RANK_SSGT_FULL3=上士 III
BO2_RANK_GYSGT_FULL=三级军士长
BO2_RANK_GYSGT_FULL2=三级军士长 II
BO2_RANK_GYSGT_FULL3=三级军士长 III
BO2_RANK_MSGT_FULL=二级军士长
BO2_RANK_MSGT_FULL2=二级军士长 II
BO2_RANK_MSGT_FULL3=二级军士长 III
BO2_RANK_MGYSGT_FULL=一级军士长
BO2_RANK_MGYSGT_FULL2=一级军士长 II
BO2_RANK_MGYSGT_FULL3=一级军士长 III
BO2_RANK_2NDLT_FULL=少尉
BO2_RANK_2NDLT_FULL2=少尉 II
BO2_RANK_2NDLT_FULL3=少尉 III
BO2_RANK_LT_FULL=中尉
BO2_RANK_LT_FULL2=中尉 II
BO2_RANK_LT_FULL3=中尉 III
BO2_RANK_CPT_FULL=上尉
BO2_RANK_CPT_FULL2=上尉 II
BO2_RANK_CPT_FULL3=上尉 III
BO2_RANK_MAJ_FULL=少校
BO2_RANK_MAJ_FULL2=少校 II
BO2_RANK_MAJ_FULL3=少校 III
BO2_RANK_LTCOL_FULL=中校
BO2_RANK_LTCOL_FULL2=中校 II
BO2_RANK_LTCOL_FULL3=中校 III
BO2_RANK_COL_FULL=上校
BO2_RANK_COL_FULL2=上校 II
BO2_RANK_COL_FULL3=上校 III
BO2_RANK_BGEN_FULL=准将
BO2_RANK_BGEN_FULL2=准将 II
BO2_RANK_BGEN_FULL3=准将 III
BO2_RANK_MAJGEN_FULL=少将
BO2_RANK_MAJGEN_FULL2=少将 II
BO2_RANK_MAJGEN_FULL3=少将 III
BO2_RANK_LTGEN_FULL=中将
BO2_RANK_LTGEN_FULL2=中将 II
BO2_RANK_LTGEN_FULL3=中将 III
BO2_RANK_GEN_FULL=上将
BO2_RANK_GEN_FULL2=上将 II
BO2_RANK_GEN_FULL3=上将 III
BO2_RANK_COM_FULL=指挥官
