#---------- CoD4 HUD | 简体中文 | Simplified Chinese
# Translator: WhatUziname7

# Factions
CoD4_MPUI_MARINES=海军陆战队
CoD4_MPUI_SPETSNAZ=俄罗斯特种部队
CoD4_MPUI_OPFOR=反对派武装
CoD4_MPUI_SAS=英国特别空勤团

CoD4_MPUI_MARINES_SHORT=陆战队
CoD4_MPUI_SPETSNAZ_SHORT=俄特
CoD4_MPUI_OPFOR_SHORT=反对派
CoD4_MPUI_SAS_SHORT=S.A.S.

# Challenges
CoD4_MP_CHALLENGE_COMPLETED=挑战完成！