#---------- Black Ops II HUD | Deutsch | German
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEALS
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Söldner
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Miliz

BO2_MPUI_SEALS_SHORT=SEALS
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Söldner
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Miliz

BO2_MPUI_SEALS_SHORT_CAPS=SEALS
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=SÖLDNER
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILIZ

# Splashes
BO2_MEDAL_FIRST_KILL=Starter
BO2_MEDAL_ASSISTED_SUICIDE=Selbstmordhilfe
BO2_MEDAL_HEADSHOT=Volltreffer
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=Comeback
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=Aus dem Jenseits
BO2_MEDAL_LONGSHOT_KILL=Weitschuss
BO2_MEDAL_REVENGE_KILL=Vergeltung
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=Überlebender
BO2_MEDAL_KILL_ENEMY_IN_AIR=Luftikus
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=Tödliche Präzision
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=Vierer
BO2_MEDAL_KILLSTREAK_5=Blutrünstig
BO2_MEDAL_KILLSTREAK_10=Gnadenlos
BO2_MEDAL_KILLSTREAK_15=Skrupellos
BO2_MEDAL_KILLSTREAK_20=Unnachgiebig
BO2_MEDAL_KILLSTREAK_25=Brutal
BO2_MEDAL_KILLSTREAK_30=Nuklear
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=Unaufhaltsam
BO2_MEDAL_MULTIKILL_2=Doppelabschuss
BO2_MEDAL_MULTIKILL_3=Dreifachabschuss
BO2_MEDAL_MULTIKILL_4=Zornabschuss
BO2_MEDAL_MULTIKILL_5=Wahnsinnsabschuss
BO2_MEDAL_MULTIKILL_6=Superabschuss
BO2_MEDAL_MULTIKILL_7=Mega-Abschuss
BO2_MEDAL_MULTIKILL_8=Ultra-Abschuss
BO2_MEDAL_MULTIKILL_MORE_THAN_8=Abschusskette
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=Rächer
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=Retter

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s PUNKTE ZUM SIEG
