#---------- CoD4 HUD | Deutsch | German
# Translator: Original Game

# Factions
CoD4_MPUI_MARINES=Marines
CoD4_MPUI_SPETSNAZ=Speznas
CoD4_MPUI_OPFOR=OpFor
CoD4_MPUI_SAS=SAS

CoD4_MPUI_MARINES_SHORT=Marines
CoD4_MPUI_SPETSNAZ_SHORT=Speznas
CoD4_MPUI_OPFOR_SHORT=OpFor
CoD4_MPUI_SAS_SHORT=SAS

# Challenges
CoD4_MP_CHALLENGE_COMPLETED=Herausford. geschafft!