#---------- Black Ops HUD | Deutsch | German
# Translator: Original Game

# Factions
BO1_MP_TROPAS_NAME=TROPAS
BO1_MP_NVA_NAME=NVA
BO1_MP_RUSSIAN_NAME=SPEZNAS
BO1_MP_SPECOPS_NAME=BLACK OPS
BO1_MP_MARINE_NAME=SOG
BO1_MP_REBELS_NAME=OP 40

BO1_MPUI_TROPAS_SHORT=Tropas
BO1_MPUI_NVA_SHORT=NVA
BO1_MPUI_RUSSIAN_SHORT=Speznas
BO1_MPUI_SPECOPS_SHORT=Black Ops
BO1_MPUI_MARINE_SHORT=SOG
BO1_MPUI_REBELS_SHORT=Op 40

BO1_MPUI_TROPAS_SHORT_CAPS=TROPAS
BO1_MPUI_NVA_SHORT_CAPS=NVA
BO1_MPUI_RUSSIAN_SHORT_CAPS=SPEZNAS
BO1_MPUI_SPECOPS_SHORT_CAPS=BLACK OPS
BO1_MPUI_MARINE_SHORT_CAPS=SOG
BO1_MPUI_REBELS_SHORT_CAPS=OP 40

# Splashes
BO1_MEDAL_BUZZ_KILL=Spielverderber
BO1_MEDAL_BUZZ_KILL_DESC=Feind kurz vor einer Abschussserie gestoppt.
BO1_MEDAL_LONG_SHOT=Fernkämpfer
BO1_MEDAL_LONG_SHOT_DESC=Feind per Fernangriff ausgeschaltet.
BO1_MEDAL_HEAD_SHOT=Volltreffer
BO1_MEDAL_HEAD_SHOT_DESC=Bumm! Volltreffer.
BO1_MEDAL_STUCK_TO_PLAYER=Klette
BO1_MEDAL_STUCK_TO_PLAYER_DESC=Einem Feind einen Sprengsatz angeheftet.
BO1_MEDAL_BULLS_EYE=Skalpierer
BO1_MEDAL_BULLS_EYE_DESC=Feind mit einem Tomahawk getötet.
BO1_MEDAL_EXECUTION=Vollstrecker
BO1_MEDAL_EXECUTION_DESC=Feind am Boden mit Volltreffer getötet.
BO1_MEDAL_COMEBACK=Comeback
BO1_MEDAL_COMEBACK_DESC=Von einer Todesserie erholt.
BO1_MEDAL_AVENGER=Rächer
BO1_MEDAL_AVENGER_DESC=Feind ausgeschaltet, der gerade einen Teamkameraden getötet hat.
BO1_MEDAL_AFTERLIFE=Aus dem Jenseits
BO1_MEDAL_AFTERLIFE_DESC=Feind getötet, während Sie tot waren.
BO1_MEDAL_DOUBLE_KILL=Doppelabschuss
BO1_MEDAL_DOUBLE_KILL_DESC=2 Leute in schneller Abfolge getötet.
BO1_MEDAL_TRIPLE_KILL=Dreifachabschuss
BO1_MEDAL_TRIPLE_KILL_DESC=3 Leute in schneller Abfolge getötet.
BO1_MEDAL_MULTI_KILL=Multiabschuss
BO1_MEDAL_MULTI_KILL_DESC=Mehr als 3 in schneller Abfolge getötet.
BO1_MEDAL_FIRST_BLOOD=Starter
BO1_MEDAL_FIRST_BLOOD_DESC=Den ersten Abschuss gelandet.
BO1_MEDAL_BACK_STABBER=Verräter
BO1_MEDAL_BACK_STABBER_DESC=Einem Spieler das Messer in den Rücken gerammt.
BO1_MEDAL_HIJACKER=Dieb
BO1_MEDAL_HIJACKER_DESC=Feindliche Kiste gestohlen.
BO1_MEDAL_SHARE_PACKAGE=Vorratsteiler
BO1_MEDAL_SHARE_PACKAGE_DESC=Ein Teamkamerad hat Ihre Kiste geschützt.
BO1_MEDAL_ONE_SHOT_KILL=Schuss, Treffer
BO1_MEDAL_ONE_SHOT_KILL_DESC=Feind mit einem Schuss getötet.
BO1_MEDAL_PAYBACK=Zahltag
BO1_MEDAL_PAYBACK_DESC=Feind getötet, der Sie getötet hat.
BO1_MEDAL_RESCUER=Retter
BO1_MEDAL_RESCUER_DESC=Einen verwundeten Teamkameraden gerettet.
BO1_MEDAL_ASSISTED_SUICIDE=Selbstmordhilfe
BO1_MEDAL_ASSISTED_SUICIDE_DESC=Einen Feind verletzt, der Selbstmord begangen hat.
BO1_MEDAL_HEROIC=Überragend
BO1_MEDAL_HEROIC_DESC=Mit Zweiter Chance einen Punkt erobert.
BO1_MEDAL_ASSISTS=Assist
BO1_MEDAL_ASSISTS_DESC=Bei einem Abschuss geholfen.
BO1_MEDAL_DESTROYER=Schrott
BO1_MEDAL_DESTROYER_DESC=Ein feindliches Fahrzeug zerstört.
BO1_MEDAL_STREAKER=Serientäter
BO1_MEDAL_STREAKER_DESC=Eine Abschussserie angefordert.
BO1_MEDAL_HERO=Held
BO1_MEDAL_HERO_DESC=Die Bombe entschärft.
BO1_MEDAL_ANTI_BOMBER=Anti-Bomber
BO1_MEDAL_ANTI_BOMBER_DESC=Den feindlichen Bombenentschärfer getötet.
BO1_MEDAL_OFFENSE=Angriff
BO1_MEDAL_OFFENSE_DESC=Einen Feind beim Ziel getötet.
BO1_MEDAL_DEFENSE=Verteidigung
BO1_MEDAL_DEFENSE_DESC=Einen Feind beim Verteidigungspunkt getötet.
BO1_MEDAL_POSITION_SECURE=Gesichert
BO1_MEDAL_POSITION_SECURE_DESC=Ein Ziel erobert.
BO1_MEDAL_FLAG_RUNNER=Flaggenläufer
BO1_MEDAL_FLAG_RUNNER_DESC=Die feindliche Flagge aufgenommen.
BO1_MEDAL_FLAG_CAPTURE=Flaggen-Einnehmer
BO1_MEDAL_FLAG_CAPTURE_DESC=Die feindliche Flagge erobert.
BO1_MEDAL_SABOTEUR=Saboteur
BO1_MEDAL_SABOTEUR_DESC=Die Bombe platziert.
BO1_MEDAL_BOMBER=Bomber
BO1_MEDAL_BOMBER_DESC=Die Bombe gezündet.
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=Ein Konter-Spionageflugzeug abgeschossen.
BO1_MEDAL_DESTROYER_UAV_DESC=Ein Spionageflugzeug abgeschossen.
BO1_MEDAL_DESTROYER_TURRET_DESC=Ein Geschütz ausgeschaltet.
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=Einen Helikopter abgeschossen.
BO1_MEDAL_FLAG_RETURN=Zurückbringer
BO1_MEDAL_FLAG_RETURN_DESC=Die Flagge zurückgebracht.
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=Geschütz-Treffer
BO1_MEDAL_BALLISTIC_KNIFE_KILL=Spieß
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=Einen Feind mit dem ballistischen Messer abgeschossen.
BO1_MEDAL_BANK_SHOT=Abpraller
BO1_MEDAL_BANK_SHOT_DESC=Den Feind mit einem abgeprallten Tomahawk ausgeschaltet.
BO1_MEDAL_REVIVE=Sanitäter
BO1_MEDAL_REVIVE_DESC=Einen Teamkameraden wiederbelebt
BO1_MEDAL_DESTROYER_M220_TOW=Freier Himmel
BO1_MEDAL_DESTROYER_M220_TOW_DESC=Eine Walküre ausgeschaltet.
BO1_MEDAL_DESTROYER_RCBOMB=Fahrspaß
BO1_MEDAL_DESTROYER_RCBOMB_DESC=Fernlenkladung ausgeschaltet.
BO1_MEDAL_AIRCRAFT_ASSIST=Abschusshilfe
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=Beim Abschuss eines feindlichen Flugzeugs geholfen.

# Round Starter
BO1_MP_MATCH_STARTING_IN=SPIEL BEGINNT IN

# Other
BO1_MENU_WINNING_CAPS=SIEG
BO1_MENU_LOSING_CAPS=NIEDERLAGE
BO1_MENU_TIED_CAPS=UNENTSCHIEDEN

BO1_MENU_WINNING=Sieg
BO1_MENU_TIED=Unentschieden
BO1_MENU_LOSING=Niederlage

# Scoreboard
BO1_CGAME_SB_KILLS=Absch.
BO1_CGAME_SB_ASSISTS=Assis.
BO1_CGAME_SB_KDRATIO=Quote
BO1_CGAME_SB_SCORE=Pkt.
BO1_CGAME_SB_DEATHS=Tode
BO1_CGAME_SB_PING=Ping

# Gamemodes
BO1_OBJECTIVES_SD_ATTACKER_HINT=ZERSTÖREN SIE ZIEL A ODER B
BO1_OBJECTIVES_SD_DEFENDER_HINT=BESCHÜTZEN SIE ZIELE A UND B
BO1_OBJECTIVES_SAB_HINT=FEINDLICHES ZIEL ZERSTÖREN
BO1_OBJECTIVES_DOM_HINT=EROBERN SIE DIE FLAGGEN UND VERTEIDIGEN SIE SIE
BO1_OBJECTIVES_DM_HINT=ELIMINIEREN SIE ANDERE SPIELER
BO1_OBJECTIVES_TDM_HINT=ELIMINIEREN SIE FEINDLICHE SPIELER
BO1_OBJECTIVES_CTF_HINT=NEHMEN SIE DIE FEINDLICHE FLAGGE EIN
BO1_OBJECTIVES_DEM_ATTACKER_HINT=ZERSTÖREN SIE ZIELE A UND B
