#---------- CoD HUD Settings | Deutsch | German
# Translator: Machine translated

# ------------------[ GENERAL ]------------------
CoDHUD.Title=CoD HUD

CoDHUD.Client=Client
CoDHUD.Server=Server
CoDHUD.General=Allgemein

CoDHUD.Close=Schließen

CoDHUD.Default=Standard: %s
CoDHUD.Current=Aktuell: %s

# ------------------[ MENU GLYPHS ]------------------
CoDHUD.Glyph.Toggle=[+attack] Umschalten
CoDHUD.Glyph.Open=[+attack] Öffnen
CoDHUD.Glyph.OpenMenu=[+attack] Menü öffnen
CoDHUD.Glyph.Select=[+attack] Auswählen
CoDHUD.Glyph.Confirm=[+attack] Bestätigen
CoDHUD.Glyph.Return=[+attack] Zurück
CoDHUD.Glyph.Close=[+attack] Schließen
CoDHUD.Glyph.Tab=[+attack] Tab öffnen
CoDHUD.Glyph.Reset=[+attack2] Zurücksetzen

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.RoundStart=Rundensteuerung

CoDHUD.RoundStart.Gamemode=Spielmodus
CoDHUD.RoundStart.Info=Wähle den zu spielenden Spielmodus.

CoDHUD.RoundStart.Start=Runde starten
CoDHUD.RoundStart.Start.desc=Sobald ein Spielmodus ausgewählt wurde und die Einstellungen deinen Wünschen entsprechen, kannst du den Rundenstart beginnen.

CoDHUD.RoundStart.Notice=Bist du sicher, dass du eine neue Runde starten möchtest?\nAlle Punktestände werden zurückgesetzt und alle Spieler respawnen.
CoDHUD.RoundStart.Yes=Runde starten

CoDHUD.RoundStart.Timer=Rundenstart-Timer
CoDHUD.RoundStart.Timer.desc=Wie viele Sekunden Unterbrechung soll es vor Beginn der Runde geben.

CoDHUD.RoundStart.Autobalance=Fraktionen beim Rundenstart zufällig verteilen
CoDHUD.RoundStart.Autobalance.desc=Falls aktiviert, werden alle Spieler beim Start der Runde zufällig einer gültigen Fraktion zugewiesen.

CoDHUD.Scorelimit=Punktelimit
CoDHUD.Scorelimit.desc=Legt das maximale Punktelimit auf der Punkteanzeige fest.\n\nGemessen in Kills.

CoDHUD.Timelimit=Zeitlimit
CoDHUD.Timelimit.desc=Legt das Zeitlimit fest, bevor die Runde automatisch endet.\n\nGemessen in Minuten.\n\nAuf 0 setzen für unbegrenzt.

CoDHUD.Autobalance.Amount=Auto-Balance-Teamlimit
CoDHUD.Autobalance.Amount.desc=Legt die maximale Anzahl an Fraktionen fest, zu denen Spieler automatisch ausgeglichen werden können.

CoDHUD.Autobalance.Amount.disable=Deaktiviert
CoDHUD.Autobalance.Amount.2=2 Teams
CoDHUD.Autobalance.Amount.3=3 Teams
CoDHUD.Autobalance.Amount.4=4 Teams

CoDHUD.RoundStart.Auto=Runde beim Serverstart automatisch beginnen
CoDHUD.RoundStart.Auto.desc=Falls aktiviert, beginnt sofort eine neue Runde, sobald der erste Spieler dem Server beitritt.

CoDHUD.Admin.ResetTime=Runden-Timer zurücksetzen
CoDHUD.Admin.ResetTime.desc=Setzt den aktuellen Runden-Timer unabhängig vom aktuellen Wert auf den Wert des Zeitlimits zurück.

CoDHUD.ForceEndRound=Runde zwangsweise beenden
CoDHUD.ForceEndRound.desc=Klicke hier, wenn du die Runde vor Erreichen des Punkte- oder Zeitlimits beenden musst oder möchtest.

CoDHUD.ForceEndRound.Notice=Bist du sicher, dass du die Runde zwangsweise beenden möchtest?

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen="Spiel beendet" aktivieren
CoDHUD.Admin.EndScreen.desc=Aktiviert ein „Spiel beendet“-System, sobald das Punktelimit erreicht wird.

CoDHUD.Admin.EndScreen.StartNext=Nächste Runde nach Spielende starten
CoDHUD.Admin.EndScreen.StartNext.desc=Falls aktiviert, beginnt nach Ablauf der Spielende-Dauer automatisch eine neue Runde.\n\nFalls deaktiviert, respawnen alle Spieler normal.

CoDHUD.Admin.FriendlyFire=Eigenbeschuss erlauben
CoDHUD.Admin.FriendlyFire.desc=Falls aktiviert, können Spieler derselben Fraktion einander Schaden zufügen.\n\nGilt nur im Team-Deathmatch.

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=Fraktionen & HUD-Typ einschränken
CoDHUD.Admin.RestrictType.Choose=Spiel auswählen
CoDHUD.Admin.RestrictType.desc=Wähle, auf welchen CoD-Titel Benutzer beschränkt werden sollen. Dies beeinflusst das HUD und die verfügbaren Fraktionen.

CoDHUD.Admin.RestrictType.Warning=Warnung!\nDas Wechseln des Spiels hat folgende Konsequenzen:\n- Die Fraktionen aller Spieler werden zufällig ausgewählt.\n- Alle Spielerpunkte werden auf 0 zurückgesetzt.\n- Alle Spieler werden getötet und respawnen.\n\nBist du sicher, dass du das Spiel wechseln möchtest?

CoDHUD.Type.cod4=Modern Warfare 1
CoDHUD.Type.waw=World at War
CoDHUD.Type.mw2=Modern Warfare 2
CoDHUD.Type.bo1=Black Ops
CoDHUD.Type.mw3=Modern Warfare 3
CoDHUD.Type.bo2=Black Ops II
CoDHUD.Type.ghosts=Ghosts
CoDHUD.Type.aw=Advanced Warfare
CoDHUD.Type.bo3=Black Ops III
CoDHUD.Type.iw=Infinite Warfare
CoDHUD.Type.ww2=WWII

CoDHUD.Admin.RestrictFactionChance=Fraktionswechsel einschränken
CoDHUD.Admin.RestrictFactionChance.desc=Lege fest, wann Spieler ihre Fraktion wechseln dürfen.

CoDHUD.Admin.RestrictFactionChance.disable=Kann nicht wechseln
CoDHUD.Admin.RestrictFactionChance.freely=Kann frei wechseln
CoDHUD.Admin.RestrictFactionChance.pool=Nur aus aktivem Pool

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=Fraktionsauswahl
CoDHUD.Faction.Select.desc=Wähle, welche Fraktion du repräsentieren möchtest.\nBeeinflusst deinen Freund-oder-Feind-Status und ändert Ansager sowie Theme passend zur Fraktion.

CoDHUD.Faction.ChangeWarning=Warnung!\nDas Wechseln des Teams hat folgende Konsequenzen:\n- Dein Punktestand wird auf 0 zurückgesetzt.\n- Du wirst getötet und respawnst.\n\nBist du sicher, dass du die Fraktion wechseln möchtest?

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=Schnellzugriff

CoDHUD.Quick.DisableHUD=Alle HUD-Optionen schnell deaktivieren
CoDHUD.Quick.DisableHUD.desc=Deaktiviert alle CoD-HUD-Optionen.

# ---------[ HUD-RELATED ]---------
CoDHUD.HUD=HUD-Einstellungen

# Multiple
CoDHUD.HUD.Outline=Umrandeter Text
CoDHUD.HUD.Outline.desc=Aktiviert umrandete Texte auf einigen Elementen, damit sie in sehr hellen Bereichen besser lesbar sind.

CoDHUD.HUD.Sound=SFX abspielen
CoDHUD.HUD.Sound.desc=Spielt zugehörige Soundeffekte ab, sofern der HUD-Typ dies unterstützt.

CoDHUD.HUD.Time.Total=Aktive Zeit
CoDHUD.HUD.Time.Total.desc=Wie lange die Variable nach vollständigem Einblenden sichtbar bleibt, bevor sie wieder ausgeblendet wird.

CoDHUD.HUD.Time.Fadein=Einblendzeit
CoDHUD.HUD.Time.Fadein.desc=Wie lange das Einblenden dieser Variable dauert.

CoDHUD.HUD.Time.Fadeout=Ausblendzeit
CoDHUD.HUD.Time.Fadeout.desc=Wie lange das Ausblenden dieser Variable dauert.

# Scale
CoDHUD.HUD.Scale=UI-Skalierung

CoDHUD.HUD.Scale.Enable=UI-Skalierungs-Multiplikator
CoDHUD.HUD.Scale.Enable.desc=Passt die Skalierung der vom CoD HUD verwendeten UI-Elemente an.\n\nNützlich für niedrige oder Ultrawide-Auflösungen.\n\n<color=255,255,100>Hinweis</color>: Das Menü wird nach dem Anwenden neu geladen.\n\n<color=255,100,100>WARNUNG</color>: Einige Elemente könnten stark falsch ausgerichtet werden, wenn der Wert unnötig zu hoch oder zu niedrig eingestellt wird.

# Scoreboard
CoDHUD.HUD.Scoreboard=Punktetafel

CoDHUD.HUD.Scoreboard.Enable=Punktetafel aktivieren
CoDHUD.HUD.Scoreboard.Enable.desc=Aktiviert die Punktetafel. Zeigt die aktuell von allen Spielern belegten Fraktionen an.

# Score Counter
CoDHUD.HUD.Scorecounter=Punkteanzeige

CoDHUD.HUD.Scorecounter.Enable=Punkteanzeige aktivieren
CoDHUD.HUD.Scorecounter.Enable.desc=Aktiviert einen Server-Timer, ein Fraktionssymbol und Punktestände.\n\nEinige HUD-Typen zeigen das Fraktionssymbol nicht an.

# Medals
CoDHUD.HUD.Medals=Medaillen

CoDHUD.HUD.Medals.Enable=Medaillen aktivieren
CoDHUD.HUD.Medals.Enable.desc=Aktiviert Medaillen, die durch bestimmte Aktionen wie schnelle Kills oder Kopfschüsse verdient werden.\n\nBeachte, dass einige HUD-Typen nur Text anzeigen, während andere Text und Symbole besitzen.

CoDHUD.HUD.Medals.Speedup=Schneller bei langer Warteschlange
CoDHUD.HUD.Medals.Speedup.desc=Beschleunigt die Medaillen-Warteschlange, wenn viele Medaillen gleichzeitig anstehen.\n\nJe nach HUD-Typ werden außerdem die zugehörigen SFX deaktiviert, wenn mehr als 3 Medaillen in der Warteschlange sind.

# Kill Feed
CoDHUD.HUD.Killfeed=Killfeed

CoDHUD.HUD.Killfeed.Enable=Killfeed aktivieren
CoDHUD.HUD.Killfeed.Enable.desc=Aktiviert den Killfeed.

# Minimap
CoDHUD.HUD.Minimap=Minikarte

CoDHUD.HUD.Minimap.Enable=Minikarte aktivieren
CoDHUD.HUD.Minimap.Enable.desc=Aktiviert die Minikarte.

# Hitmarker
CoDHUD.HUD.Hitmarker=Treffermarkierung

CoDHUD.HUD.Hitmarker.Enable=Treffermarkierung aktivieren
CoDHUD.HUD.Hitmarker.Enable.desc=Aktiviert die Treffermarkierung und den zugehörigen Treffer-Sound.

# Weapon Info
CoDHUD.HUD.WeaponInfo=Waffeninformationen

CoDHUD.HUD.WeaponInfo.Enable=Waffeninformationen aktivieren
CoDHUD.HUD.WeaponInfo.Enable.desc=Aktiviert die Waffeninformationsanzeige mit Waffenname und Munitionszähler.\n\nEinige HUD-Typen integrieren hier zusätzlich den Kompass.

CoDHUD.HUD.WeaponPrompts.Enable=Waffenhinweise aktivieren
CoDHUD.HUD.WeaponPrompts.Enable.desc=Aktiviert Waffenhinweise wie Benachrichtigungen über niedrige Munition.

# XP Counter
CoDHUD.HUD.XP=XP-Anzeige

CoDHUD.HUD.XP.Enable=XP-Anzeige aktivieren
CoDHUD.HUD.XP.Enable.desc=Aktiviert XP-Benachrichtigungen.

# Target ID / IFF
CoDHUD.HUD.IFF=Freund oder Feind identifizieren

CoDHUD.HUD.IFF.Enable=IFF aktivieren
CoDHUD.HUD.IFF.Enable.desc=Aktiviert ein „Freund oder Feind identifizieren“-System, das den Namen des Ziels über dessen Kopf anzeigt, wenn du in seine Nähe zielst.

# Death Icon
CoDHUD.HUD.DeathIcon=Todesicon

CoDHUD.HUD.DeathIcon.Enable=Todesicon aktivieren
CoDHUD.HUD.DeathIcon.Enable.desc=Aktiviert das Todesicon, das angezeigt wird, wenn ein Spieler derselben Fraktion stirbt.

# Chat
CoDHUD.HUD.Chat=Chat

CoDHUD.HUD.Chat.Enable=Chat aktivieren
CoDHUD.HUD.Chat.Enable.desc=Aktiviert den Chat.

# Headers
CoDHUD.HUD.Headers=Überschriften

CoDHUD.HUD.Headers.Enable=Header-Benachrichtigungen aktivieren
CoDHUD.HUD.Headers.Enable.desc=Aktiviert Header-Benachrichtigungen, beispielsweise beim Abschließen von Herausforderungen oder beim Levelaufstieg.

# Subtitles
CoDHUD.HUD.Subtitles=Untertitel

CoDHUD.HUD.Subtitles.Enable=Untertitel aktivieren
CoDHUD.HUD.Subtitles.Enable.desc=Aktiviert Untertitel, wenn eine Sprecher-Voice-Line abgespielt wird.\n\n<color=255,100,100>Warnung</color>: Untertitel werden für die englischen Sprachzeilen erstellt.\n\n<color=255,255,100>Hinweis</color>: Übersetzte Untertitel sind nicht verfügbar.

CoDHUD.HUD.Subtitles.Callsign=Rufzeichen aktivieren
CoDHUD.HUD.Subtitles.Callsign.desc=Aktiviert das Rufzeichen des aktuell abgespielten Sprechers.

CoDHUD.HUD.Subtitles.NameAlign=Rufzeichen-Ausrichtung
CoDHUD.HUD.Subtitles.NameAlign.desc=Wählen Sie, wo das Rufzeichen des Sprechers angezeigt werden soll.

CoDHUD.HUD.Subtitles.NameAlign.Left=Links neben dem Text
CoDHUD.HUD.Subtitles.NameAlign.Top=Über dem Text

# ---------[ OTHER SETTINGS ]---------
CoDHUD.Settings=Weitere Einstellungen
CoDHUD.Audio=Audio-Einstellungen
CoDHUD.Audio.Announcer=Ansager
CoDHUD.Audio.Music=Musik

CoDHUD.Audio.Announcer.Enable=Ansager-Stimme aktivieren
CoDHUD.Audio.Announcer.Enable.desc=Aktiviert den Ansager.

CoDHUD.Audio.Announcer.English=Englischen Ansager erzwingen
CoDHUD.Audio.Announcer.English.desc=Erzwingt englische Ansagerstimmen unabhängig von der Spielsprache.

CoDHUD.Audio.Music.Enable=Musik aktivieren
CoDHUD.Audio.Music.Enable.desc=Aktiviert Musik.

CoDHUD.Audio.Music.Ambient=Ambient-Musik aktivieren
CoDHUD.Audio.Music.Ambient.desc=Aktiviert Ambient-Musik im Hintergrund.

CoDHUD.Reset=Einstellungen zurücksetzen
CoDHUD.Challenges.Reset=Herausforderungen zurücksetzen
CoDHUD.Challenges.Reset.desc=Setzt alle freigeschalteten Herausforderungen zurück.

CoDHUD.Rank.Reset=Rang & Statistiken zurücksetzen
CoDHUD.Rank.Reset.desc=Setzt den Rang und alle Statistiken des aktuellen HUDs zurück.
CoDHUD.Rank.Reset.Warning=Warnung!\nDu bist dabei, deinen Rang und deine Statistiken für dieses HUD zurückzusetzen!\nDies kann nicht rückgängig gemacht werden! Bist du sicher, dass du Rang und Statistiken zurücksetzen möchtest?

CoDHUD.Menu=Menü-Einstellungen
CoDHUD.Menu.Fullscreen=Im Vollbild öffnen
CoDHUD.Menu.Fullscreen.desc=Öffnet das CoD-HUD-Menü im Vollbild statt in einem kleineren Fenster.

CoDHUD.Menu.SFX=Menü-SFX
CoDHUD.Menu.SFX.desc=Spielt thematische Menü-Soundeffekte beim Überfahren oder Drücken von Buttons ab.

CoDHUD.Menu.Music=Menümusik
CoDHUD.Menu.Music.desc=Spielt thematische Menümusik ab, wenn irgendeine CoD-HUD-Menüinstanz aktiv ist.

CoDHUD.Menu.HideDesc=Beschreibung ausblenden
CoDHUD.Menu.HideDesc.desc=Falls aktiviert, werden Menübeschreibungen ausgeblendet.

CoDHUD.Menu.HidePrompts=Hinweise ausblenden
CoDHUD.Menu.HidePrompts.desc=Falls aktiviert, werden die Button-Hinweise im Menü ausgeblendet.

CoDHUD.Menu.OpenSpeed=Öffnungsgeschwindigkeit des Menüs
CoDHUD.Menu.OpenSpeed.desc=Wie schnell das CoD-HUD-Menü neue Instanzen öffnet.\n\nGemessen in Sekunden.

CoDHUD.Menu.CloseSpeed=Schließgeschwindigkeit des Menüs
CoDHUD.Menu.CloseSpeed.desc=Wie schnell das CoD-HUD-Menü Instanzen schließt.\n\nGemessen in Sekunden.

# ---------[ RANK & STATS ]---------
CoDHUD.Stats=Spielerstatistiken
CoDHUD.Stats.Rank=Spielerlevel: %d - %s
CoDHUD.Stats.XPNext=XP für nächsten Rang: %d
CoDHUD.Stats.XP=Gesamte XP: %d
CoDHUD.Stats.Kills=Gesamte Kills: %d
CoDHUD.Stats.Headshots=Kopfschüsse: %d
CoDHUD.Stats.Deaths=Gesamte Tode: %d
CoDHUD.Stats.Challenges=Abgeschlossene Herausforderungen: %d

CoDHUD.Stats.Unknown=Unbekannt