#---------- Black Ops II HUD | English
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEALS
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Söldner
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Miliz

BO2_MPUI_SEALS_SHORT=SEALS
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Söldner
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Miliz

BO2_MPUI_SEALS_SHORT_CAPS=SEALS
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=SÖLDNER
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILIZ

# Splashes
BO2_MEDAL_FIRST_KILL=STARTER
BO2_MEDAL_ASSISTED_SUICIDE=SELBSTMORDHILFE
BO2_MEDAL_HEADSHOT=VOLLTREFFER
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=COMEBACK
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=AUS DEM JENSEITS
BO2_MEDAL_LONGSHOT_KILL=WEITSCHUSS
BO2_MEDAL_REVENGE_KILL=VERGELTUNG
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=ÜBERLEBENDER
BO2_MEDAL_KILL_ENEMY_IN_AIR=LUFTIKUS
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=TÖDLICHE PRÄZISION
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=VIERER
BO2_MEDAL_KILLSTREAK_5=BLUTRÜNSTIG
BO2_MEDAL_KILLSTREAK_10=GNADENLOS
BO2_MEDAL_KILLSTREAK_15=SKRUPELLOS
BO2_MEDAL_KILLSTREAK_20=UNNACHGIEBIG
BO2_MEDAL_KILLSTREAK_25=BRUTAL
BO2_MEDAL_KILLSTREAK_30=NUKLEAR
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=UNAUFHALTSAM
BO2_MEDAL_MULTIKILL_2=DOPPELABSCHUSS
BO2_MEDAL_MULTIKILL_3=DREIFACHABSCHUSS
BO2_MEDAL_MULTIKILL_4=ZORNABSCHUSS
BO2_MEDAL_MULTIKILL_5=WAHNSINNSABSCHUSS
BO2_MEDAL_MULTIKILL_6=SUPERABSCHUSS
BO2_MEDAL_MULTIKILL_7=MEGA-ABSCHUSS
BO2_MEDAL_MULTIKILL_8=ULTRA-ABSCHUSS
BO2_MEDAL_MULTIKILL_MORE_THAN_8=ABSCHUSSKETTE
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=RÄCHER
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=RETTER

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s PUNKTE ZUM SIEG
