#---------- CoD HUD System Notifications | Deutsch | German
# Translator: Machine translated

CoDHUD.System.ResetTime=Runden-Timer auf %s zurückgesetzt.
CoDHUD.System.ResetTime.Off=Runden-Timer entfernt.

CoDHUD.System.RestrictType=Spiel wurde zu %s geändert.
CoDHUD.System.RestrictType.NotNow=Spiel kann momentan nicht geändert werden.

CoDHUD.System.Faction.NotNow=Fraktionen können momentan nicht geändert werden.
CoDHUD.System.Faction.Denied=Fraktionen können nicht geändert werden.

CoDHUD.System.ChallengeReset=Alle Herausforderungen wurden zurückgesetzt.
CoDHUD.System.RankReset=Rang und Statistiken des HUDs '%s' wurden zurückgesetzt.

CoDHUD.System.CVChanged=Servervariable '%s' wurde auf %s geändert.

CoDHUD.System.ForceEndRound.NotNow=Die Runde kann momentan nicht zwangsweise beendet werden.
CoDHUD.System.ForceEndRound.NotStarting=Eine gerade startende Runde kann nicht zwangsweise beendet werden.