#---------- CoD: World at War HUD | Deutsch | German
# Translator: Original Game

# Factions
WAW_MPUI_RUSSIAN=Rote Armee
WAW_MPUI_JAPANESE=Japaner
WAW_MPUI_GERMAN=Deutsche
WAW_MPUI_MARINE=Marines

WAW_MPUI_RUSSIAN_SHORT=Rote Armee
WAW_MPUI_JAPANESE_SHORT=Japaner
WAW_MPUI_GERMAN_SHORT=Deutsche
WAW_MPUI_MARINE_SHORT=Marines

# Gamemodes
WAW_MPUI_TANK_WAR=Krieg
WAW_OBJECTIVES_TWAR_HINT=Erobern Sie die Flaggen und verteidigen Sie sie.