#---------- Black Ops II Ranks | Deutsch | German
# Translator: Original Game

# Notifications
BO2_RANK_PROMOTED=Sie wurden befördert!
BO2_RANK_PLAYER_WAS_PROMOTED=%s wurde befördert zum %s!

# Ranks
BO2_RANK_PRVT_FULL=Private
BO2_RANK_PRVT_FULL2=Private II
BO2_RANK_PRVT_FULL3=Private III
BO2_RANK_PFC_FULL=Private First Class
BO2_RANK_PFC_FULL2=Private First Class II
BO2_RANK_PFC_FULL3=Private First Class III
BO2_RANK_LCPL_FULL=Lance Corporal
BO2_RANK_LCPL_FULL2=Lance Corporal II
BO2_RANK_LCPL_FULL3=Lance Corporal III
BO2_RANK_CPL_FULL=Corporal
BO2_RANK_CPL_FULL2=Corporal II
BO2_RANK_CPL_FULL3=Corporal III
BO2_RANK_SGT_FULL=Sergeant
BO2_RANK_SGT_FULL2=Sergeant II
BO2_RANK_SGT_FULL3=Sergeant III
BO2_RANK_SSGT_FULL=Staff Sergeant
BO2_RANK_SSGT_FULL2=Staff Sergeant II
BO2_RANK_SSGT_FULL3=Staff Sergeant III
BO2_RANK_GYSGT_FULL=Gunnery Sergeant
BO2_RANK_GYSGT_FULL2=Gunnery Sergeant II
BO2_RANK_GYSGT_FULL3=Gunnery Sergeant III
BO2_RANK_MSGT_FULL=Master Sergeant
BO2_RANK_MSGT_FULL2=Master Sergeant II
BO2_RANK_MSGT_FULL3=Master  Sergeant III
BO2_RANK_MGYSGT_FULL=Master Gunnery Sergeant
BO2_RANK_MGYSGT_FULL2=Master Gunnery Sergeant II
BO2_RANK_MGYSGT_FULL3=Master Gunnery Sergeant III
BO2_RANK_2NDLT_FULL=Second Lieutenant
BO2_RANK_2NDLT_FULL2=Second Lieutenant II
BO2_RANK_2NDLT_FULL3=Second Lieutenant III
BO2_RANK_LT_FULL=Lieutenant
BO2_RANK_LT_FULL2=Lieutenant II
BO2_RANK_LT_FULL3=Lieutenant III
BO2_RANK_CPT_FULL=Captain
BO2_RANK_CPT_FULL2=Captain II
BO2_RANK_CPT_FULL3=Captain III
BO2_RANK_MAJ_FULL=Major
BO2_RANK_MAJ_FULL2=Major II
BO2_RANK_MAJ_FULL3=Major III
BO2_RANK_LTCOL_FULL=Lieutenant Colonel
BO2_RANK_LTCOL_FULL2=Lieutenant Colonel II
BO2_RANK_LTCOL_FULL3=Lieutenant Colonel III
BO2_RANK_COL_FULL=Colonel
BO2_RANK_COL_FULL2=Colonel II
BO2_RANK_COL_FULL3=Colonel III
BO2_RANK_BGEN_FULL=Brigadier General
BO2_RANK_BGEN_FULL2=Brigadier General II
BO2_RANK_BGEN_FULL3=Brigadier General III
BO2_RANK_MAJGEN_FULL=Major General
BO2_RANK_MAJGEN_FULL2=Major General II
BO2_RANK_MAJGEN_FULL3=Major General III
BO2_RANK_LTGEN_FULL=Lieutenant General
BO2_RANK_LTGEN_FULL2=Lieutenant General II
BO2_RANK_LTGEN_FULL3=Lieutenant General III
BO2_RANK_GEN_FULL=General
BO2_RANK_GEN_FULL2=General II
BO2_RANK_GEN_FULL3=General III
BO2_RANK_COM_FULL=Commander
