#---------- CoD: World at War Ranks | Español | Spanish
# Translator: Original Game

# Notifications
WAW_RANK_PROMOTED=¡Has sido ascendido!
WAW_RANK_PLAYER_WAS_PROMOTED=¡%s ha ascendido a %s!
  
# Ranks
WAW_RANK_PVT_FULL=Soldado
WAW_RANK_PFC_FULL=Soldado de primera
WAW_RANK_CPL_FULL=Cabo primero
WAW_RANK_SGT_FULL=Cabo mayor
WAW_RANK_SSGT_FULL=Sargento primero
WAW_RANK_GYSGT_FULL=Suboficial
WAW_RANK_MSGT_FULL=Subteniente
WAW_RANK_SGTM_FULL=Brigada
WAW_RANK_2NDLT_FULL=Alférez
WAW_RANK_1STLT_FULL=Teniente
WAW_RANK_CAPT_FULL=Capitán
WAW_RANK_MAJ_FULL=Comandante
WAW_RANK_LTCOL_FULL=Teniente coronel
WAW_RANK_COL_FULL=Coronel
WAW_RANK_BGEN_FULL=General de brigada
WAW_RANK_MAJGEN_FULL=General de división
WAW_RANK_LTGEN_FULL=Teniente general
WAW_RANK_GEN_FULL=General de ejército
WAW_RANK_COMM_FULL=Capitán general
WAW_RANK_1STLT_FULL2=Teniente I
WAW_RANK_1STLT_FULL3=Teniente II
WAW_RANK_2NDLT_FULL2=Alférez I
WAW_RANK_2NDLT_FULL3=Alférez II
WAW_RANK_BGEN_FULL2=General de brigada I
WAW_RANK_BGEN_FULL3=General de brigada II
WAW_RANK_CAPT_FULL2=Capitán I
WAW_RANK_CAPT_FULL3=Capitán II
WAW_RANK_COL_FULL2=Coronel I
WAW_RANK_COL_FULL3=Coronel II
WAW_RANK_CPL_FULL2=Cabo primero I
WAW_RANK_CPL_FULL3=Cabo primero II
WAW_RANK_GYSGT_FULL2=Suboficial I
WAW_RANK_GYSGT_FULL3=Suboficial II
WAW_RANK_LCPL_FULL2=Cabo primero I
WAW_RANK_LCPL_FULL3=Cabo primero II
WAW_RANK_LTCOL_FULL2=Teniente coronel I
WAW_RANK_LTCOL_FULL3=Teniente coronel II
WAW_RANK_MAJ_FULL2=Comandante I
WAW_RANK_MAJ_FULL3=Comandante II
WAW_RANK_MAJGEN_FULL2=General de división I
WAW_RANK_MAJGEN_FULL3=General de división II
WAW_RANK_MGYSGT_FULL2=Suboficial mayor I
WAW_RANK_MGYSGT_FULL3=Suboficial mayor II
WAW_RANK_MSGT_FULL2=Subteniente I
WAW_RANK_MSGT_FULL3=Subteniente II
WAW_RANK_PFC_FULL2=Soldado de primera I
WAW_RANK_PFC_FULL3=Soldado de primera II
WAW_RANK_PVT_FULL2=Soldado I
WAW_RANK_PVT_FULL3=Soldado II
WAW_RANK_REC_FULL2=Recluta I
WAW_RANK_REC_FULL3=Recluta II
WAW_RANK_SGT_FULL2=Cabo mayor I
WAW_RANK_SGT_FULL3=Cabo mayor II
WAW_RANK_SSGT_FULL2=Sargento primero I
WAW_RANK_SSGT_FULL3=Sargento primero II
WAW_RANK_LTGEN_FULL2=Teniente general I
WAW_RANK_LTGEN_FULL3=Teniente general II
WAW_RANK_GYSGT_FULL4=Suboficial III
WAW_RANK_LTGEN_FULL4=Teniente general III
WAW_RANK_MAJGEN_FULL4=General de división III
WAW_RANK_BGEN_FULL4=General de brigada III
WAW_RANK_COL_FULL4=Coronel III
WAW_RANK_LTCOL_FULL4=Teniente coronel III
WAW_RANK_MAJ_FULL4=Comandante III
WAW_RANK_CAPT_FULL4=Capitán III
WAW_RANK_1STLT_FULL4=Teniente III
WAW_RANK_2NDLT_FULL4=Alférez III
WAW_RANK_SSGT_FULL4=Sargento primero III
WAW_RANK_MSGT_FULL4=Subteniente III
WAW_RANK_SGTM_FULL2=Brigada I
WAW_RANK_SGTM_FULL3=Brigada II
WAW_RANK_SGTM_FULL4=Brigada III
