#---------- MW3 Ranks | Español | Spanish
# Translator: Original Game

# Notifications
MW3_RANK_PROMOTED=¡Has sido ascendido!
MW3_RANK_PROMOTED_WEAPON=¡Tu rango de arma ha aumentado!
MW3_RANK_PLAYER_WAS_PROMOTED=¡%s ha ascendido a %s!

# Ranks
MW3_RANK_REC_FULL=Recluta
MW3_RANK_PVT_FULL=Soldado
MW3_RANK_PFC_FULL=Soldado primero
MW3_RANK_LCPL_FULL=Cabo
MW3_RANK_CPL_FULL=Cabo primero
MW3_RANK_SGT_FULL=Cabo mayor
MW3_RANK_SSGT_FULL=Sargento
MW3_RANK_GYSGT_FULL=Sargento primero
MW3_RANK_MSGT_FULL=Brigada
MW3_RANK_MGYSGT_FULL=Suboficial mayor
MW3_RANK_2NDLT_FULL=Alférez
MW3_RANK_1STLT_FULL=Teniente
MW3_RANK_CAPT_FULL=Capitán
MW3_RANK_MAJ_FULL=Comandante
MW3_RANK_LTCOL_FULL=Teniente coronel
MW3_RANK_COL_FULL=Coronel
MW3_RANK_BGEN_FULL=General de brigada
MW3_RANK_MAJGEN_FULL=General de división
MW3_RANK_LTGEN_FULL=Teniente general
MW3_RANK_GEN_FULL=Disposiciones generales
MW3_RANK_COMM_FULL=Capitán general
MW3_RANK_1STLT_FULL2=Teniente I
MW3_RANK_1STLT_FULL3=Teniente II
MW3_RANK_2NDLT_FULL2=Alférez I
MW3_RANK_2NDLT_FULL3=Alférez II
MW3_RANK_BGEN_FULL2=General de brigada I
MW3_RANK_BGEN_FULL3=General de brigada II
MW3_RANK_CAPT_FULL2=Capitán I
MW3_RANK_CAPT_FULL3=Capitán II
MW3_RANK_COL_FULL2=Coronel I
MW3_RANK_COL_FULL3=Coronel II
MW3_RANK_COMM_FULL2=Capitán general I
MW3_RANK_COMM_FULL3=Capitán general II
MW3_RANK_CPL_FULL2=Cabo primero I
MW3_RANK_CPL_FULL3=Cabo primero II
MW3_RANK_GEN_FULL2=General de ejército I
MW3_RANK_GEN_FULL3=General de ejército II
MW3_RANK_GYSGT_FULL2=Sargento primero I
MW3_RANK_GYSGT_FULL3=Sargento primero II
MW3_RANK_LCPL_FULL2=Cabo I
MW3_RANK_LCPL_FULL3=Cabo II
MW3_RANK_LTCOL_FULL2=Teniente coronel I
MW3_RANK_LTCOL_FULL3=Teniente coronel II
MW3_RANK_MAJ_FULL2=Comandante I
MW3_RANK_MAJ_FULL3=Comandante II
MW3_RANK_MAJGEN_FULL2=General de división I
MW3_RANK_MAJGEN_FULL3=General de división II
MW3_RANK_MGYSGT_FULL2=Suboficial mayor I
MW3_RANK_MGYSGT_FULL3=Suboficial mayor II
MW3_RANK_MSGT_FULL2=Brigada I
MW3_RANK_MSGT_FULL3=Brigada II
MW3_RANK_PFC_FULL2=Soldado primero I
MW3_RANK_PFC_FULL3=Soldado primero II
MW3_RANK_PVT_FULL2=Soldado I
MW3_RANK_PVT_FULL3=Soldado II
MW3_RANK_REC_FULL2=Recluta I
MW3_RANK_REC_FULL3=Recluta II
MW3_RANK_SGT_FULL2=Cabo mayor I
MW3_RANK_SGT_FULL3=Cabo mayor II
MW3_RANK_SSGT_FULL2=Sargento I
MW3_RANK_SSGT_FULL3=Sargento II
MW3_RANK_LTGEN_FULL2=Teniente general I
MW3_RANK_LTGEN_FULL3=Teniente general II
MW3_RANK_SGTMAJ_FULL=Subteniente
MW3_RANK_SGTMAJ_FULL2=Subteniente I
MW3_RANK_SGTMAJ_FULL3=Subteniente II
MW3_RANK_SGTMAJ_FULL_N=Subteniente %s
MW3_RANK_COMM_FULL_N=Capitán general %s
MW3_RANK_SPC_FULL=Especialista
MW3_RANK_SPC_FULL2=Especialista I
MW3_RANK_SPC_FULL3=Especialista II
MW3_RANK_SPC_FULL_N=Especialista %s
MW3_RANK_SFC_FULL=Sargento de primera clase
MW3_RANK_SFC_FULL2=Sargento de primera clase I
MW3_RANK_SFC_FULL3=Sargento de primera clase II
MW3_RANK_SFC_FULL_N=Sargento de primera clase %s
MW3_RANK_1STSGT_FULL=Sargento de primera
MW3_RANK_1STSGT_FULL2=Sargento de primera I
MW3_RANK_1STSGT_FULL3=Sargento de primera II
MW3_RANK_1STSGT_FULL_N=Sargento de primera %s
MW3_RANK_CSM_FULL=Suboficial mayor
MW3_RANK_CSM_FULL2=Suboficial mayor I
MW3_RANK_CSM_FULL3=Suboficial mayor II
MW3_RANK_CSM_FULL_N=Suboficial mayor %s
MW3_RANK_CSM_FULL4=Suboficial mayor III
MW3_RANK_GEN_FULL4=General del ejército III
MW3_RANK_LTGEN_FULL4=Teniente general III
MW3_RANK_MAJGEN_FULL4=General de división III
MW3_RANK_BGEN_FULL4=General de brigada III
MW3_RANK_COL_FULL4=Coronel III
MW3_RANK_LTCOL_FULL4=Teniente coronel III
MW3_RANK_MAJ_FULL4=Comandante III
MW3_RANK_CAPT_FULL4=Capitán III
MW3_RANK_1STLT_FULL4=Teniente III
MW3_RANK_2NDLT_FULL4=Alférez III
MW3_RANK_SSGT_FULL4=Sargento III
MW3_RANK_SFC_FULL4=Sargento de primera clase III
MW3_RANK_MSGT_FULL4=Brigada III
MW3_RANK_1STSGT_FULL4=Sargento de primera III
MW3_RANK_SGTMAJ_FULL4=Subteniente III
