#---------- CoD: World at War HUD | Español | Spanish
# Translator: Original Game

# Factions
WAW_MPUI_RUSSIAN=Ejército Rojo
WAW_MPUI_JAPANESE=Ejército Imperial
WAW_MPUI_GERMAN=Wehrmacht
WAW_MPUI_MARINE=Marines

WAW_MPUI_RUSSIAN_SHORT=Ejército Rojo
WAW_MPUI_JAPANESE_SHORT=Ejército Imperial
WAW_MPUI_GERMAN_SHORT=Wehrmacht
WAW_MPUI_MARINE_SHORT=Marines

# Gamemodes
WAW_MPUI_TANK_WAR=Guerra
WAW_OBJECTIVES_TWAR_HINT=Captura y defiende banderas.