#---------- CoD HUD System Notifications | Español | Spanish
# Translator: Machine translated

CoDHUD.System.ResetTime=Temporizador de ronda restablecido a %s.
CoDHUD.System.ResetTime.Off=Temporizador de ronda eliminado.

CoDHUD.System.RestrictType=El juego fue cambiado a %s.
CoDHUD.System.RestrictType.NotNow=No se puede cambiar el juego ahora mismo.

CoDHUD.System.Faction.NotNow=No se pueden cambiar las facciones ahora mismo.
CoDHUD.System.Faction.Denied=No se pueden cambiar las facciones.

CoDHUD.System.ChallengeReset=Todos los desafíos fueron restablecidos.
CoDHUD.System.RankReset=El rango y las estadísticas del HUD '%s' fueron restablecidos.

CoDHUD.System.CVChanged=La variable del servidor '%s' fue cambiada a %s.

CoDHUD.System.ForceEndRound.NotNow=No se puede finalizar la ronda por la fuerza ahora mismo.
CoDHUD.System.ForceEndRound.NotStarting=No se puede finalizar por la fuerza una ronda que se está iniciando actualmente.