#---------- Black Ops II HUD | English
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEAL
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercenarios
BO2_MP_ISA_NAME=AAI
BO2_MP_CD_NAME=Milicia

BO2_MPUI_SEALS_SHORT=SEAL
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercenario
BO2_MPUI_ISA_SHORT=AAI
BO2_MPUI_CD_SHORT=Milicia

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCENARIOS
BO2_MPUI_ISA_SHORT_CAPS=AAI
BO2_MPUI_CD_SHORT_CAPS=MILICIA

# Splashes
BO2_MEDAL_FIRST_KILL=PRIMERA SANGRE
BO2_MEDAL_ASSISTED_SUICIDE=EUTANASIA
BO2_MEDAL_HEADSHOT=TIRO A LA CABEZA
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=RECUPERACIÓN
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=MÁS ALLÁ
BO2_MEDAL_LONGSHOT_KILL=TIRO LEJANO
BO2_MEDAL_REVENGE_KILL=VENGANZA
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=SUPERVIVIENTE
BO2_MEDAL_KILL_ENEMY_IN_AIR=TIRO AÉREO
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=UN TIRO BASTA
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=CUATRO BAJAS
BO2_MEDAL_KILLSTREAK_5=SANGUINARIO
BO2_MEDAL_KILLSTREAK_10=DESPIADADO
BO2_MEDAL_KILLSTREAK_15=INEXORABLE
BO2_MEDAL_KILLSTREAK_20=IMPLACABLE
BO2_MEDAL_KILLSTREAK_25=BRUTAL
BO2_MEDAL_KILLSTREAK_30=NUCLEAR
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=IMPARABLE
BO2_MEDAL_MULTIKILL_2=DOBLE BAJA
BO2_MEDAL_MULTIKILL_3=TRIPLE BAJA
BO2_MEDAL_MULTIKILL_4=BAJA FURIOSA
BO2_MEDAL_MULTIKILL_5=TURBOBAJA
BO2_MEDAL_MULTIKILL_6=SUPERBAJA
BO2_MEDAL_MULTIKILL_7=MEGABAJA
BO2_MEDAL_MULTIKILL_8=ULTRABAJA
BO2_MEDAL_MULTIKILL_MORE_THAN_8=CADENA DE BAJAS
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=VENGADOR
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=SALVADOR

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s PUNTOS PARA GANAR
