#---------- Black Ops Ranks | Español | Spanish
# Translator: Original Game

# Notifications
BO1_RANK_PROMOTED_TO=Ascendido: ¡nivel %s!
BO1_RANK_PLAYER_WAS_PROMOTED=¡%s ha ascendido a %s!
  
# Ranks
BO1_RANK_PRVT_FULL=Soldado
BO1_RANK_PRVT_FULL2=Soldado I
BO1_RANK_PRVT_FULL3=Soldado II
BO1_RANK_PRVT_FULL_N=Soldado %s
BO1_RANK_PFC_FULL=Soldado primero
BO1_RANK_PFC_FULL2=Soldado primero I
BO1_RANK_PFC_FULL3=Soldado primero II
BO1_RANK_PFC_FULL_N=Soldado primero %s
BO1_RANK_SPC_FULL=Especialista
BO1_RANK_SPC_FULL2=Especialista I
BO1_RANK_SPC_FULL3=Especialista II
BO1_RANK_SPC_FULL_N=Especialista %s
BO1_RANK_CPL_FULL=Cabo primero
BO1_RANK_CPL_FULL2=Cabo primero I
BO1_RANK_CPL_FULL3=Cabo primero II
BO1_RANK_CPL_FULL_N=Cabo primero %s
BO1_RANK_SGT_FULL=Cabo mayor
BO1_RANK_SGT_FULL2=Cabo mayor I
BO1_RANK_SGT_FULL3=Cabo mayor II
BO1_RANK_SGT_FULL_N=Cabo mayor %s
BO1_RANK_SSGT_FULL=Sargento
BO1_RANK_SSGT_FULL2=Sargento I
BO1_RANK_SSGT_FULL3=Sargento II
BO1_RANK_SSGT_FULL_N=Sargento %s
BO1_RANK_SFC_FULL=Sargento primero
BO1_RANK_SFC_FULL2=Sargento primero I
BO1_RANK_SFC_FULL3=Sargento primero II
BO1_RANK_SFC_FULL_N=Sargento primero %s
BO1_RANK_SGTM_FULL=Subteniente
BO1_RANK_SGTM_FULL2=Subteniente I
BO1_RANK_SGTM_FULL3=Subteniente II
BO1_RANK_SGTM_FULL_N=Subteniente %s
BO1_RANK_LT_FULL=Teniente
BO1_RANK_LT_FULL2=Teniente I
BO1_RANK_LT_FULL3=Teniente II
BO1_RANK_LT_FULL_N=Teniente %s
BO1_RANK_CPT_FULL=Capitán
BO1_RANK_CPT_FULL2=Capitán I
BO1_RANK_CPT_FULL3=Capitán II
BO1_RANK_CPT_FULL_N=Capitán %s
BO1_RANK_MAJ_FULL=Comandante
BO1_RANK_MAJ_FULL2=Comandante I
BO1_RANK_MAJ_FULL3=Comandante II
BO1_RANK_MAJ_FULL_N=Comandante %s
BO1_RANK_LTCOL_FULL=Teniente coronel
BO1_RANK_LTCOL_FULL2=Teniente coronel I
BO1_RANK_LTCOL_FULL3=Teniente coronel II
BO1_RANK_LTCOL_FULL_N=Teniente coronel %s
BO1_RANK_COL_FULL=Coronel
BO1_RANK_COL_FULL2=Coronel I
BO1_RANK_COL_FULL3=Coronel II
BO1_RANK_COL_FULL_N=Coronel %s
BO1_RANK_BRIGGEN_FULL=General de brigada
BO1_RANK_BRIGGEN_FULL2=General de brigada I
BO1_RANK_BRIGGEN_FULL3=General de brigada II
BO1_RANK_BRIGGEN_FULL_N=General de brigada %s
BO1_RANK_MAJGEN_FULL=General de división
BO1_RANK_MAJGEN_FULL2=General de división I
BO1_RANK_MAJGEN_FULL3=General de división II
BO1_RANK_MAJGEN_FULL_N=General de división %s
BO1_RANK_LTGEN_FULL=Teniente general
BO1_RANK_LTGEN_FULL2=Teniente general I
BO1_RANK_LTGEN_FULL3=Teniente general II
BO1_RANK_LTGEN_FULL_N=Teniente general %s
BO1_RANK_GEN_FULL=General de ejército
BO1_RANK_COM_FULL=Capitán general
