#---------- Black Ops II HUD | Español | Spanish
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEAL
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercenarios
BO2_MP_ISA_NAME=AAI
BO2_MP_CD_NAME=Milicia

BO2_MPUI_SEALS_SHORT=SEAL
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercenario
BO2_MPUI_ISA_SHORT=AAI
BO2_MPUI_CD_SHORT=Milicia

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCENARIOS
BO2_MPUI_ISA_SHORT_CAPS=AAI
BO2_MPUI_CD_SHORT_CAPS=MILICIA

# Splashes
BO2_MEDAL_FIRST_KILL=Primera sangre
BO2_MEDAL_ASSISTED_SUICIDE=Eutanasia
BO2_MEDAL_HEADSHOT=Tiro a la cabeza
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=Recuperación
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=Más allá
BO2_MEDAL_LONGSHOT_KILL=Tiro lejano
BO2_MEDAL_REVENGE_KILL=Venganza
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=Superviviente
BO2_MEDAL_KILL_ENEMY_IN_AIR=Tiro aéreo
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=Un tiro basta
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=Cuatro bajas
BO2_MEDAL_KILLSTREAK_5=Sanguinario
BO2_MEDAL_KILLSTREAK_10=Despiadado
BO2_MEDAL_KILLSTREAK_15=Inexorable
BO2_MEDAL_KILLSTREAK_20=Implacable
BO2_MEDAL_KILLSTREAK_25=Brutal
BO2_MEDAL_KILLSTREAK_30=Nuclear
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=Imparable
BO2_MEDAL_MULTIKILL_2=Doble baja
BO2_MEDAL_MULTIKILL_3=Triple baja
BO2_MEDAL_MULTIKILL_4=Baja furiosa
BO2_MEDAL_MULTIKILL_5=Turbobaja
BO2_MEDAL_MULTIKILL_6=Superbaja
BO2_MEDAL_MULTIKILL_7=Megabaja
BO2_MEDAL_MULTIKILL_8=Ultrabaja
BO2_MEDAL_MULTIKILL_MORE_THAN_8=Cadena de bajas
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=Vengador
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=Salvador

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s PUNTOS PARA GANAR
