#---------- MW2 HUD | Español | Spanish
# Translator: Original Game

# Notifications
MW2_RANK_PROMOTED=¡Has sido ascendido!
MW2_RANK_PLAYER_WAS_PROMOTED=¡%s ha ascendido a %s!

# Ranks
MW2_RANK_REC_FULL=Recluta
MW2_RANK_PVT_FULL=Soldado
MW2_RANK_PFC_FULL=Cabo
MW2_RANK_LCPL_FULL=Soldado de primera
MW2_RANK_CPL_FULL=Cabo primero
MW2_RANK_SGT_FULL=Cabo mayor
MW2_RANK_SSGT_FULL=Sargento
MW2_RANK_GYSGT_FULL=Brigada de artillería
MW2_RANK_MSGT_FULL=Brigada
MW2_RANK_MGYSGT_FULL=Brig. artillería mayor
MW2_RANK_2NDLT_FULL=Alférez
MW2_RANK_1STLT_FULL=Teniente
MW2_RANK_CAPT_FULL=Capitán
MW2_RANK_MAJ_FULL=Comandante
MW2_RANK_LTCOL_FULL=Teniente coronel
MW2_RANK_COL_FULL=Coronel
MW2_RANK_BGEN_FULL=General de brigada
MW2_RANK_MAJGEN_FULL=General de división
MW2_RANK_LTGEN_FULL=Teniente general
MW2_RANK_GEN_FULL=General del ejército
MW2_RANK_COMM_FULL=Capitán general
MW2_RANK_1STLT_FULL2=Teniente I
MW2_RANK_1STLT_FULL3=Teniente II
MW2_RANK_2NDLT_FULL2=Alférez I
MW2_RANK_2NDLT_FULL3=Alférez II
MW2_RANK_BGEN_FULL2=General de brigada I
MW2_RANK_BGEN_FULL3=General de brigada II
MW2_RANK_CAPT_FULL2=Capitán I
MW2_RANK_CAPT_FULL3=Capitán II
MW2_RANK_COL_FULL2=Coronel I
MW2_RANK_COL_FULL3=Coronel II
MW2_RANK_COMM_FULL2=Capitán general I
MW2_RANK_COMM_FULL3=Capitán general II
MW2_RANK_CPL_FULL2=Cabo primero I
MW2_RANK_CPL_FULL3=Cabo primero II
MW2_RANK_GEN_FULL2=General del ejército I
MW2_RANK_GEN_FULL3=General del ejército II
MW2_RANK_GYSGT_FULL2=Brigada de artillería I
MW2_RANK_GYSGT_FULL3=Brigada de artillería II
MW2_RANK_LCPL_FULL2=Soldado de primera I
MW2_RANK_LCPL_FULL3=Soldado de primera II
MW2_RANK_LTCOL_FULL2=Teniente coronel I
MW2_RANK_LTCOL_FULL3=Teniente coronel II
MW2_RANK_MAJ_FULL2=Comandante I
MW2_RANK_MAJ_FULL3=Comandante II
MW2_RANK_MAJGEN_FULL2=General de división I
MW2_RANK_MAJGEN_FULL3=General de división II
MW2_RANK_MGYSGT_FULL2=Brig. artillería mayor I
MW2_RANK_MGYSGT_FULL3=Brig. artillería mayor II
MW2_RANK_MSGT_FULL2=Brigada I
MW2_RANK_MSGT_FULL3=Brigada II
MW2_RANK_PFC_FULL2=Cabo I
MW2_RANK_PFC_FULL3=Cabo II
MW2_RANK_PVT_FULL2=Soldado I
MW2_RANK_PVT_FULL3=Soldado II
MW2_RANK_REC_FULL2=Recluta I
MW2_RANK_REC_FULL3=Recluta II
MW2_RANK_SGT_FULL2=Cabo mayor I
MW2_RANK_SGT_FULL3=Cabo mayor II
MW2_RANK_SSGT_FULL2=Sargento I
MW2_RANK_SSGT_FULL3=Sargento II
MW2_RANK_LTGEN_FULL2=Teniente general I
MW2_RANK_LTGEN_FULL3=Teniente general II
MW2_RANK_SGTMAJ_FULL=Subteniente
MW2_RANK_SGTMAJ_FULL2=Subteniente I
MW2_RANK_SGTMAJ_FULL3=Subteniente II
MW2_RANK_SPC_FULL=Especialista
MW2_RANK_SPC_FULL2=Especialista I
MW2_RANK_SPC_FULL3=Especialista II
MW2_RANK_SFC_FULL=Sargento primero
MW2_RANK_SFC_FULL2=Sargento primero I
MW2_RANK_SFC_FULL3=Sargento primero II
MW2_RANK_1STSGT_FULL=Brigada 1a clase
MW2_RANK_1STSGT_FULL2=Brigada 1a clase I
MW2_RANK_1STSGT_FULL3=Brigada 1a clase II
MW2_RANK_CSM_FULL=Suboficial mayor
MW2_RANK_CSM_FULL2=Suboficial mayor I
MW2_RANK_CSM_FULL3=Suboficial mayor II
MW2_RANK_CSM_FULL4=Suboficial mayor III
MW2_RANK_GEN_FULL4=General del ejército III
MW2_RANK_LTGEN_FULL4=Teniente general III
MW2_RANK_MAJGEN_FULL4=General de división III
MW2_RANK_BGEN_FULL4=General de brigada III
MW2_RANK_COL_FULL4=Coronel III
MW2_RANK_LTCOL_FULL4=Teniente coronel III
MW2_RANK_MAJ_FULL4=Comandante III
MW2_RANK_CAPT_FULL4=Capitán III
MW2_RANK_1STLT_FULL4=Teniente III
MW2_RANK_2NDLT_FULL4=Alférez III
