#---------- Black Ops HUD | Español | Spanish
# Translator: Original Game

# Factions
BO1_MP_TROPAS_NAME=TROPAS
BO1_MP_NVA_NAME=NVA
BO1_MP_RUSSIAN_NAME=SPETSNAZ
BO1_MP_SPECOPS_NAME=BLACK OPS
BO1_MP_MARINE_NAME=SOG
BO1_MP_REBELS_NAME=OP. 40

BO1_MPUI_TROPAS_SHORT=Tropas
BO1_MPUI_NVA_SHORT=NVA
BO1_MPUI_RUSSIAN_SHORT=Spetsnaz
BO1_MPUI_SPECOPS_SHORT=Black Ops
BO1_MPUI_MARINE_SHORT=SOG
BO1_MPUI_REBELS_SHORT=Op. 40

BO1_MPUI_TROPAS_SHORT_CAPS=TROPAS
BO1_MPUI_NVA_SHORT_CAPS=NVA
BO1_MPUI_RUSSIAN_SHORT_CAPS=SPETSNAZ
BO1_MPUI_SPECOPS_SHORT_CAPS=BLACK OPS
BO1_MPUI_MARINE_SHORT_CAPS=SOG
BO1_MPUI_REBELS_SHORT_CAPS=OP. 40

# Splashes
BO1_MEDAL_BUZZ_KILL=Aguafiestas
BO1_MEDAL_BUZZ_KILL_DESC=Has matado un enemigo que iba a tener racha de bajas.
BO1_MEDAL_LONG_SHOT=Tiro lejano
BO1_MEDAL_LONG_SHOT_DESC=Has matado a un enemigo a distancia.
BO1_MEDAL_HEAD_SHOT=Tiro cabeza
BO1_MEDAL_HEAD_SHOT_DESC=¡Bum! A la cabeza.
BO1_MEDAL_STUCK_TO_PLAYER=Pillado
BO1_MEDAL_STUCK_TO_PLAYER_DESC=Has puesto un explosivo a un enemigo.
BO1_MEDAL_BULLS_EYE=Cazacabelleras
BO1_MEDAL_BULLS_EYE_DESC=Has matado a un enemigo con un tomahawk.
BO1_MEDAL_EXECUTION=Ejecución
BO1_MEDAL_EXECUTION_DESC=Has matado a un enemigo caído de un tiro a la cabeza.
BO1_MEDAL_COMEBACK=Recuperación
BO1_MEDAL_COMEBACK_DESC=Te has recuperado de una racha de muertes.
BO1_MEDAL_AVENGER=Vengador
BO1_MEDAL_AVENGER_DESC=Has matado a un enemigo que hace poco mató a un compañero.
BO1_MEDAL_AFTERLIFE=Más allá
BO1_MEDAL_AFTERLIFE_DESC=Has matado a un enemigo estando muerto.
BO1_MEDAL_DOUBLE_KILL=Doble baja
BO1_MEDAL_DOUBLE_KILL_DESC=Has matado a 2 personas en poco tiempo.
BO1_MEDAL_TRIPLE_KILL=Triple baja
BO1_MEDAL_TRIPLE_KILL_DESC=Has matado a 3 personas en poco tiempo.
BO1_MEDAL_MULTI_KILL=Baja múltiple
BO1_MEDAL_MULTI_KILL_DESC=Has matado a más de 3 en poco tiempo.
BO1_MEDAL_FIRST_BLOOD=Primera sangre
BO1_MEDAL_FIRST_BLOOD_DESC=Has conseguido la primera baja.
BO1_MEDAL_BACK_STABBER=Apuñalador
BO1_MEDAL_BACK_STABBER_DESC=Has apuñalado a un jugador por la espalda.
BO1_MEDAL_HIJACKER=Secuestrador
BO1_MEDAL_HIJACKER_DESC=Has robado una caja enemiga.
BO1_MEDAL_SHARE_PACKAGE=Paquete común
BO1_MEDAL_SHARE_PACKAGE_DESC=Un compañero salvó tu caja.
BO1_MEDAL_ONE_SHOT_KILL=Un tiro basta
BO1_MEDAL_ONE_SHOT_KILL_DESC=Has matado a un enemigo de un tiro.
BO1_MEDAL_PAYBACK=Venganza
BO1_MEDAL_PAYBACK_DESC=Has matado al enemigo que te mató.
BO1_MEDAL_RESCUER=Rescatador
BO1_MEDAL_RESCUER_DESC=Has salvado a un compañero herido.
BO1_MEDAL_ASSISTED_SUICIDE=Eutanasia
BO1_MEDAL_ASSISTED_SUICIDE_DESC=Has herido a un enemigo que se suicidó.
BO1_MEDAL_HEROIC=Más allá
BO1_MEDAL_HEROIC_DESC=Has tomado un punto estando en Segunda oportunidad.
BO1_MEDAL_ASSISTS=Asistencia
BO1_MEDAL_ASSISTS_DESC=Has ayudado en una baja.
BO1_MEDAL_DESTROYER=Chatarrero
BO1_MEDAL_DESTROYER_DESC=Has destruido un vehículo enemigo.
BO1_MEDAL_STREAKER=En racha
BO1_MEDAL_STREAKER_DESC=Has solicitado una racha de bajas.
BO1_MEDAL_HERO=Héroe
BO1_MEDAL_HERO_DESC=Has desactivado la bomba.
BO1_MEDAL_ANTI_BOMBER=Antibombas
BO1_MEDAL_ANTI_BOMBER_DESC=Has matado a un enemigo que estaba desactivando una bomba.
BO1_MEDAL_OFFENSE=Ofensiva
BO1_MEDAL_OFFENSE_DESC=Has matado a un enemigo cerca del objetivo.
BO1_MEDAL_DEFENSE=Defensa
BO1_MEDAL_DEFENSE_DESC=Has matado a un enemigo cerca del punto de defensa.
BO1_MEDAL_POSITION_SECURE=Pos. asegurada
BO1_MEDAL_POSITION_SECURE_DESC=Has tomado un objetivo.
BO1_MEDAL_FLAG_RUNNER=Portador
BO1_MEDAL_FLAG_RUNNER_DESC=Has cogido la bandera enemiga.
BO1_MEDAL_FLAG_CAPTURE=Toma bandera
BO1_MEDAL_FLAG_CAPTURE_DESC=Has conseguido la bandera enemiga.
BO1_MEDAL_SABOTEUR=Saboteador
BO1_MEDAL_SABOTEUR_DESC=Has colocado la bomba.
BO1_MEDAL_BOMBER=Terrorista
BO1_MEDAL_BOMBER_DESC=Has detonado la bomba.
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=Has derribado un avión de contraespionaje.
BO1_MEDAL_DESTROYER_UAV_DESC=Has derribado un avión espía.
BO1_MEDAL_DESTROYER_TURRET_DESC=Has acabado con una torreta.
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=Has derribado un helicóptero.
BO1_MEDAL_FLAG_RETURN=Devol. bandera
BO1_MEDAL_FLAG_RETURN_DESC=Has devuelto la bandera.
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=Baja torreta
BO1_MEDAL_BALLISTIC_KNIFE_KILL=Ensartado
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=Has matado a un enemigo con el cuchillo balístico.
BO1_MEDAL_BANK_SHOT=De rebote
BO1_MEDAL_BANK_SHOT_DESC=Has matado a un enemigo con un tomahawk rebotado.
BO1_MEDAL_REVIVE=Sanitario
BO1_MEDAL_REVIVE_DESC=Has reanimado a un compañero caído.
BO1_MEDAL_DESTROYER_M220_TOW=Interceptado
BO1_MEDAL_DESTROYER_M220_TOW_DESC=Has destruido un Valkyrie.
BO1_MEDAL_DESTROYER_RCBOMB=Ira al volante
BO1_MEDAL_DESTROYER_RCBOMB_DESC=Has destruido un RC-XD.
BO1_MEDAL_AIRCRAFT_ASSIST=Chatarrero adjunto
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=Has ayudado a derribar una aeronave enemiga.

# Round Starter
BO1_MP_MATCH_STARTING_IN=LA PARTIDA EMPIEZA EN

# Other
BO1_MENU_WINNING_CAPS=GANANDO
BO1_MENU_LOSING_CAPS=PERDIENDO
BO1_MENU_TIED_CAPS=EMPATE

BO1_MENU_WINNING=Ganando
BO1_MENU_TIED=Empate
BO1_MENU_LOSING=Perdiendo

# Scoreboard
BO1_CGAME_SB_KILLS=Bajas
BO1_CGAME_SB_ASSISTS=Asistenc.
BO1_CGAME_SB_KDRATIO=Prop.
BO1_CGAME_SB_SCORE=Punt.
BO1_CGAME_SB_DEATHS=Muertes
BO1_CGAME_SB_PING=Ping

# Gamemodes
BO1_OBJECTIVES_SD_ATTACKER_HINT=DESTRUYE EL OBJETIVO A O EL B
BO1_OBJECTIVES_SD_DEFENDER_HINT=PROTEGE LOS OBJETIVOS A Y B
BO1_OBJECTIVES_SAB_HINT=DESTRUYE EL BLANCO ENEMIGO
BO1_OBJECTIVES_DOM_HINT=TOMA Y DEFIENDE BANDERAS
BO1_OBJECTIVES_DM_HINT=ELIMINA A LOS DEMÁS JUGADORES
BO1_OBJECTIVES_TDM_HINT=ELIMINA A LOS JUGADORES ENEMIGOS
BO1_OBJECTIVES_CTF_HINT=TOMA LA BANDERA
BO1_OBJECTIVES_DEM_ATTACKER_HINT=DESTRUYE LOS OBJETIVOS A Y B
