#---------- CoD HUD Settings | Español | Spanish
# Translator: Machine translated

# ------------------[ GENERAL ]------------------
CoDHUD.Title=CoD HUD

CoDHUD.Client=Cliente
CoDHUD.Server=Servidor
CoDHUD.General=General

CoDHUD.Close=Cerrar

CoDHUD.Default=Predeterminado: %s
CoDHUD.Current=Actual: %s

# ------------------[ MENU GLYPHS ]------------------
CoDHUD.Glyph.Toggle=[+attack] Alternar
CoDHUD.Glyph.Open=[+attack] Abrir
CoDHUD.Glyph.OpenMenu=[+attack] Abrir menú
CoDHUD.Glyph.Select=[+attack] Seleccionar
CoDHUD.Glyph.Confirm=[+attack] Confirmar
CoDHUD.Glyph.Return=[+attack] Volver
CoDHUD.Glyph.Close=[+attack] Cerrar
CoDHUD.Glyph.Tab=[+attack] Abrir pestaña
CoDHUD.Glyph.Reset=[+attack2] Restablecer

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.RoundStart=Controles de ronda

CoDHUD.RoundStart.Gamemode=Modo de juego
CoDHUD.RoundStart.Info=Elige el modo de juego.

CoDHUD.RoundStart.Start=Iniciar ronda
CoDHUD.RoundStart.Start.desc=Una vez seleccionado el modo de juego y configuradas las opciones a tu gusto, puedes iniciar el proceso de comienzo de ronda.

CoDHUD.RoundStart.Notice=¿Seguro que quieres iniciar una nueva ronda?\nTodas las puntuaciones se reiniciarán y todos los jugadores reaparecerán.
CoDHUD.RoundStart.Yes=Iniciar ronda

CoDHUD.RoundStart.Timer=Temporizador de inicio de ronda
CoDHUD.RoundStart.Timer.desc=Cuántos segundos de intermedio debe haber antes de que comience la ronda.

CoDHUD.RoundStart.Autobalance=Aleatorizar facciones al comenzar la ronda
CoDHUD.RoundStart.Autobalance.desc=Si está activado, todos los jugadores serán colocados aleatoriamente en una facción válida cuando comience la ronda.

CoDHUD.Scorelimit=Límite de puntuación
CoDHUD.Scorelimit.desc=Establece el límite máximo de puntuación mostrado en el contador.\n\nMedido en bajas.

CoDHUD.Timelimit=Límite de tiempo
CoDHUD.Timelimit.desc=Establece el límite de tiempo antes de que la ronda termine automáticamente.\n\nMedido en minutos.\n\nEstablece 0 para ilimitado.

CoDHUD.Autobalance.Amount=Límite de equipos para autoequilibrio
CoDHUD.Autobalance.Amount.desc=Establece la cantidad máxima de facciones a las que los jugadores pueden ser autoequilibrados.

CoDHUD.Autobalance.Amount.disable=Desactivado
CoDHUD.Autobalance.Amount.2=2 Equipos
CoDHUD.Autobalance.Amount.3=3 Equipos
CoDHUD.Autobalance.Amount.4=4 Equipos

CoDHUD.RoundStart.Auto=Iniciar ronda automáticamente al arrancar el servidor
CoDHUD.RoundStart.Auto.desc=Si está activado, una nueva ronda comenzará inmediatamente cuando el primer jugador se una al servidor.

CoDHUD.Admin.ResetTime=Restablecer temporizador de ronda
CoDHUD.Admin.ResetTime.desc=Restablece el temporizador actual de la ronda desde su valor actual al valor configurado en el límite de tiempo.

CoDHUD.ForceEndRound=Forzar finalización de la ronda
CoDHUD.ForceEndRound.desc=Haz clic aquí si necesitas o quieres terminar la ronda antes de alcanzar el límite de puntuación o tiempo.

CoDHUD.ForceEndRound.Notice=¿Seguro que quieres terminar la ronda a la fuerza?

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen=Activar \"Fin de partida\"
CoDHUD.Admin.EndScreen.desc=Activa un sistema de \"fin de partida\" cuando se alcance el límite de puntuación.

CoDHUD.Admin.EndScreen.StartNext=Iniciar siguiente ronda después del fin de partida
CoDHUD.Admin.EndScreen.StartNext.desc=Si está activado, una vez finalizada la duración del fin de partida, comenzará una nueva ronda.\n\nSi está desactivado, todos los jugadores reaparecerán normalmente.

CoDHUD.Admin.FriendlyFire=Permitir fuego amigo
CoDHUD.Admin.FriendlyFire.desc=Si está activado, los jugadores de la misma facción podrán dañarse entre sí.\n\nSolo se aplica en Duelo por equipos.

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=Restringir facciones y tipo de HUD
CoDHUD.Admin.RestrictType.Choose=Elegir juego
CoDHUD.Admin.RestrictType.desc=Elige a qué título de CoD restringir a los usuarios. Esto afecta al HUD y a las facciones disponibles.

CoDHUD.Admin.RestrictType.Warning=¡Advertencia!\nCambiar de juego tendrá las siguientes consecuencias:\n- Las facciones de todos los jugadores serán seleccionadas aleatoriamente.\n- Todas las puntuaciones de los jugadores se reiniciarán a 0.\n- Todos los jugadores morirán y reaparecerán.\n\n¿Seguro que quieres cambiar de juego?

CoDHUD.Type.cod4=Modern Warfare 1
CoDHUD.Type.waw=World at War
CoDHUD.Type.mw2=Modern Warfare 2
CoDHUD.Type.bo1=Black Ops
CoDHUD.Type.mw3=Modern Warfare 3
CoDHUD.Type.bo2=Black Ops II
CoDHUD.Type.ghosts=Ghosts
CoDHUD.Type.aw=Advanced Warfare
CoDHUD.Type.bo3=Black Ops III
CoDHUD.Type.iw=Infinite Warfare
CoDHUD.Type.ww2=WWII

CoDHUD.Admin.RestrictFactionChance=Restringir cambio de facciones
CoDHUD.Admin.RestrictFactionChance.desc=Elige cuándo los jugadores pueden cambiar de facción.

CoDHUD.Admin.RestrictFactionChance.disable=No puede cambiar
CoDHUD.Admin.RestrictFactionChance.freely=Puede cambiar libremente
CoDHUD.Admin.RestrictFactionChance.pool=Solo desde el grupo activo

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=Selección de facción
CoDHUD.Faction.Select.desc=Elige qué facción representar.\nAfecta a tu estado de amigo o enemigo y cambia el narrador y el tema para coincidir con la facción.

CoDHUD.Faction.ChangeWarning=¡Advertencia!\nCambiar de equipo tendrá las siguientes consecuencias:\n- Tu puntuación se reiniciará a 0.\n- Morirás y reaparecerás.\n\n¿Seguro que quieres cambiar de facción?

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=Acceso rápido

CoDHUD.Quick.DisableHUD=Desactivar rápidamente todas las opciones del HUD
CoDHUD.Quick.DisableHUD.desc=Desactiva todas las opciones del HUD de CoD.

# ---------[ HUD-RELATED ]---------
CoDHUD.HUD=Ajustes del HUD

# Multiple
CoDHUD.HUD.Outline=Texto con contorno
CoDHUD.HUD.Outline.desc=Activa texto con contorno en algunos elementos para hacerlos más fáciles de leer en áreas muy brillantes.

CoDHUD.HUD.Sound=Reproducir SFX
CoDHUD.HUD.Sound.desc=Reproduce efectos de sonido asociados si el tipo de HUD los soporta.

CoDHUD.HUD.Time.Total=Tiempo activo
CoDHUD.HUD.Time.Total.desc=Cuánto tiempo permanece visible la variable después de aparecer completamente antes de desvanecerse.

CoDHUD.HUD.Time.Fadein=Tiempo de aparición
CoDHUD.HUD.Time.Fadein.desc=Cuánto tarda esta variable en aparecer.

CoDHUD.HUD.Time.Fadeout=Tiempo de desvanecimiento
CoDHUD.HUD.Time.Fadeout.desc=Cuánto tarda esta variable en desaparecer.

# Scale
CoDHUD.HUD.Scale=Escala de UI

CoDHUD.HUD.Scale.Enable=Multiplicador de escala de UI
CoDHUD.HUD.Scale.Enable.desc=Ajusta la escala de los elementos de UI utilizados por el HUD de CoD.\n\nÚtil para resoluciones bajas o ultrapanorámicas.\n\n<color=255,255,100>Nota</color>: Recargará el menú al aplicarse.\n\n<color=255,100,100>ADVERTENCIA</color>: Algunos elementos podrían quedar gravemente desalineados si el valor se establece demasiado alto o demasiado bajo innecesariamente.

# Scoreboard
CoDHUD.HUD.Scoreboard=Marcador

CoDHUD.HUD.Scoreboard.Enable=Activar marcador
CoDHUD.HUD.Scoreboard.Enable.desc=Activa el marcador. Muestra las facciones ocupadas actualmente por todos los jugadores.

# Score Counter
CoDHUD.HUD.Scorecounter=Contador de puntuación

CoDHUD.HUD.Scorecounter.Enable=Activar contador de puntuación
CoDHUD.HUD.Scorecounter.Enable.desc=Activa un temporizador del servidor, el icono de facción y los contadores de puntuación.\n\nAlgunos tipos de HUD no mostrarán el icono de facción.

# Medals
CoDHUD.HUD.Medals=Medallas

CoDHUD.HUD.Medals.Enable=Activar medallas
CoDHUD.HUD.Medals.Enable.desc=Activa las medallas, obtenidas al realizar ciertas acciones como bajas rápidas o disparos a la cabeza.\n\nTen en cuenta que algunos tipos de HUD solo tienen texto, mientras que otros tienen texto e iconos.

CoDHUD.HUD.Medals.Speedup=Más rápido si la cola es larga
CoDHUD.HUD.Medals.Speedup.desc=Acelera la cola de medallas si hay muchas acumuladas al mismo tiempo.\n\nDependiendo del tipo de HUD, también desactiva los SFX asociados si hay más de 3 medallas en cola.

# Kill Feed
CoDHUD.HUD.Killfeed=Registro de bajas

CoDHUD.HUD.Killfeed.Enable=Activar registro de bajas
CoDHUD.HUD.Killfeed.Enable.desc=Activa el registro de bajas.

# Minimap
CoDHUD.HUD.Minimap=Minimapa

CoDHUD.HUD.Minimap.Enable=Activar minimapa
CoDHUD.HUD.Minimap.Enable.desc=Activa el minimapa.

# Hitmarker
CoDHUD.HUD.Hitmarker=Marcador de impacto

CoDHUD.HUD.Hitmarker.Enable=Activar marcador de impacto
CoDHUD.HUD.Hitmarker.Enable.desc=Activa el marcador de impacto y su sonido asociado.

# Weapon Info
CoDHUD.HUD.WeaponInfo=Información de arma

CoDHUD.HUD.WeaponInfo.Enable=Activar información de arma
CoDHUD.HUD.WeaponInfo.Enable.desc=Activa la pestaña de información del arma, mostrando el nombre del arma y el contador de munición.\n\nAlgunos tipos de HUD también incorporan aquí la brújula.

CoDHUD.HUD.WeaponPrompts.Enable=Activar avisos de armas
CoDHUD.HUD.WeaponPrompts.Enable.desc=Activa avisos de armas, como notificaciones de poca munición.

# XP Counter
CoDHUD.HUD.XP=Aviso de XP

CoDHUD.HUD.XP.Enable=Activar aviso de XP
CoDHUD.HUD.XP.Enable.desc=Activa los avisos de XP.

# Target ID / IFF
CoDHUD.HUD.IFF=Identificar amigo o enemigo

CoDHUD.HUD.IFF.Enable=Activar IFF
CoDHUD.HUD.IFF.Enable.desc=Activa un sistema de \"Identificar amigo o enemigo\", mostrando el nombre del objetivo sobre su cabeza al apuntar cerca de él.

# Death Icon
CoDHUD.HUD.DeathIcon=Icono de muerte

CoDHUD.HUD.DeathIcon.Enable=Activar icono de muerte
CoDHUD.HUD.DeathIcon.Enable.desc=Activa el icono de muerte, mostrado donde muere cualquier jugador de la misma facción.

# Chat
CoDHUD.HUD.Chat=Chat

CoDHUD.HUD.Chat.Enable=Activar chat
CoDHUD.HUD.Chat.Enable.desc=Activa el chat.

# Headers
CoDHUD.HUD.Headers=Encabezados

CoDHUD.HUD.Headers.Enable=Activar avisos de encabezado
CoDHUD.HUD.Headers.Enable.desc=Activa avisos de encabezado, como al completar desafíos o subir de nivel.

# Subtitles
CoDHUD.HUD.Subtitles=Subtítulos

CoDHUD.HUD.Subtitles.Enable=Activar subtítulos
CoDHUD.HUD.Subtitles.Enable.desc=Activa los subtítulos cuando se reproduce una línea de voz del narrador.\n\nOptimizado solo para inglés. El soporte para otros idiomas puede variar.

CoDHUD.HUD.Subtitles.Callsign=Activar indicativo
CoDHUD.HUD.Subtitles.Callsign.desc=Activa el indicativo del narrador que se reproduce.

CoDHUD.HUD.Subtitles.NameAlign=Alineación del indicativo
CoDHUD.HUD.Subtitles.NameAlign.desc=Elige dónde debe ubicarse el indicativo del narrador.

CoDHUD.HUD.Subtitles.NameAlign.Left=A la izquierda del texto
CoDHUD.HUD.Subtitles.NameAlign.Top=Encima del texto

# ---------[ OTHER SETTINGS ]---------
CoDHUD.Settings=Otros ajustes
CoDHUD.Audio=Ajustes de audio
CoDHUD.Audio.Announcer=Locutor
CoDHUD.Audio.Music=Música

CoDHUD.Audio.Announcer.Enable=Activar voz del locutor
CoDHUD.Audio.Announcer.Enable.desc=Activa el locutor.

CoDHUD.Audio.Announcer.English=Forzar locutor en inglés
CoDHUD.Audio.Announcer.English.desc=Fuerza la reproducción de voces del locutor en inglés, independientemente del idioma del juego.

CoDHUD.Audio.Music.Enable=Activar música
CoDHUD.Audio.Music.Enable.desc=Activa la música.

CoDHUD.Audio.Music.Ambient=Activar música ambiental
CoDHUD.Audio.Music.Ambient.desc=Activa música ambiental de fondo.

CoDHUD.Reset=Restablecer ajustes
CoDHUD.Challenges.Reset=Restablecer desafíos
CoDHUD.Challenges.Reset.desc=Restablece todos los desafíos desbloqueados.

CoDHUD.Rank.Reset=Restablecer rango y estadísticas
CoDHUD.Rank.Reset.desc=Restablece el rango y todas las estadísticas del HUD actual.
CoDHUD.Rank.Reset.Warning=¡Advertencia!\n¡Estás a punto de restablecer tu rango y estadísticas en este HUD!\n¡Esto no se puede deshacer! ¿Seguro que quieres restablecer tu rango y estadísticas?

CoDHUD.Menu=Ajustes del menú
CoDHUD.Menu.Fullscreen=Abrir en pantalla completa
CoDHUD.Menu.Fullscreen.desc=Abre el menú del HUD de CoD en pantalla completa en lugar de una ventana pequeña.

CoDHUD.Menu.SFX=SFX del menú
CoDHUD.Menu.SFX.desc=Reproduce efectos de sonido temáticos del menú al pasar el cursor o pulsar botones.

CoDHUD.Menu.Music=Música del menú
CoDHUD.Menu.Music.desc=Reproduce música temática del menú cuando cualquier instancia del menú HUD de CoD está activa.

CoDHUD.Menu.HideDesc=Ocultar descripción
CoDHUD.Menu.HideDesc.desc=Si está activado, las descripciones del menú estarán ocultas.

CoDHUD.Menu.HidePrompts=Ocultar avisos
CoDHUD.Menu.HidePrompts.desc=Si está activado, los avisos de botones en el menú estarán ocultos.

CoDHUD.Menu.OpenSpeed=Velocidad de apertura del menú
CoDHUD.Menu.OpenSpeed.desc=Qué tan rápido el menú HUD de CoD abrirá nuevas instancias.\n\nMedido en segundos.

CoDHUD.Menu.CloseSpeed=Velocidad de cierre del menú
CoDHUD.Menu.CloseSpeed.desc=Qué tan rápido el menú HUD de CoD cerrará instancias.\n\nMedido en segundos.

# ---------[ RANK & STATS ]---------
CoDHUD.Stats=Estadísticas del jugador
CoDHUD.Stats.Rank=Nivel del jugador: %d - %s
CoDHUD.Stats.XPNext=XP para el siguiente rango: %d
CoDHUD.Stats.XP=XP total: %d
CoDHUD.Stats.Kills=Bajas totales: %d
CoDHUD.Stats.Headshots=Disparos a la cabeza: %d
CoDHUD.Stats.Deaths=Muertes totales: %d
CoDHUD.Stats.Challenges=Desafíos completados: %d

CoDHUD.Stats.Unknown=Desconocido