#---------- CoD4 HUD | Español | Spanish
# Translator: Original Game

# Factions
CoD4_MPUI_MARINES=Marines recon.
CoD4_MPUI_SPETSNAZ=Spetsnaz
CoD4_MPUI_OPFOR=OpFor
CoD4_MPUI_SAS=SAS

CoD4_MPUI_MARINES_SHORT=Marines
CoD4_MPUI_SPETSNAZ_SHORT=Spetsnaz
CoD4_MPUI_OPFOR_SHORT=OpFor
CoD4_MPUI_SAS_SHORT=SAS

# Challenges
CoD4_MP_CHALLENGE_COMPLETED=¡Desafío completado!