#---------- Black Ops II Ranks | Español | Spanish
# Translator: Original Game

# Notifications
BO2_RANK_PROMOTED=¡Has sido ascendido!
BO2_RANK_PLAYER_WAS_PROMOTED=¡%s ha ascendido a %s!

# Ranks
BO2_RANK_PRVT_FULL=Soldado
BO2_RANK_PRVT_FULL2=Soldado II
BO2_RANK_PRVT_FULL3=Soldado III
BO2_RANK_PFC_FULL=Soldado primero
BO2_RANK_PFC_FULL2=Soldado primero II
BO2_RANK_PFC_FULL3=Soldado primero III
BO2_RANK_LCPL_FULL=Cabo
BO2_RANK_LCPL_FULL2=Cabo II
BO2_RANK_LCPL_FULL3=Cabo III
BO2_RANK_CPL_FULL=Cabo primero
BO2_RANK_CPL_FULL2=Cabo primero II
BO2_RANK_CPL_FULL3=Cabo primero III
BO2_RANK_SGT_FULL=Cabo mayor
BO2_RANK_SGT_FULL2=Cabo mayor II
BO2_RANK_SGT_FULL3=Cabo mayor III
BO2_RANK_SSGT_FULL=Sgto.
BO2_RANK_SSGT_FULL2=Sargento II
BO2_RANK_SSGT_FULL3=Sargento III
BO2_RANK_GYSGT_FULL=Sgto. primero
BO2_RANK_GYSGT_FULL2=Sargento primero II
BO2_RANK_GYSGT_FULL3=Sargento primero III
BO2_RANK_MSGT_FULL=Brigada
BO2_RANK_MSGT_FULL2=Brigada II
BO2_RANK_MSGT_FULL3=Brigada III
BO2_RANK_MGYSGT_FULL=Suboficial mayor
BO2_RANK_MGYSGT_FULL2=Suboficial mayor II
BO2_RANK_MGYSGT_FULL3=Suboficial mayor III
BO2_RANK_2NDLT_FULL=Subteniente
BO2_RANK_2NDLT_FULL2=Subteniente II
BO2_RANK_2NDLT_FULL3=Subteniente III
BO2_RANK_LT_FULL=Teniente
BO2_RANK_LT_FULL2=Teniente II
BO2_RANK_LT_FULL3=Teniente III
BO2_RANK_CPT_FULL=Capitán
BO2_RANK_CPT_FULL2=Capitán II
BO2_RANK_CPT_FULL3=Capitán III
BO2_RANK_MAJ_FULL=Comandante
BO2_RANK_MAJ_FULL2=Comandante II
BO2_RANK_MAJ_FULL3=Comandante III
BO2_RANK_LTCOL_FULL=Teniente coronel
BO2_RANK_LTCOL_FULL2=Teniente coronel II
BO2_RANK_LTCOL_FULL3=Teniente coronel III
BO2_RANK_COL_FULL=Coronel
BO2_RANK_COL_FULL2=Coronel II
BO2_RANK_COL_FULL3=Coronel III
BO2_RANK_BGEN_FULL=General de brigada
BO2_RANK_BGEN_FULL2=General de brigada II
BO2_RANK_BGEN_FULL3=General de brigada III
BO2_RANK_MAJGEN_FULL=General de división
BO2_RANK_MAJGEN_FULL2=General de división II
BO2_RANK_MAJGEN_FULL3=General de división III
BO2_RANK_LTGEN_FULL=Teniente general
BO2_RANK_LTGEN_FULL2=Teniente general II
BO2_RANK_LTGEN_FULL3=Teniente general III
BO2_RANK_GEN_FULL=General
BO2_RANK_GEN_FULL2=General de ejército II
BO2_RANK_GEN_FULL3=General del ejército III
BO2_RANK_COM_FULL=Capitán general
