#---------- CoD: World at War HUD | Русский | Russian
# Translator: Original Game

# Factions
WAW_MPUI_RUSSIAN=Красная армия
WAW_MPUI_JAPANESE=Имперская армия
WAW_MPUI_GERMAN=Вермахт
WAW_MPUI_MARINE=Рейдеры

WAW_MPUI_RUSSIAN_SHORT=Красная армия
WAW_MPUI_JAPANESE_SHORT=Имперская армия
WAW_MPUI_GERMAN_SHORT=Вермахт
WAW_MPUI_MARINE_SHORT=Рейдеры

# Gamemodes
WAW_MPUI_TANK_WAR=Война
WAW_OBJECTIVES_TWAR_HINT=Захватывайте флаги и защищайте их.