#---------- MW3 HUD | Русский | Russian
# Translator: Original Game

# Factions
MW3_MP_SAS=Специальная авиационная служба
MW3_MP_INNERCIRCLE_NAME=Личная охрана
MW3_MP_AFRICA_MILITIA_NAME=Африканские ополченцы
MW3_MP_DELTA_NAME=Подразделение Дельта
MW3_MP_GIGN=GIGN
MW3_MP_SPETSNAZ_NAME=Спецназ
MW3_MP_PMC_NAME=Наемники
	
MW3_MP_SAS_SHORT_NAME=САС
MW3_MP_INNERCIRCLE_SHORT_NAME=Личная охрана
MW3_MP_AFRICA_MILITIA_SHORT_NAME=Ополченцы
MW3_MP_DELTA_SHORT_NAME=Дельта
MW3_MP_GIGN_SHORT_NAME=GIGN
MW3_MPUI_SPETSNAZ_SHORT=Спецназ
MW3_MP_PMC_SHORT_NAME=Наемники

# Notifications
MW3_RANK_PROMOTED=Вас повысили!
MW3_RANK_PROMOTED_WEAPON=Уровень оружия вырос!
MW3_RANK_PLAYER_WAS_PROMOTED=%s получает новое звание: %s!

# Ranks
MW3_RANK_REC_FULL=Новобранец
MW3_RANK_PVT_FULL=Рядовой
MW3_RANK_PFC_FULL=Рядовой первого класса
MW3_RANK_LCPL_FULL=Младший капрал
MW3_RANK_CPL_FULL=Капрал
MW3_RANK_SGT_FULL=Сержант
MW3_RANK_SSGT_FULL=Штаб-сержант
MW3_RANK_GYSGT_FULL=Комендор-сержант
MW3_RANK_MSGT_FULL=Мастер-сержант
MW3_RANK_MGYSGT_FULL=Мастер-комендор-сержант
MW3_RANK_2NDLT_FULL=Второй лейтенант
MW3_RANK_1STLT_FULL=Первый лейтенант
MW3_RANK_CAPT_FULL=Капитан
MW3_RANK_MAJ_FULL=Майор
MW3_RANK_LTCOL_FULL=Подполковник
MW3_RANK_COL_FULL=Полковник
MW3_RANK_BGEN_FULL=Бригадный генерал
MW3_RANK_MAJGEN_FULL=Генерал-майор
MW3_RANK_LTGEN_FULL=Генерал-лейтенант
MW3_RANK_GEN_FULL=Генерал
MW3_RANK_COMM_FULL=Коммандер
MW3_RANK_1STLT_FULL2=Первый лейтенант I
MW3_RANK_1STLT_FULL3=Первый лейтенант II
MW3_RANK_2NDLT_FULL2=Второй лейтенант I
MW3_RANK_2NDLT_FULL3=Второй лейтенант II
MW3_RANK_BGEN_FULL2=Бригадный генерал I
MW3_RANK_BGEN_FULL3=Бригадный генерал II
MW3_RANK_CAPT_FULL2=Капитан I
MW3_RANK_CAPT_FULL3=Капитан II
MW3_RANK_COL_FULL2=Полковник I
MW3_RANK_COL_FULL3=Полковник II
MW3_RANK_COMM_FULL2=Коммандер I
MW3_RANK_COMM_FULL3=Коммандер II
MW3_RANK_CPL_FULL2=Капрал I
MW3_RANK_CPL_FULL3=Капрал II
MW3_RANK_GEN_FULL2=Генерал I
MW3_RANK_GEN_FULL3=Генерал II
MW3_RANK_GYSGT_FULL2=Комендор-сержант I
MW3_RANK_GYSGT_FULL3=Комендор-сержант II
MW3_RANK_LCPL_FULL2=Младший капрал I
MW3_RANK_LCPL_FULL3=Младший капрал II
MW3_RANK_LTCOL_FULL2=Подполковник I
MW3_RANK_LTCOL_FULL3=Подполковник II
MW3_RANK_MAJ_FULL2=Майор I
MW3_RANK_MAJ_FULL3=Майор II
MW3_RANK_MAJGEN_FULL2=Генерал-майор I
MW3_RANK_MAJGEN_FULL3=Генерал-майор II
MW3_RANK_MGYSGT_FULL2=Мастер-комендор-сержант I
MW3_RANK_MGYSGT_FULL3=Мастер-комендор-сержант II
MW3_RANK_MSGT_FULL2=Мастер-сержант I
MW3_RANK_MSGT_FULL3=Мастер-сержант II
MW3_RANK_PFC_FULL2=Рядовой первого класса I
MW3_RANK_PFC_FULL3=Рядовой первого класса II
MW3_RANK_PVT_FULL2=Рядовой I
MW3_RANK_PVT_FULL3=Рядовой II
MW3_RANK_REC_FULL2=Новобранец I
MW3_RANK_REC_FULL3=Новобранец II
MW3_RANK_SGT_FULL2=Сержант I
MW3_RANK_SGT_FULL3=Сержант II
MW3_RANK_SSGT_FULL2=Штаб-сержант I
MW3_RANK_SSGT_FULL3=Штаб-сержант II
MW3_RANK_LTGEN_FULL2=Генерал-лейтенант I
MW3_RANK_LTGEN_FULL3=Генерал-лейтенант II
MW3_RANK_SGTMAJ_FULL=Сержант-майор
MW3_RANK_SGTMAJ_FULL2=Сержант-майор I
MW3_RANK_SGTMAJ_FULL3=Сержант-майор II
MW3_RANK_SGTMAJ_FULL_N=Сержант-майор %s
MW3_RANK_COMM_FULL_N=Коммандер %s
MW3_RANK_SPC_FULL=Специалист
MW3_RANK_SPC_FULL2=Специалист I
MW3_RANK_SPC_FULL3=Специалист II
MW3_RANK_SPC_FULL_N=Специалист %s
MW3_RANK_SFC_FULL=Сержант 1 класса
MW3_RANK_SFC_FULL2=Сержант 1 класса I
MW3_RANK_SFC_FULL3=Сержант 1 класса II
MW3_RANK_SFC_FULL_N=Сержант 1 класса %s
MW3_RANK_1STSGT_FULL=Первый сержант
MW3_RANK_1STSGT_FULL2=Первый сержант I
MW3_RANK_1STSGT_FULL3=Первый сержант II
MW3_RANK_1STSGT_FULL_N=Первый сержант %s
MW3_RANK_CSM_FULL=Команд-сержант-майор
MW3_RANK_CSM_FULL2=Команд-сержант-майор I
MW3_RANK_CSM_FULL3=Команд-сержант-майор II
MW3_RANK_CSM_FULL_N=Команд-сержант-майор %s
MW3_RANK_CSM_FULL4=Команд-сержант-майор III
MW3_RANK_GEN_FULL4=Генерал III
MW3_RANK_LTGEN_FULL4=Генерал-лейтенант III
MW3_RANK_MAJGEN_FULL4=Генерал-майор III
MW3_RANK_BGEN_FULL4=Бригадный генерал III
MW3_RANK_COL_FULL4=Полковник III
MW3_RANK_LTCOL_FULL4=Подполковник III
MW3_RANK_MAJ_FULL4=Майор III
MW3_RANK_CAPT_FULL4=Капитан III
MW3_RANK_1STLT_FULL4=Первый лейтенантIII
MW3_RANK_2NDLT_FULL4=Второй лейтенант III
MW3_RANK_SSGT_FULL4=Штаб-сержант III
MW3_RANK_SFC_FULL4=Сержант 1 класса III
MW3_RANK_MSGT_FULL4=Мастер-сержант III
MW3_RANK_1STSGT_FULL4=Первый сержант III
MW3_RANK_SGTMAJ_FULL4=Сержант-майор III
