#---------- MW2 HUD | Русский | Russian
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Военные рейнджеры
MW2_MP_SEALS_UDT_NAME="Морские котики" ВМС США
MW2_MP_MILITIA_NAME=Ополчение
MW2_MP_TASKFORCE_NAME=ОТГ-141
MW2_MP_OPFOR_NAME=Сепаратисты
MW2_MP_SPETSNAZ_NAME=Спецназ

MW2_MP_US_ARMY_SHORT_NAME=Рейнджеры
MW2_MP_SEALS_UDT_SHORT_NAME="Морские котики"
MW2_MP_MILITIA_SHORT_NAME=Ополчение
MW2_MP_TASKFORCE_SHORT_NAME=ОТГ-141
MW2_MPUI_OPFOR_SHORT=Сепаратисты
MW2_MPUI_SPETSNAZ_SHORT=Спецназ

# Splashes
MW2_SPLASHES_HEADSHOT=Прямо в голову!
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=Помощь в суициде!
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Вы помогли противнику совершить самоубийство
MW2_SPLASHES_LONGSHOT=Дальний выстрел!
MW2_SPLASHES_LONGSHOT_DESC=Убийство с дальнего расстояния!
MW2_SPLASHES_EXECUTION=Казнь!
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=Мститель!
MW2_SPLASHES_AVENGER_DESC=Вы отомстили за товарища по команде.
MW2_SPLASHES_DEFENDER=Защитник!
MW2_SPLASHES_DEFENDER_DESC=Вы спасли товарища по команде.
MW2_SPLASHES_POSTHUMOUS=Загробная жизнь!
MW2_SPLASHES_POSTHUMOUS_DESC=Вы убили противника после собственной смерти.
MW2_SPLASHES_REVENGE=Расплата!
MW2_SPLASHES_REVENGE_DESC=Вы отомстили.
MW2_SPLASHES_DOUBLEKILL=Двойное убийство!
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Тройное убийство!
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Множественное убийство!
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=Первая кровь!
MW2_SPLASHES_FIRSTBLOOD_DESC=Вы совершили первое убийство.
MW2_SPLASHES_BUZZKILL=Зануда!
MW2_SPLASHES_BUZZKILL_DESC=Вы в последний момент не дали противнику совершить серию.
MW2_SPLASHES_COMEBACK=Возвращение!
MW2_SPLASHES_COMEBACK_DESC=Вы восстановились после серии смертей.
MW2_SPLASHES_FLAGRETURN=Спасение флага!
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Игрок с флагом!
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Позиция захвачена!
MW2_SPLASHES_CAPTURE_DESC=Цель захвачена.
MW2_SPLASHES_DEFEND=Оборона!
MW2_SPLASHES_DEFEND_DESC=Вам удалось защитить цель.
MW2_SPLASHES_ASSAULT=Нападение!
MW2_SPLASHES_ASSAULT_DESC=Вы убили защитника.
MW2_SPLASHES_PLANT=Диверсант!
MW2_SPLASHES_PLANT_DESC=Вы заложили бомбу.
MW2_SPLASHES_DEFUSE=Герой!
MW2_SPLASHES_DEFUSE_DESC=Вы обезвредили бомбу.
MW2_SPLASHES_SAB_OVERTIME=Дополнительное время!
MW2_SPLASHES_SAB_OVERTIME_DESC=Ближайшая к бомбе база будет уничтожена.
MW2_SPLASHES_MARTYRDOM_DESC=После смерти вы уроните гранату.
MW2_SPLASHES_FINALSTAND_DESC=Когда вас убьют, вы получите еще один шанс.
MW2_SPLASHES_ENDGAME_DESC=Ближайшие пару секунд у вас будет дополнительное здоровье.
MW2_SPLASHES_C4DEATH_DESC=Перед смертью оттолкните заряд С4.
MW2_SPLASHES_KNIFETHROW_DESC=Вы убили противника метательным ножом.
MW2_SPLASHES_KNIFETHROW=В яблочко!
MW2_SPLASHES_HIJACKER_DESC=Захвачен вражеский контейнер со снабжением.
MW2_SPLASHES_HIJACKER=Захватчик!
MW2_SPLASHES_HIJACKED=%s похищает вашу гуманитарную помощь.
MW2_SPLASHES_DEFCON_LOWER=БОЕВАЯ ГОТОВНОСТЬ снижена!
MW2_SPLASHES_DEFCON_RAISE=БОЕВАЯ ГОТОВНОСТЬ повышена.
MW2_SPLASHES_DEFCON_LOWER_DESC=Требования к наградам повышены.
MW2_SPLASHES_DEFCON_RAISE_DESC=Требования к наградам снижены.
MW2_SPLASHES_DEFCON_5=БОЕВАЯ ГОТОВНОСТЬ 5
MW2_SPLASHES_DEFCON_4=Боевая готовность: 4.
MW2_SPLASHES_DEFCON_3=БОЕВАЯ ГОТОВНОСТЬ 3
MW2_SPLASHES_DEFCON_2=БОЕВАЯ ГОТОВНОСТЬ 2
MW2_SPLASHES_DEFCON_1=БОЕВАЯ ГОТОВНОСТЬ 1
MW2_SPLASHES_DEFCON_5_DESC=БОЕВАЯ ГОТОВНОСТЬ 5
MW2_SPLASHES_DEFCON_4_DESC=Бой начинается!
MW2_SPLASHES_DEFCON_3_DESC=Спецгруз доставлен!
MW2_SPLASHES_DEFCON_2_DESC=Изменение в наградах за серию!
MW2_SPLASHES_DEFCON_1_DESC=За захват цели очки начисляются вдвойне!
MW2_SPLASHES_COMBATHIGH_DESC=Ненадолго повышено здоровье.
MW2_SPLASHES_RESTED=Увеличение ежедневного приобретения опыта!
MW2_SPLASHES_RESTED_DESC=Каждый день вы получаете дополнительные очки опыта!
MW2_SPLASHES_RESTED_DONE=Начислены дополнительные очки опыта за день.
MW2_SPLASHES_RESTED_DONE_DESC=Получены дополнительные очки опыта.
MW2_SPLASHES_VIP=Вы теперь VIP.
MW2_SPLASHES_STUCK_SEMTEX=Прилип!
MW2_SPLASHES_STUCK_SEMTEX_DESC=Вы поразили противника пластидом!
MW2_SPLASHES_HEROIC=Подвиг!
MW2_SPLASHES_HEROIC_DESC=Вы воспользовались последним шансом и захватили цель!
MW2_SPLASHES_DENIED=Стоп!
MW2_SPLASHES_DENIED_DESC=Вы прервали тактическую высадку противника!
MW2_SPLASHES_DESTROYED_INSERTION=Высадка десанта прервана.
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=забрал ваш ящик!
MW2_SPLASHES_REVIVER_DESC=Вы реанимировали товарища по команде.
MW2_SPLASHES_REVIVER=Реаниматор!
MW2_SPLASHES_GIVEAWAY_SENTRY=...захвачено сторожевое орудие.
MW2_SPLASHES_GIVEAWAY_AIRDROP=забрал сброшенную награду.
MW2_SPLASHES_SEMTEX_STUCK=Вас поразили пластидом.
MW2_SPLASHES_ONE_SHOT_KILL=Убийство одним выстрелом
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Один выстрел... Один труп
MW2_SPLASHES_NINJA_DEFUSE=Ниндзя
MW2_SPLASHES_NINJA_DEFUSE_DESC=Хитро - хитро...
MW2_SPLASHES_COPYCAT_DESC=Похитить класс убийцы во время просмотра повтора смерти.
MW2_SPLASHES_COPIED=Класс скопирован!
MW2_SPLASHES_REVIVED=Вас реанимировали.
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Остался один!
MW2_SPLASHES_LAST_ENEMY_ALIVE=Остался один!
MW2_SPLASHES_SHIELDASSIST=Контроль над толпой!
MW2_SPLASHES_SHIELDASSIST_DESC=Вы мастер разрушения.
MW2_SPLASHES_DESTROYED_HELICOPTER=Вертолет уничтожен!
MW2_SPLASHES_DESTROYED_PAVELOW="Пейв лоу" уничтожен!
MW2_SPLASHES_DESTROYED_UAV=БПЛА уничтожен!
MW2_SPLASHES_DESTROYED_HARRIER="Харриер" уничтожен!
MW2_SPLASHES_DESTROYED_AC130=AC130 уничтожен!
MW2_SPLASHES_DESTROYED_MINIGUNNER=Вертолет уничтожен!
MW2_SPLASHES_FLAG_RETURN=Флаг спасен!
MW2_SPLASHES_FLAG_CAPTURE=Флаг захвачен!
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=Ваш флаг захвачен!
MW2_SPLASHES_FLAG_PICKUP_ENEMY=Захвачен вражеский флаг!
MW2_SPLASHES_FLAG_PICKUP=Захвачен флаг!
MW2_SPLASHES_CAPTURED_NUKE=Захвачен ядерный заряд!
MW2_SPLASHES_DESC_CAPTURED_NUKE=Захвачен ядерный заряд.
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Доступен магазин с повышенной емкостью!
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Доступен датчик сердцебиения!
MW2_SPLASHES_UNLOCKED_AKIMBO=Доступно парное оружие!
MW2_SPLASHES_UNLOCKED_THERMAL=Доступен тепловизор!
MW2_SPLASHES_UNLOCKED_EOTECH=Доступен голографический прицел.
MW2_SPLASHES_UNLOCKED_SHOTGUN=Доступен дробовик!
MW2_SPLASHES_GRABBED_THE_FLAG=Флаг захвачен!
MW2_SPLASHES_HIJACKED_SENTRY=Похищена сторожевая пушка.
MW2_SPLASHES_HIJACKED_AIRDROP=Похищен ящик со снабжением.
MW2_SPLASHES_BOMB_PLANTED=Бомба заложена!
MW2_SPLASHES_BOMB_DEFUSED=Бомба обезврежена!
MW2_SPLASHES_TIMEADDED=Дополнительное время!
MW2_SPLASHES_GTNW_OVERTIME=Внезапная смерть!
MW2_SPLASHES_GTNW_OVERTIME_DESC=Нет возрождений.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Цель уничтожена!
MW2_SPLASHES_SAVED_OBJECTIVE=Цель защищена!
MW2_SPLASHES_CAPTURED_HQ=Штаб захвачен!
MW2_SPLASHES_DESTROYED_HQ=Штаб разрушен!
MW2_SPLASHES_BOMB_TAKEN=Бомба взята!
MW2_SPLASHES_BOMB_DROPPED=Бомба брошена!
MW2_SPLASHES_KILLED_CARRIER=Противник с бомбой убит!
MW2_SPLASHES_SHAREPACKAGE=Поделиться снабжением!
MW2_SPLASHES_SHAREPACKAGE_DESC=Ваш товарищ по команде отбил у врага ящик со снабжением!
MW2_SPLASHES_DESTROYED_COUNTER_UAV=Беспилотник восстановлен!
MW2_SPLASHES_FLAGS_CAPTURE=Захватывает флаг!
MW2_SPLASHES_FLAG_ASSAULT=Нападение на флаг!
MW2_SPLASHES_FLAG_DEFEND=Защита флага!
MW2_SPLASHES_FLAG_ASSAULT_DESC=Вы убили защитника флага.
MW2_SPLASHES_FLAG_DEFEND_DESC=Вам удалось защитить флаг.
MW2_SPLASHES_FLAG_CAPTURED=Флаг захвачен!
MW2_SPLASHES_FLAG_CAPTURED_DESC=Вы захватили вражеский флаг.
MW2_SPLASHES_SECURED_POSITION=Позиция захвачена!
MW2_SPLASHES_SECURED_POSITION_A=Объект А захвачен!
MW2_SPLASHES_SECURED_POSITION_B=Объект B захвачен!
MW2_SPLASHES_SECURED_POSITION_C=Объект С захвачен!
MW2_SPLASHES_TIME_ADDED=Дополнительное время!
MW2_SPLASHES_TIME_ADDED_DESC=Зона минирования разрушена. Время увеличено.

# Other
MW2_MP_CONNECTED=Игрок %s подключен.
MW2_MP_DISCONNECTED=Игрок %s отключен.
MW2_EXE_LEFTGAME=%s покидает игру

MW2_PLATFORM_RELOAD=Перезарядка
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Мало боеприпасов
MW2_WEAPON_NO_AMMO=Нет боеприпасов

MW2_MPUI_WINNING_CAPS=ВЫ ВЫИГРЫВАЕТЕ
MW2_MPUI_LOSING_CAPS=ВЫ ПРОИГРЫВАЕТЕ
MW2_MPUI_TIED_CAPS=НИЧЬЯ

MW2_CGAME_SB_SCORE=Счет
MW2_CGAME_SB_DEATHS=Смерти
MW2_CGAME_SB_KILLS=Убийства
MW2_CGAME_SB_ASSISTS=Помощь

MW2_PLATFORM_THROWBACKGRENADE=%s кинуть обратно

MW2_MP_FIRSTPLACE_NAME=1. %s
MW2_MP_SECONDPLACE_NAME=2. %s
MW2_MP_THIRDPLACE_NAME=3. %s

# Partially custom
MW2_GAME_CHANGEDTO=%s изменено на %s

# Round Starter
MW2_MP_MATCH_STARTING_IN=До начала боя:
MW2_MP_MATCH_RESUMING_IN=До продолжения боя:
  
# Gamemodes
MW2_MPUI_SABOTAGE=Диверсия
MW2_MPUI_DEATHMATCH=Каждый за себя
MW2_MPUI_CAPTURE_THE_FLAG=Захват флага
MW2_MPUI_HEADQUARTERS=Штаб
MW2_MPUI_SEARCH_AND_DESTROY=Бомба
MW2_MPUI_WAR=Командный бой
MW2_MPUI_DOMINATION=Превосходство
MW2_MPUI_ONE_FLAG=ЗФ: один флаг
MW2_MPUI_ARENA=Арена
MW2_MPUI_DD=Уничтожение
MW2_MPUI_VIP=VIP
MW2_MPUI_GTNW=Третья мировая

MW2_MP_OBJ_DM_HINT=Уничтожьте других игроков
MW2_MP_OBJ_WAR_HINT=Нейтрализуйте игроков противника
MW2_OBJECTIVES_WAR_HINT=Нейтрализуйте игроков противника.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Уничтожьте объект A или Б.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Защищайте объекты A и Б.
MW2_OBJECTIVES_SAB_HINT=Уничтожьте вражеский объект.
MW2_OBJECTIVES_DOM_HINT=Захватывайте флаги и защищайте их.
MW2_OBJECTIVES_DM_HINT=Уничтожьте других игроков
MW2_OBJECTIVES_KOTH_HINT=Удерживайте штаб.
MW2_OBJECTIVES_CTF_HINT=Захватите вражеский флаг.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Захватите вражеский флаг.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Защищайте флаг.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Уничтожьте объекты А и В.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Защищайте объекты A и Б.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Убейте важную персону, не дав добраться в точку эвакуации.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Защитите важную персону, помогая добраться в точку эвакуации.
MW2_OBJECTIVES_ARENA_HINT=Уничтожьте противника или захватите флаг.
MW2_OBJECTIVES_GTNW_HINT=Захватите ядерный чемоданчик.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Захватите флаг противника.

# Round Ender
MW2_MP_DRAW=Ничья
MW2_MP_VICTORY=Победа!
MW2_MP_DEFEAT=Поражение!
MW2_MP_ROUND_DRAW=Ничья
MW2_MP_ROUND_WIN=Победа в раунде
MW2_MP_ROUND_LOSS=Поражение в раунде
MW2_MP_HALFTIME=Конец полупериода
MW2_MP_OVERTIME=Дополнительное время
MW2_MP_MATCH_BONUS_IS=Призовые очки: %s

MW2_MP_SCORE_LIMIT_REACHED=Достигнут лимит очков
MW2_MP_ROUND_LIMIT_REACHED=Все раунды завершены
MW2_MP_TIME_LIMIT_REACHED=Время вышло
MW2_MP_HOST_ENDED_GAME=Администратор завершил игру

# Notifications
MW2_RANK_PROMOTED=Вы получили новое звание!
MW2_RANK_PLAYER_WAS_PROMOTED=%s получает новое звание: %s!

# Ranks
MW2_RANK_REC_FULL=Рекрут
MW2_RANK_PVT_FULL=Закрытая
MW2_RANK_PFC_FULL=Рядовой 1-го класса
MW2_RANK_LCPL_FULL=Младший капрал
MW2_RANK_CPL_FULL=Капрал
MW2_RANK_SGT_FULL=Сержант
MW2_RANK_SSGT_FULL=Штаб-сержант
MW2_RANK_GYSGT_FULL=Комендор-сержант
MW2_RANK_MSGT_FULL=Мастер-сержант
MW2_RANK_MGYSGT_FULL=Мастер-комендор-сержант
MW2_RANK_2NDLT_FULL=Второй лейтенант
MW2_RANK_1STLT_FULL=Первый лейтенант
MW2_RANK_CAPT_FULL=Капитан
MW2_RANK_MAJ_FULL=Майор
MW2_RANK_LTCOL_FULL=Подполковник
MW2_RANK_COL_FULL=Полковник
MW2_RANK_BGEN_FULL=Бригадный генерал
MW2_RANK_MAJGEN_FULL=Генерал-майор
MW2_RANK_LTGEN_FULL=Генерал-лейтенант
MW2_RANK_GEN_FULL=Общие
MW2_RANK_COMM_FULL=Коммандер
MW2_RANK_1STLT_FULL2=Первый лейтенант I
MW2_RANK_1STLT_FULL3=Первый лейтенант II
MW2_RANK_2NDLT_FULL2=Второй лейтенант I
MW2_RANK_2NDLT_FULL3=Второй лейтенант II
MW2_RANK_BGEN_FULL2=Бригадный генерал I
MW2_RANK_BGEN_FULL3=Бригадный генерал II
MW2_RANK_CAPT_FULL2=Капитан I
MW2_RANK_CAPT_FULL3=Капитан II
MW2_RANK_COL_FULL2=Полковник I
MW2_RANK_COL_FULL3=Полковник II
MW2_RANK_COMM_FULL2=Коммандер I
MW2_RANK_COMM_FULL3=Коммандер II
MW2_RANK_CPL_FULL2=Капрал I
MW2_RANK_CPL_FULL3=Капрал II
MW2_RANK_GEN_FULL2=Генерал I
MW2_RANK_GEN_FULL3=Генерал II
MW2_RANK_GYSGT_FULL2=Комендор-сержант I
MW2_RANK_GYSGT_FULL3=Комендор-сержант II
MW2_RANK_LCPL_FULL2=Младший капрал I
MW2_RANK_LCPL_FULL3=Младший капрал II
MW2_RANK_LTCOL_FULL2=Подполковник I
MW2_RANK_LTCOL_FULL3=Подполковник II
MW2_RANK_MAJ_FULL2=Майор I
MW2_RANK_MAJ_FULL3=Майор II
MW2_RANK_MAJGEN_FULL2=Генерал-майор I
MW2_RANK_MAJGEN_FULL3=Генерал-майор II
MW2_RANK_MGYSGT_FULL2=Мастер-комендор-сержант I
MW2_RANK_MGYSGT_FULL3=Мастер-комендор-сержант II
MW2_RANK_MSGT_FULL2=Мастер-сержант I
MW2_RANK_MSGT_FULL3=Мастер-сержант II
MW2_RANK_PFC_FULL2=Рядовой 1-го класса I
MW2_RANK_PFC_FULL3=Рядовой 1-го класса II
MW2_RANK_PVT_FULL2=Рядовой I
MW2_RANK_PVT_FULL3=Рядовой II
MW2_RANK_REC_FULL2=Рекрут I
MW2_RANK_REC_FULL3=Рекрут II
MW2_RANK_SGT_FULL2=Сержант I
MW2_RANK_SGT_FULL3=Сержант II
MW2_RANK_SSGT_FULL2=Штаб-сержант I
MW2_RANK_SSGT_FULL3=Штаб-сержант II
MW2_RANK_LTGEN_FULL2=Генерал-лейтенант I
MW2_RANK_LTGEN_FULL3=Генерал-лейтенант II
MW2_RANK_SGTMAJ_FULL=Сержант-майор
MW2_RANK_SGTMAJ_FULL2=Сержант-майор I
MW2_RANK_SGTMAJ_FULL3=Сержант-майор II
MW2_RANK_SPC_FULL=Специалист
MW2_RANK_SPC_FULL2=Специалист I
MW2_RANK_SPC_FULL3=Специалист II
MW2_RANK_SFC_FULL=Сержант первого класса
MW2_RANK_SFC_FULL2=Сержант первого класса I
MW2_RANK_SFC_FULL3=Сержант первого класса II
MW2_RANK_1STSGT_FULL=Первый сержант
MW2_RANK_1STSGT_FULL2=Первый сержант I
MW2_RANK_1STSGT_FULL3=Первый сержант II
MW2_RANK_CSM_FULL=Комманд-сержант-майор
MW2_RANK_CSM_FULL2=Комманд-сержант-майор I
MW2_RANK_CSM_FULL3=Комманд-сержант-майор II
MW2_RANK_CSM_FULL4=Комманд-сержант-майор III
MW2_RANK_GEN_FULL4=Генерал III
MW2_RANK_LTGEN_FULL4=Генерал-лейтенант III
MW2_RANK_MAJGEN_FULL4=Генерал-майор III
MW2_RANK_BGEN_FULL4=Бригадный генерал III
MW2_RANK_COL_FULL4=Полковник III
MW2_RANK_LTCOL_FULL4=Подполковник III
MW2_RANK_MAJ_FULL4=Майор III
MW2_RANK_CAPT_FULL4=Капитан III
MW2_RANK_1STLT_FULL4=Первый лейтенант III
MW2_RANK_2NDLT_FULL4=Второй лейтенант III
