#---------- Black Ops II Ranks | Русский | Russian
# Translator: Original Game

# Notifications
BO2_RANK_PROMOTED=Вы повышены в звании!
BO2_RANK_PLAYER_WAS_PROMOTED=%s получает звание %s!

# Ranks
BO2_RANK_PRVT_FULL=Рядовой
BO2_RANK_PRVT_FULL2=Рядовой 2
BO2_RANK_PRVT_FULL3=Рядовой 3
BO2_RANK_PFC_FULL=Рядовой 1-го класса
BO2_RANK_PFC_FULL2=Рядовой 1-го класса 2
BO2_RANK_PFC_FULL3=Рядовой 1-го класса 3
BO2_RANK_LCPL_FULL=Младший капрал
BO2_RANK_LCPL_FULL2=Младший капрал 2
BO2_RANK_LCPL_FULL3=Младший капрал 3
BO2_RANK_CPL_FULL=Капрал
BO2_RANK_CPL_FULL2=Капрал 2
BO2_RANK_CPL_FULL3=Капрал 3
BO2_RANK_SGT_FULL=Сержант
BO2_RANK_SGT_FULL2=Сержант 2
BO2_RANK_SGT_FULL3=Сержант 3
BO2_RANK_SSGT_FULL=Штаб-сержант
BO2_RANK_SSGT_FULL2=Штаб-сержант 2
BO2_RANK_SSGT_FULL3=Штаб-сержант 3
BO2_RANK_GYSGT_FULL=Командор-сержант
BO2_RANK_GYSGT_FULL2=Командор-сержант 2
BO2_RANK_GYSGT_FULL3=Командор-сержант 3
BO2_RANK_MSGT_FULL=Мастер-сержант
BO2_RANK_MSGT_FULL2=Мастер-сержант 2
BO2_RANK_MSGT_FULL3=Мастер-сержант 3
BO2_RANK_MGYSGT_FULL=Старший Командор-сержант
BO2_RANK_MGYSGT_FULL2=Старший Командор-сержант 2
BO2_RANK_MGYSGT_FULL3=Старший Командор-сержант 3
BO2_RANK_2NDLT_FULL=Второй лейтенант
BO2_RANK_2NDLT_FULL2=Второй лейтенант 2
BO2_RANK_2NDLT_FULL3=Второй лейтенант 3
BO2_RANK_LT_FULL=Лейтенант
BO2_RANK_LT_FULL2=Лейтенант 2
BO2_RANK_LT_FULL3=Лейтенант 3
BO2_RANK_CPT_FULL=Капитан
BO2_RANK_CPT_FULL2=Капитан 2
BO2_RANK_CPT_FULL3=Капитан 3
BO2_RANK_MAJ_FULL=Майор
BO2_RANK_MAJ_FULL2=Майор 2
BO2_RANK_MAJ_FULL3=Майор 3
BO2_RANK_LTCOL_FULL=Подполковник
BO2_RANK_LTCOL_FULL2=Подполковник 2
BO2_RANK_LTCOL_FULL3=Подполковник 3
BO2_RANK_COL_FULL=Полковник
BO2_RANK_COL_FULL2=Полковник 2
BO2_RANK_COL_FULL3=Полковник 3
BO2_RANK_BGEN_FULL=Бригадный генерал
BO2_RANK_BGEN_FULL2=Бригадный генерал 2
BO2_RANK_BGEN_FULL3=Бригадный генерал 3
BO2_RANK_MAJGEN_FULL=Генерал-майор
BO2_RANK_MAJGEN_FULL2=Генерал-майор 2
BO2_RANK_MAJGEN_FULL3=Генерал-майор 3
BO2_RANK_LTGEN_FULL=Генерал-лейтенант
BO2_RANK_LTGEN_FULL2=Генерал-лейтенант 2
BO2_RANK_LTGEN_FULL3=Генерал-лейтенант 3
BO2_RANK_GEN_FULL=Генерал
BO2_RANK_GEN_FULL2=Генерал 2
BO2_RANK_GEN_FULL3=Генерал 3
BO2_RANK_COM_FULL=Коммандер
