#---------- Black Ops II HUD | Русский | Russian
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=МОРСКИЕ КОТИКИ
BO2_MP_PLA_NAME=КСС
BO2_MP_FBI_NAME=ФБР
BO2_MP_PMC_NAME=Наемники
BO2_MP_ISA_NAME=ИСА
BO2_MP_CD_NAME=Ополчение

BO2_MPUI_SEALS_SHORT=Котики
BO2_MPUI_PLA_SHORT=КСС
BO2_MPUI_FBI_SHORT=ФБР
BO2_MPUI_PMC_SHORT=Наемники
BO2_MPUI_ISA_SHORT=ИСА
BO2_MPUI_CD_SHORT=Ополченцы

BO2_MPUI_SEALS_SHORT_CAPS=КОТИКИ
BO2_MPUI_PLA_SHORT_CAPS=КСС
BO2_MPUI_FBI_SHORT_CAPS=ФБР
BO2_MPUI_PMC_SHORT_CAPS=НАЕМНИКИ
BO2_MPUI_ISA_SHORT_CAPS=ИСА
BO2_MPUI_CD_SHORT_CAPS=ОПОЛЧЕНИЕ

# Splashes
BO2_MEDAL_FIRST_KILL=Первая кровь
BO2_MEDAL_ASSISTED_SUICIDE=Эвтаназия
BO2_MEDAL_HEADSHOT=В голову
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=Возвращение
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=Загробная жизнь
BO2_MEDAL_LONGSHOT_KILL=Орлиный глаз
BO2_MEDAL_REVENGE_KILL=Месть
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=Выживший
BO2_MEDAL_KILL_ENEMY_IN_AIR=В воздухе
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=1 выстрел, 1 труп
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=Четыре строки
BO2_MEDAL_KILLSTREAK_5=Кровожадный
BO2_MEDAL_KILLSTREAK_10=Безжалостный
BO2_MEDAL_KILLSTREAK_15=Непреклонный
BO2_MEDAL_KILLSTREAK_20=Неотступный
BO2_MEDAL_KILLSTREAK_25=Безжалостный
BO2_MEDAL_KILLSTREAK_30=Ядерный
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=Неудержимый
BO2_MEDAL_MULTIKILL_2=Двойное убийство
BO2_MEDAL_MULTIKILL_3=Тройное убийство
BO2_MEDAL_MULTIKILL_4=Яростное убийство
BO2_MEDAL_MULTIKILL_5=Безумное убийство
BO2_MEDAL_MULTIKILL_6=Супер-убийство
BO2_MEDAL_MULTIKILL_7=Мега-убийство
BO2_MEDAL_MULTIKILL_8=Ультра-убийство
BO2_MEDAL_MULTIKILL_MORE_THAN_8=Серия убийств
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=Мститель
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=Спаситель

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s ОЧКОВ ДО ПОБЕДЫ

# Notifications
BO2_RANK_PROMOTED=Вы повышены в звании!
BO2_RANK_PLAYER_WAS_PROMOTED=%s получает звание %s!

# Ranks
BO2_RANK_PRVT_FULL=Рядовой
BO2_RANK_PRVT_FULL2=Рядовой 2
BO2_RANK_PRVT_FULL3=Рядовой 3
BO2_RANK_PFC_FULL=Рядовой 1-го класса
BO2_RANK_PFC_FULL2=Рядовой 1-го класса 2
BO2_RANK_PFC_FULL3=Рядовой 1-го класса 3
BO2_RANK_LCPL_FULL=Младший капрал
BO2_RANK_LCPL_FULL2=Младший капрал 2
BO2_RANK_LCPL_FULL3=Младший капрал 3
BO2_RANK_CPL_FULL=Капрал
BO2_RANK_CPL_FULL2=Капрал 2
BO2_RANK_CPL_FULL3=Капрал 3
BO2_RANK_SGT_FULL=Сержант
BO2_RANK_SGT_FULL2=Сержант 2
BO2_RANK_SGT_FULL3=Сержант 3
BO2_RANK_SSGT_FULL=Штаб-сержант
BO2_RANK_SSGT_FULL2=Штаб-сержант 2
BO2_RANK_SSGT_FULL3=Штаб-сержант 3
BO2_RANK_GYSGT_FULL=Командор-сержант
BO2_RANK_GYSGT_FULL2=Командор-сержант 2
BO2_RANK_GYSGT_FULL3=Командор-сержант 3
BO2_RANK_MSGT_FULL=Мастер-сержант
BO2_RANK_MSGT_FULL2=Мастер-сержант 2
BO2_RANK_MSGT_FULL3=Мастер-сержант 3
BO2_RANK_MGYSGT_FULL=Старший Командор-сержант
BO2_RANK_MGYSGT_FULL2=Старший Командор-сержант 2
BO2_RANK_MGYSGT_FULL3=Старший Командор-сержант 3
BO2_RANK_2NDLT_FULL=Второй лейтенант
BO2_RANK_2NDLT_FULL2=Второй лейтенант 2
BO2_RANK_2NDLT_FULL3=Второй лейтенант 3
BO2_RANK_LT_FULL=Лейтенант
BO2_RANK_LT_FULL2=Лейтенант 2
BO2_RANK_LT_FULL3=Лейтенант 3
BO2_RANK_CPT_FULL=Капитан
BO2_RANK_CPT_FULL2=Капитан 2
BO2_RANK_CPT_FULL3=Капитан 3
BO2_RANK_MAJ_FULL=Майор
BO2_RANK_MAJ_FULL2=Майор 2
BO2_RANK_MAJ_FULL3=Майор 3
BO2_RANK_LTCOL_FULL=Подполковник
BO2_RANK_LTCOL_FULL2=Подполковник 2
BO2_RANK_LTCOL_FULL3=Подполковник 3
BO2_RANK_COL_FULL=Полковник
BO2_RANK_COL_FULL2=Полковник 2
BO2_RANK_COL_FULL3=Полковник 3
BO2_RANK_BGEN_FULL=Бригадный генерал
BO2_RANK_BGEN_FULL2=Бригадный генерал 2
BO2_RANK_BGEN_FULL3=Бригадный генерал 3
BO2_RANK_MAJGEN_FULL=Генерал-майор
BO2_RANK_MAJGEN_FULL2=Генерал-майор 2
BO2_RANK_MAJGEN_FULL3=Генерал-майор 3
BO2_RANK_LTGEN_FULL=Генерал-лейтенант
BO2_RANK_LTGEN_FULL2=Генерал-лейтенант 2
BO2_RANK_LTGEN_FULL3=Генерал-лейтенант 3
BO2_RANK_GEN_FULL=Генерал
BO2_RANK_GEN_FULL2=Генерал 2
BO2_RANK_GEN_FULL3=Генерал 3
BO2_RANK_COM_FULL=Коммандер
