#---------- Black Ops II HUD | English
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=МОРСКИЕ КОТИКИ
BO2_MP_PLA_NAME=КСС
BO2_MP_FBI_NAME=ФБР
BO2_MP_PMC_NAME=Наемники
BO2_MP_ISA_NAME=ИСА
BO2_MP_CD_NAME=Ополчение

BO2_MPUI_SEALS_SHORT=Котики
BO2_MPUI_PLA_SHORT=КСС
BO2_MPUI_FBI_SHORT=ФБР
BO2_MPUI_PMC_SHORT=Наемники
BO2_MPUI_ISA_SHORT=ИСА
BO2_MPUI_CD_SHORT=Ополченцы

BO2_MPUI_SEALS_SHORT_CAPS=КОТИКИ
BO2_MPUI_PLA_SHORT_CAPS=КСС
BO2_MPUI_FBI_SHORT_CAPS=ФБР
BO2_MPUI_PMC_SHORT_CAPS=НАЕМНИКИ
BO2_MPUI_ISA_SHORT_CAPS=ИСА
BO2_MPUI_CD_SHORT_CAPS=ОПОЛЧЕНИЕ

# Splashes
BO2_MEDAL_FIRST_KILL=ПЕРВАЯ КРОВЬ
BO2_MEDAL_ASSISTED_SUICIDE=ЭВТАНАЗИЯ
BO2_MEDAL_HEADSHOT=В ГОЛОВУ
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=ВОЗВРАЩЕНИЕ
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=ЗАГРОБНАЯ ЖИЗНЬ
BO2_MEDAL_LONGSHOT_KILL=ОРЛИНЫЙ ГЛАЗ
BO2_MEDAL_REVENGE_KILL=МЕСТЬ
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=ВЫЖИВШИЙ
BO2_MEDAL_KILL_ENEMY_IN_AIR=В ВОЗДУХЕ
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=1 ВЫСТРЕЛ, 1 ТРУП
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=ЧЕТЫРЕ СТРОКИ
BO2_MEDAL_KILLSTREAK_5=КРОВОЖАДНЫЙ
BO2_MEDAL_KILLSTREAK_10=БЕЗЖАЛОСТНЫЙ
BO2_MEDAL_KILLSTREAK_15=НЕПРЕКЛОННЫЙ
BO2_MEDAL_KILLSTREAK_20=НЕОТСТУПНЫЙ
BO2_MEDAL_KILLSTREAK_25=БЕЗЖАЛОСТНЫЙ
BO2_MEDAL_KILLSTREAK_30=ЯДЕРНЫЙ
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=НЕУДЕРЖИМЫЙ
BO2_MEDAL_MULTIKILL_2=ДВОЙНОЕ УБИЙСТВО
BO2_MEDAL_MULTIKILL_3=ТРОЙНОЕ УБИЙСТВО
BO2_MEDAL_MULTIKILL_4=ЯРОСТНОЕ УБИЙСТВО
BO2_MEDAL_MULTIKILL_5=БЕЗУМНОЕ УБИЙСТВО
BO2_MEDAL_MULTIKILL_6=СУПЕР-УБИЙСТВО
BO2_MEDAL_MULTIKILL_7=МЕГА-УБИЙСТВО
BO2_MEDAL_MULTIKILL_8=УЛЬТРА-УБИЙСТВО
BO2_MEDAL_MULTIKILL_MORE_THAN_8=СЕРИЯ УБИЙСТВ
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=МСТИТЕЛЬ
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=СПАСИТЕЛЬ

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s ОЧКОВ ДО ПОБЕДЫ
