#---------- CoD4 HUD | Русский | Russian
# Translator: Original Game

# Factions
CoD4_MPUI_MARINES=Рекогносцировка ВМС
CoD4_MPUI_SPETSNAZ=Спецназ
CoD4_MPUI_OPFOR=Сепаратисты
CoD4_MPUI_SAS=S.A.S.

CoD4_MPUI_MARINES_SHORT=Морская пехота
CoD4_MPUI_SPETSNAZ_SHORT=Спецназ
CoD4_MPUI_OPFOR_SHORT=Сепаратисты
CoD4_MPUI_SAS_SHORT=S.A.S.

# Challenges
CoD4_MP_CHALLENGE_COMPLETED=Испытание выполнено!