#---------- CoD HUD System Notifications | Русский | Russian
# Translator: Machine translated

CoDHUD.System.ResetTime=Таймер раунда был сброшен до %s.
CoDHUD.System.ResetTime.Off=Таймер раунда был удалён.

CoDHUD.System.RestrictType=Игра была изменена на %s.
CoDHUD.System.RestrictType.NotNow=Сейчас нельзя изменить игру.

CoDHUD.System.Faction.NotNow=Сейчас нельзя изменить фракцию.
CoDHUD.System.Faction.Denied=Нельзя изменить фракцию.

CoDHUD.System.ChallengeReset=Все испытания были сброшены.
CoDHUD.System.RankReset=Ранг и статистика HUD '%s' были сброшены.

CoDHUD.System.CVChanged=Серверная переменная '%s' была изменена на %s.

CoDHUD.System.ForceEndRound.NotNow=Сейчас нельзя принудительно завершить раунд.
CoDHUD.System.ForceEndRound.NotStarting=Нельзя принудительно завершить раунд, который сейчас запускается.