#---------- Black Ops HUD | Русский | Russian
# Translator: Original Game

# Factions
BO1_MP_TROPAS_NAME=КУБИНЦЫ
BO1_MP_NVA_NAME=Вьетнамцы
BO1_MP_RUSSIAN_NAME=СПЕЦНАЗ
BO1_MP_SPECOPS_NAME=BLACK OPS
BO1_MP_MARINE_NAME=Морпехи
BO1_MP_REBELS_NAME=СИЛЫ СОПРОТИВЛЕНИЯ

BO1_MPUI_TROPAS_SHORT=Кубинцы
BO1_MPUI_NVA_SHORT=Вьетнамцы
BO1_MPUI_RUSSIAN_SHORT=Спецназ
BO1_MPUI_SPECOPS_SHORT=Black Ops
BO1_MPUI_MARINE_SHORT=Морпехи
BO1_MPUI_REBELS_SHORT=Сопротивление

BO1_MPUI_TROPAS_SHORT_CAPS=КУБИНЦЫ
BO1_MPUI_NVA_SHORT_CAPS=ВЬЕТНАМЦЫ
BO1_MPUI_RUSSIAN_SHORT_CAPS=СПЕЦНАЗ
BO1_MPUI_SPECOPS_SHORT_CAPS=BLACK OPS
BO1_MPUI_MARINE_SHORT_CAPS=МОРПЕХИ
BO1_MPUI_REBELS_SHORT_CAPS=СИЛЫ СОПРОТИВЛЕНИЯ

# Splashes
BO1_MEDAL_BUZZ_KILL=Никаких серий!
BO1_MEDAL_BUZZ_KILL_DESC=Не дать противнику завершить почти законченную серию убийств.
BO1_MEDAL_LONG_SHOT=Орлиный глаз
BO1_MEDAL_LONG_SHOT_DESC=Убить противника на большом расстоянии.
BO1_MEDAL_HEAD_SHOT=Попадание в голову
BO1_MEDAL_HEAD_SHOT_DESC=Бах - и в голову!
BO1_MEDAL_STUCK_TO_PLAYER=Горчичник
BO1_MEDAL_STUCK_TO_PLAYER_DESC=Прилепить к противнику заряд взрывчатки.
BO1_MEDAL_BULLS_EYE=Настоящий индеец
BO1_MEDAL_BULLS_EYE_DESC=Убить противника томагавком.
BO1_MEDAL_EXECUTION=Контрольный выстрел
BO1_MEDAL_EXECUTION_DESC=Убить тяжелораненого противника выстрелом в голову.
BO1_MEDAL_COMEBACK=Возвращение
BO1_MEDAL_COMEBACK_DESC=Прервать серию смертей.
BO1_MEDAL_AVENGER=Мститель
BO1_MEDAL_AVENGER_DESC=Убить противника, убившего вашего союзника.
BO1_MEDAL_AFTERLIFE=Жизнь после смерти
BO1_MEDAL_AFTERLIFE_DESC=Убить противника, будучи мертвым.
BO1_MEDAL_DOUBLE_KILL=Двойное убийство
BO1_MEDAL_DOUBLE_KILL_DESC=Убить 2 противников подряд.
BO1_MEDAL_TRIPLE_KILL=Тройное убийство
BO1_MEDAL_TRIPLE_KILL_DESC=Убить 3 противников подряд.
BO1_MEDAL_MULTI_KILL=Групповое убийство
BO1_MEDAL_MULTI_KILL_DESC=Убить более 3 противников подряд.
BO1_MEDAL_FIRST_BLOOD=Первая кровь
BO1_MEDAL_FIRST_BLOOD_DESC=Совершить первое убийство в игре.
BO1_MEDAL_BACK_STABBER=Удар в спину
BO1_MEDAL_BACK_STABBER_DESC=Ударить противника ножом в спину.
BO1_MEDAL_HIJACKER=Угонщик
BO1_MEDAL_HIJACKER_DESC=Похитить ящик снабжения противника.
BO1_MEDAL_SHARE_PACKAGE=Господь велел делиться
BO1_MEDAL_SHARE_PACKAGE_DESC=Союзник спас ваш ящик снабжения.
BO1_MEDAL_ONE_SHOT_KILL=Один выстрел - один труп
BO1_MEDAL_ONE_SHOT_KILL_DESC=Убить противника одним выстрелом.
BO1_MEDAL_PAYBACK=Месть
BO1_MEDAL_PAYBACK_DESC=Убить противника, убившего вас.
BO1_MEDAL_RESCUER=Спаситель
BO1_MEDAL_RESCUER_DESC=Спасти раненого союзника.
BO1_MEDAL_ASSISTED_SUICIDE=Выстрел милосердия
BO1_MEDAL_ASSISTED_SUICIDE_DESC=Ранить противника, убившего себя.
BO1_MEDAL_HEROIC=Воинский подвиг
BO1_MEDAL_HEROIC_DESC=Захватить контрольный пункт во время действия "Последнего шанса".
BO1_MEDAL_ASSISTS=Помощь
BO1_MEDAL_ASSISTS_DESC=Помочь в убийстве.
BO1_MEDAL_DESTROYER=Металлолом
BO1_MEDAL_DESTROYER_DESC=Уничтожить технику противника.
BO1_MEDAL_STREAKER=Серийный убийца
BO1_MEDAL_STREAKER_DESC=Получить награду за серию убийств.
BO1_MEDAL_HERO=Герой
BO1_MEDAL_HERO_DESC=Обезвредить бомбу.
BO1_MEDAL_ANTI_BOMBER=Контр-бомбист
BO1_MEDAL_ANTI_BOMBER_DESC=Убить противника, обезвреживающего бомбу.
BO1_MEDAL_OFFENSE=Нападение
BO1_MEDAL_OFFENSE_DESC=Убить противника рядом с ключевым объектом.
BO1_MEDAL_DEFENSE=Оборона
BO1_MEDAL_DEFENSE_DESC=Убить противника рядом с обороняемым объектом.
BO1_MEDAL_POSITION_SECURE=Объект под контролем
BO1_MEDAL_POSITION_SECURE_DESC=Захватить ключевой объект.
BO1_MEDAL_FLAG_RUNNER=Игрок с флагом
BO1_MEDAL_FLAG_RUNNER_DESC=Подобрать флаг противника.
BO1_MEDAL_FLAG_CAPTURE=Захват флага
BO1_MEDAL_FLAG_CAPTURE_DESC=Захватить флаг противника.
BO1_MEDAL_SABOTEUR=Диверсант
BO1_MEDAL_SABOTEUR_DESC=Заложить бомбу.
BO1_MEDAL_BOMBER=Бомбист
BO1_MEDAL_BOMBER_DESC=Взорвать бомбу.
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=Вы сбили перехватчик.
BO1_MEDAL_DESTROYER_UAV_DESC=Сбить самолет-разведчик.
BO1_MEDAL_DESTROYER_TURRET_DESC=Вывести из строя башню танка.
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=Сбитый вертолет.
BO1_MEDAL_FLAG_RETURN=Возвращение флага
BO1_MEDAL_FLAG_RETURN_DESC=Вернуть свой флаг.
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=По башне - огонь!
BO1_MEDAL_BALLISTIC_KNIFE_KILL=Укол
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=Убить противника выстрелом из стреляющего ножа.
BO1_MEDAL_BANK_SHOT=Индейская хитрость
BO1_MEDAL_BANK_SHOT_DESC=Убить противника томагавком, брошенным по искривленной траектории.
BO1_MEDAL_REVIVE=Врач
BO1_MEDAL_REVIVE_DESC=Реанимировать раненого союзника.
BO1_MEDAL_DESTROYER_M220_TOW=С небес на землю
BO1_MEDAL_DESTROYER_M220_TOW_DESC=Сбить "Валькирию".
BO1_MEDAL_DESTROYER_RCBOMB=Безумие на дороге
BO1_MEDAL_DESTROYER_RCBOMB_DESC=Уничтожить радиоуправляемую машинку.
BO1_MEDAL_AIRCRAFT_ASSIST=Зенитчик
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=Помочь сбить летательный аппарат противника.

# Round Starter
BO1_MP_MATCH_STARTING_IN=ДО НАЧАЛА БОЯ:

# Other
BO1_MENU_WINNING_CAPS=ПОБЕЖДАЕТ
BO1_MENU_LOSING_CAPS=ТЕРПИТ ПОРАЖЕНИЕ
BO1_MENU_TIED_CAPS=НИЧЬЯ

BO1_MENU_WINNING=Побеждает
BO1_MENU_TIED=Ничья
BO1_MENU_LOSING=Терпит поражение

# Scoreboard
BO1_CGAME_SB_KILLS=Уб.
BO1_CGAME_SB_ASSISTS=Помощь
BO1_CGAME_SB_KDRATIO=Эфф.
BO1_CGAME_SB_SCORE=Счет
BO1_CGAME_SB_DEATHS=См.
BO1_CGAME_SB_PING=Связь

# Gamemodes
BO1_OBJECTIVES_SD_ATTACKER_HINT=УНИЧТОЖЬТЕ ОБЪЕКТ А ИЛИ Б
BO1_OBJECTIVES_SD_DEFENDER_HINT=ЗАЩИЩАЙТЕ ОБЪЕКТЫ А И Б
BO1_OBJECTIVES_SAB_HINT=УНИЧТОЖЬТЕ ВРАЖЕСКИЙ ОБЪЕКТ
BO1_OBJECTIVES_DOM_HINT=ЗАХВАТЫВАЙТЕ ФЛАГИ И ЗАЩИЩАЙТЕ ИХ
BO1_OBJECTIVES_DM_HINT=УНИЧТОЖАЙТЕ ДРУГИХ ИГРОКОВ
BO1_OBJECTIVES_TDM_HINT=НЕЙТРАЛИЗУЙТЕ ИГРОКОВ ПРОТИВНИКА
BO1_OBJECTIVES_CTF_HINT=ЗАХВАТИТЕ ВРАЖЕСКИЙ ФЛАГ
BO1_OBJECTIVES_DEM_ATTACKER_HINT=УНИЧТОЖЬТЕ ОБЪЕКТЫ А И Б

# Notifications
BO1_RANK_PROMOTED_TO=Новый уровень: %s
BO1_RANK_PLAYER_WAS_PROMOTED=Игрок %s получил новое звание: %s!
  
# Ranks
BO1_RANK_PRVT_FULL=Рядовой
BO1_RANK_PRVT_FULL2=Рядовой I
BO1_RANK_PRVT_FULL3=Рядовой II
BO1_RANK_PRVT_FULL_N=Рядовой %s
BO1_RANK_PFC_FULL=Рядовой 1-го класса
BO1_RANK_PFC_FULL2=Рядовой 1-го класса I
BO1_RANK_PFC_FULL3=Рядовой 1-го класса II
BO1_RANK_PFC_FULL_N=Рядовой 1-го класса %s
BO1_RANK_SPC_FULL=Специалист
BO1_RANK_SPC_FULL2=Специалист I
BO1_RANK_SPC_FULL3=Специалист II
BO1_RANK_SPC_FULL_N=Специалист %s
BO1_RANK_CPL_FULL=Капрал
BO1_RANK_CPL_FULL2=Капрал I
BO1_RANK_CPL_FULL3=Капрал II
BO1_RANK_CPL_FULL_N=Капрал %s
BO1_RANK_SGT_FULL=Сержант
BO1_RANK_SGT_FULL2=Сержант I
BO1_RANK_SGT_FULL3=Сержант II
BO1_RANK_SGT_FULL_N=Сержант %s
BO1_RANK_SSGT_FULL=Штаб-сержант
BO1_RANK_SSGT_FULL2=Штаб-сержант I
BO1_RANK_SSGT_FULL3=Штаб-сержант II
BO1_RANK_SSGT_FULL_N=Штаб-сержант %s
BO1_RANK_SFC_FULL=Сержант 1-го класса
BO1_RANK_SFC_FULL2=Сержант 1-го класса I
BO1_RANK_SFC_FULL3=Сержант 1-го класса II
BO1_RANK_SFC_FULL_N=Сержант 1-го класса %s
BO1_RANK_SGTM_FULL=Сержант-майор
BO1_RANK_SGTM_FULL2=Сержант-майор I
BO1_RANK_SGTM_FULL3=Сержант-майор II
BO1_RANK_SGTM_FULL_N=Сержант-майор %s
BO1_RANK_LT_FULL=Лейтенант
BO1_RANK_LT_FULL2=Лейтенант I
BO1_RANK_LT_FULL3=Лейтенант II
BO1_RANK_LT_FULL_N=Лейтенант %s
BO1_RANK_CPT_FULL=Капитан
BO1_RANK_CPT_FULL2=Капитан I
BO1_RANK_CPT_FULL3=Капитан II
BO1_RANK_CPT_FULL_N=Капитан %s
BO1_RANK_MAJ_FULL=Майор
BO1_RANK_MAJ_FULL2=Майор I
BO1_RANK_MAJ_FULL3=Майор II
BO1_RANK_MAJ_FULL_N=Майор %s
BO1_RANK_LTCOL_FULL=Подполковник
BO1_RANK_LTCOL_FULL2=Подполковник I
BO1_RANK_LTCOL_FULL3=Подполковник II
BO1_RANK_LTCOL_FULL_N=Подполковник %s
BO1_RANK_COL_FULL=Полковник
BO1_RANK_COL_FULL2=Полковник I
BO1_RANK_COL_FULL3=Полковник II
BO1_RANK_COL_FULL_N=Полковник %s
BO1_RANK_BRIGGEN_FULL=Бригадный генерал
BO1_RANK_BRIGGEN_FULL2=Бригадный генерал I
BO1_RANK_BRIGGEN_FULL3=Бригадный генерал II
BO1_RANK_BRIGGEN_FULL_N=Бригадный генерал %s
BO1_RANK_MAJGEN_FULL=Генерал-майор
BO1_RANK_MAJGEN_FULL2=Генерал-майор I
BO1_RANK_MAJGEN_FULL3=Генерал-майор II
BO1_RANK_MAJGEN_FULL_N=Генерал-майор %s
BO1_RANK_LTGEN_FULL=Генерал-лейтенант
BO1_RANK_LTGEN_FULL2=Генерал-лейтенант I
BO1_RANK_LTGEN_FULL3=Генерал-лейтенант II
BO1_RANK_LTGEN_FULL_N=Генерал-лейтенант %s
BO1_RANK_GEN_FULL=Общие
BO1_RANK_COM_FULL=Коммандер
