#---------- CoD4 HUD | English
# Translator: Original Game

# Factions
CoD4_MPUI_MARINES=Marine Force Recon
CoD4_MPUI_SPETSNAZ=Spetsnaz
CoD4_MPUI_OPFOR=OpFor
CoD4_MPUI_SAS=S.A.S.

CoD4_MPUI_MARINES_SHORT=Marines
CoD4_MPUI_SPETSNAZ_SHORT=Spetsnaz
CoD4_MPUI_OPFOR_SHORT=OpFor
CoD4_MPUI_SAS_SHORT=S.A.S.