#---------- Black Ops HUD | English
# Translator: Original Game

# Factions
BO1_MP_TROPAS_NAME=TROPAS
BO1_MP_NVA_NAME=NVA
BO1_MP_RUSSIAN_NAME=SPETSNAZ
BO1_MP_SPECOPS_NAME=BLACK OPS
BO1_MP_MARINE_NAME=SOG
BO1_MP_REBELS_NAME=OP 40

BO1_MPUI_TROPAS_SHORT=Tropas
BO1_MPUI_NVA_SHORT=NVA
BO1_MPUI_RUSSIAN_SHORT=Spetsnaz
BO1_MPUI_SPECOPS_SHORT=Black Ops
BO1_MPUI_MARINE_SHORT=SOG
BO1_MPUI_REBELS_SHORT=Op 40

BO1_MPUI_TROPAS_SHORT_CAPS=TROPAS
BO1_MPUI_NVA_SHORT_CAPS=NVA
BO1_MPUI_RUSSIAN_SHORT_CAPS=SPETSNAZ
BO1_MPUI_SPECOPS_SHORT_CAPS=BLACK OPS
BO1_MPUI_MARINE_SHORT_CAPS=SOG
BO1_MPUI_REBELS_SHORT_CAPS=OP 40

# Splashes
BO1_MEDAL_BUZZ_KILL=Buzz Kill
BO1_MEDAL_BUZZ_KILL_DESC=Stopped enemy short of a killstreak.
BO1_MEDAL_LONG_SHOT=LongshotF
BO1_MEDAL_LONG_SHOT_DESC=Killed an enemy from a distance.
BO1_MEDAL_HEAD_SHOT=Headshot
BO1_MEDAL_HEAD_SHOT_DESC=Boom, headshot.
BO1_MEDAL_STUCK_TO_PLAYER=Stuck
BO1_MEDAL_STUCK_TO_PLAYER_DESC=Stuck an explosive to an enemy.
BO1_MEDAL_BULLS_EYE=Scalper
BO1_MEDAL_BULLS_EYE_DESC=Killed an enemy with a Tomahawk.
BO1_MEDAL_EXECUTION=Execution
BO1_MEDAL_EXECUTION_DESC=Killed a downed enemy with a headshot.
BO1_MEDAL_COMEBACK=Comeback
BO1_MEDAL_COMEBACK_DESC=Recovered from a death streak.
BO1_MEDAL_AVENGER=Avenger
BO1_MEDAL_AVENGER_DESC=Killed an enemy who recently killed a teammate.
BO1_MEDAL_AFTERLIFE=Afterlife
BO1_MEDAL_AFTERLIFE_DESC=Killed an enemy while dead.
BO1_MEDAL_DOUBLE_KILL=Double Kill
BO1_MEDAL_DOUBLE_KILL_DESC=Killed 2 people in rapid succession.
BO1_MEDAL_TRIPLE_KILL=Triple Kill
BO1_MEDAL_TRIPLE_KILL_DESC=Killed 3 people in rapid succession.
BO1_MEDAL_MULTI_KILL=Multi Kill
BO1_MEDAL_MULTI_KILL_DESC=Killed more than 3 in rapid succession.
BO1_MEDAL_FIRST_BLOOD=First Blood
BO1_MEDAL_FIRST_BLOOD_DESC=Got the first kill.
BO1_MEDAL_BACK_STABBER=Backstabber
BO1_MEDAL_BACK_STABBER_DESC=Knifed a player in the back.
BO1_MEDAL_HIJACKER=Hijacker
BO1_MEDAL_HIJACKER_DESC=Stole an enemy crate.
BO1_MEDAL_SHARE_PACKAGE=Share Package
BO1_MEDAL_SHARE_PACKAGE_DESC=A teammate saved your crate.
BO1_MEDAL_ONE_SHOT_KILL=One Shot, One Kill
BO1_MEDAL_ONE_SHOT_KILL_DESC=Killed an enemy with one shot.
BO1_MEDAL_PAYBACK=Payback
BO1_MEDAL_PAYBACK_DESC=Killed the enemy who killed you.
BO1_MEDAL_RESCUER=Rescuer
BO1_MEDAL_RESCUER_DESC=Saved a wounded teammate.
BO1_MEDAL_ASSISTED_SUICIDE=Assisted Suicide
BO1_MEDAL_ASSISTED_SUICIDE_DESC=Injured an enemy who killed himself.
BO1_MEDAL_HEROIC=Above and Beyond
BO1_MEDAL_HEROIC_DESC=Captured a point while in Second Chance.
BO1_MEDAL_ASSISTS=Assist
BO1_MEDAL_ASSISTS_DESC=Assisted in a kill.
BO1_MEDAL_DESTROYER=Scrapped
BO1_MEDAL_DESTROYER_DESC=Destroyed an enemy vehicle.
BO1_MEDAL_STREAKER=Streaker
BO1_MEDAL_STREAKER_DESC=Called in a Killstreak.
BO1_MEDAL_HERO=Hero
BO1_MEDAL_HERO_DESC=Defused the bomb.
BO1_MEDAL_ANTI_BOMBER=Anti-Bomber
BO1_MEDAL_ANTI_BOMBER_DESC=Killed an enemy that was defusing.
BO1_MEDAL_OFFENSE=Offense
BO1_MEDAL_OFFENSE_DESC=Killed an enemy near the objective.
BO1_MEDAL_DEFENSE=Defense
BO1_MEDAL_DEFENSE_DESC=Killed an enemy near the defense point.
BO1_MEDAL_POSITION_SECURE=Position Secure
BO1_MEDAL_POSITION_SECURE_DESC=Took an objective.
BO1_MEDAL_FLAG_RUNNER=Flag Runner
BO1_MEDAL_FLAG_RUNNER_DESC=Picked up the enemy flag.
BO1_MEDAL_FLAG_CAPTURE=Flag Capture
BO1_MEDAL_FLAG_CAPTURE_DESC=Captured the enemy flag.
BO1_MEDAL_SABOTEUR=Saboteur
BO1_MEDAL_SABOTEUR_DESC=Planted the bomb.
BO1_MEDAL_BOMBER=Bomber
BO1_MEDAL_BOMBER_DESC=Detonated the bomb.
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=Brought down a Counter-Spy Plane.
BO1_MEDAL_DESTROYER_UAV_DESC=Brought down a Spy Plane.
BO1_MEDAL_DESTROYER_TURRET_DESC=Took out a turret.
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=Brought down a helicopter.
BO1_MEDAL_FLAG_RETURN=Flag Return
BO1_MEDAL_FLAG_RETURN_DESC=Returned the flag.
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=Turret Kill
BO1_MEDAL_BALLISTIC_KNIFE_KILL=Skewer
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=Shot and killed an enemy with the Ballistic Knife.
BO1_MEDAL_BANK_SHOT=Bank Shot
BO1_MEDAL_BANK_SHOT_DESC=Killed enemy with a banked Tomahawk.
BO1_MEDAL_REVIVE=Medic
BO1_MEDAL_REVIVE_DESC=Revived a downed teammate.
BO1_MEDAL_DESTROYER_M220_TOW=Off The Air
BO1_MEDAL_DESTROYER_M220_TOW_DESC=Took out a Valkyrie.
BO1_MEDAL_DESTROYER_RCBOMB=Road Rage
BO1_MEDAL_DESTROYER_RCBOMB_DESC=Took out an RC-XD.
BO1_MEDAL_AIRCRAFT_ASSIST=Scrap Assist
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=Assisted in a taking down an enemy Aircraft.

# Round Starter
BO1_MP_MATCH_STARTING_IN=MATCH BEGINS IN

# Gamemodes
BO1_OBJECTIVES_SD_ATTACKER_HINT=DESTROY TARGET A OR B
BO1_OBJECTIVES_SD_DEFENDER_HINT=PROTECT TARGETS A AND B
BO1_OBJECTIVES_SAB_HINT=DESTROY THE ENEMY TARGET
BO1_OBJECTIVES_DOM_HINT=CAPTURE THE FLAGS AND DEFEND THEM
BO1_OBJECTIVES_DM_HINT=ELIMINATE OTHER PLAYERS
BO1_OBJECTIVES_TDM_HINT=ELIMINATE ENEMY PLAYERS
BO1_OBJECTIVES_CTF_HINT=CAPTURE THE ENEMY FLAG
BO1_OBJECTIVES_DEM_ATTACKER_HINT=DESTROY TARGETS A AND B