#---------- Black Ops II HUD | English
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEALS
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercs
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Militia

BO2_MPUI_SEALS_SHORT=SEALS
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercs
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Militia

BO2_MPUI_SEALS_SHORT_CAPS=SEALS
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCS
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILITIA

# Splashes
BO2_MEDAL_FIRST_KILL=First Blood
BO2_MEDAL_ASSISTED_SUICIDE=Assisted Suicide
BO2_MEDAL_HEADSHOT=Headshot
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=Comeback
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=Afterlife
BO2_MEDAL_LONGSHOT_KILL=Long Shot
BO2_MEDAL_REVENGE_KILL=Revenge
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=Survivor
BO2_MEDAL_KILL_ENEMY_IN_AIR=Airshot
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=One Shot, One Kill
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=Quad Feed
BO2_MEDAL_KILLSTREAK_5=Bloodthirsty
BO2_MEDAL_KILLSTREAK_10=Merciless
BO2_MEDAL_KILLSTREAK_15=Ruthless
BO2_MEDAL_KILLSTREAK_20=Relentless
BO2_MEDAL_KILLSTREAK_25=Brutal
BO2_MEDAL_KILLSTREAK_30=Nuclear
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=Unstoppable
BO2_MEDAL_MULTIKILL_2=Double Kill
BO2_MEDAL_MULTIKILL_3=Triple Kill
BO2_MEDAL_MULTIKILL_4=Fury Kill
BO2_MEDAL_MULTIKILL_5=Frenzy Kill
BO2_MEDAL_MULTIKILL_6=Super Kill
BO2_MEDAL_MULTIKILL_7=Mega Kill
BO2_MEDAL_MULTIKILL_8=Ultra Kill
BO2_MEDAL_MULTIKILL_MORE_THAN_8=Kill Chain
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=Avenger
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=Savior
BO2_MEDAL_KILL_ENEMY_SHOOTING_TEAMSHIELD=Tango Down