#---------- CoD HUD System Notifications | English
# Translator: Moka

CoDHUD.System.ResetTime=Round timer reset to %s.
CoDHUD.System.ResetTime.Off=Round timer removed.

CoDHUD.System.RestrictType=Game was changed to %s.
CoDHUD.System.RestrictType.NotNow=Cannot change game right now.

CoDHUD.System.Faction.NotNow=Cannot change factions right now.
CoDHUD.System.Faction.Denied=Cannot change factions.

CoDHUD.System.ChallengeReset=All challenges were reset.
CoDHUD.System.RankReset=%s ranks and stats were reset.

CoDHUD.System.CVChanged=Server variable '%s' changed to %s.

CoDHUD.System.ForceEndRound.NotNow=Cannot forcefully end the round right now.
CoDHUD.System.ForceEndRound.NotStarting=Cannot forcefully end a round that is currently starting.