#---------- Black Ops Ranks | Italiano | Italian
# Translator: Original Game

# Notifications
BO1_RANK_PROMOTED_TO=Promosso al livello %s!
BO1_RANK_PLAYER_WAS_PROMOTED=%s è stato promosso a %s!
  
# Ranks
BO1_RANK_PRVT_FULL=Soldato
BO1_RANK_PRVT_FULL2=Soldato I
BO1_RANK_PRVT_FULL3=Soldato II
BO1_RANK_PRVT_FULL_N=Soldato %s
BO1_RANK_PFC_FULL=Soldato scelto
BO1_RANK_PFC_FULL2=Soldato scelto I
BO1_RANK_PFC_FULL3=Soldato scelto II
BO1_RANK_PFC_FULL_N=Soldato scelto %s
BO1_RANK_SPC_FULL=Specialista
BO1_RANK_SPC_FULL2=Specialista I
BO1_RANK_SPC_FULL3=Specialista II
BO1_RANK_SPC_FULL_N=Specialista %s
BO1_RANK_CPL_FULL=Caporale
BO1_RANK_CPL_FULL2=Caporale I
BO1_RANK_CPL_FULL3=Caporale II
BO1_RANK_CPL_FULL_N=Caporale %s
BO1_RANK_SGT_FULL=Sergente
BO1_RANK_SGT_FULL2=Sergente I
BO1_RANK_SGT_FULL3=Sergente II
BO1_RANK_SGT_FULL_N=Sergente %s
BO1_RANK_SSGT_FULL=Caporale maggiore
BO1_RANK_SSGT_FULL2=Caporale magg. capo I
BO1_RANK_SSGT_FULL3=Caporale magg. capo I
BO1_RANK_SSGT_FULL_N=Caporale magg. capo %s
BO1_RANK_SFC_FULL=Sergente di prima classe
BO1_RANK_SFC_FULL2=Sergente di prima classe I
BO1_RANK_SFC_FULL3=Sergente di prima classe II
BO1_RANK_SFC_FULL_N=Sergente di prima classe %s
BO1_RANK_SGTM_FULL=Maresciallo
BO1_RANK_SGTM_FULL2=Maresciallo I
BO1_RANK_SGTM_FULL3=Maresciallo II
BO1_RANK_SGTM_FULL_N=Maresciallo %s
BO1_RANK_LT_FULL=Tenente
BO1_RANK_LT_FULL2=Tenente I
BO1_RANK_LT_FULL3=Tenente II
BO1_RANK_LT_FULL_N=Tenente %s
BO1_RANK_CPT_FULL=Capitano
BO1_RANK_CPT_FULL2=Capitano I
BO1_RANK_CPT_FULL3=Capitano II
BO1_RANK_CPT_FULL_N=Capitano %s
BO1_RANK_MAJ_FULL=Maggiore
BO1_RANK_MAJ_FULL2=Maggiore I
BO1_RANK_MAJ_FULL3=Maggiore II
BO1_RANK_MAJ_FULL_N=Maggiore %s
BO1_RANK_LTCOL_FULL=Tenente colonnello
BO1_RANK_LTCOL_FULL2=Tenente colonnello I
BO1_RANK_LTCOL_FULL3=Tenente colonnello II
BO1_RANK_LTCOL_FULL_N=Tenente colonnello %s
BO1_RANK_COL_FULL=Colonnello
BO1_RANK_COL_FULL2=Colonnello I
BO1_RANK_COL_FULL3=Colonnello II
BO1_RANK_COL_FULL_N=Colonnello %s
BO1_RANK_BRIGGEN_FULL=Generale di brigata
BO1_RANK_BRIGGEN_FULL2=Generale di brigata I
BO1_RANK_BRIGGEN_FULL3=Generale di brigata II
BO1_RANK_BRIGGEN_FULL_N=Generale di brigata %s
BO1_RANK_MAJGEN_FULL=Generale di divisione
BO1_RANK_MAJGEN_FULL2=Generale di divisione I
BO1_RANK_MAJGEN_FULL3=Generale di divisione II
BO1_RANK_MAJGEN_FULL_N=Generale di divisione %s
BO1_RANK_LTGEN_FULL=Gen. di corpo d'armata
BO1_RANK_LTGEN_FULL2=Gen. di corpo d'armata I
BO1_RANK_LTGEN_FULL3=Gen. di corpo d'armata II
BO1_RANK_LTGEN_FULL_N=Gen. di corpo d'armata %s
BO1_RANK_GEN_FULL=Generale
BO1_RANK_COM_FULL=Comandante
