#---------- Black Ops II HUD | Italiano | Italian
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEAL
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercenari
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Milizia

BO2_MPUI_SEALS_SHORT=SEAL
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercenari
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Milizia

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCENARI
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILIZIA

# Splashes
BO2_MEDAL_FIRST_KILL=Primo sangue
BO2_MEDAL_ASSISTED_SUICIDE=Suicidio assistito
BO2_MEDAL_HEADSHOT=Colpo alla testa
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=Ritorno
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=Aldilà
BO2_MEDAL_LONGSHOT_KILL=Colpo a distanza
BO2_MEDAL_REVENGE_KILL=Vendetta
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=Sopravvissuto
BO2_MEDAL_KILL_ENEMY_IN_AIR=Colpo volante
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=Un colpo, un morto
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=Uccisione quadrupla
BO2_MEDAL_KILLSTREAK_5=Sanguinario
BO2_MEDAL_KILLSTREAK_10=Senza pietà
BO2_MEDAL_KILLSTREAK_15=Senz'anima
BO2_MEDAL_KILLSTREAK_20=Instancabile
BO2_MEDAL_KILLSTREAK_25=Brutale
BO2_MEDAL_KILLSTREAK_30=Nucleare
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=Inarrestabile
BO2_MEDAL_MULTIKILL_2=Doppia uccisione
BO2_MEDAL_MULTIKILL_3=Uccisione tripla
BO2_MEDAL_MULTIKILL_4=Uccisione furiosa
BO2_MEDAL_MULTIKILL_5=Uccisione furiosa
BO2_MEDAL_MULTIKILL_6=Super uccisione
BO2_MEDAL_MULTIKILL_7=Mega uccisione
BO2_MEDAL_MULTIKILL_8=Ultra uccisione
BO2_MEDAL_MULTIKILL_MORE_THAN_8=Uccisione a catena
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=Vendicatore
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=Salvatore

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s PUNTI PER VINCERE

# Notifications
BO2_RANK_PROMOTED=Sei stato promosso!
BO2_RANK_PLAYER_WAS_PROMOTED=%s è stato promosso a %s!

# Ranks
BO2_RANK_PRVT_FULL=Soldato
BO2_RANK_PRVT_FULL2=Soldato II
BO2_RANK_PRVT_FULL3=Soldato III
BO2_RANK_PFC_FULL=Soldato scelto
BO2_RANK_PFC_FULL2=Soldato scelto II
BO2_RANK_PFC_FULL3=Soldato scelto III
BO2_RANK_LCPL_FULL=Sottocaporale
BO2_RANK_LCPL_FULL2=Sottocaporale II
BO2_RANK_LCPL_FULL3=Sottocaporale III
BO2_RANK_CPL_FULL=Caporale
BO2_RANK_CPL_FULL2=Caporale II
BO2_RANK_CPL_FULL3=Caporale III
BO2_RANK_SGT_FULL=Sergente
BO2_RANK_SGT_FULL2=Sergente II
BO2_RANK_SGT_FULL3=Sergente III
BO2_RANK_SSGT_FULL=Caporale maggiore capo
BO2_RANK_SSGT_FULL2=Caporale maggiore capo II
BO2_RANK_SSGT_FULL3=Caporale maggiore capo III
BO2_RANK_GYSGT_FULL=Sergente artigliere
BO2_RANK_GYSGT_FULL2=Sergente artigliere II
BO2_RANK_GYSGT_FULL3=Sergente artigliere III
BO2_RANK_MSGT_FULL=Sergente maestro
BO2_RANK_MSGT_FULL2=Sergente maestro II
BO2_RANK_MSGT_FULL3=Sergente maestro III
BO2_RANK_MGYSGT_FULL=Sergente maggiore artigliere
BO2_RANK_MGYSGT_FULL2=Sergente maggiore artigliere II
BO2_RANK_MGYSGT_FULL3=Sergente maggiore artigliere III
BO2_RANK_2NDLT_FULL=Sottotenente
BO2_RANK_2NDLT_FULL2=Sottotenente II
BO2_RANK_2NDLT_FULL3=Sottotenente III
BO2_RANK_LT_FULL=Tenente
BO2_RANK_LT_FULL2=Tenente II
BO2_RANK_LT_FULL3=Tenente III
BO2_RANK_CPT_FULL=Capitano
BO2_RANK_CPT_FULL2=Capitano II
BO2_RANK_CPT_FULL3=Capitano III
BO2_RANK_MAJ_FULL=Maggiore
BO2_RANK_MAJ_FULL2=Maggiore II
BO2_RANK_MAJ_FULL3=Maggiore III
BO2_RANK_LTCOL_FULL=Tenente colonnello
BO2_RANK_LTCOL_FULL2=Tenente colonnello II
BO2_RANK_LTCOL_FULL3=Tenente colonnello III
BO2_RANK_COL_FULL=Colonnello
BO2_RANK_COL_FULL2=Colonnello II
BO2_RANK_COL_FULL3=Colonnello III
BO2_RANK_BGEN_FULL=Generale di brigata
BO2_RANK_BGEN_FULL2=Generale di brigata II
BO2_RANK_BGEN_FULL3=Generale di brigata III
BO2_RANK_MAJGEN_FULL=Generale di divisione
BO2_RANK_MAJGEN_FULL2=Generale di divisione II
BO2_RANK_MAJGEN_FULL3=Generale di divisione III
BO2_RANK_LTGEN_FULL=Generale di corpo d'armata
BO2_RANK_LTGEN_FULL2=Generale di corpo d'armata II
BO2_RANK_LTGEN_FULL3=Generale di corpo d'armata III
BO2_RANK_GEN_FULL=Generale
BO2_RANK_GEN_FULL2=Generale II
BO2_RANK_GEN_FULL3=Generale III
BO2_RANK_COM_FULL=Comandante
