#---------- Black Ops II HUD | Italiano | Italian
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEAL
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercenari
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Milizia

BO2_MPUI_SEALS_SHORT=SEAL
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercenari
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Milizia

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCENARI
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILIZIA

# Splashes
BO2_MEDAL_FIRST_KILL=Primo sangue
BO2_MEDAL_ASSISTED_SUICIDE=Suicidio assistito
BO2_MEDAL_HEADSHOT=Colpo alla testa
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=Ritorno
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=Aldilà
BO2_MEDAL_LONGSHOT_KILL=Colpo a distanza
BO2_MEDAL_REVENGE_KILL=Vendetta
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=Sopravvissuto
BO2_MEDAL_KILL_ENEMY_IN_AIR=Colpo volante
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=Un colpo, un morto
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=Uccisione quadrupla
BO2_MEDAL_KILLSTREAK_5=Sanguinario
BO2_MEDAL_KILLSTREAK_10=Senza pietà
BO2_MEDAL_KILLSTREAK_15=Senz'anima
BO2_MEDAL_KILLSTREAK_20=Instancabile
BO2_MEDAL_KILLSTREAK_25=Brutale
BO2_MEDAL_KILLSTREAK_30=Nucleare
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=Inarrestabile
BO2_MEDAL_MULTIKILL_2=Doppia uccisione
BO2_MEDAL_MULTIKILL_3=Uccisione tripla
BO2_MEDAL_MULTIKILL_4=Uccisione furiosa
BO2_MEDAL_MULTIKILL_5=Uccisione furiosa
BO2_MEDAL_MULTIKILL_6=Super uccisione
BO2_MEDAL_MULTIKILL_7=Mega uccisione
BO2_MEDAL_MULTIKILL_8=Ultra uccisione
BO2_MEDAL_MULTIKILL_MORE_THAN_8=Uccisione a catena
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=Vendicatore
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=Salvatore

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s PUNTI PER VINCERE
