#---------- CoD HUD System Notifications | Italiano | Italian
# Translator: Machine translated

CoDHUD.System.ResetTime=Timer del round reimpostato a %s.
CoDHUD.System.ResetTime.Off=Timer del round rimosso.

CoDHUD.System.RestrictType=Il gioco è stato cambiato in %s.
CoDHUD.System.RestrictType.NotNow=Impossibile cambiare gioco in questo momento.

CoDHUD.System.Faction.NotNow=Impossibile cambiare fazione in questo momento.
CoDHUD.System.Faction.Denied=Impossibile cambiare fazione.

CoDHUD.System.ChallengeReset=Tutte le sfide sono state reimpostate.
CoDHUD.System.RankReset=Il grado e le statistiche dell'HUD '%s' sono stati reimpostati.

CoDHUD.System.CVChanged=La variabile del server '%s' è stata cambiata in %s.

CoDHUD.System.ForceEndRound.NotNow=Impossibile terminare forzatamente il round in questo momento.
CoDHUD.System.ForceEndRound.NotStarting=Impossibile terminare forzatamente un round che sta iniziando.