#---------- Black Ops II HUD | English
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEAL
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercenari
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Milizia

BO2_MPUI_SEALS_SHORT=SEAL
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercenari
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Milizia

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCENARI
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILIZIA

# Splashes
BO2_MEDAL_FIRST_KILL=PRIMO SANGUE
BO2_MEDAL_ASSISTED_SUICIDE=SUICIDIO ASSISTITO
BO2_MEDAL_HEADSHOT=COLPO ALLA TESTA
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=RITORNO
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=ALDILÀ
BO2_MEDAL_LONGSHOT_KILL=COLPO A DISTANZA
BO2_MEDAL_REVENGE_KILL=VENDETTA
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=SOPRAVVISSUTO
BO2_MEDAL_KILL_ENEMY_IN_AIR=COLPO VOLANTE
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=UN COLPO, UN MORTO
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=UCCISIONE QUADRUPLA
BO2_MEDAL_KILLSTREAK_5=SANGUINARIO
BO2_MEDAL_KILLSTREAK_10=SENZA PIETÀ
BO2_MEDAL_KILLSTREAK_15=SENZ'ANIMA
BO2_MEDAL_KILLSTREAK_20=INSTANCABILE
BO2_MEDAL_KILLSTREAK_25=BRUTALE
BO2_MEDAL_KILLSTREAK_30=NUCLEARE
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=INARRESTABILE
BO2_MEDAL_MULTIKILL_2=DOPPIA UCCISIONE
BO2_MEDAL_MULTIKILL_3=UCCISIONE TRIPLA
BO2_MEDAL_MULTIKILL_4=UCCISIONE FURIOSA
BO2_MEDAL_MULTIKILL_5=UCCISIONE FURIOSA
BO2_MEDAL_MULTIKILL_6=SUPER UCCISIONE
BO2_MEDAL_MULTIKILL_7=MEGA UCCISIONE
BO2_MEDAL_MULTIKILL_8=ULTRA UCCISIONE
BO2_MEDAL_MULTIKILL_MORE_THAN_8=UCCISIONE A CATENA
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=VENDICATORE
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=SALVATORE

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s PUNTI PER VINCERE
