#---------- CoD HUD Settings | Italiano | Italian
# Translator: Machine translated

# ------------------[ GENERAL ]------------------
CoDHUD.Title=CoD HUD

CoDHUD.Client=Client
CoDHUD.Server=Server
CoDHUD.General=Generale

CoDHUD.Close=Chiudi

CoDHUD.Default=Predefinito: %s
CoDHUD.Current=Attuale: %s

# ------------------[ MENU GLYPHS ]------------------
CoDHUD.Glyph.Toggle=[+attack] Attiva/Disattiva
CoDHUD.Glyph.Open=[+attack] Apri
CoDHUD.Glyph.OpenMenu=[+attack] Apri menu
CoDHUD.Glyph.Select=[+attack] Seleziona
CoDHUD.Glyph.Confirm=[+attack] Conferma
CoDHUD.Glyph.Return=[+attack] Indietro
CoDHUD.Glyph.Close=[+attack] Chiudi
CoDHUD.Glyph.Tab=[+attack] Apri scheda
CoDHUD.Glyph.Reset=[+attack2] Ripristina

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.RoundStart=Controlli round

CoDHUD.RoundStart.Gamemode=Modalità di gioco
CoDHUD.RoundStart.Info=Scegli la modalità di gioco.

CoDHUD.RoundStart.Start=Avvia round
CoDHUD.RoundStart.Start.desc=Una volta selezionata una modalità di gioco e configurate le impostazioni a tuo piacimento, puoi avviare il processo di inizio round.

CoDHUD.RoundStart.Notice=Sei sicuro di voler iniziare un nuovo round?\nTutti i punteggi verranno azzerati e tutti i giocatori rinasceranno.
CoDHUD.RoundStart.Yes=Avvia round

CoDHUD.RoundStart.Timer=Timer di inizio round
CoDHUD.RoundStart.Timer.desc=Quanti secondi di intermezzo devono esserci prima che inizi il round.

CoDHUD.RoundStart.Autobalance=Randomizza fazioni all'inizio del round
CoDHUD.RoundStart.Autobalance.desc=Se attivato, tutti i giocatori verranno assegnati casualmente a una fazione valida all'inizio del round.

CoDHUD.Scorelimit=Limite punteggio
CoDHUD.Scorelimit.desc=Imposta il limite massimo di punteggio mostrato nel contatore.\n\nMisurato in uccisioni.

CoDHUD.Timelimit=Limite di tempo
CoDHUD.Timelimit.desc=Imposta il limite di tempo prima della fine automatica del round.\n\nMisurato in minuti.\n\nImposta a 0 per illimitato.

CoDHUD.Autobalance.Amount=Limite auto-bilanciamento squadre
CoDHUD.Autobalance.Amount.desc=Imposta il numero massimo di fazioni a cui i giocatori possono essere auto-bilanciati.

CoDHUD.Autobalance.Amount.disable=Disattivato
CoDHUD.Autobalance.Amount.2=2 squadre
CoDHUD.Autobalance.Amount.3=3 squadre
CoDHUD.Autobalance.Amount.4=4 squadre

CoDHUD.RoundStart.Auto=Avvia automaticamente il round all'avvio del server
CoDHUD.RoundStart.Auto.desc=Se attivato, un nuovo round inizierà immediatamente quando il primo giocatore entra nel server.

CoDHUD.Admin.ResetTime=Reset timer del round
CoDHUD.Admin.ResetTime.desc=Reimposta il timer del round corrente al valore del limite di tempo impostato.

CoDHUD.ForceEndRound=Forza fine round
CoDHUD.ForceEndRound.desc=Clicca qui se devi o vuoi terminare il round prima del raggiungimento del limite di punteggio o tempo.

CoDHUD.ForceEndRound.Notice=Sei sicuro di voler terminare forzatamente il round?

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen=Abilita "Fine partita"
CoDHUD.Admin.EndScreen.desc=Abilita un sistema di "fine partita" quando viene raggiunto il limite di punteggio.

CoDHUD.Admin.EndScreen.StartNext=Avvia nuova partita dopo la fine match
CoDHUD.Admin.EndScreen.StartNext.desc=Se attivato, una volta terminata la durata del fine partita, inizierà un nuovo round.\n\nSe disattivato, tutti i giocatori respawneranno normalmente.

CoDHUD.Admin.FriendlyFire=Abilita fuoco amico
CoDHUD.Admin.FriendlyFire.desc=Se attivato, i giocatori della stessa fazione possono danneggiarsi tra loro.\n\nSi applica solo nel Team Deathmatch.

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=Limita fazioni e tipo HUD
CoDHUD.Admin.RestrictType.Choose=Scegli gioco
CoDHUD.Admin.RestrictType.desc=Scegli a quale titolo CoD limitare gli utenti. Questo influisce sull'HUD e sulle fazioni disponibili.

CoDHUD.Admin.RestrictType.Warning=Attenzione!\nCambiare gioco avrà le seguenti conseguenze:\n- Tutte le fazioni dei giocatori verranno assegnate casualmente.\n- Tutti i punteggi dei giocatori verranno azzerati.\n- Tutti i giocatori verranno uccisi e rianimati.\n\nSei sicuro di voler cambiare gioco?

CoDHUD.Type.cod4=Modern Warfare 1
CoDHUD.Type.waw=World at War
CoDHUD.Type.mw2=Modern Warfare 2
CoDHUD.Type.bo1=Black Ops
CoDHUD.Type.mw3=Modern Warfare 3
CoDHUD.Type.bo2=Black Ops II
CoDHUD.Type.ghosts=Ghosts
CoDHUD.Type.aw=Advanced Warfare
CoDHUD.Type.bo3=Black Ops III
CoDHUD.Type.iw=Infinite Warfare
CoDHUD.Type.ww2=WWII

CoDHUD.Admin.RestrictFactionChance=Limita cambio fazione
CoDHUD.Admin.RestrictFactionChance.desc=Scegli quando i giocatori possono cambiare fazione.

CoDHUD.Admin.RestrictFactionChance.disable=Non può cambiare
CoDHUD.Admin.RestrictFactionChance.freely=Cambio libero
CoDHUD.Admin.RestrictFactionChance.pool=Solo dal gruppo attivo

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=Selezione fazione
CoDHUD.Faction.Select.desc=Scegli quale fazione rappresentare.\nInfluisce sul tuo stato amico/nemico e cambia il narratore e il tema in base alla fazione.

CoDHUD.Faction.ChangeWarning=Attenzione!\nCambiare squadra avrà le seguenti conseguenze:\n- Il tuo punteggio verrà azzerato a 0.\n- Verrai ucciso e rinascerai.\n\nSei sicuro di voler cambiare fazione?

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=Accesso rapido

CoDHUD.Quick.DisableHUD=Disattivazione rapida di tutte le opzioni HUD
CoDHUD.Quick.DisableHUD.desc=Disattiva tutte le opzioni del CoD HUD.

# ---------[ HUD-RELATED ]---------
CoDHUD.HUD=Impostazioni HUD

# Multiple
CoDHUD.HUD.Outline=Testo contornato
CoDHUD.HUD.Outline.desc=Attiva il testo contornato su alcuni elementi per renderli più leggibili in aree molto luminose.

CoDHUD.HUD.Sound=Riproduci SFX
CoDHUD.HUD.Sound.desc=Riproduce effetti sonori associati se supportati dal tipo di HUD.

CoDHUD.HUD.Time.Total=Tempo attivo
CoDHUD.HUD.Time.Total.desc=Quanto a lungo la variabile rimane sullo schermo dopo essere completamente apparsa prima di scomparire.

CoDHUD.HUD.Time.Fadein=Tempo di comparsa
CoDHUD.HUD.Time.Fadein.desc=Quanto tempo impiega questa variabile ad apparire.

CoDHUD.HUD.Time.Fadeout=Tempo di scomparsa
CoDHUD.HUD.Time.Fadeout.desc=Quanto tempo impiega questa variabile a scomparire.

# Scale
CoDHUD.HUD.Scale=Scala UI

CoDHUD.HUD.Scale.Enable=Moltiplicatore scala UI
CoDHUD.HUD.Scale.Enable.desc=Regola la scala degli elementi UI usati dal CoD HUD.\n\nUtile per risoluzioni basse o ultrawide.\n\n<color=255,255,100>Nota</color>: ricaricherà il menu quando applicato.\n\n<color=255,100,100>AVVERTENZA</color>: alcuni elementi potrebbero risultare fortemente disallineati se il valore è troppo alto o troppo basso.

# Scoreboard
CoDHUD.HUD.Scoreboard=Classifica

CoDHUD.HUD.Scoreboard.Enable=Abilita classifica
CoDHUD.HUD.Scoreboard.Enable.desc=Abilita la classifica. Mostra le fazioni attualmente occupate da tutti i giocatori.

# Score Counter
CoDHUD.HUD.Scorecounter=Contatore punteggio

CoDHUD.HUD.Scorecounter.Enable=Abilita contatore punteggio
CoDHUD.HUD.Scorecounter.Enable.desc=Abilita un timer del server, un'icona di fazione e i contatori di punteggio.\n\nAlcuni tipi di HUD non mostreranno l'icona di fazione.

# Medals
CoDHUD.HUD.Medals=Medaglie

CoDHUD.HUD.Medals.Enable=Abilita medaglie
CoDHUD.HUD.Medals.Enable.desc=Abilita le medaglie, ottenute eseguendo azioni come uccisioni rapide o colpi alla testa.\n\nNota: alcuni tipi di HUD hanno solo testo, altri testo e icone.

CoDHUD.HUD.Medals.Speedup=Più veloce se coda lunga
CoDHUD.HUD.Medals.Speedup.desc=Velocizza la coda delle medaglie se ce ne sono molte in attesa.\n\nA seconda del tipo di HUD, disabilita anche gli SFX se ci sono più di 3 medaglie in coda.

# Kill Feed
CoDHUD.HUD.Killfeed=Feed uccisioni

CoDHUD.HUD.Killfeed.Enable=Abilita feed uccisioni
CoDHUD.HUD.Killfeed.Enable.desc=Abilita il feed uccisioni.

# Minimap
CoDHUD.HUD.Minimap=Minimappa

CoDHUD.HUD.Minimap.Enable=Abilita minimappa
CoDHUD.HUD.Minimap.Enable.desc=Abilita la minimappa.

# Hitmarker
CoDHUD.HUD.Hitmarker=Indicatore colpo

CoDHUD.HUD.Hitmarker.Enable=Abilita indicatore colpo
CoDHUD.HUD.Hitmarker.Enable.desc=Abilita l'indicatore colpo e il suono associato.

# Weapon Info
CoDHUD.HUD.WeaponInfo=Info arma

CoDHUD.HUD.WeaponInfo.Enable=Abilita info arma
CoDHUD.HUD.WeaponInfo.Enable.desc=Abilita la scheda info arma con nome arma e munizioni.\n\nAlcuni HUD includono anche la bussola qui.

CoDHUD.HUD.WeaponPrompts.Enable=Abilita promemoria arma
CoDHUD.HUD.WeaponPrompts.Enable.desc=Abilita i promemoria dell'arma, come le notifiche di munizioni basse.

# XP Counter
CoDHUD.HUD.XP=Notifica XP

CoDHUD.HUD.XP.Enable=Abilita notifica XP
CoDHUD.HUD.XP.Enable.desc=Abilita le notifiche XP.

# Target ID / IFF
CoDHUD.HUD.IFF=Identifica amico o nemico

CoDHUD.HUD.IFF.Enable=Abilita IFF
CoDHUD.HUD.IFF.Enable.desc=Abilita un sistema "Identifica amico o nemico", mostrando il nome del bersaglio sopra la testa quando lo si mira.

# Death Icon
CoDHUD.HUD.DeathIcon=Icona morte

CoDHUD.HUD.DeathIcon.Enable=Abilita icona morte
CoDHUD.HUD.DeathIcon.Enable.desc=Abilita l'icona morte mostrata quando un giocatore della stessa fazione muore.

# Chat
CoDHUD.HUD.Chat=Chat

CoDHUD.HUD.Chat.Enable=Abilita chat
CoDHUD.HUD.Chat.Enable.desc=Abilita la chat.

# Headers
CoDHUD.HUD.Headers=Intestazioni

CoDHUD.HUD.Headers.Enable=Abilita notifiche intestazione
CoDHUD.HUD.Headers.Enable.desc=Abilita notifiche di intestazione, come completamento sfide o avanzamento di livello.

# Subtitles
CoDHUD.HUD.Subtitles=Sottotitoli

CoDHUD.HUD.Subtitles.Enable=Abilita sottotitoli
CoDHUD.HUD.Subtitles.Enable.desc=Abilita i sottotitoli quando viene riprodotta una linea vocale del commentatore.\n\nOttimizzato solo per l'inglese. Il supporto per altre lingue può variare.

CoDHUD.HUD.Subtitles.Callsign=Abilita nominativo
CoDHUD.HUD.Subtitles.Callsign.desc=Abilita il nominativo del commentatore in riproduzione.

CoDHUD.HUD.Subtitles.NameAlign=Allineamento nominativo
CoDHUD.HUD.Subtitles.NameAlign.desc=Scegli dove posizionare il nominativo del commentatore.

CoDHUD.HUD.Subtitles.NameAlign.Left=A sinistra del testo
CoDHUD.HUD.Subtitles.NameAlign.Top=Sopra il testo

# ---------[ OTHER SETTINGS ]---------
CoDHUD.Settings=Altre impostazioni
CoDHUD.Audio=Impostazioni audio
CoDHUD.Audio.Announcer=Annunciatore
CoDHUD.Audio.Music=Musica

CoDHUD.Audio.Announcer.Enable=Abilita voce annunciatore
CoDHUD.Audio.Announcer.Enable.desc=Abilita l'annunciatore.

CoDHUD.Audio.Announcer.English=Forza annunciatore inglese
CoDHUD.Audio.Announcer.English.desc=Forza le voci dell'annunciatore in inglese indipendentemente dalla lingua di gioco.

CoDHUD.Audio.Music.Enable=Abilita musica
CoDHUD.Audio.Music.Enable.desc=Abilita la musica.

CoDHUD.Audio.Music.Ambient=Abilita musica ambientale
CoDHUD.Audio.Music.Ambient.desc=Abilita musica ambientale in sottofondo.

CoDHUD.Reset=Ripristina impostazioni
CoDHUD.Challenges.Reset=Ripristina sfide
CoDHUD.Challenges.Reset.desc=Ripristina tutte le sfide sbloccate.

CoDHUD.Rank.Reset=Ripristina rango e statistiche
CoDHUD.Rank.Reset.desc=Ripristina il rango e tutte le statistiche dell'HUD corrente.
CoDHUD.Rank.Reset.Warning=Attenzione!\nStai per ripristinare il tuo rango e le statistiche su questo HUD!\nQuesta azione non può essere annullata! Sei sicuro?

CoDHUD.Menu=Impostazioni menu
CoDHUD.Menu.Fullscreen=Apri a schermo intero
CoDHUD.Menu.Fullscreen.desc=Apre il menu CoD HUD a schermo intero invece che in una finestra più piccola.

CoDHUD.Menu.SFX=SFX menu
CoDHUD.Menu.SFX.desc=Riproduce effetti sonori del menu quando si passa sopra o si premono i pulsanti.

CoDHUD.Menu.Music=Musica menu
CoDHUD.Menu.Music.desc=Riproduce musica del menu quando qualsiasi istanza del menu CoD HUD è attiva.

CoDHUD.Menu.HideDesc=Nascondi descrizione
CoDHUD.Menu.HideDesc.desc=Se attivato, le descrizioni del menu saranno nascoste.

CoDHUD.Menu.HidePrompts=Nascondi prompt
CoDHUD.Menu.HidePrompts.desc=Se attivato, i prompt dei pulsanti nel menu saranno nascosti.

CoDHUD.Menu.OpenSpeed=Velocità apertura menu
CoDHUD.Menu.OpenSpeed.desc=Quanto velocemente il menu CoD HUD apre nuove istanze.\n\nMisurato in secondi.

CoDHUD.Menu.CloseSpeed=Velocità chiusura menu
CoDHUD.Menu.CloseSpeed.desc=Quanto velocemente il menu CoD HUD chiude le istanze.\n\nMisurato in secondi.

# ---------[ RANK & STATS ]---------
CoDHUD.Stats=Statistiche giocatore
CoDHUD.Stats.Rank=Livello giocatore: %d - %s
CoDHUD.Stats.XPNext=XP per prossimo rango: %d
CoDHUD.Stats.XP=XP totale: %d
CoDHUD.Stats.Kills=Uccisioni totali: %d
CoDHUD.Stats.Headshots=Colpi alla testa: %d
CoDHUD.Stats.Deaths=Morti totali: %d
CoDHUD.Stats.Challenges=Sfide completate: %d

CoDHUD.Stats.Unknown=Sconosciuto