#---------- CoD4 HUD | Italiano | Italian
# Translator: Original Game

# Factions
CoD4_MPUI_MARINES=Squadra ricogniz. marine
CoD4_MPUI_SPETSNAZ=Unità Spetsnaz
CoD4_MPUI_OPFOR=Nemici
CoD4_MPUI_SAS=Unità SAS

CoD4_MPUI_MARINES_SHORT=Marine
CoD4_MPUI_SPETSNAZ_SHORT=Unità Spetsnaz
CoD4_MPUI_OPFOR_SHORT=Nemici
CoD4_MPUI_SAS_SHORT=Unità SAS