#---------- Black Ops HUD | Italiano | Italian
# Translator: Original Game

# Factions
BO1_MP_TROPAS_NAME=TROPAS
BO1_MP_NVA_NAME=NVA
BO1_MP_RUSSIAN_NAME=SPETSNAZ
BO1_MP_SPECOPS_NAME=BLACK OPS
BO1_MP_MARINE_NAME=SOG
BO1_MP_REBELS_NAME=OP 40

BO1_MPUI_TROPAS_SHORT=Tropas
BO1_MPUI_NVA_SHORT=NVA
BO1_MPUI_RUSSIAN_SHORT=Unità Spetsnaz
BO1_MPUI_SPECOPS_SHORT=Black Ops
BO1_MPUI_MARINE_SHORT=SOG
BO1_MPUI_REBELS_SHORT=OP40

BO1_MPUI_TROPAS_SHORT_CAPS=TROPAS
BO1_MPUI_NVA_SHORT_CAPS=NVA
BO1_MPUI_RUSSIAN_SHORT_CAPS=SPETSNAZ
BO1_MPUI_SPECOPS_SHORT_CAPS=BLACK OPS
BO1_MPUI_MARINE_SHORT_CAPS=SOG
BO1_MPUI_REBELS_SHORT_CAPS=OP40

# Splashes
BO1_MEDAL_BUZZ_KILL=Guastafeste
BO1_MEDAL_BUZZ_KILL_DESC=Hai fermato una serie di uccisioni di un nemico
BO1_MEDAL_LONG_SHOT=Cecchino
BO1_MEDAL_LONG_SHOT_DESC=Hai ucciso un nemico da lontano
BO1_MEDAL_HEAD_SHOT=Colpo in testa
BO1_MEDAL_HEAD_SHOT_DESC=Boom, colpo alla testa!
BO1_MEDAL_STUCK_TO_PLAYER=Attaccata
BO1_MEDAL_STUCK_TO_PLAYER_DESC=Attacca un esplosivo su un nemico.
BO1_MEDAL_BULLS_EYE=Scalpo
BO1_MEDAL_BULLS_EYE_DESC=Hai ucciso un nemico con un Tomahawk
BO1_MEDAL_EXECUTION=Esecuzione
BO1_MEDAL_EXECUTION_DESC=Hai ucciso un nemico a terra con un colpo alla testa
BO1_MEDAL_COMEBACK=Ritorno
BO1_MEDAL_COMEBACK_DESC=Hai recuperato da una serie di morti
BO1_MEDAL_AVENGER=Vendicatore
BO1_MEDAL_AVENGER_DESC=Hai ucciso un nemico che ha appena eliminato un compagno.
BO1_MEDAL_AFTERLIFE=Aldilà
BO1_MEDAL_AFTERLIFE_DESC=Hai ucciso un nemico mentre eri morto
BO1_MEDAL_DOUBLE_KILL=Doppio
BO1_MEDAL_DOUBLE_KILL_DESC=Hai ucciso 2 persone in rapida successione.
BO1_MEDAL_TRIPLE_KILL=Triplo
BO1_MEDAL_TRIPLE_KILL_DESC=Hai ucciso 3 persone in rapida successione.
BO1_MEDAL_MULTI_KILL=Strage
BO1_MEDAL_MULTI_KILL_DESC=Hai ucciso più di 3 persone in rapida successione.
BO1_MEDAL_FIRST_BLOOD=Primo sangue
BO1_MEDAL_FIRST_BLOOD_DESC=Esegui la prima uccisione
BO1_MEDAL_BACK_STABBER=Traditore
BO1_MEDAL_BACK_STABBER_DESC=Hai accoltellato un giocatore alla schiena
BO1_MEDAL_HIJACKER=Dirottatore
BO1_MEDAL_HIJACKER_DESC=Hai rubato una cassa nemica.
BO1_MEDAL_SHARE_PACKAGE=Lavoro
BO1_MEDAL_SHARE_PACKAGE_DESC=Un compagno di squadra ha salvato la tua cassa.
BO1_MEDAL_ONE_SHOT_KILL=Un colpo, un morto
BO1_MEDAL_ONE_SHOT_KILL_DESC=Hai ucciso un nemico con un colpo solo
BO1_MEDAL_PAYBACK=Vendetta
BO1_MEDAL_PAYBACK_DESC=Hai ucciso il tuo assassino
BO1_MEDAL_RESCUER=Soccorritore
BO1_MEDAL_RESCUER_DESC=Hai salvato un compagno di squadra ferito
BO1_MEDAL_ASSISTED_SUICIDE=Infame
BO1_MEDAL_ASSISTED_SUICIDE_DESC=Hai ferito un nemico che si è ucciso
BO1_MEDAL_HEROIC=Gesto eroico
BO1_MEDAL_HEROIC_DESC=Ha ottenuto un punto durante Seconda occasione.
BO1_MEDAL_ASSISTS=Finezza
BO1_MEDAL_ASSISTS_DESC=Hai eseguito un assist
BO1_MEDAL_DESTROYER=Smantellato
BO1_MEDAL_DESTROYER_DESC=Hai distrutto un veicolo nemico
BO1_MEDAL_STREAKER=Serie letale
BO1_MEDAL_STREAKER_DESC=Hai attivato una serie di uccisioni
BO1_MEDAL_HERO=Eroe
BO1_MEDAL_HERO_DESC=Hai disinnescato la bomba
BO1_MEDAL_ANTI_BOMBER=Anti-bomba
BO1_MEDAL_ANTI_BOMBER_DESC=Ucciso un nemico che stava disinnescando.
BO1_MEDAL_OFFENSE=Attacco
BO1_MEDAL_OFFENSE_DESC=Hai ucciso un nemico vicino all'obiettivo
BO1_MEDAL_DEFENSE=Difesa
BO1_MEDAL_DEFENSE_DESC=Hai ucciso un nemico vicino al punto di difesa
BO1_MEDAL_POSITION_SECURE=Occupazione
BO1_MEDAL_POSITION_SECURE_DESC=Hai occupato un obiettivo
BO1_MEDAL_FLAG_RUNNER=Porta bandiera
BO1_MEDAL_FLAG_RUNNER_DESC=Hai raccolto la bandiera nemica
BO1_MEDAL_FLAG_CAPTURE=Ruba bandiera
BO1_MEDAL_FLAG_CAPTURE_DESC=Hai catturato la bandiera nemica
BO1_MEDAL_SABOTEUR=Sabotatore
BO1_MEDAL_SABOTEUR_DESC=Hai piazzato la bomba
BO1_MEDAL_BOMBER=Attentatore
BO1_MEDAL_BOMBER_DESC=Hai fatto detonare la bomba
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=Hai abbattuto un Controspionaggio.
BO1_MEDAL_DESTROYER_UAV_DESC=Abbattuto un aereo spia.
BO1_MEDAL_DESTROYER_TURRET_DESC=Hai distrutto una torretta
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=Hai abbattuto un elicottero.
BO1_MEDAL_FLAG_RETURN=Rendi bandiera
BO1_MEDAL_FLAG_RETURN_DESC=Hai riportato la bandiera
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=Distruggitorre
BO1_MEDAL_BALLISTIC_KNIFE_KILL=Infilzato
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=Hai colpito e ucciso un nemico con il coltello balistico.
BO1_MEDAL_BANK_SHOT=Rimbalzo
BO1_MEDAL_BANK_SHOT_DESC=Hai ucciso un nemico di rimbalzo con un tomahawk.
BO1_MEDAL_REVIVE=Medico
BO1_MEDAL_REVIVE_DESC=Hai riportato in vita un compagno di squadra.
BO1_MEDAL_DESTROYER_M220_TOW=Via dal cielo
BO1_MEDAL_DESTROYER_M220_TOW_DESC=Hai distrutto un Valkyrie.
BO1_MEDAL_DESTROYER_RCBOMB=Fuoco e fiamme
BO1_MEDAL_DESTROYER_RCBOMB_DESC=Hai distrutto un RC-XD!
BO1_MEDAL_AIRCRAFT_ASSIST=Gregario di valore
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=Hai eseguito un assist nell'abbattimento di un velivolo nemico.

# Round Starter
BO1_MP_MATCH_STARTING_IN=LA PARTITA COMINCIA FRA

# Other
BO1_MENU_WINNING_CAPS=VITTORIA
BO1_MENU_LOSING_CAPS=SCONFITTA
BO1_MENU_TIED_CAPS=PAREGGIO

BO1_MENU_WINNING=Vittoria
BO1_MENU_TIED=Pareggio
BO1_MENU_LOSING=Sconfitta

# Scoreboard
BO1_CGAME_SB_KILLS=Ucc.
BO1_CGAME_SB_ASSISTS=Assist
BO1_CGAME_SB_KDRATIO=Rateo
BO1_CGAME_SB_SCORE=Punti
BO1_CGAME_SB_DEATHS=Morti
BO1_CGAME_SB_PING=Ping

# Gamemodes
BO1_OBJECTIVES_SD_ATTACKER_HINT=DISTRUGGI IL BERSAGLIO A O B
BO1_OBJECTIVES_SD_DEFENDER_HINT=PROTEGGI GLI OBIETTIVI A E B
BO1_OBJECTIVES_SAB_HINT=DISTRUGGI IL BERSAGLIO NEMICO
BO1_OBJECTIVES_DOM_HINT=CATTURA LE BANDIERE E DIFENDILE
BO1_OBJECTIVES_DM_HINT=ELIMINA GLI ALTRI GIOCATORI
BO1_OBJECTIVES_TDM_HINT=ELIMINA I GIOCATORI NEMICI
BO1_OBJECTIVES_CTF_HINT=CATTURA BANDIERA
BO1_OBJECTIVES_DEM_ATTACKER_HINT=DISTRUGGI I BERSAGLI A E B
