#---------- CoD: World at War Ranks | Italiano | Italian
# Translator: Original Game

# Notifications
WAW_RANK_PROMOTED=Promozione!
WAW_RANK_PLAYER_WAS_PROMOTED=%s è stato promosso %s!
  
# Ranks
WAW_RANK_PVT_FULL=Soldato semplice
WAW_RANK_PFC_FULL=Soldato scelto
WAW_RANK_CPL_FULL=Caporale
WAW_RANK_SGT_FULL=Sergente
WAW_RANK_SSGT_FULL=Caporale m. capo I
WAW_RANK_GYSGT_FULL=Sergente artigliere
WAW_RANK_MSGT_FULL=Sergente maggiore
WAW_RANK_SGTM_FULL=Maresciallo
WAW_RANK_2NDLT_FULL=Sottotenente
WAW_RANK_1STLT_FULL=Tenente
WAW_RANK_CAPT_FULL=Capitano
WAW_RANK_MAJ_FULL=Maggiore
WAW_RANK_LTCOL_FULL=Tenente colonnello
WAW_RANK_COL_FULL=Colonnello
WAW_RANK_BGEN_FULL=Generale di brigata
WAW_RANK_MAJGEN_FULL=Generale di divisione
WAW_RANK_LTGEN_FULL=Generale corpo arm.
WAW_RANK_GEN_FULL=Generale
WAW_RANK_COMM_FULL=Comandante
WAW_RANK_1STLT_FULL2=Tenente I
WAW_RANK_1STLT_FULL3=Tenente II
WAW_RANK_2NDLT_FULL2=Sottotenente I
WAW_RANK_2NDLT_FULL3=Sottotenente II
WAW_RANK_BGEN_FULL2=Generale di brigata I
WAW_RANK_BGEN_FULL3=Generale di brigata II
WAW_RANK_CAPT_FULL2=Capitano I
WAW_RANK_CAPT_FULL3=Capitano II
WAW_RANK_COL_FULL2=Colonnello I
WAW_RANK_COL_FULL3=Colonnello II
WAW_RANK_CPL_FULL2=Caporale I
WAW_RANK_CPL_FULL3=Caporale II
WAW_RANK_GYSGT_FULL2=Sergente artigliere I
WAW_RANK_GYSGT_FULL3=Sergente artigliere II
WAW_RANK_LCPL_FULL2=Caporale LCpl I
WAW_RANK_LCPL_FULL3=Caporale LCpl II
WAW_RANK_LTCOL_FULL2=Tenente colonnello I
WAW_RANK_LTCOL_FULL3=Tenente colonnello II
WAW_RANK_MAJ_FULL2=Maggiore I
WAW_RANK_MAJ_FULL3=Maggiore II
WAW_RANK_MAJGEN_FULL2=Generale di divisione I
WAW_RANK_MAJGEN_FULL3=Generale di divisione II
WAW_RANK_MGYSGT_FULL2=Sergente maggiore artigliere I
WAW_RANK_MGYSGT_FULL3=Sergente maggiore artigliere II
WAW_RANK_MSGT_FULL2=Sergente maggiore I
WAW_RANK_MSGT_FULL3=Sergente maggiore II
WAW_RANK_PFC_FULL2=Soldato scelto I
WAW_RANK_PFC_FULL3=Soldato scelto II
WAW_RANK_PVT_FULL2=Soldato I
WAW_RANK_PVT_FULL3=Soldato II
WAW_RANK_REC_FULL2=Recluta I
WAW_RANK_REC_FULL3=Recluta II
WAW_RANK_SGT_FULL2=Sergente I
WAW_RANK_SGT_FULL3=Sergente II
WAW_RANK_SSGT_FULL2=Caporale m. capo I
WAW_RANK_SSGT_FULL3=Caporale m. capo II
WAW_RANK_LTGEN_FULL2=Generale corpo arm. I
WAW_RANK_LTGEN_FULL3=Generale corpo arm. II
WAW_RANK_GYSGT_FULL4=Sergente artigliere III
WAW_RANK_LTGEN_FULL4=Generale corpo arm. III
WAW_RANK_MAJGEN_FULL4=Generale di divisione III
WAW_RANK_BGEN_FULL4=Generale di brigata III
WAW_RANK_COL_FULL4=Colonnello III
WAW_RANK_LTCOL_FULL4=Tenente colonnello III
WAW_RANK_MAJ_FULL4=Maggiore III
WAW_RANK_CAPT_FULL4=Capitano III
WAW_RANK_1STLT_FULL4=Tenente III
WAW_RANK_2NDLT_FULL4=Sottotenente III
WAW_RANK_SSGT_FULL4=Caporale m. capo III
WAW_RANK_MSGT_FULL4=Sergente maggiore III
WAW_RANK_SGTM_FULL2=Maresciallo I
WAW_RANK_SGTM_FULL3=Maresciallo II
WAW_RANK_SGTM_FULL4=Maresciallo III
