#---------- CoD: World at War HUD | Italiano | Italian
# Translator: Original Game

# Factions
WAW_MPUI_RUSSIAN=Armata Rossa
WAW_MPUI_JAPANESE=Esercito imperiale
WAW_MPUI_GERMAN=Wehrmacht
WAW_MPUI_MARINE=Incursori marine

WAW_MPUI_RUSSIAN_SHORT=Armata Rossa
WAW_MPUI_JAPANESE_SHORT=Esercito imperiale
WAW_MPUI_GERMAN_SHORT=Wehrmacht
WAW_MPUI_MARINE_SHORT=Incursori marine

# Gamemodes
WAW_MPUI_TANK_WAR=Guerra
WAW_OBJECTIVES_TWAR_HINT=Prendi le bandiere e difendile.