#---------- CoD4 HUD | Français | French
# Translator: Original Game

# Factions
CoD4_MPUI_MARINES=Troupes des Marines
CoD4_MPUI_SPETSNAZ=Spetsnaz
CoD4_MPUI_OPFOR=Ennemi
CoD4_MPUI_SAS=SAS

CoD4_MPUI_MARINES_SHORT=Marines
CoD4_MPUI_SPETSNAZ_SHORT=Spetsnaz
CoD4_MPUI_OPFOR_SHORT=Ennemi
CoD4_MPUI_SAS_SHORT=SAS