#---------- CoD: World at War HUD | Français | French
# Translator: Original Game

# Factions
WAW_MPUI_RUSSIAN=Armée Rouge
WAW_MPUI_JAPANESE=Armée impériale
WAW_MPUI_GERMAN=Wehrmacht
WAW_MPUI_MARINE=Raiders des Marines

WAW_MPUI_RUSSIAN_SHORT=Armée Rouge
WAW_MPUI_JAPANESE_SHORT=Armée impériale
WAW_MPUI_GERMAN_SHORT=Wehrmacht
WAW_MPUI_MARINE_SHORT=Raiders des Marines

# Gamemodes
WAW_MPUI_TANK_WAR=Guerre
WAW_OBJECTIVES_TWAR_HINT=Capturez les drapeaux et défendez-les.

# Notifications
WAW_RANK_PROMOTED=Vous avez été promu !
WAW_RANK_PLAYER_WAS_PROMOTED=%s a été promu : %s !
  
# Ranks
WAW_RANK_PVT_FULL=Soldat
WAW_RANK_PFC_FULL=Soldat 1e classe
WAW_RANK_CPL_FULL=Caporal-chef
WAW_RANK_SGT_FULL=Sergent
WAW_RANK_SSGT_FULL=Sergent-chef
WAW_RANK_GYSGT_FULL=Sergent artilleur
WAW_RANK_MSGT_FULL=Adjudant
WAW_RANK_SGTM_FULL=Adjudant-chef
WAW_RANK_2NDLT_FULL=Sous-lieutenant
WAW_RANK_1STLT_FULL=Lieutenant
WAW_RANK_CAPT_FULL=Capitaine
WAW_RANK_MAJ_FULL=Commandant
WAW_RANK_LTCOL_FULL=Lieutenant-colonel
WAW_RANK_COL_FULL=Colonel
WAW_RANK_BGEN_FULL=Général de brigade
WAW_RANK_MAJGEN_FULL=Général de division
WAW_RANK_LTGEN_FULL=Général corps armée
WAW_RANK_GEN_FULL=Général
WAW_RANK_COMM_FULL=Maréchal
WAW_RANK_1STLT_FULL2=Lieutenant I
WAW_RANK_1STLT_FULL3=Lieutenant II
WAW_RANK_2NDLT_FULL2=Sous-lieutenant I
WAW_RANK_2NDLT_FULL3=Sous-lieutenant II
WAW_RANK_BGEN_FULL2=Général de brigade I
WAW_RANK_BGEN_FULL3=Général de brigade II
WAW_RANK_CAPT_FULL2=Capitaine I
WAW_RANK_CAPT_FULL3=Capitaine II
WAW_RANK_COL_FULL2=Colonel I
WAW_RANK_COL_FULL3=Colonel II
WAW_RANK_CPL_FULL2=Caporal-chef I
WAW_RANK_CPL_FULL3=Caporal-chef II
WAW_RANK_GYSGT_FULL2=Sergent artilleur I
WAW_RANK_GYSGT_FULL3=Sergent artilleur II
WAW_RANK_LCPL_FULL2=Caporal I
WAW_RANK_LCPL_FULL3=Caporal II
WAW_RANK_LTCOL_FULL2=Lieutenant-colonel I
WAW_RANK_LTCOL_FULL3=Lieutenant-colonel II
WAW_RANK_MAJ_FULL2=Commandant I
WAW_RANK_MAJ_FULL3=Commandant II
WAW_RANK_MAJGEN_FULL2=Général de division I
WAW_RANK_MAJGEN_FULL3=Général de division II
WAW_RANK_MGYSGT_FULL2=Adjudant artilleur I
WAW_RANK_MGYSGT_FULL3=Adjudant artilleur II
WAW_RANK_MSGT_FULL2=Adjudant I
WAW_RANK_MSGT_FULL3=Adjudant II
WAW_RANK_PFC_FULL2=Soldat 1e classe I
WAW_RANK_PFC_FULL3=Soldat 1e classe II
WAW_RANK_PVT_FULL2=Soldat I
WAW_RANK_PVT_FULL3=Soldat II
WAW_RANK_REC_FULL2=Recrue I
WAW_RANK_REC_FULL3=Recrue II
WAW_RANK_SGT_FULL2=Sergent I
WAW_RANK_SGT_FULL3=Sergent II
WAW_RANK_SSGT_FULL2=Sergent-chef I
WAW_RANK_SSGT_FULL3=Sergent-chef II
WAW_RANK_LTGEN_FULL2=Général corps armée I
WAW_RANK_LTGEN_FULL3=Général corps armée II
WAW_RANK_GYSGT_FULL4=Sergent artilleur III
WAW_RANK_LTGEN_FULL4=Général c. armée III
WAW_RANK_MAJGEN_FULL4=Général de division III
WAW_RANK_BGEN_FULL4=Général de brigade III
WAW_RANK_COL_FULL4=Colonel III
WAW_RANK_LTCOL_FULL4=Lieutenant-colonel III
WAW_RANK_MAJ_FULL4=Commandant III
WAW_RANK_CAPT_FULL4=Capitaine III
WAW_RANK_1STLT_FULL4=Lieutenant III
WAW_RANK_2NDLT_FULL4=Sous-lieutenant III
WAW_RANK_SSGT_FULL4=Sergent-chef III
WAW_RANK_MSGT_FULL4=Adjudant III
WAW_RANK_SGTM_FULL2=Adjudant-chef I
WAW_RANK_SGTM_FULL3=Adjudant-chef II
WAW_RANK_SGTM_FULL4=Adjudant-chef III
