#---------- CoD HUD System Notifications | Français | French
# Translator: Machine translated

CoDHUD.System.ResetTime=Le minuteur de manche a été réinitialisé à %s.
CoDHUD.System.ResetTime.Off=Le minuteur de manche a été supprimé.

CoDHUD.System.RestrictType=Le jeu a été changé en %s.
CoDHUD.System.RestrictType.NotNow=Impossible de changer de jeu pour le moment.

CoDHUD.System.Faction.NotNow=Impossible de changer de faction pour le moment.
CoDHUD.System.Faction.Denied=Impossible de changer de faction.

CoDHUD.System.ChallengeReset=Tous les défis ont été réinitialisés.
CoDHUD.System.RankReset=Le rang et les statistiques du HUD '%s' ont été réinitialisés.

CoDHUD.System.CVChanged=La variable serveur '%s' a été changée en %s.

CoDHUD.System.ForceEndRound.NotNow=Impossible de forcer la fin de la manche pour le moment.
CoDHUD.System.ForceEndRound.NotStarting=Impossible de forcer la fin d'une manche en cours de démarrage.