#---------- Black Ops II HUD | Français | French
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEAL
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercenaires
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Milice

BO2_MPUI_SEALS_SHORT=SEAL
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercenaires
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Milice

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCENAIRES
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILICE

# Splashes
BO2_MEDAL_FIRST_KILL=Premier sang
BO2_MEDAL_ASSISTED_SUICIDE=Suicide assisté
BO2_MEDAL_HEADSHOT=Tir dans la tête
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=Retour
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=Post mortem
BO2_MEDAL_LONGSHOT_KILL=Tir de loin
BO2_MEDAL_REVENGE_KILL=Vengeance
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=Rescapé
BO2_MEDAL_KILL_ENEMY_IN_AIR=Élimination aérienne
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=Une balle, un mort
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=4 pièces
BO2_MEDAL_KILLSTREAK_5=Sanguinaire
BO2_MEDAL_KILLSTREAK_10=Sans pitié
BO2_MEDAL_KILLSTREAK_15=Impitoyable
BO2_MEDAL_KILLSTREAK_20=Implacable
BO2_MEDAL_KILLSTREAK_25=Brutal
BO2_MEDAL_KILLSTREAK_30=Nucléaire
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=Invincible
BO2_MEDAL_MULTIKILL_2=Double meurtre
BO2_MEDAL_MULTIKILL_3=Triple meurtre
BO2_MEDAL_MULTIKILL_4=Tueur fou
BO2_MEDAL_MULTIKILL_5=Tuerie
BO2_MEDAL_MULTIKILL_6=Massacre
BO2_MEDAL_MULTIKILL_7=Carnage
BO2_MEDAL_MULTIKILL_8=Extermination
BO2_MEDAL_MULTIKILL_MORE_THAN_8=Chaîne d'éliminations
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=Vengeur
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=Sauveur

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s POINTS POUR GAGNER
