#---------- Black Ops HUD | Français | French
# Translator: Original Game

# Factions
BO1_MP_TROPAS_NAME=TROPAS
BO1_MP_NVA_NAME=ANV
BO1_MP_RUSSIAN_NAME=SPETSNAZ
BO1_MP_SPECOPS_NAME=BLACK OPS
BO1_MP_MARINE_NAME=GOS
BO1_MP_REBELS_NAME=OP 40

BO1_MPUI_TROPAS_SHORT=Tropas
BO1_MPUI_NVA_SHORT=ANV
BO1_MPUI_RUSSIAN_SHORT=Spetsnaz
BO1_MPUI_SPECOPS_SHORT=Black Ops
BO1_MPUI_MARINE_SHORT=GOS
BO1_MPUI_REBELS_SHORT=OP 40

BO1_MPUI_TROPAS_SHORT_CAPS=TROPAS
BO1_MPUI_NVA_SHORT_CAPS=ANV
BO1_MPUI_RUSSIAN_SHORT_CAPS=SPETSNAZ
BO1_MPUI_SPECOPS_SHORT_CAPS=BLACK OPS
BO1_MPUI_MARINE_SHORT_CAPS=GOS
BO1_MPUI_REBELS_SHORT_CAPS=OP 40

# Splashes
BO1_MEDAL_BUZZ_KILL=Rabat-joie
BO1_MEDAL_BUZZ_KILL_DESC=A tué un ennemi qui allait réaliser une série de victimes.
BO1_MEDAL_LONG_SHOT=Tir de loin
BO1_MEDAL_LONG_SHOT_DESC=A tué un ennemi de loin.
BO1_MEDAL_HEAD_SHOT=Tir mortel
BO1_MEDAL_HEAD_SHOT_DESC=Et bim, dans la tête.
BO1_MEDAL_STUCK_TO_PLAYER=Colleur
BO1_MEDAL_STUCK_TO_PLAYER_DESC=A collé un explosif sur un ennemi.
BO1_MEDAL_BULLS_EYE=Scalpeur
BO1_MEDAL_BULLS_EYE_DESC=A tué un ennemi avec un tomahawk.
BO1_MEDAL_EXECUTION=Exécution
BO1_MEDAL_EXECUTION_DESC=A tué un ennemi à terre d'une balle dans la tête.
BO1_MEDAL_COMEBACK=Come-back
BO1_MEDAL_COMEBACK_DESC=S'est remis d'une série de morts.
BO1_MEDAL_AVENGER=Vengeur
BO1_MEDAL_AVENGER_DESC=A tué un ennemi qui venait de tuer un coéquipier.
BO1_MEDAL_AFTERLIFE=Post mortem
BO1_MEDAL_AFTERLIFE_DESC=A tué un ennemi en étant mort.
BO1_MEDAL_DOUBLE_KILL=Double meurtre
BO1_MEDAL_DOUBLE_KILL_DESC=A tué deux ennemis en très peu de temps.
BO1_MEDAL_TRIPLE_KILL=Triple meurtre
BO1_MEDAL_TRIPLE_KILL_DESC=A tué 3 ennemis en très peu de temps.
BO1_MEDAL_MULTI_KILL=Multi-meurtre
BO1_MEDAL_MULTI_KILL_DESC=A tué plus de trois ennemis en très peu de temps.
BO1_MEDAL_FIRST_BLOOD=Premier sang
BO1_MEDAL_FIRST_BLOOD_DESC=A tué le premier.
BO1_MEDAL_BACK_STABBER=Poignard furtif
BO1_MEDAL_BACK_STABBER_DESC=A tué un joueur d'un coup de couteau dans le dos.
BO1_MEDAL_HIJACKER=Pirate
BO1_MEDAL_HIJACKER_DESC=A volé une caisse ennemie.
BO1_MEDAL_SHARE_PACKAGE=Colis partagé
BO1_MEDAL_SHARE_PACKAGE_DESC=Un coéquipier a sauvé votre caisse.
BO1_MEDAL_ONE_SHOT_KILL=Une balle, un mort
BO1_MEDAL_ONE_SHOT_KILL_DESC=A tué un ennemi d'une seule balle.
BO1_MEDAL_PAYBACK=Vengeance
BO1_MEDAL_PAYBACK_DESC=A tué un ennemi qui l'a tué.
BO1_MEDAL_RESCUER=Sauveur
BO1_MEDAL_RESCUER_DESC=A sauvé un coéquipier blessé.
BO1_MEDAL_ASSISTED_SUICIDE=Huile sur le feu
BO1_MEDAL_ASSISTED_SUICIDE_DESC=A blessé un ennemi qui s'est tué lui-même.
BO1_MEDAL_HEROIC=Motivé !
BO1_MEDAL_HEROIC_DESC=A capturé une position en étant en Deuxième chance.
BO1_MEDAL_ASSISTS=Assistance
BO1_MEDAL_ASSISTS_DESC=A aidé à tuer un ennemi.
BO1_MEDAL_DESTROYER=Ferrailleur
BO1_MEDAL_DESTROYER_DESC=A détruit un véhicule ennemi.
BO1_MEDAL_STREAKER=Tête de série
BO1_MEDAL_STREAKER_DESC=A obtenu un bonus de série de victimes.
BO1_MEDAL_HERO=Héros
BO1_MEDAL_HERO_DESC=A désamorcé la bombe.
BO1_MEDAL_ANTI_BOMBER=Protège-bombe
BO1_MEDAL_ANTI_BOMBER_DESC=A tué un ennemi en plein désamorçage.
BO1_MEDAL_OFFENSE=Assaillant
BO1_MEDAL_OFFENSE_DESC=A tué un ennemi près de l'objectif.
BO1_MEDAL_DEFENSE=Défense
BO1_MEDAL_DEFENSE_DESC=A tué un ennemi près du point de défense.
BO1_MEDAL_POSITION_SECURE=Lieu sécurisé
BO1_MEDAL_POSITION_SECURE_DESC=A pris un objectif.
BO1_MEDAL_FLAG_RUNNER=Transporteur
BO1_MEDAL_FLAG_RUNNER_DESC=A ramassé le drapeau ennemi.
BO1_MEDAL_FLAG_CAPTURE=À moi !
BO1_MEDAL_FLAG_CAPTURE_DESC=A capturé le drapeau ennemi.
BO1_MEDAL_SABOTEUR=Saboteur
BO1_MEDAL_SABOTEUR_DESC=A posé la bombe.
BO1_MEDAL_BOMBER=Artificier
BO1_MEDAL_BOMBER_DESC=A fait exploser la bombe.
BO1_MEDAL_DESTROYER_COUNTERUAV_DESC=A abattu un avion anti-espion.
BO1_MEDAL_DESTROYER_UAV_DESC=A abattu un avion-espion.
BO1_MEDAL_DESTROYER_TURRET_DESC=A détruit une tourelle.
BO1_MEDAL_DESTROYER_HELICOPTER_DESC=A abattu un hélico.
BO1_MEDAL_FLAG_RETURN=Le voilà !
BO1_MEDAL_FLAG_RETURN_DESC=A rapporté le drapeau.
BO1_MEDAL_DESC_POPUP=%s %s
BO1_MEDAL_XP_POPUP=+%s
BO1_MEDAL_CP_POPUP=+%s
BO1_MEDAL_DESTROYER_TURRET=Brise-tourelle
BO1_MEDAL_BALLISTIC_KNIFE_KILL=Embrocheur
BO1_MEDAL_BALLISTIC_KNIFE_KILL_DESC=A tué un ennemi avec le couteau balistique.
BO1_MEDAL_BANK_SHOT=Tir-rebond
BO1_MEDAL_BANK_SHOT_DESC=A tué un ennemi avec un tomahawk (tir avec rebond).
BO1_MEDAL_REVIVE=Médecin
BO1_MEDAL_REVIVE_DESC=A réanimé un coéquipier.
BO1_MEDAL_DESTROYER_M220_TOW=Déesse déchue
BO1_MEDAL_DESTROYER_M220_TOW_DESC=A abattu une Valkyrie.
BO1_MEDAL_DESTROYER_RCBOMB=Sans voiture
BO1_MEDAL_DESTROYER_RCBOMB_DESC=A détruit un RC-XD.
BO1_MEDAL_AIRCRAFT_ASSIST=Assistant ferrailleur
BO1_MEDAL_AIRCRAFT_ASSIST_DESC=A aidé à abattre un avion ennemi.

# Round Starter
BO1_MP_MATCH_STARTING_IN=DÉBUT PARTIE DANS

# Other
BO1_MENU_WINNING_CAPS=EN TÊTE
BO1_MENU_LOSING_CAPS=DÉFAITE
BO1_MENU_TIED_CAPS=ÉGALITÉ

BO1_MENU_WINNING=En tête
BO1_MENU_TIED=Égalité
BO1_MENU_LOSING=Défaite

# Scoreboard
BO1_CGAME_SB_KILLS=Vctm
BO1_CGAME_SB_ASSISTS=Assistances
BO1_CGAME_SB_KDRATIO=Ratio
BO1_CGAME_SB_SCORE=Score
BO1_CGAME_SB_DEATHS=Morts
BO1_CGAME_SB_PING=Ping

# Gamemodes
BO1_OBJECTIVES_SD_ATTACKER_HINT=DÉTRUISEZ LA CIBLE A OU B
BO1_OBJECTIVES_SD_DEFENDER_HINT=PROTÉGEZ LES CIBLES A ET B.
BO1_OBJECTIVES_SAB_HINT=DÉTRUISEZ LA CIBLE ENNEMIE
BO1_OBJECTIVES_DOM_HINT=CAPTUREZ LES DRAPEAUX ET DÉFENDEZ-LES.
BO1_OBJECTIVES_DM_HINT=ÉLIMINEZ D'AUTRES JOUEURS
BO1_OBJECTIVES_TDM_HINT=ÉLIMINEZ LES JOUEURS ENNEMIS
BO1_OBJECTIVES_CTF_HINT=CAPTUREZ LE DRAPEAU ENNEMI
BO1_OBJECTIVES_DEM_ATTACKER_HINT=DÉTRUISEZ LES CIBLES A ET B

# Notifications
BO1_RANK_PROMOTED_TO=Promotion : niveau %s !
BO1_RANK_PLAYER_WAS_PROMOTED=%s a été promu : %s !
  
# Ranks
BO1_RANK_PRVT_FULL=Soldat
BO1_RANK_PRVT_FULL2=Soldat I
BO1_RANK_PRVT_FULL3=Soldat II
BO1_RANK_PRVT_FULL_N=Soldat %s
BO1_RANK_PFC_FULL=Soldat 1re classe
BO1_RANK_PFC_FULL2=Soldat 1re classe I
BO1_RANK_PFC_FULL3=Soldat 1re classe II
BO1_RANK_PFC_FULL_N=Soldat 1re classe %s
BO1_RANK_SPC_FULL=Spécialiste
BO1_RANK_SPC_FULL2=Spécialiste I
BO1_RANK_SPC_FULL3=Spécialiste II
BO1_RANK_SPC_FULL_N=Spécialiste %s
BO1_RANK_CPL_FULL=Caporal-chef
BO1_RANK_CPL_FULL2=Caporal-chef I
BO1_RANK_CPL_FULL3=Caporal-chef II
BO1_RANK_CPL_FULL_N=Caporal-chef %s
BO1_RANK_SGT_FULL=Sergent
BO1_RANK_SGT_FULL2=Sergent I
BO1_RANK_SGT_FULL3=Sergent II
BO1_RANK_SGT_FULL_N=Sergent %s
BO1_RANK_SSGT_FULL=Sergent-chef
BO1_RANK_SSGT_FULL2=Sergent-chef I
BO1_RANK_SSGT_FULL3=Sergent-chef II
BO1_RANK_SSGT_FULL_N=Sergent-chef %s
BO1_RANK_SFC_FULL=Sergent 1re classe
BO1_RANK_SFC_FULL2=Sergent 1re classe I
BO1_RANK_SFC_FULL3=Sergent 1re classe II
BO1_RANK_SFC_FULL_N=Sergent 1re classe %s
BO1_RANK_SGTM_FULL=Sergent-major
BO1_RANK_SGTM_FULL2=Sergent-major I
BO1_RANK_SGTM_FULL3=Sergent-major II
BO1_RANK_SGTM_FULL_N=Sergent-major %s
BO1_RANK_LT_FULL=Lieutenant
BO1_RANK_LT_FULL2=Lieutenant I
BO1_RANK_LT_FULL3=Lieutenant II
BO1_RANK_LT_FULL_N=Lieutenant %s
BO1_RANK_CPT_FULL=Capitaine
BO1_RANK_CPT_FULL2=Capitaine I
BO1_RANK_CPT_FULL3=Capitaine II
BO1_RANK_CPT_FULL_N=Capitaine %s
BO1_RANK_MAJ_FULL=Commandant
BO1_RANK_MAJ_FULL2=Commandant I
BO1_RANK_MAJ_FULL3=Commandant II
BO1_RANK_MAJ_FULL_N=Commandant %s
BO1_RANK_LTCOL_FULL=Lieutenant-colonel
BO1_RANK_LTCOL_FULL2=Lieutenant-colonel I
BO1_RANK_LTCOL_FULL3=Lieutenant-colonel II
BO1_RANK_LTCOL_FULL_N=Lieutenant-colonel %s
BO1_RANK_COL_FULL=Colonel
BO1_RANK_COL_FULL2=Colonel I
BO1_RANK_COL_FULL3=Colonel II
BO1_RANK_COL_FULL_N=Colonel %s
BO1_RANK_BRIGGEN_FULL=Général de brigade
BO1_RANK_BRIGGEN_FULL2=Général de brigade I
BO1_RANK_BRIGGEN_FULL3=Général de brigade II
BO1_RANK_BRIGGEN_FULL_N=Général de brigade %s
BO1_RANK_MAJGEN_FULL=Général de division
BO1_RANK_MAJGEN_FULL2=Général de division I
BO1_RANK_MAJGEN_FULL3=Général de division II
BO1_RANK_MAJGEN_FULL_N=Général de division %s
BO1_RANK_LTGEN_FULL=Gén. corps d'armée
BO1_RANK_LTGEN_FULL2=Gén. corps d'armée I
BO1_RANK_LTGEN_FULL3=Gén. corps d'armée II
BO1_RANK_LTGEN_FULL_N=Gén. corps d'armée %s
BO1_RANK_GEN_FULL=Général
BO1_RANK_COM_FULL=Commandant
