#---------- Black Ops Ranks | Français | French
# Translator: Original Game

# Notifications
BO1_RANK_PROMOTED_TO=Promotion : niveau %s !
BO1_RANK_PLAYER_WAS_PROMOTED=%s a été promu : %s !
  
# Ranks
BO1_RANK_PRVT_FULL=Soldat
BO1_RANK_PRVT_FULL2=Soldat I
BO1_RANK_PRVT_FULL3=Soldat II
BO1_RANK_PRVT_FULL_N=Soldat %s
BO1_RANK_PFC_FULL=Soldat 1re classe
BO1_RANK_PFC_FULL2=Soldat 1re classe I
BO1_RANK_PFC_FULL3=Soldat 1re classe II
BO1_RANK_PFC_FULL_N=Soldat 1re classe %s
BO1_RANK_SPC_FULL=Spécialiste
BO1_RANK_SPC_FULL2=Spécialiste I
BO1_RANK_SPC_FULL3=Spécialiste II
BO1_RANK_SPC_FULL_N=Spécialiste %s
BO1_RANK_CPL_FULL=Caporal-chef
BO1_RANK_CPL_FULL2=Caporal-chef I
BO1_RANK_CPL_FULL3=Caporal-chef II
BO1_RANK_CPL_FULL_N=Caporal-chef %s
BO1_RANK_SGT_FULL=Sergent
BO1_RANK_SGT_FULL2=Sergent I
BO1_RANK_SGT_FULL3=Sergent II
BO1_RANK_SGT_FULL_N=Sergent %s
BO1_RANK_SSGT_FULL=Sergent-chef
BO1_RANK_SSGT_FULL2=Sergent-chef I
BO1_RANK_SSGT_FULL3=Sergent-chef II
BO1_RANK_SSGT_FULL_N=Sergent-chef %s
BO1_RANK_SFC_FULL=Sergent 1re classe
BO1_RANK_SFC_FULL2=Sergent 1re classe I
BO1_RANK_SFC_FULL3=Sergent 1re classe II
BO1_RANK_SFC_FULL_N=Sergent 1re classe %s
BO1_RANK_SGTM_FULL=Sergent-major
BO1_RANK_SGTM_FULL2=Sergent-major I
BO1_RANK_SGTM_FULL3=Sergent-major II
BO1_RANK_SGTM_FULL_N=Sergent-major %s
BO1_RANK_LT_FULL=Lieutenant
BO1_RANK_LT_FULL2=Lieutenant I
BO1_RANK_LT_FULL3=Lieutenant II
BO1_RANK_LT_FULL_N=Lieutenant %s
BO1_RANK_CPT_FULL=Capitaine
BO1_RANK_CPT_FULL2=Capitaine I
BO1_RANK_CPT_FULL3=Capitaine II
BO1_RANK_CPT_FULL_N=Capitaine %s
BO1_RANK_MAJ_FULL=Commandant
BO1_RANK_MAJ_FULL2=Commandant I
BO1_RANK_MAJ_FULL3=Commandant II
BO1_RANK_MAJ_FULL_N=Commandant %s
BO1_RANK_LTCOL_FULL=Lieutenant-colonel
BO1_RANK_LTCOL_FULL2=Lieutenant-colonel I
BO1_RANK_LTCOL_FULL3=Lieutenant-colonel II
BO1_RANK_LTCOL_FULL_N=Lieutenant-colonel %s
BO1_RANK_COL_FULL=Colonel
BO1_RANK_COL_FULL2=Colonel I
BO1_RANK_COL_FULL3=Colonel II
BO1_RANK_COL_FULL_N=Colonel %s
BO1_RANK_BRIGGEN_FULL=Général de brigade
BO1_RANK_BRIGGEN_FULL2=Général de brigade I
BO1_RANK_BRIGGEN_FULL3=Général de brigade II
BO1_RANK_BRIGGEN_FULL_N=Général de brigade %s
BO1_RANK_MAJGEN_FULL=Général de division
BO1_RANK_MAJGEN_FULL2=Général de division I
BO1_RANK_MAJGEN_FULL3=Général de division II
BO1_RANK_MAJGEN_FULL_N=Général de division %s
BO1_RANK_LTGEN_FULL=Gén. corps d'armée
BO1_RANK_LTGEN_FULL2=Gén. corps d'armée I
BO1_RANK_LTGEN_FULL3=Gén. corps d'armée II
BO1_RANK_LTGEN_FULL_N=Gén. corps d'armée %s
BO1_RANK_GEN_FULL=Général
BO1_RANK_COM_FULL=Commandant
