#---------- Black Ops II HUD | English
# Translator: Original Game

# Factions
BO2_MP_SEALS_NAME=SEAL
BO2_MP_PLA_NAME=SDC
BO2_MP_FBI_NAME=FBI
BO2_MP_PMC_NAME=Mercenaires
BO2_MP_ISA_NAME=ISA
BO2_MP_CD_NAME=Milice

BO2_MPUI_SEALS_SHORT=SEAL
BO2_MPUI_PLA_SHORT=SDC
BO2_MPUI_FBI_SHORT=FBI
BO2_MPUI_PMC_SHORT=Mercenaires
BO2_MPUI_ISA_SHORT=ISA
BO2_MPUI_CD_SHORT=Milice

BO2_MPUI_SEALS_SHORT_CAPS=SEAL
BO2_MPUI_PLA_SHORT_CAPS=SDC
BO2_MPUI_FBI_SHORT_CAPS=FBI
BO2_MPUI_PMC_SHORT_CAPS=MERCENAIRES
BO2_MPUI_ISA_SHORT_CAPS=ISA
BO2_MPUI_CD_SHORT_CAPS=MILICE

# Splashes
BO2_MEDAL_FIRST_KILL=PREMIER SANG
BO2_MEDAL_ASSISTED_SUICIDE=SUICIDE ASSISTÉ
BO2_MEDAL_HEADSHOT=TIR DANS LA TÊTE
BO2_MEDAL_COMEBACK_FROM_DEATHSTREAK=RETOUR
BO2_MEDAL_KILL_ENEMY_AFTER_DEATH=POST MORTEM
BO2_MEDAL_LONGSHOT_KILL=TIR DE LOIN
BO2_MEDAL_REVENGE_KILL=VENGEANCE
BO2_MEDAL_KILL_ENEMY_WHEN_INJURED=RESCAPÉ
BO2_MEDAL_KILL_ENEMY_IN_AIR=ÉLIMINATION AÉRIENNE
BO2_MEDAL_KILL_ENEMY_ONE_BULLET=UNE BALLE, UN MORT
BO2_MEDAL_UNINTERRUPTED_OBIT_FEED_KILLS=4 PIÈCES
BO2_MEDAL_KILLSTREAK_5=SANGUINAIRE
BO2_MEDAL_KILLSTREAK_10=SANS PITIÉ
BO2_MEDAL_KILLSTREAK_15=IMPITOYABLE
BO2_MEDAL_KILLSTREAK_20=IMPLACABLE
BO2_MEDAL_KILLSTREAK_25=BRUTAL
BO2_MEDAL_KILLSTREAK_30=NUCLÉAIRE
BO2_MEDAL_KILLSTREAK_MORE_THAN_30=INVINCIBLE
BO2_MEDAL_MULTIKILL_2=DOUBLE MEURTRE
BO2_MEDAL_MULTIKILL_3=TRIPLE MEURTRE
BO2_MEDAL_MULTIKILL_4=TUEUR FOU
BO2_MEDAL_MULTIKILL_5=TUERIE
BO2_MEDAL_MULTIKILL_6=MASSACRE
BO2_MEDAL_MULTIKILL_7=CARNAGE
BO2_MEDAL_MULTIKILL_8=EXTERMINATION
BO2_MEDAL_MULTIKILL_MORE_THAN_8=CHAÎNE D'ÉLIMINATIONS
BO2_MEDAL_KILL_ENEMY_WHO_KILLED_TEAMMATE=VENGEUR
BO2_MEDAL_KILL_ENEMY_INJURING_TEAMMATE=SAUVEUR

# Other
BO2_MPUI_X_POINTS_TO_WIN_CAPS=%s POINTS POUR GAGNER
