#---------- CoD HUD Settings | Français | French
# Translator: Machine translated

# ------------------[ GENERAL ]------------------
CoDHUD.Title=CoD HUD

CoDHUD.Client=Client
CoDHUD.Server=Serveur
CoDHUD.General=Général

CoDHUD.Close=Fermer

CoDHUD.Default=Par défaut : %s
CoDHUD.Current=Actuel : %s

# ------------------[ MENU GLYPHS ]------------------
CoDHUD.Glyph.Toggle=[+attack] Basculer
CoDHUD.Glyph.Open=[+attack] Ouvrir
CoDHUD.Glyph.OpenMenu=[+attack] Ouvrir le menu
CoDHUD.Glyph.Select=[+attack] Sélectionner
CoDHUD.Glyph.Confirm=[+attack] Confirmer
CoDHUD.Glyph.Return=[+attack] Retour
CoDHUD.Glyph.Close=[+attack] Fermer
CoDHUD.Glyph.Tab=[+attack] Ouvrir l'onglet
CoDHUD.Glyph.Reset=[+attack2] Réinitialiser

# ------------------[ ADMIN SETTINGS ]------------------
# ---------[ ROUND START ]---------
CoDHUD.RoundStart=Contrôles de manche

CoDHUD.RoundStart.Gamemode=Mode de jeu
CoDHUD.RoundStart.Info=Choisissez le mode de jeu.

CoDHUD.RoundStart.Start=Lancer la manche
CoDHUD.RoundStart.Start.desc=Une fois un mode de jeu sélectionné et les paramètres définis selon vos préférences, vous pouvez lancer le processus de début de manche.

CoDHUD.RoundStart.Notice=Êtes-vous sûr de vouloir lancer une nouvelle manche ?\nTous les scores seront réinitialisés et tous les joueurs réapparaîtront.
CoDHUD.RoundStart.Yes=Lancer la manche

CoDHUD.RoundStart.Timer=Minuteur de début de manche
CoDHUD.RoundStart.Timer.desc=Nombre de secondes d'intermission avant le début de la manche.

CoDHUD.RoundStart.Autobalance=Répartition aléatoire des factions au début de la manche
CoDHUD.RoundStart.Autobalance.desc=Si activé, tous les joueurs seront placés aléatoirement dans une faction valide au début de la manche.

CoDHUD.Scorelimit=Limite de score
CoDHUD.Scorelimit.desc=Définit la limite maximale de score affichée sur le compteur de score.\n\nMesuré en éliminations.

CoDHUD.Timelimit=Limite de temps
CoDHUD.Timelimit.desc=Définit la limite de temps avant la fin automatique de la manche.\n\nMesuré en minutes.\n\nMettre à 0 pour illimité.

CoDHUD.Autobalance.Amount=Limite d'équilibrage des équipes
CoDHUD.Autobalance.Amount.desc=Définit le nombre maximal de factions auxquelles les joueurs peuvent être automatiquement répartis.

CoDHUD.Autobalance.Amount.disable=Désactivé
CoDHUD.Autobalance.Amount.2=2 équipes
CoDHUD.Autobalance.Amount.3=3 équipes
CoDHUD.Autobalance.Amount.4=4 équipes

CoDHUD.RoundStart.Auto=Démarrer automatiquement une manche au lancement du serveur
CoDHUD.RoundStart.Auto.desc=Si activé, une nouvelle manche commencera immédiatement dès que le premier joueur rejoint le serveur.

CoDHUD.Admin.ResetTime=Réinitialiser le minuteur de manche
CoDHUD.Admin.ResetTime.desc=Réinitialise le minuteur de manche actuel à la valeur définie par la limite de temps.

CoDHUD.ForceEndRound=Forcer la fin de la manche
CoDHUD.ForceEndRound.desc=Cliquez ici si vous devez ou souhaitez terminer la manche avant que la limite de score ou de temps ne soit atteinte.

CoDHUD.ForceEndRound.Notice=Êtes-vous sûr de vouloir forcer la fin de la manche ?

# ---------[ ROUND END ]---------
CoDHUD.Admin.EndScreen=Activer "Fin de partie"
CoDHUD.Admin.EndScreen.desc=Active un système de fin de partie lorsque la limite de score est atteinte.

CoDHUD.Admin.EndScreen.StartNext=Lancer la prochaine manche après la fin de partie
CoDHUD.Admin.EndScreen.StartNext.desc=Si activé, une nouvelle manche commencera après la durée de fin de partie.\n\nSi désactivé, tous les joueurs réapparaîtront normalement.

CoDHUD.Admin.FriendlyFire=Activer le tir ami
CoDHUD.Admin.FriendlyFire.desc=Si activé, les joueurs de la même faction peuvent s'infliger des dégâts.\n\nS'applique uniquement en Match à mort en équipe.

# ---------[ FACTION & HUD TYPE RESTRICTION ]---------
CoDHUD.Admin.RestrictType=Restreindre factions et type de HUD
CoDHUD.Admin.RestrictType.Choose=Choisir le jeu
CoDHUD.Admin.RestrictType.desc=Choisissez à quel titre CoD limiter les utilisateurs. Cela affecte le HUD et les factions disponibles.

CoDHUD.Admin.RestrictType.Warning=Attention !\nChanger de jeu entraînera les conséquences suivantes :\n- Les factions de tous les joueurs seront choisies aléatoirement.\n- Tous les scores des joueurs seront remis à 0.\n- Tous les joueurs seront tués et réapparaîtront.\n\nÊtes-vous sûr de vouloir changer de jeu ?

CoDHUD.Type.cod4=Modern Warfare 1
CoDHUD.Type.waw=World at War
CoDHUD.Type.mw2=Modern Warfare 2
CoDHUD.Type.bo1=Black Ops
CoDHUD.Type.mw3=Modern Warfare 3
CoDHUD.Type.bo2=Black Ops II
CoDHUD.Type.ghosts=Ghosts
CoDHUD.Type.aw=Advanced Warfare
CoDHUD.Type.bo3=Black Ops III
CoDHUD.Type.iw=Infinite Warfare
CoDHUD.Type.ww2=WWII

CoDHUD.Admin.RestrictFactionChance=Restreindre le changement de faction
CoDHUD.Admin.RestrictFactionChance.desc=Définit quand les joueurs sont autorisés à changer de faction.

CoDHUD.Admin.RestrictFactionChance.disable=Impossible de changer
CoDHUD.Admin.RestrictFactionChance.freely=Changement libre
CoDHUD.Admin.RestrictFactionChance.pool=Uniquement depuis le pool actif

# ------------------[ CLIENT SETTINGS ]------------------
# ---------[ FACTION-RELATED ]---------
CoDHUD.Faction.Select=Sélection de faction
CoDHUD.Faction.Select.desc=Choisissez la faction que vous représentez.\nAffecte votre statut ami/ennemi et modifie le narrateur ainsi que le thème en fonction de la faction.

CoDHUD.Faction.ChangeWarning=Attention !\nChanger d'équipe entraîne les conséquences suivantes :\n- Votre score sera remis à 0.\n- Vous serez tué et réapparaîtrez.\n\nÊtes-vous sûr de vouloir changer de faction ?

# ---------[ QUICK-ACCESS ]---------
CoDHUD.Quick.title=Accès rapide

CoDHUD.Quick.DisableHUD=Désactivation rapide de toutes les options du HUD
CoDHUD.Quick.DisableHUD.desc=Désactive toutes les options du HUD CoD.

# ---------[ HUD-RELATED ]---------
CoDHUD.HUD=Paramètres du HUD

# Multiple
CoDHUD.HUD.Outline=Texte contouré
CoDHUD.HUD.Outline.desc=Active les textes contourés sur certains éléments pour améliorer la lisibilité dans les zones très lumineuses.

CoDHUD.HUD.Sound=Lire les effets sonores
CoDHUD.HUD.Sound.desc=Joue les effets sonores associés si le type de HUD le prend en charge.

CoDHUD.HUD.Time.Total=Durée d'affichage
CoDHUD.HUD.Time.Total.desc=Durée pendant laquelle la variable reste affichée après être complètement apparue avant de disparaître.

CoDHUD.HUD.Time.Fadein=Temps d'apparition
CoDHUD.HUD.Time.Fadein.desc=Durée nécessaire pour faire apparaître cette variable.

CoDHUD.HUD.Time.Fadeout=Temps de disparition
CoDHUD.HUD.Time.Fadeout.desc=Durée nécessaire pour faire disparaître cette variable.

# Scale
CoDHUD.HUD.Scale=Échelle de l'interface

CoDHUD.HUD.Scale.Enable=Multiplicateur d'échelle UI
CoDHUD.HUD.Scale.Enable.desc=Ajuste l'échelle des éléments d'interface utilisés par le HUD CoD.\n\nUtile pour les résolutions faibles ou ultra-larges.\n\n<color=255,255,100>Note</color> : le menu sera rechargé lors de l'application.\n\n<color=255,100,100>ATTENTION</color> : certains éléments peuvent être fortement désalignés si la valeur est trop élevée ou trop faible.

# Scoreboard
CoDHUD.HUD.Scoreboard=Tableau des scores

CoDHUD.HUD.Scoreboard.Enable=Activer le tableau des scores
CoDHUD.HUD.Scoreboard.Enable.desc=Active le tableau des scores. Affiche les factions actuellement occupées par tous les joueurs.

# Score Counter
CoDHUD.HUD.Scorecounter=Compteur de score

CoDHUD.HUD.Scorecounter.Enable=Activer le compteur de score
CoDHUD.HUD.Scorecounter.Enable.desc=Active un minuteur serveur, une icône de faction et les compteurs de score.\n\nCertains types de HUD n'affichent pas l'icône de faction.

# Medals
CoDHUD.HUD.Medals=Médailles

CoDHUD.HUD.Medals.Enable=Activer les médailles
CoDHUD.HUD.Medals.Enable.desc=Active les médailles obtenues en réalisant certaines actions comme des éliminations rapides ou des tirs à la tête.\n\nNotez que certains types de HUD n'affichent que du texte, tandis que d'autres affichent texte et icônes.

CoDHUD.HUD.Medals.Speedup=Accélérer si file d'attente longue
CoDHUD.HUD.Medals.Speedup.desc=Accélère la file des médailles lorsqu'il y en a beaucoup en attente.\n\nSelon le type de HUD, désactive aussi les effets sonores si plus de 3 médailles sont en file.

# Kill Feed
CoDHUD.HUD.Killfeed=Fil de kills

CoDHUD.HUD.Killfeed.Enable=Activer le fil de kills
CoDHUD.HUD.Killfeed.Enable.desc=Active le fil de kills.

# Minimap
CoDHUD.HUD.Minimap=Minicarte

CoDHUD.HUD.Minimap.Enable=Activer la minicarte
CoDHUD.HUD.Minimap.Enable.desc=Active la minicarte.

# Hitmarker
CoDHUD.HUD.Hitmarker=Indicateur de tir

CoDHUD.HUD.Hitmarker.Enable=Activer l'indicateur de tir
CoDHUD.HUD.Hitmarker.Enable.desc=Active l'indicateur de tir et son son associé.

# Weapon Info
CoDHUD.HUD.WeaponInfo=Infos arme

CoDHUD.HUD.WeaponInfo.Enable=Activer les infos arme
CoDHUD.HUD.WeaponInfo.Enable.desc=Active l'onglet d'informations de l'arme, affichant le nom et les munitions.\n\nCertains HUD intègrent aussi la boussole ici.

CoDHUD.HUD.WeaponPrompts.Enable=Activer les alertes d'arme
CoDHUD.HUD.WeaponPrompts.Enable.desc=Active les alertes d'arme, comme les notifications de munitions faibles.

# XP Counter
CoDHUD.HUD.XP=Notification XP

CoDHUD.HUD.XP.Enable=Activer les notifications XP
CoDHUD.HUD.XP.Enable.desc=Active les notifications XP.

# Target ID / IFF
CoDHUD.HUD.IFF=Identification ami ou ennemi

CoDHUD.HUD.IFF.Enable=Activer IFF
CoDHUD.HUD.IFF.Enable.desc=Active un système d'identification ami/ennemi affichant le nom de la cible au-dessus de sa tête lorsque vous la visez.

# Death Icon
CoDHUD.HUD.DeathIcon=Icône de mort

CoDHUD.HUD.DeathIcon.Enable=Activer l'icône de mort
CoDHUD.HUD.DeathIcon.Enable.desc=Active l'icône affichée lorsqu'un joueur de la même faction meurt.

# Chat
CoDHUD.HUD.Chat=Chat

CoDHUD.HUD.Chat.Enable=Activer le chat
CoDHUD.HUD.Chat.Enable.desc=Active le chat.

# Headers
CoDHUD.HUD.Headers=En-têtes

CoDHUD.HUD.Headers.Enable=Activer les notifications d'en-tête
CoDHUD.HUD.Headers.Enable.desc=Active les notifications d'en-tête, comme lors de l'accomplissement de défis ou du passage de niveau.

# Subtitles
CoDHUD.HUD.Subtitles=Sous-titres

CoDHUD.HUD.Subtitles.Enable=Activer les sous-titres
CoDHUD.HUD.Subtitles.Enable.desc=Active les sous-titres lorsqu'une réplique de l'annonceur est jouée.\n\n<color=255,100,100>Avertissement</color> : Les sous-titres sont créés à partir des répliques vocales en anglais.\n\n<color=255,255,100>Remarque</color> : Les sous-titres traduits ne sont pas disponibles.

CoDHUD.HUD.Subtitles.Callsign=Activer l'indicatif
CoDHUD.HUD.Subtitles.Callsign.desc=Active l'indicatif de l'annonceur en cours de lecture.

CoDHUD.HUD.Subtitles.NameAlign=Alignement de l'indicatif
CoDHUD.HUD.Subtitles.NameAlign.desc=Choisissez où placer l'indicatif de l'annonceur.

CoDHUD.HUD.Subtitles.NameAlign.Left=À gauche du texte
CoDHUD.HUD.Subtitles.NameAlign.Top=Au-dessus du texte

# ---------[ OTHER SETTINGS ]---------
CoDHUD.Settings=Autres paramètres
CoDHUD.Audio=Paramètres audio
CoDHUD.Audio.Announcer=Annonceur
CoDHUD.Audio.Music=Musique

CoDHUD.Audio.Announcer.Enable=Activer la voix de l'annonceur
CoDHUD.Audio.Announcer.Enable.desc=Active l'annonceur.

CoDHUD.Audio.Announcer.English=Forcer l'annonceur anglais
CoDHUD.Audio.Announcer.English.desc=Force les voix anglaises de l'annonceur, quelle que soit la langue du jeu.

CoDHUD.Audio.Music.Enable=Activer la musique
CoDHUD.Audio.Music.Enable.desc=Active la musique.

CoDHUD.Audio.Music.Ambient=Activer la musique ambiante
CoDHUD.Audio.Music.Ambient.desc=Active la musique ambiante en arrière-plan.

CoDHUD.Reset=Réinitialiser les paramètres
CoDHUD.Challenges.Reset=Réinitialiser les défis
CoDHUD.Challenges.Reset.desc=Réinitialise tous les défis débloqués.

CoDHUD.Rank.Reset=Réinitialiser rang et statistiques
CoDHUD.Rank.Reset.desc=Réinitialise le rang et toutes les statistiques du HUD actuel.
CoDHUD.Rank.Reset.Warning=Attention !\nVous êtes sur le point de réinitialiser votre rang et vos statistiques sur ce HUD !\nCette action est irréversible ! Êtes-vous sûr ?

CoDHUD.Menu=Paramètres du menu
CoDHUD.Menu.Fullscreen=Ouvrir en plein écran
CoDHUD.Menu.Fullscreen.desc=Ouvre le menu CoD HUD en plein écran au lieu d'une petite fenêtre.

CoDHUD.Menu.SFX=Effets sonores du menu
CoDHUD.Menu.SFX.desc=Joue des effets sonores de menu lors du survol ou des clics.

CoDHUD.Menu.Music=Musique du menu
CoDHUD.Menu.Music.desc=Joue de la musique de menu lorsque le menu CoD HUD est actif.

CoDHUD.Menu.HideDesc=Masquer les descriptions
CoDHUD.Menu.HideDesc.desc=Si activé, les descriptions du menu seront masquées.

CoDHUD.Menu.HidePrompts=Masquer les invites
CoDHUD.Menu.HidePrompts.desc=Si activé, les invites de boutons du menu seront masquées.

CoDHUD.Menu.OpenSpeed=Vitesse d'ouverture du menu
CoDHUD.Menu.OpenSpeed.desc=Vitesse à laquelle le menu CoD HUD ouvre de nouvelles instances.\n\nMesuré en secondes.

CoDHUD.Menu.CloseSpeed=Vitesse de fermeture du menu
CoDHUD.Menu.CloseSpeed.desc=Vitesse à laquelle le menu CoD HUD ferme les instances.\n\nMesuré en secondes.

# ---------[ RANK & STATS ]---------
CoDHUD.Stats=Statistiques du joueur
CoDHUD.Stats.Rank=Niveau du joueur : %d - %s
CoDHUD.Stats.XPNext=XP pour le prochain rang : %d
CoDHUD.Stats.XP=XP totale : %d
CoDHUD.Stats.Kills=Éliminations totales : %d
CoDHUD.Stats.Headshots=Tirs à la tête : %d
CoDHUD.Stats.Deaths=Morts totales : %d
CoDHUD.Stats.Challenges=Défis complétés : %d

CoDHUD.Stats.Unknown=Inconnu