#---------- MW2 HUD | Français | French
# Translator: Original Game

# Factions
MW2_MP_US_ARMY_NAME=Rangers
MW2_MP_SEALS_UDT_NAME=Navy SEAL
MW2_MP_MILITIA_NAME=Milice
MW2_MP_TASKFORCE_NAME=Task Force 141
MW2_MP_OPFOR_NAME=Ennemi
MW2_MP_SPETSNAZ_NAME=Spetsnaz

MW2_MP_US_ARMY_SHORT_NAME=Rangers
MW2_MP_SEALS_UDT_SHORT_NAME=SEAL
MW2_MP_MILITIA_SHORT_NAME=Milice
MW2_MP_TASKFORCE_SHORT_NAME=TF 141
MW2_MPUI_OPFOR_SHORT=Ennemi
MW2_MPUI_SPETSNAZ_SHORT=Spetsnaz
  
# Splashes
MW2_SPLASHES_HEADSHOT=Pleine tête !
MW2_SPLASHES_HEADSHOT_DESC=+%s
MW2_SPLASHES_ASSISTEDSUICIDE=Suicide en direct !
MW2_SPLASHES_ASSISTEDSUICIDE_DESC=Vous avez été témoin du suicide d'un ennemi.
MW2_SPLASHES_LONGSHOT=Tir à longue distance !
MW2_SPLASHES_LONGSHOT_DESC=Joli tir à distance !
MW2_SPLASHES_EXECUTION=Exécution !
MW2_SPLASHES_EXECUTION_DESC=+%s
MW2_SPLASHES_AVENGER=Vengeur !
MW2_SPLASHES_AVENGER_DESC=Vous avez vengé un coéquipier.
MW2_SPLASHES_DEFENDER=Sauveur !
MW2_SPLASHES_DEFENDER_DESC=Vous avez sauvé un coéquipier.
MW2_SPLASHES_POSTHUMOUS=De l'au-delà !
MW2_SPLASHES_POSTHUMOUS_DESC=Vous avez tué un ennemi après votre mort.
MW2_SPLASHES_REVENGE=Vengeance !
MW2_SPLASHES_REVENGE_DESC=Vous vous êtes vengé.
MW2_SPLASHES_DOUBLEKILL=Double élimination !
MW2_SPLASHES_DOUBLEKILL_DESC=+%s
MW2_SPLASHES_TRIPLEKILL=Triple élimination !
MW2_SPLASHES_TRIPLEKILL_DESC=+%s
MW2_SPLASHES_MULTIKILL=Élimination multiple !
MW2_SPLASHES_MULTIKILL_DESC=+%s
MW2_SPLASHES_FIRSTBLOOD=Premier sang !
MW2_SPLASHES_FIRSTBLOOD_DESC=Vous avez tué la première victime.
MW2_SPLASHES_BUZZKILL=Trouble-fête !
MW2_SPLASHES_BUZZKILL_DESC=Vous avez arrêté un ennemi en pleine série d'éliminations.
MW2_SPLASHES_COMEBACK=Retour !
MW2_SPLASHES_COMEBACK_DESC=Vous avez récupéré d'une série de morts.
MW2_SPLASHES_FLAGRETURN=Retour du drapeau !
MW2_SPLASHES_FLAGRETURN_DESC=+%s
MW2_SPLASHES_FLAGPICKUP=Transporteur de drapeau !
MW2_SPLASHES_FLAGPICKUP_DESC=+%s
MW2_SPLASHES_CAPTURE=Position sécurisée !
MW2_SPLASHES_CAPTURE_DESC=Vous avez pris un objectif.
MW2_SPLASHES_DEFEND=Défense !
MW2_SPLASHES_DEFEND_DESC=Vous avez défendu l'objectif.
MW2_SPLASHES_ASSAULT=Attaque !
MW2_SPLASHES_ASSAULT_DESC=Vous avez tué un défenseur.
MW2_SPLASHES_PLANT=Saboteur !
MW2_SPLASHES_PLANT_DESC=Vous avez posé la bombe.
MW2_SPLASHES_DEFUSE=Héros !
MW2_SPLASHES_DEFUSE_DESC=Vous avez désamorcé la bombe.
MW2_SPLASHES_SAB_OVERTIME=Prolongation !
MW2_SPLASHES_SAB_OVERTIME_DESC=La base la plus proche de la bombe sera détruite.
MW2_SPLASHES_MARTYRDOM_DESC=Vous laisserez tomber une grenade dégoupillée à votre mort.
MW2_SPLASHES_FINALSTAND_DESC=Vous aurez une seconde chance quand vous vous ferez tuer.
MW2_SPLASHES_ENDGAME_DESC=Vous disposez d'un bonus de santé pour quelques secondes.
MW2_SPLASHES_C4DEATH_DESC=Sortez une charge de C4 avant de mourir.
MW2_SPLASHES_KNIFETHROW_DESC=Vous avez tué un ennemi au couteau de lancer.
MW2_SPLASHES_KNIFETHROW=Dans le mille !
MW2_SPLASHES_HIJACKER_DESC=Vous avez pris une caisse de ravitaillement ennemie.
MW2_SPLASHES_HIJACKER=Pirate !
MW2_SPLASHES_HIJACKED=%s a pris votre caisse.
MW2_SPLASHES_DEFCON_LOWER=DEFCON réduit !
MW2_SPLASHES_DEFCON_RAISE=DEFCON augmenté !
MW2_SPLASHES_DEFCON_LOWER_DESC=Bonus de séries d'éliminations améliorés !
MW2_SPLASHES_DEFCON_RAISE_DESC=Bonus de séries d'éliminations rétrogradés !
MW2_SPLASHES_DEFCON_5=DEFCON 5
MW2_SPLASHES_DEFCON_4=DEFCON 4
MW2_SPLASHES_DEFCON_3=DEFCON 3
MW2_SPLASHES_DEFCON_2=DEFCON 2
MW2_SPLASHES_DEFCON_1=DEFCON 1
MW2_SPLASHES_DEFCON_5_DESC=DEFCON 5
MW2_SPLASHES_DEFCON_4_DESC=Début du match !
MW2_SPLASHES_DEFCON_3_DESC=Largage aérien d'urgence imminent !
MW2_SPLASHES_DEFCON_2_DESC=Suivi des séries d'éliminations après avoir été tué
MW2_SPLASHES_DEFCON_1_DESC=Points des objectifs doublés !
MW2_SPLASHES_COMBATHIGH_DESC=Santé accrue pour une courte durée.
MW2_SPLASHES_RESTED=Boost d'EXP du jour !
MW2_SPLASHES_RESTED_DESC=Vous gagnez des points d'EXP bonus.
MW2_SPLASHES_RESTED_DONE=Fin Boost EXP du jour.
MW2_SPLASHES_RESTED_DONE_DESC=Points bonus d'EXP obtenus.
MW2_SPLASHES_VIP=Vous êtes le VIP.
MW2_SPLASHES_STUCK_SEMTEX=Ça va faire boum !
MW2_SPLASHES_STUCK_SEMTEX_DESC=Vous avez posé du Semtex sur un ennemi !
MW2_SPLASHES_HEROIC=Quelle bravoure !
MW2_SPLASHES_HEROIC_DESC=Vous avez pris un objectif en Baroud d'honneur !
MW2_SPLASHES_DENIED=Pas question !
MW2_SPLASHES_DENIED_DESC=Vous avez empêché l'insertion tactique d'un ennemi !
MW2_SPLASHES_DESTROYED_INSERTION=bloque votre insertion.
MW2_SPLASHES_HIJACKED_EMERGENCY_AIRDROP=a pris votre caisse !
MW2_SPLASHES_REVIVER_DESC=Vous avez ranimé un coéquipier tombé au combat.
MW2_SPLASHES_REVIVER=Réanimateur !
MW2_SPLASHES_GIVEAWAY_SENTRY=a pris une tourelle.
MW2_SPLASHES_GIVEAWAY_AIRDROP=... a pris un bonus largué.
MW2_SPLASHES_SEMTEX_STUCK=Semtex collé sur vous !
MW2_SPLASHES_ONE_SHOT_KILL=Coup mortel
MW2_SPLASHES_ONE_SHOT_KILL_DESC=Un tir... un mort.
MW2_SPLASHES_NINJA_DEFUSE=Désamorçage de Ninja
MW2_SPLASHES_NINJA_DEFUSE_DESC=En toute discrétion...
MW2_SPLASHES_COPYCAT_DESC=Volez la classe de votre tueur durant la killcam.
MW2_SPLASHES_COPIED=Classe imitée !
MW2_SPLASHES_REVIVED=vous a ranimé.
MW2_SPLASHES_LAST_TEAM_MEMBER_ALIVE=Dernier en vie !
MW2_SPLASHES_LAST_ENEMY_ALIVE=Dernier en vie !
MW2_SPLASHES_SHIELDASSIST=Forces antiémeute !
MW2_SPLASHES_SHIELDASSIST_DESC=Vous faites une excellente diversion.
MW2_SPLASHES_DESTROYED_HELICOPTER=a détruit un hélico !
MW2_SPLASHES_DESTROYED_PAVELOW=a détruit un Pave Low !
MW2_SPLASHES_DESTROYED_UAV=a détruit un drone !
MW2_SPLASHES_DESTROYED_HARRIER=a détruit un Harrier !
MW2_SPLASHES_DESTROYED_AC130=a détruit l'AC-130 !
MW2_SPLASHES_DESTROYED_MINIGUNNER=a détruit un hélico !
MW2_SPLASHES_FLAG_RETURN=a rapporté le drapeau !
MW2_SPLASHES_FLAG_CAPTURE=a capturé le drapeau !
MW2_SPLASHES_FLAG_PICKUP_FRIENDLY=a pris votre drapeau !
MW2_SPLASHES_FLAG_PICKUP_ENEMY=a le drapeau ennemi !
MW2_SPLASHES_FLAG_PICKUP=a pris le drapeau !
MW2_SPLASHES_CAPTURED_NUKE=Bombe nucl. capturée !
MW2_SPLASHES_DESC_CAPTURED_NUKE=Bombe nucl. capturée !
MW2_SPLASHES_UNLOCKED_EXTENDED_MAGS=Charg. grde cap. dispo.
MW2_SPLASHES_UNLOCKED_HEARTBEAT=Capteur card. dispo.
MW2_SPLASHES_UNLOCKED_AKIMBO=Akimbo débloqué !
MW2_SPLASHES_UNLOCKED_THERMAL=Lunette therm. dispo.
MW2_SPLASHES_UNLOCKED_EOTECH=Viseur holog. dispo.
MW2_SPLASHES_UNLOCKED_SHOTGUN=F. à pompe débloqué !
MW2_SPLASHES_GRABBED_THE_FLAG=Vous avez pris le drapeau !
MW2_SPLASHES_HIJACKED_SENTRY=a pris votre tourelle.
MW2_SPLASHES_HIJACKED_AIRDROP=a pris votre caisse.
MW2_SPLASHES_BOMB_PLANTED=Bombe posée !
MW2_SPLASHES_BOMB_DEFUSED=Bombe désamorcée !
MW2_SPLASHES_TIMEADDED=Temps ajouté !
MW2_SPLASHES_GTNW_OVERTIME=Mort subite !
MW2_SPLASHES_GTNW_OVERTIME_DESC=Pas de réapparition.
MW2_SPLASHES_DESTROYED_OBJECTIVE=Objectif détruit !
MW2_SPLASHES_SAVED_OBJECTIVE=Objectif sauvé !
MW2_SPLASHES_CAPTURED_HQ=Q.G. capturé !
MW2_SPLASHES_DESTROYED_HQ=Q.G. détruit !
MW2_SPLASHES_BOMB_TAKEN=Bombe prise !
MW2_SPLASHES_BOMB_DROPPED=Bombe perdue !
MW2_SPLASHES_KILLED_CARRIER=Porteur de bombe tué !
MW2_SPLASHES_SHAREPACKAGE=Partage de colis !
MW2_SPLASHES_SHAREPACKAGE_DESC=Un de vos coéquipiers a sauvé votre colis stratégique de l'ennemi !
MW2_SPLASHES_DESTROYED_COUNTER_UAV=Drone rétabli !
MW2_SPLASHES_FLAGS_CAPTURE=a capturé un drapeau !
MW2_SPLASHES_FLAG_ASSAULT=Assault du drapeau !
MW2_SPLASHES_FLAG_DEFEND=Drapeau défendu !
MW2_SPLASHES_FLAG_ASSAULT_DESC=Vous avez tué un défenseur de drapeau.
MW2_SPLASHES_FLAG_DEFEND_DESC=Vous avez défendu le drapeau.
MW2_SPLASHES_FLAG_CAPTURED=Drapeau capturé !
MW2_SPLASHES_FLAG_CAPTURED_DESC=Vous avez capturé le drapeau ennemi.
MW2_SPLASHES_SECURED_POSITION=Position sécurisée !
MW2_SPLASHES_SECURED_POSITION_A=Position A sécurisée !
MW2_SPLASHES_SECURED_POSITION_B=Position B sécurisée !
MW2_SPLASHES_SECURED_POSITION_C=Position C sécurisée !
MW2_SPLASHES_TIME_ADDED=Bonus de temps !
MW2_SPLASHES_TIME_ADDED_DESC=Site détruit. Bonus de temps de jeu.

# Other
MW2_MP_CONNECTED=%s connecté
MW2_MP_DISCONNECTED=%s déconnecté
MW2_EXE_LEFTGAME=%s a quitté la partie

MW2_PLATFORM_RELOAD=Recharger
MW2_PLATFORM_LOW_AMMO_NO_RELOAD=Peu de munitions
MW2_WEAPON_NO_AMMO=Pas de munition

MW2_MPUI_WINNING_CAPS=EN TÊTE
MW2_MPUI_LOSING_CAPS=DÉFAITE
MW2_MPUI_TIED_CAPS=ÉGALITÉ

MW2_CGAME_SB_SCORE=Score
MW2_CGAME_SB_DEATHS=Morts
MW2_CGAME_SB_KILLS=Élim.
MW2_CGAME_SB_ASSISTS=Assist.

MW2_PLATFORM_THROWBACKGRENADE=%s renvoyer

MW2_MP_FIRSTPLACE_NAME=1er %s
MW2_MP_SECONDPLACE_NAME=2e %s
MW2_MP_THIRDPLACE_NAME=3e %s

# Partially custom
MW2_GAME_CHANGEDTO=%s changé en %s

# Round Starter
MW2_MP_MATCH_STARTING_IN=Début du match dans :
MW2_MP_MATCH_RESUMING_IN=Reprise du match dans :

# Gamemodes
MW2_MPUI_SABOTAGE=Sabotage
MW2_MPUI_DEATHMATCH=Mêlée générale
MW2_MPUI_CAPTURE_THE_FLAG=Capture du drapeau
MW2_MPUI_HEADQUARTERS=QG
MW2_MPUI_SEARCH_AND_DESTROY=Recherche et destruction
MW2_MPUI_WAR=Match à mort par équipe
MW2_MPUI_DOMINATION=Domination
MW2_MPUI_ONE_FLAG=CDD avec un drapeau
MW2_MPUI_ARENA=Arène
MW2_MPUI_DD=Démolition
MW2_MPUI_VIP=VIP
MW2_MPUI_GTNW=Guerre thermonucléaire mondiale

MW2_MP_OBJ_DM_HINT=Éliminez les autres joueurs.
MW2_MP_OBJ_WAR_HINT=Éliminez les joueurs ennemis.
MW2_OBJECTIVES_WAR_HINT=Éliminez les joueurs ennemis.
MW2_OBJECTIVES_SD_ATTACKER_HINT=Détruisez la cible A ou la cible B.
MW2_OBJECTIVES_SD_DEFENDER_HINT=Protégez les cibles A et B.
MW2_OBJECTIVES_SAB_HINT=Détruisez la cible de l'ennemi.
MW2_OBJECTIVES_DOM_HINT=Capturez les drapeaux et défendez-les.
MW2_OBJECTIVES_DM_HINT=Éliminez les autres joueurs.
MW2_OBJECTIVES_KOTH_HINT=Tenez le QG.
MW2_OBJECTIVES_CTF_HINT=Capturez le drapeau ennemi.
MW2_OBJECTIVES_ONE_FLAG_ATTACKER_HINT=Capturez le drapeau ennemi.
MW2_OBJECTIVES_ONE_FLAG_DEFENDER_HINT=Défendez le drapeau.
MW2_OBJECTIVES_DD_ATTACKER_HINT=Détruisez les cibles A et B.
MW2_OBJECTIVES_DD_DEFENDER_HINT=Protégez les cibles A et B.
MW2_OBJECTIVES_VIP_ATTACKER_HINT=Tuez le VIP et empêchez-le d'atteindre la zone d'extraction.
MW2_OBJECTIVES_VIP_DEFENDER_HINT=Défendez le VIP et aidez-le à atteindre la zone d'extraction.
MW2_OBJECTIVES_ARENA_HINT=Éliminez l'ennemi ou capturez le drapeau.
MW2_OBJECTIVES_GTNW_HINT=Prenez la bombe nucléaire.
MW2_OBJECTIVES_GRAB_FLAG_HINT=Attrapez le drapeau ennemi.

# Round Ender
MW2_MP_DRAW=Égalité
MW2_MP_VICTORY=Victoire !
MW2_MP_DEFEAT=Défaite !
MW2_MP_ROUND_DRAW=Match nul
MW2_MP_ROUND_WIN=Manche gagnée
MW2_MP_ROUND_LOSS=Manche perdue
MW2_MP_HALFTIME=Mi-temps
MW2_MP_OVERTIME=Prolongation
MW2_MP_MATCH_BONUS_IS=Bonus de match : %s

MW2_MP_SCORE_LIMIT_REACHED=Limite de score atteinte
MW2_MP_ROUND_LIMIT_REACHED=Limite de la manche atteinte
MW2_MP_TIME_LIMIT_REACHED=Durée limite atteinte
MW2_MP_HOST_ENDED_GAME=L'hôte a mis fin à la partie.

# Notifications
MW2_RANK_PROMOTED=Vous avez été promu !
MW2_RANK_PLAYER_WAS_PROMOTED=%s a été promu : %s !

# Ranks
MW2_RANK_REC_FULL=Recrue
MW2_RANK_PVT_FULL=Soldat
MW2_RANK_PFC_FULL=Soldat 1ère classe
MW2_RANK_LCPL_FULL=Caporal
MW2_RANK_CPL_FULL=Caporal-chef
MW2_RANK_SGT_FULL=Sergent
MW2_RANK_SSGT_FULL=Sergent-chef
MW2_RANK_GYSGT_FULL=Sergent artilleur
MW2_RANK_MSGT_FULL=Adjudant
MW2_RANK_MGYSGT_FULL=Adjudant artilleur
MW2_RANK_2NDLT_FULL=Sous-lieutenant
MW2_RANK_1STLT_FULL=Lieutenant
MW2_RANK_CAPT_FULL=Capitaine
MW2_RANK_MAJ_FULL=Commandant
MW2_RANK_LTCOL_FULL=Lieutenant-colonel
MW2_RANK_COL_FULL=Colonel
MW2_RANK_BGEN_FULL=Général de brigade
MW2_RANK_MAJGEN_FULL=Général de division
MW2_RANK_LTGEN_FULL=Gén. corps d'armée
MW2_RANK_GEN_FULL=Général
MW2_RANK_COMM_FULL=Maréchal
MW2_RANK_1STLT_FULL2=Lieutenant I
MW2_RANK_1STLT_FULL3=Lieutenant II
MW2_RANK_2NDLT_FULL2=Sous-lieutenant I
MW2_RANK_2NDLT_FULL3=Sous-lieutenant II
MW2_RANK_BGEN_FULL2=Général de brigade I
MW2_RANK_BGEN_FULL3=Général de brigade II
MW2_RANK_CAPT_FULL2=Capitaine I
MW2_RANK_CAPT_FULL3=Capitaine II
MW2_RANK_COL_FULL2=Colonel I
MW2_RANK_COL_FULL3=Colonel II
MW2_RANK_COMM_FULL2=Maréchal I
MW2_RANK_COMM_FULL3=Maréchal II
MW2_RANK_CPL_FULL2=Caporal-chef I
MW2_RANK_CPL_FULL3=Caporal-chef II
MW2_RANK_GEN_FULL2=Général I
MW2_RANK_GEN_FULL3=Général II
MW2_RANK_GYSGT_FULL2=Sergent artilleur I
MW2_RANK_GYSGT_FULL3=Sergent artilleur II
MW2_RANK_LCPL_FULL2=Caporal I
MW2_RANK_LCPL_FULL3=Caporal II
MW2_RANK_LTCOL_FULL2=Lieutenant-colonel I
MW2_RANK_LTCOL_FULL3=Lieutenant-colonel II
MW2_RANK_MAJ_FULL2=Commandant I
MW2_RANK_MAJ_FULL3=Commandant II
MW2_RANK_MAJGEN_FULL2=Général de division I
MW2_RANK_MAJGEN_FULL3=Général de division II
MW2_RANK_MGYSGT_FULL2=Adjudant artilleur I
MW2_RANK_MGYSGT_FULL3=Adjudant artilleur II
MW2_RANK_MSGT_FULL2=Adjudant I
MW2_RANK_MSGT_FULL3=Adjudant II
MW2_RANK_PFC_FULL2=Soldat 1ère classe I
MW2_RANK_PFC_FULL3=Soldat 1ère classe II
MW2_RANK_PVT_FULL2=Soldat I
MW2_RANK_PVT_FULL3=Soldat II
MW2_RANK_REC_FULL2=Recrue I
MW2_RANK_REC_FULL3=Recrue II
MW2_RANK_SGT_FULL2=Sergent I
MW2_RANK_SGT_FULL3=Sergent II
MW2_RANK_SSGT_FULL2=Sergent-chef I
MW2_RANK_SSGT_FULL3=Sergent-chef II
MW2_RANK_LTGEN_FULL2=Gén. corps d'armée I
MW2_RANK_LTGEN_FULL3=Gén. corps d'armée II
MW2_RANK_SGTMAJ_FULL=Sergent-major
MW2_RANK_SGTMAJ_FULL2=Sergent-major I
MW2_RANK_SGTMAJ_FULL3=Sergent-major II
MW2_RANK_SPC_FULL=Spécialiste
MW2_RANK_SPC_FULL2=Spécialiste I
MW2_RANK_SPC_FULL3=Spécialiste II
MW2_RANK_SFC_FULL=Sergent de 1ère classe
MW2_RANK_SFC_FULL2=Sergent de 1ère classe I
MW2_RANK_SFC_FULL3=Sergent de 1ère classe II
MW2_RANK_1STSGT_FULL=Adjudant-chef
MW2_RANK_1STSGT_FULL2=Adjudant-chef I
MW2_RANK_1STSGT_FULL3=Adjudant-chef II
MW2_RANK_CSM_FULL=Sergent-major cmdt
MW2_RANK_CSM_FULL2=Sergent-major cmdt I
MW2_RANK_CSM_FULL3=Sergent-major cmdt II
MW2_RANK_CSM_FULL4=Sergent-major cmdt III
MW2_RANK_GEN_FULL4=Général III
MW2_RANK_LTGEN_FULL4=Gén. corps d'armée III
MW2_RANK_MAJGEN_FULL4=Général de division III
MW2_RANK_BGEN_FULL4=Général de brigade III
MW2_RANK_COL_FULL4=Colonel III
MW2_RANK_LTCOL_FULL4=Lieutenant-colonel III
MW2_RANK_MAJ_FULL4=Commandant III
MW2_RANK_CAPT_FULL4=Capitaine III
MW2_RANK_1STLT_FULL4=Lieutenant III
MW2_RANK_2NDLT_FULL4=Sous-lieutenant III
