#---------- CoD: World at War HUD | Français | French
# Translator: Original Game

# Factions
WAW_MPUI_RUSSIAN=Armée Rouge
WAW_MPUI_JAPANESE=Armée impériale
WAW_MPUI_GERMAN=Wehrmacht
WAW_MPUI_MARINE=Raiders des Marines

WAW_MPUI_RUSSIAN_SHORT=Armée Rouge
WAW_MPUI_JAPANESE_SHORT=Armée impériale
WAW_MPUI_GERMAN_SHORT=Wehrmacht
WAW_MPUI_MARINE_SHORT=Raiders des Marines

# Gamemodes
WAW_MPUI_TANK_WAR=Guerre
WAW_OBJECTIVES_TWAR_HINT=Capturez les drapeaux et défendez-les.